src/vector/jitsi/index.scss, src/vector/jitsi/index.ts
Fixes https://github.com/vector-im/element-web/issues/15571
=> Fix Jitsi regressions with custom themes

Dockerfile, README.md
We now have a Docker repo named `element-web`, so this updates docs to match.
Fixes https://github.com/vector-im/element-web/issues/14930
=> Rename Docker repo in docs

README.md
I've added inotify instance limit info based on: these issues [#15750](https://github.com/vector-im/element-web/issues/15750), [#15774](https://github.com/vector-im/element-web/issues/15774) and this StackOverflow [question](https://stackoverflow.com/questions/64919108/error-emfile-too-many-open-files-watch-unless-i-use-sudo/64941113#64941113).
=> Add inotify instance limit info to README

release.sh
It generally does not make much sense to publish an entire application like this
to NPM, so we've agreed to stop doing so going forward.
Fixes https://github.com/vector-im/element-web/issues/14902
=> Stop publishing Element to NPM

.stylelintrc.js, docs/app-load.md, docs/config.md, docs/jitsi.md, docs/review.md, docs/skinning thoughts.md, package.json, scripts/issues-no-state.pl, src/vector/init.tsx, src/vector/jitsi/index.scss, src/vector/jitsi/index.ts, src/vector/platform/ElectronPlatform.tsx, src/vector/platform/VectorBasePlatform.ts, src/vector/rageshakesetup.ts, webpack.config.js
Now that we aren't publishing the app to NPM any more, we can fix basic details like the package name.
This also includes some other misc. rebrandings as well.
=> Rebrand package name and other details

package.json, src/vector/index.ts, webpack.config.js, yarn.lock
This changes the KaTeX CSS inclusion to function just like the other bits of the
CSS that we import from dependencies.
=> Include KaTeX CSS as a dependency

src/vector/platform/WebPlatform.ts
After a notification arrives, when the user focuses on element, the
notification never goes away (unless directly interacted with), this was a bug.
displayNotification was never returning the notification handle, which means
that matrix-react-sdk later on had no way to .close it.
Closes #16026, please see that bug for more info about following the code flow that lead to this.
Signed-off-by: Alexandru M Stan <alex@hypertriangle.com>
=> webplatform: Fix notification closing

src/@types/global.d.ts, src/vector/init.tsx, src/vector/platform/ElectronPlatform.tsx
This adjusts to match changes on the desktop side where we now use Electron's
context isolation feature to expose only the IPC channels and methods we
actually expect to use.
Depends on https://github.com/vector-im/element-desktop/pull/163
=> Use isolated IPC API

src/vector/index.ts, src/vector/init.tsx, src/vector/platform/WebPlatform.ts
At the moment, there's no point in installing the empty service worker on
Electron.
Fixes https://github.com/vector-im/element-web/issues/16008
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/5545
=> Skip the service worker for Electron

scripts/docker-link-repos.sh
An extra step is needed for develop Docker builds after recent build process changes. This was regressed by https://github.com/vector-im/element-web/pull/15999.
Fixes https://github.com/vector-im/element-web/issues/16119
=> Fix develop Docker builds

yarn.lock
This (should) fix `element-web` CI failures on develop.
=> Fix Widget API version confusion

Dockerfile
This updates to Node 14 (current LTS) as well as moving from Debian Stretch to
Buster for the base OS. The Debian upgrade brings along a newer Python 3.8,
which is actively supported.
=> Move to newer base image for Docker builds

src/vector/app.tsx
Has additional benefit of not leaving the loginToken in history
=> Use history replaceState instead of redirect for SSO flow

src/@types/global.d.ts
This changes to an interface for Electron types so that other layers can merge
in further APIs as needed, such as the JS SDK.
Related to https://github.com/matrix-org/matrix-js-sdk/pull/1594
=> Fix Electron type merging

src/vector/index.ts
As mentioned in https://github.com/vector-im/element-web/issues/16020#issuecomment-774384598, we're depending on the `dotAll` / `s` regex feature. This adds a test so browsers without this see an error screen.
=> Add RegExp dotAll feature test

element.io/develop/config.json
The Countly experiment has ended, so this removes the configuration to enable it.
=> Disable Countly

package.json, src/vector/app.tsx, src/vector/platform/WebPlatform.ts, yarn.lock
Related to https://github.com/vector-im/element-web/pull/16292
=> fix / sso: make sure to delete only loginToken after redirect

src/vector/jitsi/index.ts
This is an aesthetic change to the Jitsi widget and has no bearing on the widget's functionality.
Paired with https://github.com/matrix-org/matrix-react-sdk/pull/5649
=> Jitsi widget: Read room name from query parameters

docs/labs.md
Documents https://github.com/matrix-org/matrix-react-sdk/pull/5668
=> Document feature_spaces

docs/config.md, src/vector/jitsi/index.ts
Starts jitsi streaming to a specially configured URL so that the
jitsi server can start an audio-only stream, in combination with an
API to manage audio streams by room ID.
Requires https://github.com/matrix-org/matrix-react-sdk/pull/5707
=> Add option for audio live streaming

docs/customisations.md, webpack.config.js
The new regex considers Windows as an OS, and the added array helps reduce merge conflicts for the future.
=> Improve docs for customisations

src/vector/index.ts, src/vector/init.tsx, src/vector/rageshakesetup.ts
This also delays the persistence until later in the app startup - this is fine for the reasons listed on the partner PR: https://github.com/matrix-org/matrix-react-sdk/pull/5767
Fixes https://github.com/vector-im/element-web/issues/16694
=> Disable rageshake persistence if no logs would be submitted

README.md
The message that notifies a developer that the Element build is finished does not reflect the current output
Updating the documentation to make sure that developers will not wait in vain for that message to appear
=> Updated expected webpack output in setup guide

res/css/structures/ErrorView.scss
Output from linter:
```
$ stylelint 'res/css/**/*.scss'
res/css/structures/ErrorView.scss
25:20   ✖  Expected "DXImageTransform.Microsoft.gradient" to be "dximagetransform.microsoft.gradient"   function-name-case               
25:56   ✖  Unexpected whitespace after "(" in a single-line function                                    function-parentheses-space-inside
25:103  ✖  Expected single space after "," in a single-line function                                    function-comma-space-after       
25:118  ✖  Unexpected whitespace before ")" in a single-line function                                   function-parentheses-space-inside
44:27   ✖  Expected "#03B381" to be "#03b381"                                                           color-hex-case                   
57:16   ✖  Expected …
```
=> Fix style lint issues

Dockerfile
Use `gzip_static` to reduce compressible asset sizes. Useful for Tor and other low-bandwidth networks.
**Uncompressed: 3.2 MiB**
```
% curl -sSL -D - -o /dev/null http://localhost:8001/bundles/10710025de4329178620/vendors~init.js 
HTTP/1.1 200 OK
Server: nginx/1.19.8
Date: Tue, 16 Mar 2021 21:16:36 GMT
Content-Type: application/javascript
Content-Length: 3338041
Last-Modified: Tue, 16 Mar 2021 21:03:49 GMT
Connection: keep-alive
ETag: "60511d35-32ef39"
Accept-Ranges: bytes
```
**Compressed: 891 kiB**
```
% curl -sSL -D - -o /dev/null --compressed http://localhost:8001/bundles/10710025de4329178620/vendors~init.js
HTTP/1.1 200 OK
Server: nginx/1.19.8
Date: Tue, 16 Mar 2021 21:16:05 GMT
Content-Type: application/javascript
Content-Length: 912580
Last-Modified: Tue, 16 Mar 2021 21:03:49 GMT …
```
=> Docker image: serve pre-compressed assets using gzip_static

docs/labs.md, webpack.config.js
**See https://github.com/matrix-org/matrix-react-sdk/pull/5769**
=> Add webpack config and labs flag docs for voice messages

Dockerfile
Reverts vector-im/element-web#16698
Fixes https://github.com/vector-im/element-web/issues/16837
This needs more consideration before being used in practice.
=> Revert "Docker image: serve pre-compressed assets using gzip_static"

docs/config.md, src/vector/app.tsx
For deployments which want this sort of functionality for their users. Ideal for self-hosted deployments.
No react-sdk changes needed.
=> Support a config option to skip login/welcome and go to SSO

docs/config.md, src/async-components/structures/CompatibilityView.tsx, src/i18n/strings/en_EN.json, src/vector/mobile_guide/index.html
This is similar to the desktopBuilds config option.
The mobile setup guide and static incompatible browser pages are not touched by these options given they are static assets and easily replaced.
=> Add mobile download link configuration

webpack.config.js
Improves vector-im/element-web#14750
More and more people use Nightly builds as their main client. When bundling the app in a CI environment webpack is in development mode.
Doing so means that sources are not minified, we benefit from source maps, BUT we run React development build. Which is great when an engineer is actively working on the app, but adds significant runtime overhead (3-5x slower in development compared to production)
* Fig1: React production, room filtering in a "small" account, 65ms blocking time, 445ms script execution time
* Fig2: React development, room filtering in a "small" account, 401.6ms blocking time, 1461 script execution time
PS: Sorry for the larger diff, the linter was not happy, the tl;dr is [`0532c9c`](https://github.com/vector-im/element-web/commit/0532c9c …
=> Use React production mode in CI builds

scripts/ci_package.sh, webpack.config.js
With the approach in https://github.com/vector-im/element-web/pull/16969, Webpack seems to sometimes do what we want, sometimes not... I haven't quite worked out why. Perhaps there's some conflict or race in Webpack's defaults...?
This new approach seems to work as expected when running `./scripts/ci_package.sh`, which matches what development deployments are doing.
=> Fix `NODE_ENV` value for CI environments

webpack.config.js
While it sounds like a useful warning at first, it turns out the warnings it prints are ones we're unlike to ever act on, such as adding percentages and pixels, which seem fine to have. This resets to default behaviour, which leaves the warning off.
=> Disable `postcss-calc`'s noisy `warnWhenCannotResolve` option

docs/review.md
In the past, we have occasionally written different kinds of tests for Element and the SDKs, but it hasn't been a consistent focus. Going forward, we'd like to change that.
This adds a new review policy which encourages tests for new features. As with everything, we'll continue to tune this based on feedback.
=> Add code quality review policy

package.json
This is useful when you're doing cross-browser testing on a service which demands you use "localhost.com" for reasons.
=> Disable host checking on the webpack dev server

package.json, yarn.lock
To fix inevitable build errors.
**Strongly recommended for inclusion before the RC**
=> Update matrix-widget-api/react-sdk dependency reference

webpack.config.js
As described in https://github.com/vector-im/element-web/issues/17330#issuecomment-842530812, this should prevent the newly introduced version of `html-webpack-plugin` from minifying `.html` files, like e.g. `index.html`, `jitsi.html`, et cetera …
Quoting @jryans via https://github.com/vector-im/element-web/issues/17330#issuecomment-842415694:
> The content of the `index.html` file is not a supported API surface, so it might change at any time.
> 
> This document minification was not done on purpose, but instead it happened as a side effect of upgrading. We would happily accept a PR to fix this, but it is also not a priority for the core team.
Could someone with a dev environment please test and, hopefully, accept this change back to not minifying the `.html` files?
Thank you very much.
— …
=> Prevent minification of `.html` files

config.sample.json, docs/kubernetes.md, docs/labs.md
Removed since design wants to avoid associating slowness with the brand (goes with matrix-org/matrix-react-sdk#6078).
=> Remove logo spinner

package.json, src/vector/init.tsx, yarn.lock
Port https://github.com/vector-im/element-web/pull/17433 to release
=> [Release] Bump libolm dependency, and update package name

scripts/copy-res.js
The package name was updated in #17433, but this path to copy `olm_legacy.js` into place was overlooked.
Closes #17463.
=> Fix Olm asm.js support

package.json, yarn.lock
Blocked by matrix-org/matrix-react-sdk#6165
The `yarn.lock` file defined here will only be true once the other PR has been merged
=> ⚛️ Upgrade to React@17

webpack.config.js
All of our supported browsers understand `woff2`, so there's no need to make everyone preload the older `woff` as well.
=> Preload only `woff2` fonts

src/i18n/strings/en_EN.json, src/vector/platform/ElectronPlatform.tsx
Requires https://github.com/matrix-org/matrix-react-sdk/pull/6088
Towards https://github.com/vector-im/element-web/issues/17128
=> Spaces keyboard shortcuts first cut

element.io/app/config.json, element.io/develop/config.json
I've seen a fair number of people asking how to get to these rooms. It seems like it would make sense to add this to the default room directory.
=> Add libera.chat to default room directory

package.json
Following #17774, fixing a bad copy paste for the path
=> Fix canvas-filter-polyfill mock path

src/vector/index.html
Fixes vector-im/element-web#6162
Requires matrix-org/matrix-react-sdk#6279
=> Enhance security by disallowing CSP object-src rule

src/vector/index.html
Fixes the following warning for https://github.com/matrix-org/matrix-react-sdk/pull/6137
=> Remove spurious overflow: auto on #matrixchat element

package.json, yarn.lock
See https://github.com/kjur/jsrsasign/security/advisories/GHSA-27fj-mc8w-j9wg
for details.
=> Update jsrsasign to ^10.2.0 (Includes fix for CVE-2021-30246)

package.json, webpack.config.js, yarn.lock
In the midst of matrix-org/matrix-react-sdk#6291 I came accross a bug where valid CSS would not be processed correctly by PostCSS (including the latest version)
```
.test {
--variable: 50px;
}
.test2 {
width: calc(100 - var(--variable));
}
```
In order to achieve the effect that I require I would like to remove the `calc()` processing, that is already supporting by all the browsers currently in the browserslist
=> Remove PostCSS calc() processing

Dockerfile
As of https://github.com/vector-im/element-web/pull/17967, `canvas` is no longer used, so we don't need install these native deps for building it on arm64.
=> Remove canvas native dependencies from Dockerfile

Dockerfile
Reverts vector-im/element-web#17927
due to privileged port issue, might need some more work before it returns.
=> Revert "Don't run nginx as root in docker"

package.json
=> Ignore workers for jest tests because it disagrees with worker-loader

src/vector/app.tsx
E.g if you click a link to room/#foo:bar?via=baz we'll redirect to room/#foo:bar and now hitting back takes you back to the ?via=baz and means you have to hit back twice without this change
=> Fix browser history getting stuck looping back to the same room

docs/translating.md
This adds the new [translators space](https://matrix.to/#/#element-translators:matrix.org) to the translations guide.
=> Add the Matrix Space to the translations guide

package.json, src/async-components/structures/CompatibilityView.tsx, src/async-components/structures/ErrorView.tsx, src/components/views/auth/VectorAuthFooter.tsx, src/vector/platform/ElectronPlatform.tsx, src/vector/platform/VectorBasePlatform.ts, src/vector/platform/WebPlatform.ts, yarn.lock
Requires https://github.com/matrix-org/eslint-plugin-matrix-org/pull/10
=> Conform to new typescript eslint rules

README.md
Add "prevalence" labels to use as a guideline for how often issues crop up.
Combine prevalence and severity to indicate correspondence to how defects
should be prioritised by the team.
Signed-off-by: Ekaterina Gerasimova <kittykat3756@gmail.com>
=> Update issue labelling guidelines in README

.github/workflows/triage-incoming.yml
GitHub bug means that GITHUB_TOKEN doesn't work according to
documentation at https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token because it doesn't have the right permissions for moving stuff to a project board.
The automation throws this error:
Error: Resource not accessible by integration
Use our own generated token for now.
Signed-off-by: Ekaterina Gerasimova <kittykat3756@gmail.com>
=> Triage automation: update token

.github/workflows/triage-priority-bugs.yml
Automatically move all bugs with the right label combinations onto the Priority bugs column on the Web App Team's board.
Signed-off-by: Ekaterina Gerasimova <kittykat3756@gmail.com>
---
=> Issue triage: move priority bugs onto team board

.github/workflows/triage-priority-bugs.yml
=> Issue triage: move only defects into priority bugs

docs/pr-previews.md
It's not in the checks section anymore.
---
=> Update PR previews doc post GHA

.env.example, webpack.config.js
This PR fixes two issues with CSS hot-reload when using legacy themes:
1. The name of the legacy themes in `.env.sample` is wrong. The themes are called `legacy-light` and `legacy-dark` and not `light-legacy` and `dark-legacy`, respectively.
2. When the `legacy-light` theme is enabled in `.env`, e.g. `MATRIX_THEMES='legacy-light'`, running `yarn start` results in the following error:
```
const themeImportPath = cssThemes[`theme-${ t }`].replace('./node_modules/', '');
^
TypeError: Cannot read property 'replace' of undefined
at element-web/webpack.config.js:70:63
at Array.map (<anonymous>)
at getThemesImports (element-web/webpack.config.js:69:39)
```
---
A reviewer can add one of: `T-Deprecation`, …
=> Fix isues with CSS hot-reload

package.json, yarn.lock
Without this, the build can end up with two widget APIs and conflict - not a fun time.
---
=> Update matrix-widget-api dependency

docs/labs.md
Document `feature_new_layout_switcher` flag to `labs.md`.
---
=> Document missing features in labs.md

.github/workflows/issues_to_projects.yaml
This might not work at all.
---
=> Issue automation: test GitHub's new shiny boards

.github/workflows/issues_to_projects.yaml
Beta boards automation is different from old boards
This reverts commit b873185c684843484ada463eb7c06bdc42036dde.
---
=> Revert "Issue automation: test GitHub's new shiny boards"

.github/ISSUE_TEMPLATE/bug-desktop.yml, .github/ISSUE_TEMPLATE/bug-web.yml
Feedback received asking to merge templates so they take up less space
and are quicker for developers to fill.
The new template will look like this:
Instead of this:
---
=> Issue templates: merge expected and actual results

element.io/develop/config.json
Point posthog nightly at prod posthog infrastructure. This will enable posthog tracking for those who have switched labs flag on, on develop.
See https://github.com/vector-im/element-web/blob/develop/docs/config.md
---
=> Enable posthog on develop

.github/workflows/issues_to_projects.yaml, .github/workflows/triage-priority-bugs.yml, README.md
Lets use slightly more sensible labels for Occurrence: Frequent,
Occasional and Uncommon.
Also point README to the shared element-meta wiki.
On merging, a few other tasks need to be completed:
---
=> Issue labelling and process home updates

src/vector/platform/ElectronPlatform.tsx
Fixes https://github.com/vector-im/element-web/issues/18481
Requires https://github.com/matrix-org/matrix-react-sdk/pull/6804
---
* Fix space keyboard shortcuts conflicting with native zoom shortcuts ([\#19037](https://github.com/vector-im/element-web/pull/19037)). Fixes #18481.
=> Fix space keyboard shortcuts conflicting with native zoom shortcuts

docs/translating-dev.md
Fixing it once more because https://github.com/vector-im/element-web/pull/19080 didn't work out as intended.
---
=> Fix link to README in translation-docs again

docs/jitsi.md
I've removed the (old) documentation notice about the iOS Element client that ignored the homeserver configuration for a custom Jitsi URL.
Related issues/pull requests:
* https://github.com/vector-im/element-ios/issues/3158
* https://github.com/vector-im/element-ios/pull/4283
Notes: Removed iOS app Jitsi homeserver URL notice in the documentation
Signed-off-by: Max Kratz <account@maxkratz.com>
---
=> Removed iOS app Jitsi homeserver URL notice in the documentation

.github/workflows/triage-priority-bugs.yml
All incoming issues labelled with A-E2EE* and A-*spaces* labels should go to appropriate teams, and not to P1 in the web app team project.
Review of logic would be appreciated.
---
=> Don't give E2EE and spaces issues to web app team

webpack.config.js
With previous settings, our JS files for develop are so large that sentry's webserver rejects the upload.
In this change - 
* re-enable minification to reduce the size of the files
* update the CI sourcemap setting from `eval-source-map` to `source-map` to move the embedded source out of the .js payload and into .js.map files
This step fixed the issue for me locally at least by reducing the size of `init.js` from ~25MB to a 2MB js + 10MB .map
This PR also includes a careful refactor of the loading of build config depending on the args and environment, its best to follow this commit by commit.
---
A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change …
=> Update minification and sourcemap settings on CI builds for sentry

.github/workflows/triage-incoming.yml, .github/workflows/triage-move-labelled.yml, .github/workflows/triage-move-unlabelled.yml, .github/workflows/triage-priority-bugs.yml
This is better in case the tag is ever assigned to another commit.
---
=> Reference commits instead of tags in workflows

webpack.config.js
Reverts vector-im/element-web#19583
This change is causing the buildkite job to die during webpack (mostly likely OOM)
---
=> Revert "Update minification and sourcemap settings on CI builds for sentry"

webpack.config.js
Attempt #2 at https://github.com/vector-im/element-web/pull/19583 but disabling minification in CI, as it uses too much memory for our poor old buildkite agent
---
=> Sentry sourcemaps without CI minification

.github/workflows/triage-move-labelled.yml
This could fix the obscure "#ERROR# HttpError: Validation Failed" that
we're getting in failed actions.
---
=> Workflow: use our special token instead of github

.github/workflows/triage-move-labelled.yml
Docs say to use curly brackets, internet says that can break
multiline conditionals.
Trying to fix the if statement applying only to the first step in the job and
the second step ignoring the conditional.
---
=> Update triage workflow to fix conditional

docs/labs.md, element.io/develop/config.json, webpack.config.js
=> Document feature_spaces_metaspaces

src/vector/platform/WebPlatform.ts
For the web platform, rather than fetching the version of the app from a file on the server which it was downloaded from, fetch it from process.env.VERSION which is set at compile time.
This ensures that the version actually reflects the bundle which is currently running; this isn't necessarily true otherwise, consider after an update when the static files have been updated but the browser is still running an old version.
It also means we don't have to wait for a network request just to get the app's version.
The file this was previously fetched from is written during packaging at https://github.com/vector-im/element-web/blob/develop/scripts/package.sh#L25 - it's the same `VERSION` build variable but stripped of leading `v` if its a semver, which we replicate at runtime
---
This PR …
=> Get version from build VERSION variable

.github/workflows/triage-move-labelled.yml, .github/workflows/triage-move-unlabelled.yml, .github/workflows/triage-priority-bugs.yml
- Fix filtering for Design issues
- Split out spaces jobs for new and old boards, so they don't
depend on each other
- Remove voice message job for the old board
- Rename Priority bugs workflow to be shorter
- Improve naming for jobs so they're easier to read in the GitHub
Actions page
---
=> Issue workflow improvements

yarn.lock
This appears to have wanted to update all the dependencies of the react-sdk as well, but at least it avoids two widget apis running in release builds.
---
=> Fix widget-api dependency with a react-sdk upgrade

src/vector/platform/WebPlatform.ts
We need to strip the leading v from the local app version in `pollForUpdate` to ensure it compares correctly the version from the `/version` request indicating what the latest available version is. Previously, we only stripped the leading in `getAppVersion` which is used in some other places but not to decide whether an update is available.
Fixes https://github.com/vector-im/element-web/issues/20058
---
=> Normalize the local app version when checking for updates

Dockerfile, scripts/ci_package.sh, scripts/docker-package.sh, scripts/get-version-from-git.sh, scripts/normalize-version.sh, scripts/package.sh, src/vector/platform/WebPlatform.ts
Fixes https://github.com/vector-im/element-web/issues/20074
* Refactor generation of a git-hash-based version into get-version-from-git
* Refactor normalization of versions (stripping leading v) into normalize-version.sh
* Call get-version-from-git from ci_package.sh, call normalize-version from package.sh
* Refactor docker-write-version.sh into docker-package.sh, which both writes the
version file and invokes yarn build passing VERSION
* Normalize the version received from the server
---
=> Fix Docker build versioning

Dockerfile, scripts/ci_package.sh, scripts/docker-package.sh, scripts/get-version-from-git.sh, scripts/normalize-version.sh, scripts/package.sh, src/vector/platform/WebPlatform.ts
Push https://github.com/vector-im/element-web/pull/20077 to release-v1.9.6 branch
Note this release has already gone out, but for the parts of the change which affect the Docker build only, we can update without needing to do a hotfix of app.element.io 
---
=> Fix Docker build versioning (#20077)

src/vector/index.html
Signed-off-by: Kerry Archibald <kerrya@element.io>
Add `aria-hidden` and empty `alt` to hidden preload svgs
https://element-io.atlassian.net/browse/PSE-180
---
=> add aria-hidden and alt for preload svg images

.github/workflows/triage-move-review-requests.yml
pull_request doesn't have the right permissions for the action to work correctly as the action is being run on a forked project.
---
=> Update trigger for PR workflow

.github/workflows/triage-move-labelled.yml
Signed-off-by: ankur12-1610 <anknerd.12@gmail.com>
Fixes: #20016 
Added a job in `.github/workflows/triage-move-labelled.yml` which adds a `Z-Labs` label for the features behind labs flags.
Test:
---
=> Added a workflow to triage Labs issues better.

package.json, yarn.lock
Applies new spacing rules from https://github.com/matrix-org/eslint-plugin-matrix-org/pull/20. (No errors were found over here.)
This also changes to a published version for the ESLint plugin, which should avoid the Yarn cache hell caused by Git dependencies.
---
=> Fix spacing errors

scripts/fetch-develop.deps.sh
Prevents this:
```
+ git clone git://github.com/matrix-org/matrix-js-sdk.git matrix-js-sdk --branch develop --depth 1
Cloning into 'matrix-js-sdk'...
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
---
=> Fix git protocol usage for CI

.github/workflows/triage-move-unlabelled.yml
Signed-off-by: ankur12-1610 <anknerd.12@gmail.com>
Fixes: #20376
Workflow run:
---
=> Added a workflow to remove Z-Labs label.

config.sample.json, docs/config.md, docs/jitsi.md, docs/kubernetes.md, scripts/build-jitsi.js
Related https://github.com/matrix-org/matrix-react-sdk/pull/7514
---
=> Update default Jitsi URLs to meet.element.io

src/vector/jitsi/index.ts
Signed-off-by: Kerry Archibald <kerrya@element.io>
Fixes: https://github.com/vector-im/element-web/issues/20637
https://element-io.atlassian.net/browse/PSE-272
Before:
https://user-images.githubusercontent.com/3055605/150136483-b0c9d562-f7fc-4cb3-ad1a-cec6e35c38bb.mov
After:
https://user-images.githubusercontent.com/3055605/150136781-a0df4080-eedb-4804-93f2-810ce987954c.mov
---
=> Persist jitsi only after meeting is joined

docs/labs.md, element.io/develop/config.json
Requires https://github.com/matrix-org/matrix-react-sdk/pull/7613
---
=> De-labs Metaspaces

config.sample.json, element.io/app/config.json, element.io/develop/config.json
This adds a new setting implemented in matrix-org/matrix-react-sdk#7598 to avoid cluttering the main rageshake repo with UISI autorageshakes.
---
=> Set app name for UISI autorageshakes in sample config and element.io configs

nginx/conf.d/default.conf
These files are the minimal set that should be uncached to help element-web to rapidly respond to config and version updates. We currently only handle the index.html page but we should also look at config.json and version as we will treat these specially on develop.element.io and staging.element.io
This is related to the issue #20033 , where we also needed to make sure these were uncached; i thought we should do it here for completeness too.
To test:
```
docker pull vectorim/element-web:latest
docker build -t element-web:nginx-changes .
docker run -p 50000:80 vectorim/element-web:latest
curl -v http://localhost:50000/ > /dev/null # note cache-control: no-cache header is set
curl -v http://localhost:50000/version > /dev/null # note cache-control: no-cache header is NOT set
curl -v …
```
=> Add Cache-Control: no-cache headers for non-bundled files in docker container.

docs/labs.md
Document jump to date labs feature
Feature added in:
- https://github.com/matrix-org/matrix-react-sdk/pull/7339
- https://github.com/matrix-org/matrix-react-sdk/pull/7372
- MSC3030: https://github.com/matrix-org/matrix-doc/pull/303
---
=> Document jump to date labs feature (MSC3030)

docs/labs.md
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/7703
---
=> Remove the Location Sharing labs feature

.github/workflows/triage-labelled.yml
Updates the list of labels behind labs flags to reflect the release of polls and message bubbles.
Notes: none
---
=> Update labs issue labels

element.io/develop/config.json
=> Enable new search experience by default on Develop & Nightly

package.json, webpack.config.js, yarn.lock
We don't appear to currently use any of the syntax `postcss-extend` enables, and
also this is community plugin which no longer works with newer PostCSS core
versions, so it would become an obstacle in the future if we wanted to upgrade.
---
=> Remove postcss-extend

src/vector/platform/ElectronPlatform.tsx
Improves https://github.com/vector-im/element-web/issues/21049#issuecomment-1039034559
Type: defect
---
* Fix command key missing in keyboard shortcuts tab ([\#21102](https://github.com/vector-im/element-web/pull/21102)). Contributed by @SimonBrandner.
=> Fix command key missing in keyboard shortcuts tab

docs/customisations.md, webpack.config.js
Intended for customisation endpoints - see included docs.
**Note**: there is internal context available on this change. Please ping me internally if curious/required.
`T-Task` because it's not really a "feature" in the traditional/useful sense.
---
=> Make customisations (and general file overrides) easier to specify

docs/config.md, src/vector/jitsi/index.ts
Stop-gap for https://github.com/vector-im/element-web/issues/20503
No tests for this because it's painful, sorry.
---
* Add a config.json option to skip the built-in Jitsi welcome screen ([\#21190](https://github.com/vector-im/element-web/pull/21190)).
=> Add a config.json option to skip the built-in Jitsi welcome screen

docs/config.md
=> Add docs for `logout_redirect_url`

.eslintrc.js, docs/translating-dev.md, src/vector/app.tsx, test/app-tests/joining-test.tsx, test/app-tests/loading-test.tsx
Paired with https://github.com/matrix-org/matrix-react-sdk/pull/7933
---
=> Mandate use of js-sdk/src/matrix import over js-sdk/src

webpack.config.js
Fixes: https://github.com/vector-im/element-web/issues/21293
Electron:
img tag require import left for theme switcher, css import top right buttons
and react component import:
---
=> fix webpack path handling for svg imports in electron

src/vector/index.html
Fixes: #21292
(Do we still need these at all?)
---
=> fix prefetch

tsconfig.json
TypeScript supports checking for "unused locals", which actually includes
locals, private fields, private methods, etc. If a private thing is actually
needed as part of the API surface, you can change it to public to resolve the
error.
This seems like a good check to have, as it highlights unused bits of code that
perhaps got lost while refactoring. This changes our config to reject them and
fixes up a few existing cases.
See also https://github.com/matrix-org/matrix-react-sdk/pull/8007, https://github.com/matrix-org/matrix-js-sdk/pull/2223
---
=> Add lint for unused locals

test/app-tests/joining-test.tsx, test/app-tests/loading-test.tsx
For https://github.com/matrix-org/matrix-react-sdk/pull/8019
---
=> Add mock to /versions API endpoint

src/vector/app.tsx, src/vector/platform/WebPlatform.ts, src/vector/routing.ts
Remove the hash event listener before reloading the page, as the reload was being swallowed by our router.
This prevented https://github.com/vector-im/element-web/pull/21272/ from working when the app was loaded (it works when the app isn't loaded).
Along the way, refactor out routing logic form app.tsx to avoid causing a circular import, and add logging for the updater so we can trace whats going on in rageshakes.
cc: @andybalaam 
partly mitigates https://github.com/vector-im/element-web/issues/9422
---
A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for …
=> Fix page reloading on initial update

config.sample.json, docs/config.md, docs/kubernetes.md, docs/theming.md, src/async-components/structures/CompatibilityView.tsx, src/components/views/auth/VectorAuthFooter.tsx, src/components/views/auth/VectorAuthHeaderLogo.tsx, src/components/views/auth/VectorAuthPage.tsx, src/vector/app.tsx, src/vector/getconfig.ts, src/vector/init.tsx, src/vector/jitsi/index.ts, src/vector/platform/ElectronPlatform.tsx, src/vector/platform/VectorBasePlatform.ts
Partnered with https://github.com/matrix-org/matrix-react-sdk/pull/8062
**Review with https://github.com/matrix-org/matrix-react-sdk/pull/8062**
*Note*: I went completely overboard and decided to rewrite most of the config.md documentation - it was getting annoying to edit, and had missing options. The detail that was previously there should have been maintained.
---
=> Update SdkConfig usage to use new translation layer + update config.md docs

README.md
While we do technically support v14, it's fallen into security releases. Let's recommend that people use whatever nodejs itself recommends instead.
---
=> Update nodejs version requirements

docs/labs.md, src/vector/jitsi/index.ts
See https://github.com/matrix-org/matrix-react-sdk/pull/8084 for the full details.
Notes: none
(notes are in the react-sdk PR)
---
=> Voice rooms prototype

README.md
Change the language from "If desired" to "Configure" to ensure people do not miss this step, as skipping this step will show the error "Invalid configuration: no default server specified." as this is a required part of configuration.
I chose these words by copying the text from the compiling from source section (see https://github.com/vector-im/element-web/blob/develop/README.md?plain=1#L135 )
---
=> Docs: Require creation of config.json as part of Getting Started

docs/config.md
Fix typo with `show_labs_settings` and document the optional `latex_maths_delims` developer option.
Signed-off-by: Sven Mäder <maeder@phys.ethz.ch>
---
=> Fix show_labs_settings config.md typo

docs/translating.md
=> Fix typo in translation docs

src/vector/jitsi/index.ts
The hangup event may or may not be handled, so we need to account for
cases where it throws an error.
Type: defect
Notes: none
Closes https://github.com/vector-im/element-web/issues/21648.
---
=> Fix stuck persistence of Jitsi widgets

src/vector/jitsi/index.scss, src/vector/jitsi/index.ts
This is important for video rooms, which always skip the prejoin screen.
Type: defect
---
* Avoid flashing the Jitsi prejoin screen at the user before skipping it ([\#21665](https://github.com/vector-im/element-web/pull/21665)).
=> Avoid flashing the Jitsi prejoin screen at the user before skipping it

src/vector/jitsi/index.ts
Type: enhancement
Closes https://github.com/vector-im/element-web/issues/21517.
---
* Handle forced disconnects from Jitsi ([\#21697](https://github.com/vector-im/element-web/pull/21697)). Fixes #21517.
=> Handle forced disconnects from Jitsi

src/vector/jitsi/index.ts
To review alongside https://github.com/matrix-org/matrix-react-sdk/pull/8287
Type: enhancement
Notes: none
(notes handled in the react-sdk PR)
---
=> Show a lobby screen in video rooms

src/vector/platform/WebPlatform.ts
Firefox is now auto-reloading when it detects a stale version, but it still doesn't seem to be pulling a new copy of the page from the cache.
Try passing the new version as the valued of `updated` to see if it'll bust the cache.
Another change attempting to resolve [9422](https://github.com/vector-im/element-web/issues/9422)
---
=> When auto-reloading, pass the new version in the updated param to attempt to cachebust

.github/workflows/triage-labelled.yml
Add 'Team: Delight' and 'Z-NewUserJourney' to the Delight board
---
=> Add github automation for new labels

src/vector/jitsi/index.ts
In rare cases with certain deployments, Jitsi Meet would explode upon setting the display name, due to these commands racing with the app's startup.
Type: defect
---
* Fix Jitsi Meet getting wedged at startup in some cases ([\#21995](https://github.com/vector-im/element-web/pull/21995)).
=> Fix Jitsi Meet getting wedged at startup in some cases

src/vector/jitsi/index.ts
By not closing Jitsi fully when an error occurs, it could get stuck in PiP mode with no way to dismiss.
---
* Fully close Jitsi conferences on errors ([\#22060](https://github.com/vector-im/element-web/pull/22060)).
=> Fully close Jitsi conferences on errors

docs/labs.md
For https://github.com/matrix-org/matrix-react-sdk/pull/8521
---
=> Remove docs for now-defunct labs flags

src/vector/jitsi/index.ts
Device labels can be blank, which makes them falsy even though they're still a valid device.
---
* Fix video rooms sometimes connecting muted when they shouldn't ([\#22125](https://github.com/vector-im/element-web/pull/22125)).
=> Fix video rooms sometimes connecting muted when they shouldn't

.github/workflows/static_analysis.yaml, scripts/copy-res.js
=> Update weblateToCounterpart to be more resilient

.github/workflows/triage-labelled.yml, .github/workflows/triage-priority-bugs.yml
The spaces responsibilities have shifted and is not looked after by the Delight team anymore.
Spaces issues will not be added to the Delight board anymore, and spaces issues will now show up in the P1 column of the app team
---
=> Remove spaces to delight board automation

src/vector/jitsi/index.ts
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/8643
**:warning: Reviewer: If no further changes are requested, please merge this and https://github.com/matrix-org/matrix-react-sdk/pull/8643 in the morning on my behalf so that we can have Jitsi logs included in any rageshakes coming out of this week's community testing session.** SonarCloud isn't happy with me using a fork, so I have no idea if automerge will work.
---
=> Patch Jitsi logs into rageshakes

.github/workflows/sonarqube.yml
Which always points to refs develop
---
=> Fix wrongly using github.ref in workflow_run actions concurrency

release.sh
Requires https://github.com/matrix-org/matrix-js-sdk/pull/2382
---
=> Remove stale release.sh parameter for no-jsdoc

src/vector/jitsi/index.ts
Notes: none
(no notes because this was regressed by https://github.com/vector-im/element-web/pull/22270, which is not yet in a release)
Closes https://github.com/vector-im/element-web/issues/22285
---
=> Work around a Jitsi log handling crash

src/vector/jitsi/index.ts
For https://github.com/matrix-org/matrix-react-sdk/pull/8701
Notes: none
(notes handled in the react-sdk PR)
---
=> Show a dialog when Jitsi encounters an error

.eslintrc.js
Per change also made on https://github.com/matrix-org/matrix-js-sdk/pull/2402
---
=> Disable no-non-null assertions lint rule

src/vector/jitsi/index.ts
Closes https://github.com/vector-im/element-web/issues/22521
---
* Work around a Jitsi bug with display name encoding ([\#22525](https://github.com/vector-im/element-web/pull/22525)). Fixes #22521.
=> Work around a Jitsi bug with display name encoding

src/i18n/strings/en_EN.json, src/vector/platform/ElectronPlatform.tsx, src/vector/platform/IPCManager.ts, src/vector/platform/PWAPlatform.ts, src/vector/platform/SeshatIndexManager.ts, src/vector/platform/VectorBasePlatform.ts, src/vector/platform/WebPlatform.ts
Requires https://github.com/vector-im/element-desktop/pull/375
I suggest reviewing commit-by-commit
---
=> Abstract electron settings properly to avoid boilerplate-hell

src/vector/jitsi/index.ts
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/8909
Closes https://github.com/vector-im/element-web/issues/22637
---
* Connect to Jitsi unmuted by default ([\#22660](https://github.com/vector-im/element-web/pull/22660)). Fixes #22637.
=> Connect to Jitsi unmuted by default

src/vector/jitsi/index.ts
If you forget to call `preventDefault` in widget action handlers, matrix-widget-api logs a bunch of errors complaining that the action is unsupported/unhandled, even if it isn't.
---
* Reduce video rooms log spam ([\#22665](https://github.com/vector-im/element-web/pull/22665)).
=> Reduce video rooms log spam

src/vector/jitsi/index.ts
Closes https://github.com/vector-im/element-web/issues/22805
---
* Remove the ability to hide yourself in video rooms ([\#22806](https://github.com/vector-im/element-web/pull/22806)). Fixes #22805.
=> Remove the ability to hide yourself in video rooms

src/vector/jitsi/index.ts, src/vector/platform/ElectronPlatform.tsx
As a stopgap solution for https://github.com/vector-im/element-web/issues/4880, we can hide the screensharing button in video rooms if the platform doesn't support it.
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/9045
Notes: none
(notes handled in the react-sdk PR)
---
=> Hide screenshare button in video rooms on Desktop

.github/workflows/build_develop.yml
This way we don't publish to develop.element.io a broken package
---
=> To consider develop built, block on static analysis & tests

package.json, yarn.lock
olm version was bumped in matrix-js-sdk in https://github.com/matrix-org/matrix-js-sdk/pull/2320
---
=> bump olm version to match bump in matrix-js-sdk

docs/labs.md
For https://github.com/matrix-org/matrix-react-sdk/pull/8764
---
=> Show current avatar and name for users in message history

.github/workflows/static_analysis.yaml
Related https://github.com/matrix-org/matrix-js-sdk/pull/2615
---
=> Add static analysis for tsc --strict

.github/workflows/dockerhub.yaml
=> Disable docker overwriting `latest` tag for RCs

package.json
I managed to mess up https://github.com/vector-im/element-web/pull/23236, leaving the lockfile in an unclean state
---
=> Fix the lockfile again

yarn.lock
Follow-up to https://github.com/vector-im/element-web/pull/23280
`yarn install` was causing the lockfile to be modified because I got this version number wrong.
---
=> Fix the lockfile, take 3

config.sample.json, docs/config.md
For https://github.com/matrix-org/matrix-react-sdk/pull/9347
---
* Add Element Call `brand` ([\#23443](https://github.com/vector-im/element-web/pull/23443)).
=> Add Element Call `brand`

docs/config.md
Signed-off-by: lukas <lukas.walter@aceart.de>
see https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$4h2hU_fKQV55TcNZuQ6co23xeMRFqHmRQuDaQdEtezo?via=matrix.org&via=privacytools.io&via=mozilla.org
@t3chguy cc
---
=> Update documentation on how to disable integration managers

package.json, src/vector/jitsi/index.ts, yarn.lock
And add missing @types/jsrsasign dependency
---
* Fix config.json failing to load for Jitsi wrapper in non-root deployment ([\#23577](https://github.com/vector-im/element-web/pull/23577)).
=> Fix config.json failing to load for Jitsi wrapper in non-root deployment

Dockerfile
Should dramatically improve dockerhub build times
BuildKit will de-dup the webpack build between the arches as well as never doing a webpack build in arm where the terser takes an hour.
---
=> Run dockerhub builder stage without emulation

.github/workflows/triage-labelled.yml
Z-Labs labels should be added to  A-Composer-WYSIWYG so that they're excluded from stats and weekly issue review
CC @andybalaam - needs to be updated when feature comes out of labs
---
=> Update issue automation for labs features

.github/workflows/triage-labelled.yml
Changing `A-Composer-WYSIWYG` to `A-Rich-Text-Editor`. There were two labels in play on some repos and the latter reflects more accurately our ongoing naming for the feature.
---
=> Change label in automation to for the rich text editor

.github/workflows/triage-labelled.yml
All "good first issue" and "Hacktoberfest" qualify as "Help Wanted" so the label should be added automatically
---
=> Add issue automation to tidy Help Wanted

.github/workflows/static_analysis.yaml
=> Enable tsc --strict CI to prevent gaining more errors

yarn.lock
This unbreaks CI by removing patch-package from js-sdk
---
=> Update matrix-events-sdk to 0.0.1 and develop ref to matrix-js-sdk

release.sh, scripts/ci_package.sh, scripts/docker-link-repos.sh, scripts/docker-package.sh, scripts/fetch-develop.deps.sh, scripts/get-version-from-git.sh, scripts/layered.sh, scripts/make-icons.sh, scripts/normalize-version.sh, scripts/package.sh
Some operating systems, such as NixOS, don't place binaries in `/bin`. The appropriate cross-platform method is to use `/usr/bin/env`.
Notes: Make build scripts work on NixOS
---
* Make build scripts work on NixOS ([\#23740](https://github.com/vector-im/element-web/pull/23740)).
=> Don't hardcode /bin/bash in scripts

.github/workflows/build_develop.yml
Requires https://github.com/vector-im/element-desktop/pull/450
The branch can then also be cleaned up
---
=> Cease uploading develop.tar.gz to Github Pages

.github/workflows/static_analysis.yaml
=> Add --noImplicitAny to strict CI check

package.json, yarn.lock
This is a reintroduction of https://github.com/vector-im/element-web/pull/23894 since https://github.com/vector-im/element-web/pull/24027 regressed it. style-loader 3 isn't compatible with Webpack 4, and causes build errors:
```
2023-01-03 20:29:40.725 [element-js] ERROR in ../matrix-react-sdk/res/themes/light/css/light.pcss
2023-01-03 20:29:40.725 [element-js] Module build failed (from ./node_modules/style-loader/dist/cjs.js):
2023-01-03 20:29:40.725 [element-js] TypeError: this.getOptions is not a function
2023-01-03 20:29:40.725 [element-js]     at Object.loader (/home/robin/code/element-web/element-web/node_modules/style-loader/dist/index.js:19:24)
```
---
=> Downgrade to style-loader 2 to regain Webpack 4 compatibility

webpack.config.js
In an attempt to fix the CSP problem caused by upgrading to worker-loader v3, explicitly set worker-loader's publicPath to "webapp" so the change in default does not cause problems on upgrade.
---
=> Explicitly set worker-loader's publicPath to webapp

package.json, webpack.config.js, yarn.lock
Fixes https://github.com/vector-im/element-web/issues/24157
See the issue for evidence that this fix works (hopefully).
---
=> Upgrade worker loader to v3 (with config fix to prevent bundling)

babel.config.js
This should fix any future problems along the lines of https://github.com/matrix-org/matrix-js-sdk/pull/3022.
---
=> Configure babel to transform logical assignment

docs/config.md
=> Update config.md - these UIFeature flags died with communities

docs/labs.md
=> labs.md: add notes about `feature_rust_crypto`

yarn.lock
Attempting to understand why https://github.com/vector-im/element-web/pull/24131 is failing by upgrading small pieces at a time.
I literally just ran
```
yarn upgrade --pattern eslint
```
---
=> yarn upgrade all eslint packages

docs/betas.md, docs/labs.md
See https://github.com/matrix-org/matrix-react-sdk/pull/9878 for context 
Fixes https://github.com/vector-im/element-web/issues/24552
---
=> Remove reference to threads in labs

src/vector/jitsi/index.ts
Jitsi itself now uses the current language of the user. However, this does not yet apply to the welcome page of the Jitsi widget that says "Join conference", which is only hard-coded to english for now.
This pulls out some changes from https://github.com/vector-im/element-web/pull/23412 which seems to be unlikely to be merged soon.
Signed-off-by: Oliver Sand <oliver.sand@nordeck.net>
Type: enhancement
---
* Pass current language into Jitsi ([\#24609](https://github.com/vector-im/element-web/pull/24609)). …
=> Pass current language into Jitsi (#24609

README.md
Firefox dropped support for this quite a while back and Safari only supports it on iOS which is not a supported OS for this project.
---
* Remove experimental PWA support for Firefox and Safari ([\#24630](https://github.com/vector-im/element-web/pull/24630)).
=> Remove experimental PWA support for Firefox and Safari

package.json
Most people probably only want the dev server to listen on localhost.
Additionally, overriding with `--host 0.0.0.0` here prevents passing a different value for `--host` to yarn. For example:
```
$ yarnpkg start:js --host=::
yarn run v1.22.19
$ webpack-dev-server --host=0.0.0.0 --output-filename=bundles/_dev_/[name].js --output-chunk-filename=bundles/_dev_/[name].js -w --mode development --disable-host-check --hot --host=::
Unset VERSION variable - this may affect build output
✖ ｢wds｣: webpack Dev Server Invalid Options
options.host should be {String|Null} (https://webpack.js.org/configuration/dev-server/#devserverhost)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
-   [ ] Tests written for new code (and old …
=> package.json: Remove --host override

.stylelintrc.js, package.json
Requires https://github.com/matrix-org/matrix-react-sdk/pull/10325
---
=> Remove deprecated stylelint rules which are handled by prettier

.github/workflows/backport.yml, .github/workflows/dockerhub.yaml, .github/workflows/static_analysis.yaml, .github/workflows/tests.yaml
Type: Task
Related: https://github.com/matrix-org/matrix-js-sdk/pull/3208
Related: https://github.com/matrix-org/matrix-react-sdk/pull/10351
Related: https://github.com/vector-im/element-web/pull/24786
Previously, we used tags to version third-party actions. t3chguy suggested we should pin them to specific commit hashes by default.
---
=> Pin versions of third-party github actions

src/vector/jitsi/index.ts
Should be merged together with https://github.com/matrix-org/matrix-react-sdk/pull/10376
We have the use case that we don't want to activate the video and/or audio of Jitsi participants by default. There is the `isAudioOnly` flag, but that has some side effects, like that a joining user must activate their camera before being able to see others who have their camera activated (hence "audio only").
This PR proposes to add flags for both the [`startWithAudioMuted`](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-configuration/#startwithaudiomuted) and [`startWithVideoMuted`](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-configuration/#startwithvideomuted) configs. These settings can be set when adding the jitsi widget to a room (we do that with a bot for example). …
=> Add API params to mute audio and/or video in Jitsi calls by default

README.md
Safari major versions work differently than any other browsers. It is tied to the OS version that is very rarely updated.
Release cadence has changed internally at Apple, and it makes sense now to do support the last 2 versions rather than the last 2 major.
---
=> Update safari support policy

.github/ISSUE_TEMPLATE/config.yml
We currently have the blank template disabled. This is limiting though as there are cases where an issue can't reasonably follow one of the other templates. As an example, many of the issues we _create_ to work on in the web app team cannot sensibly follow the template.
There was possibly a problem with spam or low quality reports in the past that has led to the blank template being disabled. Since the option appears to show at caption size at the very bottom of the list, I don't expect this to be a large problem though.
---
=> Enable blank issue template

babel.config.js, package.json, webpack.config.js, yarn.lock
Reverts vector-im/element-web#25152
Fixes https://github.com/vector-im/element-web/issues/25161
=> Revert "Strip data-testid in production builds" (#25163

code_style.md
Per https://github.com/matrix-org/matrix-react-sdk/pull/10686, these don't make much sense at the moment.
---
=> Deprecate `$spacing` variables

.eslintrc.js, package.json, src/@types/jitsi-meet.d.ts, src/async-components/structures/CompatibilityView.tsx, src/components/views/auth/VectorAuthPage.tsx, src/favicon.ts, src/vector/app.tsx, src/vector/getconfig.ts, src/vector/index.ts, src/vector/init.tsx, src/vector/jitsi/index.ts, src/vector/mobile_guide/index.ts, src/vector/platform/ElectronPlatform.tsx, src/vector/platform/IPCManager.ts, src/vector/platform/SeshatIndexManager.ts, src/vector/platform/VectorBasePlatform.ts, src/vector/platform/WebPlatform.ts, src/vector/routing.ts, test/app-tests/loading-test.tsx, test/unit-tests/favicon-test.ts, test/unit-tests/vector/getconfig-test.ts, test/unit-tests/vector/platform/ElectronPlatform-test.ts, test/unit-tests/vector/platform/WebPlatform-test.ts, test/unit-tests/vector/routing-test.ts, test/unit-tests/vector/url_utils-test.ts, yarn.lock
Requires https://github.com/matrix-org/matrix-react-sdk/pull/10691
For https://github.com/vector-im/element-web/issues/23542
---
=> Conform more of the codebase with `noImplicitAny` and `strictNullChecks` (#25174

src/vector/index.html, webpack.config.js
Doesn't close any known exploits but is good hygiene
---
* Improve Content-Security-Policy ([\#25210](https://github.com/vector-im/element-web/pull/25210)).
=> Improve Content-Security-Policy

test/app-tests/loading-test.tsx
Fix https://github.com/vector-im/element-web/issues/24769
(hopefully, again)
---
=> Ensure we actually wait for the login form to appear in loading-test

src/vector/index.html
should be merged before https://github.com/matrix-org/matrix-react-sdk/pull/10654
---
=> Add error notification audio

package.json, webpack.config.js, yarn.lock
For https://github.com/vector-im/element-web/issues/2498
Before 14.5 MB bundle.js
After 13.28 MB bundle.js
---
=> Improve bundle size and add webpack-bundle-analyzer

src/vector/getconfig.ts
Fixes https://github.com/vector-im/element-web/issues/8858
---
* Handle trailing dot FQDNs for domain-specific config.json files ([\#25351](https://github.com/vector-im/element-web/pull/25351)). Fixes #8858.
=> Handle trailing dot FQDNs for domain-specific config.json files

package.json
Without this it can't analyse the bundles only the stats
---
=> Fix analyse:webpack-bundles script

src/vector/app.tsx
The configuration `{ "sso_redirect_options": { "on_welcome_page": true } }` automatically redirects the user to the SSO login when they open Element for the first time. However, this only works if a user opens the URLs `https://my.element.local/#` or `https://my.element.local/#/welcome`. This PR adds the option to also support `https://my.element.local/` which is a more usual link when the user types in the URL manually or has a link in e.g. a company portal.
I didn't add a test because I'm unsure how to test it properly. Would that be ok? If you would prefer to have a test, I could try to add them to `loading-test.tsx`.
-   [x] Sign-off given on the changes (see …
=> Redirect to the SSO page if `sso_redirect_options.on_welcome_page` is enabled and the URL hash is empty

docs/config.md
For https://github.com/matrix-org/matrix-react-sdk/pull/11044
---
=> Add documentation for config to skip widget_build_url for DM rooms

element.io/develop/config.json
This is an experimental version of Element Call using a LiveKit SFU that we'd like to start dogfooding and gaining confidence on internally, so the current plan is to trial it on develop.element.io and Nightly for a while.
Depends on https://github.com/vector-im/element-call/pull/1127
See also https://github.com/vector-im/element-desktop/pull/1028
---
=> Point develop.element.io to our Element Call + LiveKit experiment

element.io/develop/config.json
Reverts vector-im/element-web#25636
The widget version of livekit element call is cannot be testes. We wait until it is testable in the widget version and than change it back to the livekit url.
---
=> Revert "Point develop.element.io to our Element Call + LiveKit experiment"

docs/e2ee.md
https://github.com/vector-im/customer-retainer/issues/83
Implementation:
https://github.com/matrix-org/matrix-react-sdk/pull/11120
https://github.com/matrix-org/matrix-react-sdk/pull/11122
https://github.com/matrix-org/matrix-react-sdk/pull/11125
---
=> Document `io.element.e2ee.force_disable`

docs/customisations.md, webpack.config.js
Fixes https://github.com/vector-im/element-web/issues/25733
---
* Deprecate customisations in favour of Module API ([\#25736](https://github.com/vector-im/element-web/pull/25736)). Fixes #25733.
=> Deprecate customisations in favour of Module API

docs/config.md, src/i18n/strings/en_EN.json, src/vector/app.tsx, src/vector/mobile_guide/index.ts, test/app-tests/server-config-test.ts
Closes https://github.com/vector-im/element-web/pull/19695
For https://github.com/vector-im/element-web/issues/11154
The configuration provided with default_server_config can be used as a suitable fallback in case the well-known discovery failed.
Using either of `default_server_config` or `default_server_name` is still supported and works like before.
---
* Allow default_server_config as a fallback config ([\#25682](https://github.com/vector-im/element-web/pull/25682)). Contributed by @ShadowRZ.
=> Allow default_server_config as a fallback config

docs/config.md
Requires https://github.com/matrix-org/matrix-react-sdk/pull/11261
This is to lower the maintenance & support burden when users try and mix both variants in the same configuration and the confusion that may cause.
---
* Deprecate camelCase config options ([\#25800](https://github.com/vector-im/element-web/pull/25800)).
=> Deprecate camelCase config options

src/@types/global.d.ts, src/vector/platform/ElectronPlatform.tsx, test/unit-tests/vector/platform/ElectronPlatform-test.ts
See https://github.com/electron/electron/pull/30702 - this has the benefit of the js-sdk and LiveKit not having to add custom logic for Electron
Requires https://github.com/vector-im/element-desktop/pull/1081
Requires https://github.com/matrix-org/matrix-react-sdk/pull/11266
---
=> Switch to the new `session` API for screen-sharing

package.json, webpack.config.js
matrix-react-sdk consumes them and has its own dependencies to them
---
=> Remove redundant dependencies

docs/labs.md, element.io/develop/config.json
Some things seems to have been forgotten in that file...
Removed all `feature_` that had no references anymore when doing a project wide search across JS/React/EW/ED
---
=> Removing stale labs flag

webpack.config.js
Fixes https://github.com/vector-im/element-web/issues/25905
For https://github.com/vector-im/element-web/issues/25883
To review alongside https://github.com/matrix-org/matrix-react-sdk/pull/11354
---
=> Transpile @vector-im/compound-web with babel

.github/workflows/build_debian.yaml, debian/conffiles, debian/control
For https://github.com/vector-im/element-web/issues/2777
---
* Package release builds of element-web in package.element.io debs ([\#25198](https://github.com/vector-im/element-web/pull/25198)).
=> Package release builds of element-web in package.element.io debs

docs/labs.md
We @nordeck are currently implementing the knock rooms behind the feature flag `feature_ask_to_join` (introduced in https://github.com/matrix-org/matrix-react-sdk/pull/11182).
This pull request updates the labs.md for knock rooms.
- https://github.com/matrix-org/matrix-react-sdk/pull/11353
- https://github.com/matrix-org/matrix-js-sdk/pull/3647
- https://github.com/matrix-org/matrix-react-sdk/pull/11248
- https://github.com/matrix-org/matrix-react-sdk/pull/11182
---
* Update labs.md for knock rooms …
=> Update labs.md for knock rooms

jest.config.ts
=> Update setupFilesAfterEnv to TS

webpack.config.js
Fixes an issue where the path separator is incorrect for Windows systems
---
* Fix path separator for Windows based systems ([\#25997](https://github.com/vector-im/element-web/pull/25997)).
=> Fix path separator for Windows based systems

module_system/installer.ts, package.json, webpack.config.js, yarn.lock
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/11395.
This PR includes two more changes:
Based on the discussion in [#element-dev:matrix.org](https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$0eFIe7B850Og0VsX3_AyACHcZVrva7Wzi3d25JfZOT0?via=matrix.org&via=element.io&via=envs.net). Gist: The semantic version of the Module API is not a good indicator for the compatibility of a module to the client. Element can accept modules that run on older versions of the module api as long as the Module-Surface-API stays compatible. If any non-backwards compatible change to the Module part of the API happens, this list must be reset.
This was already the case without **1.**, but now it is inevitable. Some parts of the Module API [rely on global …
=> Bump @matrix-org/react-sdk-module-api from 1.0.0 to 2.0.0

scripts/copy-res.js
For https://github.com/vector-im/element-web/issues/25608
For https://github.com/matrix-org/matrix-react-sdk/pull/11427
---
=> Simplify languages.json file and grab language names from Intl

webpack.config.js
Fixes the issue where builds would fail on Windows systems
```
OptimizeCssAssetsWebpackPluginError: EINVAL: invalid argument, mkdir 'C:\element-web\webapp\C:\matrix-react-sdk\node_modules\@vector-im\compound-design-tokens\icons'
```
Currently scoped to Compound packages only. Rationale explained in code comments
---
* Fix compound external assets path in bundle ([\#26069](https://github.com/vector-im/element-web/pull/26069)).
=> Fix compound external assets path in bundle

webpack.config.js
Needed for tooltips to work on icons, https://github.com/vector-im/compound/issues/152
Radix UI uses the [`asChild` pattern](https://www.radix-ui.com/primitives/docs/guides/composition) that relies heavily on forwarded refs in React. 
See https://react-svgr.com/docs/options/#ref
---
* Make SVGR icons use forward ref ([\#26082](https://github.com/vector-im/element-web/pull/26082)).
=> Make SVGR icons use forward ref

src/vector/index.html, webpack.config.js
This solves problems wherein the javascript debugger would get confused and
show the execution point two lines away from the source.
---
=> Move the unhomoglyph data to its own file

element.io/develop/config.json
Early feedback indicates that the defaulting happened prematurely.
This undoes https://github.com/vector-im/element-web/pull/26089.
---
=> Turn off new room header by default

docs/config.md
=> Improve config.md docs on `custom_translations_url`

package.json, yarn.lock
Translations were missing when we deployed today's release to staging, and we think this was why. The running cod didn't have a key separator set in counterpart.
---
* Bump matrix-web-i18n to 3.1.3 for KEY_SEPARATOR ([\#26287](https://github.com/vector-im/element-web/pull/26287)). Contributed by @andybalaam.
=> Bump matrix-web-i18n to 3.1.3 for KEY_SEPARATOR

.github/workflows/triage-labelled.yml
=> Remove former PS teams from issue automation

CONTRIBUTING.md
This PR addresses a minor issue in the CONTRIBUTING.md file under [Sign off](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md#sign-off) where the link to the Linux Kernel documentation have been moved to another link as described in (https://www.kernel.org/doc/Documentation/SubmittingPatches).
Signed-off-by: dharshan <dharshan2457@gmail.com>
Before:
- [Linux Kernel doc link](https://www.kernel.org/doc/Documentation/SubmittingPatches)
After:
- [Linux Kernel doc link](https://www.kernel.org/doc/html/latest/process/submitting-patches.html)
This change is trivial and should have no functional impact on the project. It simply ensures that contributors can easily access the correct Linux Kernel documentation for submitting-patches.
Please review and merge this PR. Thank …
=> Update Linux Kernel link in CONTRIBUTING.md

res/manifest.json, src/async-components/structures/CompatibilityView.tsx
Optimisations found during https://github.com/matrix-org/matrix-react-sdk/pull/11741
---
=> Remove hardcoded defaults and update manifest.json

element.io/develop/config.json
We've switched from Netlify to an in-house Kubernetes deployment with a new URL.
---
=> Update the Element Call unstable URL

src/vector/app.tsx, src/vector/init.tsx, test/app-tests/server-config-test.ts, test/app-tests/wrapper-test.tsx
When a module with the [WrapperLifecycle](https://github.com/matrix-org/matrix-react-sdk-module-api/blob/dae6a5ad26af9a2336520753035e28f2e2035549/src/lifecycles/WrapperLifecycle.ts) is active, some features don't work anymore. This affects for example the [`navigateTo`](https://github.com/matrix-org/matrix-widget-api/blob/9ab62e72c8b98087edcf1748d8c9c9f75631d030/src/WidgetApi.ts#L590-L598) feature of the Widget API. This is caused because the `hashchange` event listener is depending [on the `window.matrixChat` variable](https://github.com/nordeck/element-web/blob/53bf443dbbaefb9bf3031564a60c2ae2d88dc526/src/vector/routing.ts#L37-L43), but that is not pointing to the `MatrixChat` component when a Wrapper component is added.
We now worked-around the issue by making the Wrapper a class and …
=> Correctly fill window.matrixChat even when a Wrapper module is active

docs/config.md
=> Document `feedback.new_issue_url` & `feedback.existing_issues_url`

.github/workflows/build_debian.yaml, debian/.gitignore, debian/control
Fixes https://github.com/vector-im/element-web/issues/2777
---
* Ship element-web as a debian package ([\#26533](https://github.com/vector-im/element-web/pull/26533)). Fixes #2777.
=> Ship element-web as a debian package

docs/labs.md
---
* Add feature_disable_call_per_sender_encryption documentation (in labs.md) ([\#26548](https://github.com/vector-im/element-web/pull/26548)). Contributed by @toger5.
=> Add feature_disable_call_per_sender_encryption documentation (in labs.md)

.github/workflows/sync-labels.yml
=> Set up rudimentary workflow for manually triggering label sync

book.toml, docs/css/custom.css
| Before | After |
| ------ | ----- |
| ![image](https://github.com/vector-im/element-web/assets/2403652/cd9b5e5f-110f-4c8b-b421-1dad10cf22cc) | ![image](https://github.com/vector-im/element-web/assets/2403652/9e393931-77bd-4fcd-b1dc-8c35a800f3c3) |
| ![image](https://github.com/vector-im/element-web/assets/2403652/26fb63a6-5e8e-4d3e-845a-5b0a6ef9ad21) | ![image](https://github.com/vector-im/element-web/assets/2403652/6741f622-41cf-49c8-8f67-2fdcb3627478) |
---
=> Improve rendering style of markdown in the mdbook

element.io/develop/config.json
Relates to: vector-im/element-web#25883
---
=> Enable new room header by default on develop

build_config.sample.yaml, docs/modules.md
=> Improve Module API docs & example

variants/openDesk/build_config.yaml
This PR adds the `@nordeck/element-web-opendesk-module@0.3.0` to the `variants/openDesk/build_config.yaml`.
---
=> Add @nordeck/element-web-opendesk-module@0.3.0 to variants/openDesk/build_config.yaml

package.json, yarn.lock
Reverts element-hq/element-web#26750
Fixes https://github.com/element-hq/element-web/issues/26756
Create font regression 
---
=> Revert "Update dependency css-loader to v6"

package.json, yarn.lock
Reattempt of https://github.com/element-hq/element-web/pull/26750
v6 causes issues like https://github.com/element-hq/element-web/issues/26756 so will be avoided for the time being. tested locally.
---
=> Upgrade css-loader to v5

CONTRIBUTING.md
Notes: Fix a bug (https://github.com/element-hq/element-web/issues/26654) where the **Private sign off** process section was missing.
---
=> Added private sign off process in contributing.md

test/app-tests/loading-test.tsx, test/app-tests/server-config-test.ts, test/app-tests/wrapper-test.tsx
As with https://github.com/matrix-org/matrix-react-sdk/pull/12081: our tests need to mock a modern server, not one that was released two years ago.
Another prerequisite for https://github.com/matrix-org/matrix-js-sdk/pull/3970
---
=> Update tests not to mock out an ancient server

package.json, webpack.config.js, yarn.lock
=> Strip data-testid in production

docs/config.md
It is untested, quite limited, and largely unsupported. Will be removed in an upcoming version.
---
* Deprecate welcome bot `welcome_user_id` support ([\#26885](https://github.com/element-hq/element-web/pull/26885)).
=> Deprecate welcome bot `welcome_user_id` support

webpack.config.js
=> Remove webpack 4 hack

webpack.config.js
```
$ webpack --progress --mode production
[webpack-cli] Failed to load '/builds/selfisekai/aports/community/element-web/src/element-web-1.11.55/webpack.config.js' config
[webpack-cli] Error: Unsupported operating system or architecture! Sentry CLI does not work on this architecture.
Sentry CLI supports:
- Darwin (macOS)
- Linux and FreeBSD on x64, x86, ia32, arm64, and arm architectures
- Windows x64, x86, and ia32 architectures
```
---
=> Add workaround for webpack builds on platforms unsupported by Sentry

.github/workflows/release_prepare.yml
To avoid potential for races as upstream changelogs are ingested
---
=> Saner Releases - ensure we set up staging branches in bottom-up order

test/app-tests/loading-test.tsx
Fix some test that are failing in rust_crypto due to missing `device_id` mock.
Legacy was not reaching that point because crypto initialisation was failing anyhow because libolm not loaded (`globalThis.Olm` undefined), and the error[ is swallowed in legacy ](https://github.com/matrix-org/matrix-react-sdk/blob/01f0c668b76cee5f2d6e74e7edca41d73a76fc58/src/MatrixClientPeg.ts#L360)
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md))
---
=> Fix missing deviceId mock in test

test/app-tests/loading-test.tsx
The `loading-test.tsx` only runs correctly on legacy crypto. They are running a mix of localStorage and indexeddb storage (partial mock of indexeddb through the all stack), and also they are running without crypto (by not loading libolm). The rust sdk doesn't work this way, it's using indexeddb to store things and cannot be disabled by not loading a lib.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md))
---
=> Force legacy crypto for loading tests

docs/labs.md, element.io/develop/config.json
Depends on:
https://github.com/matrix-org/matrix-react-sdk/pull/12184
The feature flag `feature_rust_crypto` is not `true` by default.
The `config.json` for develop has been updated in order to migrate all existing users to rust (`RustCrypto.staged_rollout_percent: 100` ).
`app.element.io` is only using the default. Meaning that new logins will now use the rust crypo stack.
Existing users will stay on legacy because the `RustCrypto.staged_rollout_percent` setting default is 0.
The plan is to incrementally update the `staged_rollout_percent` on app.element.io in future releases.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/element-hq/element-web/blob/devel …
=> Update `element.io develop` configuration to migrate all existing users to the new rust crypto stack

docs/theming.md
To reflect the changes in https://github.com/matrix-org/matrix-react-sdk/pull/12240, including the removal of the username and color options (those are now themed through Compound)
---
=> Update custom themes documentation

src/vector/platform/ElectronPlatform.tsx
To strip the element-desktop-ssoid param from the redirectUri
=> Improve Element Desktop OIDC Native dynamic registration

docs/config.md
Depends on: https://github.com/matrix-org/matrix-react-sdk/pull/12259
Signed-off-by: Timo K <toger5@hotmail.de>
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md))
=> Add docs for element call external conference configuration (single-page app URL)

.github/workflows/triage-labelled.yml
Fixes https://github.com/element-hq/element-web/issues/27151
=> Remove Element-R from Z-Labs labelling

yarn.lock
Ran `yarn add github:matrix-org/matrix-react-sdk#develop` to update the `compound-design-tokens`. The new tokens used in the `react-sdk` are in the `compound-design-tokens@1.2.0` and they are missing the last release. See https://github.com/element-hq/element-web/issues/27166
The command made some minors changes on other dependencies (`string-width`, `strip-ansi`, `wrap-ansi`). It's adding new line, nothing harmful. It's seems to separate commonjs.
=> Fix missing compound design tokens

.github/workflows/build_develop.yml
Without this, when attempting to redeploy the same bundles it'd create a redirect for the live bundles via `_redirects` to R2 but this does not work for workers due to CSP seemingly.
=> Fix deploying develop when the bundles are already present in R2

.github/workflows/triage-labelled.yml
It was failing because the old project has been deleted, so update it to the new one.
=> Update the issue triage labeller for the new triage project

.github/workflows/triage-labelled.yml
With the correct URL format this time
=> Fix issue labeller job, again

src/vector/platform/ElectronPlatform.tsx
Fixes https://github.com/element-hq/element-desktop/issues/1367
Signed-off-by: Stephan Raab <info@gumara.de>
=> Fix: 1:1 call - screen sharing no longer works after pressing the cancel button in Element-Desktop

element.io/develop/config.json
While we work through fixing all the tests on https://github.com/matrix-org/matrix-react-sdk/pull/12439 enable the TAC on nightly so we can get wider testing.
Matching https://github.com/element-hq/element-desktop/pull/1635 for nightly
=> Enable the TAC in develop

.github/workflows/triage-stale-flaky-tests.yml
We will need to add this new label (`Z-Flaky-Test-Disabled`) to all the issues we've disabled
=> Prevent action from closing flaky test issues that have already been disabled

element.io/app/config.json
We've not heard any concerns recently, and the [last blocker](https://github.com/element-hq/element-web/issues/27324) was released on 23 April. Let's migrate 30% of existing `app.element.io` users.
This change will be deployed manually once the PR is merged.
Part of https://github.com/element-hq/element-web/issues/27284.
=> Roll out Rust crypto to 30% of existing users on `app.element.io`

webpack.config.js
This fixes the deprecation warning `(node:418990) [DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)`
Signed-off-by: MTRNord <mtrnord@nordgedanken.dev>
=> Modernize hash in webpack

webpack.config.js
Reverts element-hq/element-web#27464
Turns out this actually breaks the `:7` notation on deployment
cc @t3chguy
=> Revert "Modernize hash in webpack"

src/vector/platform/ElectronPlatform.tsx
Requires https://github.com/matrix-org/matrix-react-sdk/pull/12495
Requires https://github.com/element-hq/element-desktop/pull/1662
=> Fix `element-desktop-ssoid being` included in OIDC Authorization call

package.json
It was transitively loaded via typescript-eslint
=> Add missing @types/semver dev dep

element.io/app/config.json
It's time to roll out rust crypto a bit further.
Followup to https://github.com/element-hq/element-web/pull/27416. Part of https://github.com/element-hq/element-web/issues/27490.
This change will be deployed manually once the PR is merged.
=> Roll out Rust crypto to 60% of existing users on app.element.io

.github/workflows/docs.yml
Fix https://github.com/element-hq/element-web/actions/runs/9368190448/job/25789587578
Result with the fix https://github.com/element-hq/element-web/actions/runs/9402024104/job/25895123158?pr=27530
The [`0.1.16` of mdbook-combiner](https://github.com/jscarrott/mdbook-combiner/releases/tag/v0.1.16) is messing with the generated path of the `SUMMARY.MD`.
With the `0.1.15`, the path are correctly created in the generated `SUMMARY.MD` but the `0.1.16` …
=> Fix CI docs generation

package.json, src/favicon.ts, src/vector/index.ts
Requires https://github.com/matrix-org/matrix-react-sdk/pull/12614
Requires https://github.com/matrix-org/matrix-js-sdk/pull/4240
=> Remove setImmediate polyfill

src/serviceworker/index.ts
The MSC has completed FCP, so stable endpoints can be used.
Seeing as limited servers have shipped with the unstable endpoints, we're not generally concerned with backwards compatibility to `unstable` here - none of the freezing for the unauthenticated endpoints has happened yet.
For the "Matrix 1.11" bits, I am extremely confident that 1.11 will ship with MSC3916 - it's a release blocker. See https://github.com/matrix-org/matrix-spec/issues/1857 for release coordination.
**Requires https://github.com/matrix-org/matrix-react-sdk/pull/12602** (for tests)
=> Use stable endpoints for MSC3916

docs/config.md, src/vector/app.tsx
This adds the option to redirect to SSO from the login page. This may help when SSO should be the only login option, while still allowing guests to view public rooms.
Coincides with the following change: https://github.com/matrix-org/matrix-react-sdk/pull/12622
Signed-off-by: Bart van der Braak <bartvdbraak@gmail.com>
=> Add SSO redirect option for login page

.github/workflows/docs.yml
We fixed version due to https://github.com/element-hq/element-web/pull/27530
They fixed the issue https://github.com/jscarrott/mdbook-combiner/issues/37
Successful run https://github.com/element-hq/element-web/actions/runs/9758354560/job/26932715645?pr=27662
=> Remove `mdbook-combiner` version

.github/workflows/build.yml, .github/workflows/build_develop.yml, .github/workflows/static_analysis.yaml, .github/workflows/tests.yaml, .github/workflows/update-jitsi.yml
Since the js-sdk minimum requirement is the last lts (node 20)  https://github.com/matrix-org/matrix-js-sdk/pull/4293 , we need to update our workflow to use the last lts.
=> Use last node lts in workflow

src/vector/index.ts
I plan to use [v mode regexes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicodeSets#browser_compatibility) to [test for emoji sequences](https://github.com/matrix-org/matrix-react-sdk/pull/12582), and @t3chguy has advised me that we need to ensure that the "incompatible browser" screen shows if they are not supported.
=> Add a Modernizr check for v mode regexes

package.json, src/vector/index.ts, src/vector/init.tsx, webpack.config.js
Now that we use the Rust crypto stack (https://github.com/matrix-org/matrix-react-sdk/pull/12630), the legacy olm library is unneeded. Remove all the dedicated cruft for loading it.
(It is to avoid all this application-level crap that matrix-sdk-crypto-wasm has to base64 its wasm artifact, cf https://github.com/matrix-org/matrix-rust-sdk/pull/1167.)
=> Remove code which loads legacy libolm

.github/workflows/triage-labelled.yml
The old `move_needs_info_issues` action doesn't work as it's using an action designed for legacy projects and our new board is the new kind of project.
This PR should fix that and also move "Z-Flaky-Test" labelled issues to to the "Sized for maintainer" column, which is desirable.
=> Move needs info and flaky tests issues to the correct columns

docs/config.md
For https://github.com/matrix-org/matrix-react-sdk/pull/12760
=> Docs: Align `widget_build_url_ignore_dm` with call behaviour switch between 1:1 and Widget

src/serviceworker/index.ts
Some users are reporting that the service worker isn't doing its job - the most probable reason appears to be a failed versions check, but it's unclear why that would fail. This adds some debugging to help figure out what might be going on.
=> Add debugging for service worker version check

package.json, src/vector/index.ts, yarn.lock
This fixes Element on older versions of Firefox by adding a Polyfill for Intl.Segmenter. The Polyfill is conditionally imported so it only inflates the initial bundle size by about 100 bytes. On browsers that need it, the polyfill is quite large at 317Kb.
Users on these browser will still see the 'unsupported browser' screen, but will be able to click through to use the app anyway. This keeps the Intl.Segmenter modernizr check but this would also happen due to https://github.com/element-hq/element-web/pull/27674
-   [ ] Sign-off given on the changes (see …
=> Polyfill Intl.Segmenter for wider web browser compatibility

README.md
Update Supported Environments in line with decision made off the request for extended support in https://github.com/element-hq/element-web/issues/27684
=> Update Supported Environments

src/vector/jitsi/index.ts
Broken by https://github.com/matrix-org/matrix-react-sdk/pull/12790
Breaks develop deployment
=> Fix Jitsi by updating device mute updates over postMessage API

webpack.config.js
Use `console.warn` instead of an undefined `compilation` object.
Fix develop build https://github.com/element-hq/element-web/actions/runs/10249545922/job/28353165571
According to https://www.npmjs.com/package/@sentry/webpack-plugin#errorhandler only the error object is a parameter of the callback
=> Fix develop build

Dockerfile
This is to allow Docker images to be built on Windows machines
=> dos2unix more Docker scripts

package.json, yarn.lock
Namely, update the widget-sdk to avoid seeing a permissions dialog when opening the Element Call widget.
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
=> Update dependencies for MSC4157

config.sample.json, docs/config.md
See https://github.com/matrix-org/matrix-react-sdk/pull/12893
=> Add docs for widget container height option

package.json
There was a breaking change with webpack-dev-server 5. The --https argument was replaced with --server-type https.
=> Replace old webpack-dev-server https arg

.github/workflows/triage-stale-flaky-tests.yml
Stale action uses [cache](https://github.com/actions/stale?tab=readme-ov-file#statefulness) to keep track of issues it has already processed. This cache is supposed to be deleted at the end of the run but it never happens due to a lack of permission. See https://github.com/element-hq/element-web/actions/runs/10588795861/job/29341882041#step:2:7046
The end result of this is that some issues are [just never considered for closing once they're in the cache](https://github.com/element-hq/element-web/actions/runs/10588795861/job/29341882041#step:2:80). 
Relevant:
https://github.com/actions/stale/issues/1131#issuecomment-1959835001
=> Fix stale action not closing issues as expected

tsconfig.json
Due to https://github.com/matrix-org/matrix-js-sdk/pull/4377
Fix https://github.com/element-hq/element-web/actions/runs/10634158530/job/29480861412
Add `allowImportingTsExtensions` to tsconfig.json
=> Add `allowImportingTsExtensions` to tsconfig.json

config.sample.json
=> Fix default_widget_container_height in sample config

config.sample.json, docs/config.md
As per https://github.com/element-hq/matrix-react-sdk/pull/29
=> Add doc for 'force_verification config option

.github/release-drafter.yml, .github/workflows/docs.yml, .github/workflows/end-to-end-tests.yaml, .github/workflows/pending-reviews.yaml, .github/workflows/release_prepare.yml
=> Replace `matrix.org/matrix-react-sdk` with `element-hq/matrix-react-sdk` in CI

src/vector/index.ts
On further reflection with product/engineering it doesn't make sense to show the unsupported browser screen at app launch for a bug that is not commonly seen and only causes a minor UI glitch.
=> Remove regexpunicodesets modernizr check

src/vector/platform/ElectronPlatform.tsx
By switching the double slash for a single one
Fixes https://github.com/element-hq/element-desktop/issues/1889
=> Update native OIDC callback url to be RFC8252 compliant

.github/workflows/triage-labelled.yml
Since message pinning is no longer in labs
=> Don't add `labs` label for `A-Message-Pinning`

docs/labs.md
Docs update for https://github.com/element-hq/matrix-react-sdk/pull/95
=> Update docs to reflect that you can join calls without the labs flags

.github/workflows/release_prepare.yml
So it's easier to see which one failed.
=> Separate out tasks for each merge in the Prepare Release script

docs/config.md
`help_encrption_url` → [`help_encryption_url`](https://github.com/matrix-org/matrix-react-sdk/blob/v3.109.0/src/IConfigOptions.ts#L160)
=> Correct typo in option documentation

docs/labs.md
https://github.com/element-hq/matrix-react-sdk/pull/138
https://github.com/matrix-org/matrix-spec-proposals/pull/2697 is abandoned
The old dehydration feature is deprecated and not implemented in the rust crypto.
=> Remove feature_dehydration

playwright/e2e/login/login.spec.ts
Discovering what is the correct way of asserting that an element is *not* on screen with Playwright, which apparently is nontrivial.
Fixes https://github.com/element-hq/element-web/issues/28143
=> Deflake unskippable verification

src/stores/right-panel/RightPanelStore.ts, src/stores/right-panel/RightPanelStoreIPanelState.ts
Fixes https://github.com/element-hq/element-web/issues/28221
=> Fix Ctrl+F shortcut not working with minimised room summary card

playwright/e2e/settings/account-user-settings-tab.spec.ts, test/unit-tests/components/views/settings/AddRemoveThreepids-test.tsx
Fixes https://github.com/element-hq/element-web/issues/28160
=> Port the flaky add/remove 3pid test to playwright

playwright/e2e/accessibility/keyboard-navigation.spec.ts
Fixes https://github.com/element-hq/element-web/issues/28139
=> Deflake keyboard navigation test

src/async-components/views/dialogs/security/NewRecoveryMethodDialog.tsx, src/components/structures/MatrixChat.tsx, test/test-utils/test-utils.ts, test/unit-tests/async-components/dialogs/security/NewRecoveryMethodDialog-test.tsx, test/unit-tests/async-components/dialogs/security/__snapshots__/NewRecoveryMethodDialog-test.tsx.snap, test/unit-tests/components/structures/MatrixChat-test.tsx
- `Matrix.getKeyBackupEnabled` is synchronous and `MatrixClient.CryptoApi.getActiveSessionBackupVersion` si asynchronous. The component is fairly trivial and it was a good opportunity to migrate it to a functional component to handle easily the asynchronous. 
- The `newVersionInfo` props wasn't used in the component so I removed it.
=> Replace `Matrix.getKeyBackupEnabled` by `MatrixClient.CryptoApi.getActiveSessionBackupVersion`

src/AddThreepid.ts, src/Avatar.ts, src/ContentMessages.ts, src/IdentityAuthClient.tsx, src/Lifecycle.ts, src/NodeAnimator.tsx, src/Notifier.ts, src/PosthogAnalytics.ts, src/RoomInvite.tsx, src/SlashCommands.tsx, src/SlidingSyncManager.ts, src/Terms.ts, src/actions/RoomListActions.ts, src/components/structures/MatrixChat.tsx, src/components/views/dialogs/RoomUpgradeDialog.tsx, src/components/views/right_panel/UserInfo.tsx, src/components/views/settings/AddRemoveThreepids.tsx, test/unit-tests/Lifecycle-test.ts
Ironically it is sad about this PR
=> Make Sonar happier

src/ContentMessages.ts, test/test-utils/test-utils.ts, test/unit-tests/ContentMessages-test.ts
Replace `MatrixClient.isRoomEncrypted` by `MatrixClient.CryptoApi.isEncryptionEnabledInRoom` in `ContentMessages.ts`
=> Replace `MatrixClient.isRoomEncrypted` by `MatrixClient.CryptoApi.isEncryptionEnabledInRoom` in `ContentMessages.ts`

playwright/e2e/composer/RTE.spec.ts
Fixes https://github.com/element-hq/element-web/issues/26037
LeftArrow  -> ArrowLeft
=> Fix RTE mentions autocomplete test

src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx, src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx, test/unit-tests/components/views/dialogs/security/CreateSecretStorageDialog-test.tsx
- The `keyBackupKeyFromPassword` call is bound to the `keyCallback` props which is not used in `CreateSecretStorageDialog`
- Remove code bound to `keyCallback` props
=> Remove deprecated  `MatrixClient.keyBackupKeyFromPassword` call.

src/components/views/right_panel/UserInfo.tsx, src/verification.ts, test/test-utils/test-utils.ts
=> Remove `MatrixClient.requestVerification` call

playwright/e2e/spotlight/spotlight.spec.ts
Un-skips flake -> https://github.com/element-hq/element-web/issues/26138
I could not make it flake locally, even if I removed the added timeout.
Maybe we should re-enabled in case it was related to cypress or something that's been fixed in synapse?
We can leave the flake and synapse issue open till we have confirmed it's not flaking.
=> Enable "should find unknown people"

playwright/e2e/pinned-messages/index.ts
Closes https://github.com/element-hq/element-web/issues/27950
=> Fix flake in pinned message e2e test due to tooltip

playwright/e2e/crypto/crypto.spec.ts
This sometimes happens too quickly for us to test.
Fixes: #27585
=> playwright: remove flaky check

src/stores/SetupEncryptionStore.ts, test/unit-tests/stores/SetupEncryptionStore-test.ts
`MatrixClient.getDehydratedDevice` is deprecated.
[`RustCrypto.getUserDeviceInfo`](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/rust-crypto/rust-crypto.ts#L483) can still return the dehydrated devices of MSC 2697 however it was an experimental feature behind a labs flag. We can ignore and don't worry about them.
=> Remove `MatrixClient.getDehydratedDevice` call

test/unit-tests/stores/SetupEncryptionStore-test.ts
=> Replace `IBootstrapCrossSigningOpts` by `BootstrapCrossSigningOpts` to use CryptoApi type instead of old crypto type.

playwright/e2e/pinned-messages/index.ts, playwright/e2e/pinned-messages/pinned-messages.spec.ts
Closes https://github.com/element-hq/element-web/issues/28149 
Closes https://github.com/element-hq/element-web/issues/27950
Because I make CSS comment with js syntax 🤡
=> Fix pinned message e2e flakes

src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx, test/test-utils/test-utils.ts, test/unit-tests/components/views/settings/tabs/room/SecurityRoomSettingsTab-test.tsx
=> Replace `MatrixClient.isRoomEncrypted` by `MatrixClient.CryptoApi.isEncryptionEnabledInRoom` in `SecurityRoomSettingsTab`

playwright/e2e/crypto/user-verification.spec.ts
Wait for the QR code to be rendered, in an attempt to deflake these two
Fixes: https://github.com/element-hq/element-web/issues/27819
Fixes: https://github.com/element-hq/element-web/issues/27789
=> Playwright: deflake verification tests

src/stores/widgets/StopGapWidgetDriver.ts, test/unit-tests/stores/widgets/StopGapWidgetDriver-test.ts
-   [x] Tests written for new code (and old code if feasible).
-   [x] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
Removed in https://github.com/element-hq/element-web/pull/28204/files#diff-c29e6a78e44cfaf8d9b12444c2cc8bcf25df1b6d12b3de4cd2a1a31bf640eff0L417
=> Add back unencrypted path in `StopGapWidgetDriver.sendToDevice`

element.io/app/config.json, res/css/views/rooms/_RoomHeader.pcss, src/components/views/rooms/RoomHeader.tsx, src/hooks/room/useRoomCall.tsx
Update button label to say it is a Beta
For https://github.com/element-hq/element-internal/issues/638
=> Enable Element Call by default on release instances

src/DeviceListener.ts, src/i18n/strings/en_EN.json, src/toasts/SetupEncryptionToast.ts, test/unit-tests/DeviceListener-test.ts
Part of https://github.com/element-hq/element-web/issues/27455
=> Remove upgrade encryption in `DeviceListener` and `SetupEncryptionToast`

src/stores/widgets/StopGapWidgetDriver.ts, test/unit-tests/stores/widgets/StopGapWidgetDriver-test.ts
Uses new CryptoApi.encryptToDeviceMessages() to send encrypted to-device messages from widgets
-   [x] Tests written for new code (and old code if feasible).
-   [x] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
=> Support sending encrypted to device messages from widgets

.github/workflows/static_analysis.yaml
`switch_package_to_release` is now a no-op (there are no fields called `matrix_lib_*` in matrix-js-sdk's package.json), so everything after that is redundant.
=> Remove redundant `switch_package_to_release` call

src/components/views/settings/discovery/DiscoverySettings.tsx
Fixes https://github.com/element-hq/element-web/issues/28355
=> Ignore `m.3pid_changes` for Identity service 3PID changes

src/stores/widgets/StopGapWidgetDriver.ts
-   [x] Tests written for new code (and old code if feasible).
-   [x] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
=> Auto approvoce `io.element.call.reaction` capability for element call widgets

src/components/views/elements/ImageView.tsx, test/unit-tests/components/views/elements/ImageView-test.tsx
Fixes https://github.com/element-hq/element-web/issues/28018
=> Handle authenticated media when downloading from ImageView

src/stores/widgets/StopGapWidget.ts, test/unit-tests/stores/widgets/StopGapWidget-test.ts
The code that feeds events to widgets tries to enforce that only events from the end of the timeline will be passed through. This is to prevent old, irrelevant events from being passed to widgets as the timeline is back-filled. However, since encrypted events need to be decrypted asynchronously, it's not possible to feed them to a widget in a strictly linear order without introducing some kind of blocking or unreliable delivery. This code has been dropping events when they're decrypted out of order, which we consider to be an undesirable behavior.
The solution provided here is that, to reflect the asynchronous nature of decryption, encrypted events that arrive at the end of the timeline will be fed to a widget whenever they finish decrypting, even if this means feeding them out of order. …
=> Feed events to widgets as they are decrypted (even if out of order)

src/components/views/settings/tabs/user/SessionManagerTab.tsx
setSigningOutDeviceIds was adding the same device ID twice, and also possibly using an old reference to the value when updating it
Subset of https://github.com/element-hq/element-web/pull/28256
=> Refactor signing out devices to handle React 18 Strict Mode

.github/workflows/end-to-end-tests.yaml, package.json, scripts/docker-package.sh, scripts/package.sh, webpack.config.js, yarn.lock
Fixes https://github.com/element-hq/element-web/issues/12818
=> Make the version file part of webpack output

src/autocomplete/UserProvider.tsx, src/editor/autocomplete.ts, src/editor/model.ts
Fixes https://github.com/element-hq/element-web/issues/7328
=> Allow tab completing users in brackets

yarn.lock
matrix-js-sdk#develop now depends on matrix-widget-api^v1.10.0, so update the lockfile to match that. A yarn install would update the lockfile otherwise.
The correct version was reverted by element-hq/element-web#28430.
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
=> Fix matrix-widget-api version in package.json

src/utils/notifications.ts, test/unit-tests/components/views/context_menus/RoomGeneralContextMenu-test.tsx, test/unit-tests/stores/RoomViewStore-test.ts, test/unit-tests/stores/notifications/RoomNotificationState-test.ts, test/unit-tests/utils/notifications-test.ts
Both events are already being read in `getMarkedUnreadState` above. If the stable event exists, the unstable one is ignored entirely, so it should be sufficient to only write to the stable event going forward.
=> Start sending stable `m.marked_unread` events

webpack.config.js
Fixes https://github.com/element-hq/element-web/issues/24241
=> Fix source maps in production builds

src/components/structures/auth/ForgotPassword.tsx, test/unit-tests/components/structures/MatrixChat-test.tsx, test/unit-tests/components/structures/TimelinePanel-test.tsx, test/unit-tests/components/structures/auth/ForgotPassword-test.tsx, test/unit-tests/components/views/messages/DateSeparator-test.tsx, test/unit-tests/components/views/messages/MPollEndBody-test.tsx, test/unit-tests/components/views/right_panel/UserInfo-test.tsx, test/unit-tests/components/views/rooms/MessageComposer-test.tsx, test/unit-tests/components/views/settings/JoinRuleSettings-test.tsx
Closes https://github.com/element-hq/customer-success/issues/379
Closes https://github.com/element-hq/wat-internal/issues/65
=> Remove usage of legacyRoot in RTL tests

src/components/views/rooms/Autocomplete.tsx
`setState` now has different timings so we cannot assume the state changes are available immediately and must await them
Fixes https://github.com/element-hq/element-web/issues/28501
=> Fix force tab complete not working since switching to React 18 createRoot API

src/vector/platform/ElectronPlatform.tsx
=> Fix getOidcCallbackUrl for Element Desktop

src/DeviceListener.ts, src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx, src/components/structures/MatrixChat.tsx, src/components/views/dialogs/LogoutDialog.tsx, src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx, src/components/views/settings/SecureBackupPanel.tsx, src/stores/SetupEncryptionStore.ts, test/test-utils/client.ts, test/test-utils/test-utils.ts, test/unit-tests/DeviceListener-test.ts, test/unit-tests/components/structures/MatrixChat-test.tsx, test/unit-tests/components/views/dialogs/LogoutDialog-test.tsx, test/unit-tests/components/views/dialogs/security/CreateSecretStorageDialog-test.tsx, test/unit-tests/components/views/dialogs/security/RestoreKeyBackupDialog-test.tsx, test/unit-tests/components/views/settings/SecureBackupPanel-test.tsx, test/unit-tests/components/views/settings/tabs/user/SecurityUserSettingsTab-test.tsx, test/unit-tests/stores/SetupEncryptionStore-test.ts
Blocked by https://github.com/matrix-org/matrix-js-sdk/issues/4534
Use `CryptoApi.getKeyBackupInfo` instead of deprecated `MatrixClient.getKeyBackupVersion`
=> Use `CryptoApi.getKeyBackupInfo` instead of deprecated `MatrixClient.getKeyBackupVersion`

.github/actions/download-verify-element-tarball/action.yml, .github/workflows/deploy.yml
For https://github.com/element-hq/sre-internal/issues/3025
For https://github.com/element-hq/wat-internal/issues/78
=> Deploy app.element.io & staging.element.io via Github Actions

src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx, test/unit-tests/components/views/settings/tabs/room/SecurityRoomSettingsTab-test.tsx
Caused by https://github.com/element-hq/element-web/pull/28281
The encryption settings stays off when the room encryption state is loaded.
Add a spinner during the loading to avoid to have a flicker on this settings.
https://github.com/user-attachments/assets/012aeefb-ba6f-4147-bafe-9260aa299b16
https://github.com/user-attachments/assets/8684d9d4-6ce2-4fe1-b24a-7e34061b0491
=> Add spinner when room encryption is loading in room settings

src/components/views/rooms/EventTile.tsx
Temporary measure in order to get https://github.com/matrix-org/matrix-js-sdk/pull/4529 and https://github.com/element-hq/element-web/pull/28476 merged without upsetting the CI.
In short, 4529 adds new shield codes, and 28476 handles those shield codes.  If 4529 gets merged first, then TypeScript will complain in this repo because not all the shield codes are handled, and so `shieldReasonMessage` may be unset.  So the plan is to merge this PR first, so that it handles all unknown shield codes, then merge 4529, and then merge 28476 (after resolving the conflict that it will have with this PR, by replacing the changes that this PR makes).
-   [ ] New or updated `public`/`exported` symbols have accurate …
=> Temporarily add a default branch to handle unknown shield codes

playwright/e2e/crypto/decryption-failure-messages.spec.ts, src/components/structures/RoomView.tsx, src/contexts/RoomContext.ts, test/test-utils/room.ts, test/test-utils/test-utils.ts, test/unit-tests/components/structures/RoomView-test.tsx, test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap, test/unit-tests/components/views/rooms/SendMessageComposer-test.tsx
=> Replace `MatrixClient.isRoomEncrypted` by `MatrixClient.CryptoApi.isEncryptionEnabledInRoom` in RoomView

.github/workflows/release_prepare.yml
Requires https://github.com/matrix-org/matrix-js-sdk/pull/4546
=> Apply release blocker checks to cut branches workflow

src/MatrixClientPeg.ts, src/settings/Settings.tsx, test/unit-tests/MatrixClientPeg-test.ts
=> Remove `Features.RustCrypto` flag

src/components/views/rooms/MessageComposerFormatBar.tsx
Closes https://github.com/element-hq/element-web/issues/28532
- When we want to display the format bar, the component doesn't have yet its height. Since the height is hardcoded in CSS, we can use also an hardcoded value for the computation.
- Added 1 px more than the initial computation which didn't include the border size, it allows the selection to not overflow over the formatting bar.
=> Fix format bar position

src/components/views/messages/TextualBody.tsx, src/utils/react.tsx
Fixes https://github.com/element-hq/element-web/issues/28607
The issue was the pres list was mutating itself and thus the for loop only hit every other pre.
There was an additional issue in React dev mode which meant that some highlighting was never done due to the double-rendering debug that React does causing the CodeBlock components to unmount but never clean up after themselves ready for a re-mount
=> Fix code block highlighting not working reliably with many code blocks

playwright/e2e/spaces/threads-activity-centre/index.ts, playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
Fix one of the two errors of https://github.com/element-hq/element-web/issues/27643
=> Fix TAC `should mark all threads as read` e2e test

src/Notifier.ts, src/toasts/IncomingCallToast.tsx
Bugs around ringing have been resolved and it's considered generally reliable now so it's a good time to increase the timeout.
=> increase ringing timeout from 10 seconds to 90 seconds

playwright/e2e/crypto/event-shields.spec.ts
Wait for our user to fetch the bot's identity before running the test, to work around a race in the shield logic.
Hopefully, fixes https://github.com/element-hq/element-web/issues/28061
=> Playwright: fix (hopefully) flaky shields test

webpack.config.js
It muddies import error messages significantly
=> Remove stale webpack configuration

playwright/e2e/pinned-messages/index.ts
Wait for the new pinned message to be displayed in the banner to pin the next one.
Currently, we send a state event with the new pinned message lists. Until we get updated with this new list from the sync, the current pinned message list  doesn't include the new pin message.
=> Fix multiple pinned messages flaky tests

src/components/structures/RoomView.tsx, src/components/views/rooms/PinnedMessageBanner.tsx, test/unit-tests/components/views/rooms/PinnedMessageBanner-test.tsx
Closes https://github.com/element-hq/element-web/issues/28390
We notify the timeline to resize when we display or hide the pinned message banner.
I also fixed multiple warnings of unhandled react state updates in the test.
=> Fix jumpy timeline when the pinned message banner is displayed

src/components/structures/auth/E2eSetup.tsx, src/components/views/dialogs/security/InitialCryptoSetup.tsx, src/components/views/dialogs/security/InitialCryptoSetupDialog.tsx, test/components/views/dialogs/security/InitialCryptoSetupDialog-test.tsx
This is split out of https://github.com/element-hq/element-web/pull/28267 because I'm also going to have to start chopping stuff around to make it work with React 18 strict mode, so otherwise that PR will get huge.
=> Rename CreateCrossSigningDialog to InitialCryptoSetupDialog

src/accessibility/context_menu/ContextMenuButton.tsx, src/accessibility/context_menu/ContextMenuTooltipButton.tsx, src/accessibility/roving/RovingAccessibleButton.tsx, src/components/structures/auth/SoftLogout.tsx, src/components/views/auth/InteractiveAuthEntryComponents.tsx, src/components/views/dialogs/devtools/SettingExplorer.tsx, src/components/views/dialogs/spotlight/SpotlightDialog.tsx, src/components/views/dialogs/spotlight/TooltipOption.tsx, src/components/views/directory/NetworkDropdown.tsx, src/components/views/elements/AccessibleButton.tsx, src/components/views/elements/EditableItemList.tsx, src/components/views/emojipicker/Emoji.tsx, src/components/views/messages/MPollEndBody.tsx, src/components/views/messages/MessageActionBar.tsx, src/components/views/settings/SetIdServer.tsx, src/components/views/settings/devices/DeviceExpandDetailsButton.tsx, src/components/views/settings/tabs/user/MjolnirUserSettingsTab.tsx, src/components/views/spaces/SpaceBasicSettings.tsx, src/components/views/spaces/SpacePanel.tsx, src/components/views/spaces/SpaceTreeLevel.tsx, src/components/views/voip/LegacyCallView/LegacyCallViewButtons.tsx, test/unit-tests/components/structures/__snapshots__/MatrixChat-test.tsx.snap, test/unit-tests/components/views/settings/SetIntegrationManager-test.tsx, test/unit-tests/components/views/settings/tabs/user/__snapshots__/MjolnirUserSettingsTab-test.tsx.snap
With some profiling I found a hotspot around AccessibleButton's types so rewrote them to make them to be faster and more correct. First commit focuses on speed, the rest on correctness. It found a bunch of props being given to divs which don't make sense without swapping to `button`.
Before 6m 51s
After 57s
=> Make tsc faster again

playwright/e2e/crypto/user-verification.spec.ts
The latest Rust crypto crate (used by rust-sdk-crypto-wasm 11.0) requires the device keys of the device requesting verification before it accepts an incoming verification, and will drop the verification request if it doesn't have it.  This causes CI failures because the CI requests the verification too quickly, before the test user has a chance to get the bot's device keys.
Fixes a CI failure for https://github.com/matrix-org/matrix-js-sdk/pull/4566 (https://github.com/matrix-org/matrix-js-sdk/actions/runs/12158968697/job/33908198078)
=> Add delay in test to allow Alice to fetch Bob's device keys

src/stores/widgets/StopGapWidgetDriver.ts
=> Allow trusted Element Call widget to send and receive media encryption key to-device messages

src/@types/global.d.ts, src/components/structures/MatrixChat.tsx, src/components/structures/auth/E2eSetup.tsx, src/components/views/dialogs/security/InitialCryptoSetupDialog.tsx, src/stores/InitialCryptoSetupStore.ts, src/stores/SetupEncryptionStore.ts, test/components/views/dialogs/security/InitialCryptoSetupDialog-test.tsx, test/unit-tests/stores/InitialCryptoSetupStore-test.ts
To make components pure and avoid react 18 dev mode problems due to components making requests when mounted.
=> Factor out crypto setup process into a store

test/unit-tests/components/views/rooms/ReadReceiptGroup-test.tsx, test/unit-tests/components/views/rooms/__snapshots__/ReadReceiptGroup-test.tsx.snap
The date formatting appears to have changed and somehow got through the merge tests on the dependency bump.
As per comment, mock it out.
=> Fix Read Receipt Test

test/unit-tests/utils/DateUtils-test.ts
As per comment. Fixes the tests.
=> Change to en-US locale for date tests

src/components/views/rooms/UserIdentityWarning.tsx
We had some reports of misbehaviour here, so adding a bit of looging to try to
track it down.
=> Add some logging to `UserIdenitityWarning`

src/components/views/messages/TextualBody.tsx, test/unit-tests/components/views/messages/TextualBody-test.tsx
Closes https://github.com/element-hq/element-web/issues/28758
Regression due to https://github.com/element-hq/element-web/pull/28278
=> Fix url preview display

playwright/plugins/postgres/index.ts
As commented. This was flaking when I was debugging it locally (MAS was failing to start because the database wasn't ready).
=> Playwright: wait for the network listener on the postgres db

package.json, test/unit-tests/components/views/elements/SyntaxHighlight-test.tsx, test/unit-tests/components/views/rooms/MessageComposer-test.tsx, test/unit-tests/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx, test/unit-tests/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx, test/unit-tests/components/views/rooms/wysiwyg_composer/components/PlainTextComposer-test.tsx, test/unit-tests/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete-test.tsx, test/unit-tests/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx, test/unit-tests/components/views/rooms/wysiwyg_composer/utils/createMessageContent-test.ts, yarn.lock
Fixes https://github.com/element-hq/element-web/issues/28110
Fixes https://github.com/element-hq/element-web/issues/28672
Before
After
=> Update matrix-wysiwyg to consume WASM asset

Dockerfile
I'm assuming these were here because, at some point, someone checked in some files with CRLF line endings. However, that has been fixed, installing dos2unix slows down the build, and just don't do that, m'kay?
=> Docker: remove redundant dos2unix calls

Dockerfile, docker/nginx-templates/default.conf.template, docs/install.md
Notes: The HTTP listen port for the Docker image can now be configured via an environment variable.
Part of a solution to https://github.com/element-hq/element-web/issues/25926
=> Docker: allow configuration of HTTP listen port via env var

Dockerfile, docker/nginx-templates/default.conf.template, docs/install.md
Notes: The docker image now runs as a non-root user
Empirically, listening on port 80 with non-root works just fine nowadays, so we may as well do that.
~~The hacks to `nginx.conf` are based on "Running nginx as a non-root user" in https://hub.docker.com/_/nginx (and the dockerfile for `nginxinc/nginx-unprivileged`).~~ Turns out we don't need many hacks, for our usecase.
~~Based on #28840~~
Fixes #25926
=> Docker: run as non-root

playwright/e2e/crypto/backups.spec.ts, playwright/e2e/csAPI.ts
A slightly tricky one to test but an important case that people can hit, and one that otherwise wouldn't get hit a lot during normal usage, so I think probably quite a useful test to have. Mostly though, I'm about to change this to a toast, so I'd like a test to assert that it still works.
Requires https://github.com/matrix-org/matrix-js-sdk/pull/4601
=> Add a playwright test for backup reset / deleted

playwright/e2e/crypto/backups.spec.ts, playwright/e2e/oidc/oidc-native.spec.ts, playwright/plugins/homeserver/synapse/templates/mas-oidc/homeserver.yaml, playwright/plugins/matrix-authentication-service/config.yaml, playwright/plugins/matrix-authentication-service/index.ts
Requires tweaking some of the tests given the MAS UI changed
Means also we can simplify the Synapse config DRASTICALLY
Subset of https://github.com/element-hq/element-web/pull/28860
=> Update matrix-authentication-service in Playwright tests

scripts/gen-workflow-mermaid.ts
The was using a runner output instead which is not going to work in this simple script, so just skip anything that's not an array - not really sure what else we can do here short of implementing large parts of github actions.
=> Fix building the automations mermaid diagram

.github/workflows/build.yml, .github/workflows/netlify.yaml
By switching it from using the webapp from the E2E CI to the Build CI which doesn't need to await any tests
=> Speed up Netlify CI/CD

.eslintrc.js, playwright/e2e/accessibility/keyboard-navigation.spec.ts, playwright/e2e/chat-export/html-export.spec.ts, playwright/e2e/composer/RTE.spec.ts, playwright/e2e/crypto/device-verification.spec.ts, playwright/e2e/crypto/user-verification.spec.ts, playwright/e2e/crypto/utils.ts, playwright/e2e/knock/manage-knocks.spec.ts, playwright/e2e/login/utils.ts, playwright/e2e/polls/pollHistory.spec.ts, playwright/e2e/room_options/marked_unread.spec.ts, playwright/e2e/settings/account-user-settings-tab.spec.ts, playwright/e2e/settings/preferences-user-settings-tab.spec.ts, playwright/e2e/sliding-sync/sliding-sync.spec.ts, playwright/e2e/threads/threads.spec.ts, playwright/e2e/widgets/stickers.spec.ts, playwright/pages/bot.ts
Fixes https://github.com/element-hq/element-web/issues/27720
=> Fix playwright flakes due to floating promises

playwright/e2e/crypto/backups-mas.spec.ts, playwright/e2e/login/login-sso.spec.ts, playwright/e2e/login/soft_logout_oauth.spec.ts, playwright/e2e/login/utils.ts, playwright/plugins/homeserver/synapse/legacyOAuthHomeserver.ts, playwright/plugins/oauth_server/index.ts, playwright/services.ts
Fixes https://github.com/element-hq/element-web/issues/28940
Fixes https://github.com/element-hq/element-web/issues/28938
Fixes https://github.com/element-hq/element-web/issues/27887
Fixes https://github.com/element-hq/element-web/issues/28971
=> Fix flaky playwright tests

playwright/e2e/audio-player/audio-player.spec.ts, playwright/e2e/knock/create-knock-room.spec.ts, playwright/e2e/knock/knock-into-room.spec.ts, playwright/e2e/messages/messages.spec.ts, playwright/e2e/pinned-messages/pinned-messages.spec.ts, playwright/e2e/settings/encryption-user-tab/index.ts, playwright/e2e/settings/encryption-user-tab/recovery.spec.ts, playwright/e2e/spaces/spaces.spec.ts, playwright/e2e/spaces/threads-activity-centre/index.ts, playwright/e2e/timeline/timeline.spec.ts, playwright/flaky-reporter.ts, playwright/pages/ElementAppPage.ts, playwright/pages/client.ts, playwright/services.ts
Fixes https://github.com/element-hq/element-web/issues/27840
Fixes https://github.com/element-hq/element-web/issues/28999
Fixes https://github.com/element-hq/element-web/issues/28950
Fixes https://github.com/element-hq/element-web/issues/27451
=> Fix more flaky playwright tests

src/components/views/elements/LabelledToggleSwitch.tsx, src/components/views/elements/SettingsFlag.tsx, src/components/views/elements/StyledCheckbox.tsx, src/components/views/messages/MBeaconBody.tsx, src/components/views/messages/MLocationBody.tsx, src/models/Call.ts, src/rageshake/rageshake.ts, src/utils/WidgetUtils.ts, src/utils/oidc/authorize.ts, src/vector/platform/ElectronPlatform.tsx, test/setupTests.ts, test/test-utils/poll.ts, test/unit-tests/components/views/settings/Notifications-test.tsx, test/unit-tests/components/views/spaces/SpaceSettingsVisibilityTab-test.tsx, test/unit-tests/utils/oidc/authorize-test.ts
Because the js-sdk methods are changing and there's no reason for these not to use the secure versions. The dedicated upper/lower functions were *only* used in this one case, so this should do the exact same thing with the one exported function.
Others were just using randomString, none look speed-sensitive so I don't think we really need to maintain an insecure set of functions too.
Requires https://github.com/matrix-org/matrix-js-sdk/pull/4621 (merge both together)
=> Switch to secure random strings

src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx, test/unit-tests/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
The IS settings got confused with the posthog settings and were only shown if analytics were enabled.
Patch from @t3chguy
=> Fix identity server settings visibility

playwright/e2e/crypto/device-verification.spec.ts, playwright/e2e/crypto/utils.ts, playwright/e2e/settings/encryption-user-tab/recovery.spec.ts
In https://github.com/element-hq/element-web/issues/26468, the key backup section of the `Security & Privacy` tab will be removed.
To check if the key backup is in the expected state, we can directly use the matrix client and the crypto api.
=> e2e test: Check key backup with js-sdk api instead of relying of `Security & Privacy` tab

playwright/e2e/crypto/utils.ts
Task https://github.com/element-hq/element-web/issues/26468 
Following https://github.com/element-hq/element-web/pull/29066
The cross-signing section of the *Security & Privacy* tab will be removed. Instead of using the verify button of this section, we switch to the *verify device* button of the encryption tab.
=> e2e test: Verify session with the encryption tab instead of the security & privacy tab

playwright/pages/bot.ts, src/components/structures/MatrixChat.tsx, test/unit-tests/components/structures/MatrixChat-test.tsx
[`Matrix.setGlobalErrorOnUnknownDevices`](https://github.com/matrix-org/matrix-js-sdk/blob/8175683d4bc65b730e9475d016372b948b2a6cb9/src/client.ts#L2609-L2644) is not implemented in the [rust-crypto](https://github.com/matrix-org/matrix-js-sdk/blob/8175683d4bc65b730e9475d016372b948b2a6cb9/src/rust-crypto/rust-crypto.ts#L230-L237) and will be removed in https://github.com/matrix-org/matrix-js-sdk/pull/4653
=> Remove call to `MatrixClient.setGlobalErrorOnUnknownDevices`

playwright/e2e/crypto/backups.spec.ts, playwright/e2e/crypto/crypto.spec.ts, playwright/e2e/crypto/dehydration.spec.ts, playwright/e2e/crypto/utils.ts, src/SecurityManager.ts, test/unit-tests/SecurityManager-test.ts
Currently, if we need a secret that is stored in 4S under an *old* recovery key, we put up a modal prompting the user to enter that old key, but don't actually tell them which key it is we are after.
Our design doesn't really support having more than one recovery key at a time -- we tell our users that there is only one recovery key.
So, it's better to treat such secrets as non-existent, rather than bothering the user for access.
Fixes: https://github.com/element-hq/element-web/issues/29130.
Suggest review commit-by-commit.
=> Stop showing a dialog prompting the user to enter an old recovery key

res/css/views/rooms/_UserIdentityWarning.pcss, src/components/viewmodels/rooms/UserIdentityWarningViewModel.tsx, src/components/views/rooms/UserIdentityWarning.tsx, src/i18n/strings/en_EN.json, test/unit-tests/components/structures/RoomView-test.tsx, test/unit-tests/components/views/rooms/UserIdentityWarning-test.tsx
Draft: depends on https://github.com/matrix-org/matrix-js-sdk/pull/4646
Following an initial early review, I have refactored the component to now use a viewModel https://github.com/element-hq/element-web/pull/29067/commits/8325c0c3f562a437274b21649714738fae9ea2ff
The update model has also been made a lot more simple, but also less optimized; as an example a `UserTrustStatusChanged` event will trigger a new computation of all the violations in the room. If we see performances problem this could be improoved
Following initial review,
=> feat(crypto): Support verification violation composer banner

src/stores/right-panel/RightPanelStoreIPanelState.ts
This happened due to the focusRoomSearch param being stored for inactive rooms so it never got cleared
=> Ensure switching rooms does not wrongly focus timeline search

playwright/e2e/crypto/device-verification.spec.ts, playwright/e2e/crypto/toasts.spec.ts, playwright/e2e/crypto/utils.ts, playwright/e2e/settings/encryption-user-tab/encryption-tab.spec.ts, playwright/e2e/settings/encryption-user-tab/index.ts, playwright/e2e/settings/encryption-user-tab/recovery.spec.ts, playwright/pages/bot.ts
In the e2e test, the bot creates a the recovery key from a passphrase. We tend to not generate recovery key from a passphrase and this is adding complexity in the e2e test.
`verifySession` was in fact not working when using a recovery key, the UI was expecting a passphrase.
https://github.com/element-hq/element-web/blob/3c690e685a7e8c76b8b2310ced668995af942f6c/playwright/e2e/crypto/utils.ts#L248-L262
=> e2e test: by default the bot should not use a passphrase to create the recovery key

src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx, test/unit-tests/components/views/settings/tabs/user/EncryptionUserSettingsTab-test.tsx
We weren't checking the encryption state when the user cancels the reset identity flow.
https://github.com/user-attachments/assets/e7c43f5e-547f-4e37-9155-30bb8688bed3
https://github.com/user-attachments/assets/26d9c1bb-7601-4e8c-9006-d2aae8b400b5
=> Encryption tab: display correct encryption panel when user cancels the reset identity flow

playwright/e2e/crypto/backups-mas.spec.ts, playwright/e2e/crypto/utils.ts
Key backup section will be removed in https://github.com/element-hq/element-web/pull/29088. Use `checkDeviceIsConnectedKeyBackup ` to look at the keybackup instead of using the *Security & Privacy* tab
=> test(backup mas): use `checkDeviceIsConnectedKeyBackup` instead at looking at the `Security & Privacy` tab

src/components/views/voip/CallView.tsx, test/unit-tests/components/views/voip/CallView-test.tsx
This was mistakenly removed in a370a5cfa43. You can tell it was unintentional because the 'role' variable was just left unused.
=> Restore the accessibility role on call views

src/DeviceListener.ts, src/stores/ToastStore.ts, test/unit-tests/DeviceListener-test.ts
It's currently hard to debug when someone sees or hides one of these toasts. Lets's add some logging.
=> Log when we show, and hide, encryption setup toasts

src/DeviceListener.ts, src/stores/ToastStore.ts, test/unit-tests/DeviceListener-test.ts
Backport f2fae82e3281b878e5e189534f2edec5ed6a9280 from #29235
=> [Backport staging] Log when we show, and hide, encryption setup toasts

src/components/structures/RoomView.tsx, test/unit-tests/components/structures/RoomView-test.tsx
Doesn't look like this was a regression as far as I can see, but you did have to switch rooms while offline for it to start happening.
There's no use reloading the room until we're online again.
Fixes https://github.com/element-hq/element-web/issues/29072
=> Don't reload roomview on offline connectivity check

docs/labs.md, src/components/structures/LeftPanel.tsx, src/components/views/rooms/LegacyRoomList.tsx, src/components/views/rooms/NewRoomListView.tsx, src/components/views/rooms/RoomListView.tsx, src/i18n/strings/en_EN.json, src/settings/Settings.tsx, src/stores/spaces/SpaceStore.ts, test/unit-tests/components/views/rooms/LegacyRoomList-test.tsx
- Introduces lab flag for the new room list
- Create a base `RoomListView` for further development. 
- Existing `RoomList` has been renamed to `LegacyRoomList`
=> New Room List: Create new labs flag

res/css/structures/_QuickSettingsButton.pcss, src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx, src/components/views/spaces/QuickSettingsButton.tsx, src/stores/spaces/SpaceStore.ts, test/unit-tests/stores/SpaceStore-test.ts
When the new room list labs flag is enabled:
- Hide the *Favourites* and *People* meta spaces in the left panel
- Hide the related buttons in the settings and in the quick settings
- Add some extra space in the quick settings between the remaining buttons
=> New room list: hide favourites and people meta spaces

src/components/structures/LoggedInView.tsx, src/components/structures/RoomSearch.tsx, test/unit-tests/components/structures/LoggedInView-test.tsx
This PR removes the `focus_room_filter` action and replaces it by `Action.OpenSpotlight`.
1. `focus_room_filter` is fired when `KeyBindingAction.FilterRooms` is triggered:
https://github.com/element-hq/element-web/blob/4b9382f888e1e37830aebb0baaaf756f9991f9f8/src/components/structures/LoggedInView.tsx#L503-L508
2. Which is handled by `RoomSearch`, to directly open the spotlight:
https://github.com/element-hq/element-web/blob/4b9382f888e1e37830aebb0baaaf756f9991f9f8/src/components/structures/RoomSearch.tsx#L27-L43
3. We can directly ditch `focus_room_filter` and opens the spotlight:
https://github.com/element-hq/element-web/blob/1aba639c827a76a6230b02d7aa2301e33baefcda/src/components/structures/LoggedInView.tsx#L503-L506
=> Replace `focus_room_filter` dispatch by `Action.OpenSpotlight`

playwright/e2e/crypto/dehydration.spec.ts, src/components/views/settings/encryption/ChangeRecoveryKey.tsx
Clicking "Set up recovery" should set up a dehydrated device, if that feature is enabled.
Fixes #29135
=> Dehydration: enable dehydrated device on "Set up recovery"

res/css/views/rooms/_MemberListHeaderView.pcss
Allows the member list search field to grow when the right panel is resized
**Before**
https://github.com/user-attachments/assets/605f5c07-68e9-4a48-b060-0a85611fce8d
**After**
https://github.com/user-attachments/assets/66c770f9-c388-47d7-9bc9-11acb44b6ca5
=> Grow member list search field when resizing the right panel

src/components/views/settings/encryption/ChangeRecoveryKey.tsx, src/utils/ErrorUtils.tsx, test/unit-tests/components/views/settings/encryption/ChangeRecoveryKey-test.tsx, test/unit-tests/components/views/settings/encryption/__snapshots__/ChangeRecoveryKey-test.tsx.snap
I'm fed up with setup operations in EW failing silently. Rather than leaving the user with a mysteriously broken client, let's at least tell them that something has gone wrong, so that they can report the issue and we can investigate.
Obviously, showing an unactionable Error dialog is a last resort: ideally, we should handle the error ourselves, or give the user actionable steps to resolve the problem. But that takes significant design and engineering.
Just swallowing errors is the worst of all possible options.
=> ChangeRecoveryKey: error handling

res/css/views/rooms/_MemberTileView.pcss
Closes https://github.com/element-hq/element-web/issues/29250
Member list font doesn't scale with the font size selected in the user settings or the browser font size.
| Before  | After |
| ------------- | ------------- |
| <img width="1119" alt="image" src="https://github.com/user-attachments/assets/047adf4b-ad58-4ab2-8942-2658d9ba4c63" />  | <img width="1119" alt="image" src="https://github.com/user-attachments/assets/a812f109-a9a1-46f8-a6af-66befb29d8f4" />|
=> Fix font scaling in member list

src/DeviceListener.ts, test/unit-tests/DeviceListener-test.ts
This unfortunately named and unspecced flag is set by Element X to denote that the user has chosen to disable key storage and it should not automatically try to enable it again. This changes Element web to not prompt to enable recovery if this flag is set.
Split out from https://github.com/element-hq/element-web/pull/29113
=> Honour the backup disable flag from Element X

src/components/structures/HomePage.tsx, src/components/structures/MatrixChat.tsx, src/components/views/dialogs/spotlight/SpotlightDialog.tsx, src/components/views/rooms/LegacyRoomList.tsx, src/components/views/rooms/LegacyRoomListHeader.tsx, src/dispatcher/actions.ts
Move `view_create_chat` & `view_create_room` to `actions.ts`
=> Move `view_create_chat` & `view_create_room` to `actions.ts`

test/unit-tests/components/views/settings/AddRemoveThreepids-test.tsx
Hopefully fixes:
- https://github.com/element-hq/element-web/issues/29137
- https://github.com/element-hq/element-web/issues/28048
`getByRole` is slow on large trees([as per the docs](https://testing-library.com/docs/queries/byrole/#performance)), using `getByText` for the long list of country codes sped this up for me locally from 2.5s to 400ms.
=> Fix 3pid timeout flakes

test/unit-tests/components/views/elements/SyntaxHighlight-test.tsx, test/unit-tests/components/views/elements/__snapshots__/SyntaxHighlight-test.tsx.snap
fixes https://github.com/element-hq/element-web/issues/28807
From the logs it looks like the auto detection of the programming language fails and returns undefined [here](https://github.com/element-hq/element-web/blob/develop/src/components/views/elements/SyntaxHighlight.tsx#L26).
I don't think we need to be testing language auto detection as a part of this test, i think we explicitly pass a language in our uses of SyntaxHighlight at the moment. From [the docs](https://highlightjs.readthedocs.io/en/latest/api.html#highlight) it looks like the language gets passed through so this should fix the flake.
=> Fix SyntaxHighlight flake

test/unit-tests/hooks/usePublicRoomDirectory-test.tsx
fixes https://github.com/element-hq/element-web/issues/28806
This test no longer makes sense.
It looks like it got mangled [here](https://github.com/matrix-org/matrix-react-sdk/commit/4012f0c591f61627077a739c62ef82fdbb13eb05#diff-3eb367fdb1f6a6c82743841b43ce91f061cd63bde6e914cc09100b5f287cdf06R79-R93).
It seems the intent of the test was to check empty queries but has a query > 0 probably from a copy/paste typo.
[usePublicRoomDirectory](https://github.com/element-hq/element-web/blob/develop/src/hooks/usePublicRoomDirectory.ts#L100) doesn't set a filter for a query that is falsy.
I've fixed up the test to make sense, returning results(no filter) for ""
=> Fix test that doesn't make sense in usePublicRoomDirectory-test.tsx

playwright/e2e/left-panel/room-list-view/room-list-header.spec.ts, src/components/viewmodels/roomlist/RoomListHeaderViewModel.tsx, test/unit-tests/components/viewmodels/roomlist/RoomListHeaderViewModel-test.tsx
[Figma design](https://www.figma.com/design/vlmt46QDdE4dgXDiyBJXqp/Left-Panel-2025?node-id=751-22786)
Add the compose menu for spaces in the new room list header
=> New room list: add compose menu for spaces in header

.github/workflows/docker.yaml, Dockerfile, docker/docker-entrypoint.d/18-load-element-modules.sh, docker/nginx-templates/default.conf.template, docs/install.md
https://github.com/element-hq/element-web/pull/29346 to staging
=> [backport] Dynamically load Element Web modules in Docker entrypoint

playwright/e2e/crypto/device-verification.spec.ts, src/DeviceListener.ts, test/unit-tests/DeviceListener-test.ts
If another device sends us the crypto secrets (presumably because we just verified and requested the secrets), then the "key storage out of sync" toast should go away.
Also reintroduces some logging that was lost in #29290.
Suggest review commit-by-commit.
Fixes https://github.com/element-hq/element-web/issues/29110
=> Dismiss "Key storage out of sync" toast when secrets received

docker/docker-entrypoint.d/18-load-element-modules.sh
=> fix: /tmp/element-web-config may already exist preventing the container from booting up

playwright/e2e/crypto/crypto.spec.ts, playwright/e2e/invite/invite-dialog.spec.ts, res/css/_components.pcss, res/css/views/rooms/_LegacyRoomList.pcss, src/components/structures/SpaceRoomView.tsx, src/components/views/rooms/LegacyRoomList.tsx
The `RoomList` was renamed `LegacyRoomList` but the css file and classes weren't renamed.
In order to avoid futur conflict with the new room list, we will rename these files too.
=> Rename `mx_RoomList` as `mx_LegacyRoomList`

babel.config.js, package.json, yarn.lock
Only needed because we consume js-sdk code directly so its own transpiling isn't in play
This should separately be fixed, we should not need to have a superset of js-sdk's babel plugins
For https://github.com/matrix-org/matrix-js-sdk/pull/4730
=> Enable babel plugins to enable js-sdk to use decorators

res/css/views/rooms/RoomListPanel/_RoomListHeaderView.pcss, src/components/views/rooms/RoomListPanel/RoomListHeaderView.tsx, test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap, test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
Avoid the room list header to overflow when the room name is too long
| Before | After |
| ------------- | ------------- |
| <img width="358" alt="image" src="https://github.com/user-attachments/assets/b9ace49e-e677-4881-8ac9-29418fa099bb" />| <img width="358" alt="image" src="https://github.com/user-attachments/assets/958774cc-d11a-4fde-91b3-008eae7075ec" />  |
=> new room list: keep space name in one line in header

src/stores/room-list-v3/RoomListStoreV3.ts, test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
This PR modifies the new room list store so that it listens to actions on the dispatcher and re-inserts the necessary room(s) as necessary.  Based on https://github.com/element-hq/element-web/blob/develop/src/stores/room-list/RoomListStore.ts#L183
=> Room List - Update the room list store on actions from the dispatcher

test/unit-tests/components/views/rooms/UserIdentityWarning-test.tsx
Since the refactoring in https://github.com/element-hq/element-web/pull/29067, this test is redundant.
It is also flaky and hard to understand. Time for it to die.
Fixes #29266
=> Remove redundant `UserIdentityWarning` test

src/stores/room-list-v3/RoomListStoreV3.ts, src/stores/room-list-v3/skip-list/RoomNode.ts, src/stores/room-list-v3/skip-list/RoomSkipList.ts, src/stores/spaces/SpaceStore.ts, test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts, test/unit-tests/stores/room-list-v3/skip-list/RoomSkipList-test.ts
- Each room node in the skip list has a property that tells you if that node belongs to the currently active space. 
- We redo this calculation for all room nodes whenever active space changes.
- We redo this calculation for a single room when it gets an update and is re-inserted into the skip list.
- A list of sorted rooms that belong to the active space is made available through a custom iterator that skips over any nodes that are not in the active space.
Ideally the room list store would give more information about spaces (and the ability to filter by arbitrary spaces) but this should be sufficient for the time being.
=> Room List Store: Filter rooms by active space

res/css/_components.pcss, res/css/views/settings/encryption/_ResetIdentityPanel.pcss, src/components/views/settings/encryption/ResetIdentityPanel.tsx, src/i18n/strings/en_EN.json, test/unit-tests/components/views/settings/encryption/ResetIdentityPanel-test.tsx, test/unit-tests/components/views/settings/encryption/__snapshots__/ResetIdentityPanel-test.tsx.snap, test/unit-tests/components/views/settings/tabs/user/__snapshots__/EncryptionUserSettingsTab-test.tsx.snap
Part of https://github.com/element-hq/element-web/issues/29192
When the user clicks the Continue button to reset their identity, show a spinner, disable the button, and warn them not to close the window.
=> Prevent user from accidentally triggering multiple identity resets

src/components/viewmodels/roomlist/RoomListViewModel.tsx, test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
- Listen for updates from the store
- Provide a method to open rooms
=> Add more functionality to the room list vm

src/stores/room-list-v3/RoomListStoreV3.ts, src/stores/room-list-v3/skip-list/RoomNode.ts, src/stores/room-list-v3/skip-list/RoomSkipList.ts, src/stores/room-list-v3/skip-list/filters/FavouriteFilter.ts, src/stores/room-list-v3/skip-list/filters/index.ts, src/stores/room-list-v3/skip-list/iterators.ts, test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
- A filter has a method to check if a given room satisfies some condition and a key that uniquely identifies it.
- Every room node tracks which filters apply to it and provides methods to recalculate and query this info.
- This calculation is done once for all room nodes when the skip list is built.
- This calculation is repeated only for the rooms that get updated (i.e gets re-inserted into the skiplist).
- Getting a list of filtered rooms is as simple as skipping the rooms that do not have the given filter keys in the iterator.
This PR only implements the favourite filter.
=> Room List Store: Support filters by implementing just the favourite filter

src/stores/room-list-v3/RoomListStoreV3.ts, src/stores/room-list-v3/skip-list/filters/PeopleFilter.ts, src/stores/room-list-v3/skip-list/filters/RoomsFilter.ts, src/stores/room-list-v3/skip-list/filters/UnreadFilter.ts, src/stores/room-list-v3/skip-list/filters/index.ts, test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
https://github.com/element-hq/element-web/pull/29433 implemented the favourite filter.
This PR implements all the remaining primary filters: Unread, People and Rooms.
=> Room List Store: Implement rest of the primary filters

src/stores/room-list-v3/RoomListStoreV3.ts, src/stores/room-list-v3/skip-list/filters/InvitesFilter.ts, src/stores/room-list-v3/skip-list/filters/LowPriorityFilter.ts, src/stores/room-list-v3/skip-list/filters/MentionsFilter.ts, src/stores/room-list-v3/skip-list/filters/index.ts, test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
This PR implements the remaining secondary filters in the store: mentions, low priority and invites.
=> Room List Store: Implement secondary filters

src/@types/global.d.ts, src/stores/room-list-v3/RoomListStoreV3.ts
- Attaches store to window object
- If we fetch rooms and then wait for the store to be ready, we will miss any updates that happened while we were waiting (because `onAction` returns early if the skip list isn't ready). So fetch the rooms after the space store is ready.
=> Room List Store: Fetch rooms after space store is ready + attach store to window

src/components/viewmodels/roomlist/RoomListViewModel.tsx, src/i18n/strings/en_EN.json, test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
The view model provides a list of filter objects that can be rendered by the view. This is necessary because some of the primary filters will not be available when using secondary filters.
=> RoomListViewModel: Support primary filters in the view model

src/components/viewmodels/roomlist/RoomListViewModel.tsx, src/components/viewmodels/roomlist/useFilteredRooms.tsx, test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
- The vm exposes `activateSecondaryFilter` which can be called to change the secondary filter.
- The vm exposes `activeSecondaryFilter` which tells you the currently active secondary filer.
=> RoomListViewModel: Support secondary filters in the view model

src/components/views/verification/VerificationShowSas.tsx
Fixes https://github.com/element-hq/element-web/issues/29438 - change the appearance of the "They do not match" button to match how it looks in Element X.
**After**:
**Before**:
=> White background for 'They do not match' button

res/css/components/views/utils/_Flex.pcss, src/components/utils/Flex.tsx, test/unit-tests/async-components/structures/__snapshots__/ErrorView-test.tsx.snap, test/unit-tests/components/structures/__snapshots__/FilePanel-test.tsx.snap, test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap, test/unit-tests/components/views/auth/__snapshots__/InteractiveAuthEntryComponents-test.tsx.snap, test/unit-tests/components/views/right_panel/__snapshots__/ExtensionsCard-test.tsx.snap, test/unit-tests/components/views/right_panel/__snapshots__/PinnedMessagesCard-test.tsx.snap, test/unit-tests/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap, test/unit-tests/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap, test/unit-tests/components/views/rooms/RoomHeader/__snapshots__/RoomHeader-test.tsx.snap, test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomList-test.tsx.snap, test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListCell-test.tsx.snap, test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap, test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap, test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListSearch-test.tsx.snap, test/unit-tests/components/views/rooms/__snapshots__/ThirdPartyMemberInfo-test.tsx.snap, test/unit-tests/components/views/rooms/memberlist/__snapshots__/MemberTileView-test.tsx.snap, test/unit-tests/components/views/settings/encryption/__snapshots__/ResetIdentityPanel-test.tsx.snap, test/unit-tests/components/views/settings/tabs/user/__snapshots__/EncryptionUserSettingsTab-test.tsx.snap, test/unit-tests/vector/__snapshots__/init-test.ts.snap
Add `flex-wrap` options to the `Flex` component
=> Add wrap props to flex component

.github/workflows/docker.yaml, docker/docker-entrypoint.d/18-load-element-modules.sh, docker/nginx-templates/default.conf.template, docs/install.md
Switches to `/modules` to match https://github.com/element-hq/element-modules/tree/main/modules/restricted-guests/synapse#production-installation
=> Avoid using /tmp/ for bind mounts and non-tmpfs binds

src/settings/Settings.tsx, src/stores/room-list-v3/RoomListStoreV3.ts, src/stores/room-list-v3/skip-list/RoomSkipList.ts, src/stores/room-list-v3/skip-list/sorters/AlphabeticSorter.ts, src/stores/room-list-v3/skip-list/sorters/RecencySorter.ts, src/stores/room-list-v3/skip-list/sorters/index.ts, test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
- Adds a device level setting that stores the user's sorting preference.
- Adds a `type` property to the sorter so that it can be uniquely identified.
- Replace `useAlphabeticSorting()` and `useRecencySorting()` with a single `resort(type)` method.
- RLS will use the preferred sorter at start .
=> Room List Store: Save preferred sorting algorithm and use that on app launch

package.json, src/components/views/dialogs/UserSettingsDialog.tsx, yarn.lock
As it got stuck in review for 5 months and we all forgot about it
=> Add analytics constant to encryption tab

src/components/viewmodels/roomlist/RoomListHeaderViewModel.tsx, src/components/views/rooms/RoomListPanel/RoomListHeaderView.tsx, test/unit-tests/components/viewmodels/roomlist/RoomListHeaderViewModel-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/RoomListHeaderView-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap, test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
Currently in the new room list, the compose menu displays the create room action in a space even if the user doesn't have the rights to create a room.
This PR:
- fix the `canCreateRoom` condition -> check space rights
- fix the compose menu display -> available if the user can create room or video room 
- the compose button display directly the DM dialog if the user can't create room or video room.
https://github.com/user-attachments/assets/6394bcc4-bba7-4f08-8f30-1debf4670aa5
=> New room list: fix compose menu action in space 

src/components/viewmodels/roomlist/RoomListViewModel.tsx, src/components/viewmodels/roomlist/useMessagePreviewToggle.tsx, src/settings/Settings.tsx, test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx
- Adds a device level setting that holds a boolean which represents whether message previews in the room list are turned on or off.
- Adds `useMessagePreviewToggle` hook which tracks whether message preview is turned on or off and provides a function to toggle the same.
- Uses this hook in `RoomListViewModel`
Fetching the actual message preview from the store will be done in another PR.
=> RoomListViewModel: Add functionality to toggle message preview setting

src/components/viewmodels/roomlist/MessagePreviewViewModel.tsx, test/unit-tests/components/viewmodels/roomlist/MessagePreviewViewModel-test.tsx
Continuing from https://github.com/element-hq/element-web/pull/29511
This PR implements a view model for displaying message previews.
=> Implement `MessagePreviewViewModel`

src/components/viewmodels/roomlist/RoomListViewModel.tsx, src/components/viewmodels/roomlist/useIndexForActiveRoom.tsx, test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/EmptyRoomList-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/RoomListView-test.tsx
- Provides hook `useIndexForActiveRoom(rooms)` that returns the index of the currently active room in the room list.
- Uses this hook in the vm and exposes the result for the view to use.
=> RoomListViewModel: Track the index of the active room in the list

playwright/e2e/login/login-consent.spec.ts, src/components/structures/MatrixChat.tsx, test/unit-tests/components/structures/MatrixChat-test.tsx
Fixes https://github.com/element-hq/element-web/issues/29230
New behaviour: in force-verify mode, don't open the main app UI when we launch or close the "Verify with another device" dialog:
https://github.com/user-attachments/assets/f178b28c-8e15-4081-935a-f2c588cf1b4e
=> In force-verify mode, prevent bypassing by cancelling device verification

playwright/e2e/left-panel/room-list-panel/room-list.spec.ts, src/stores/room-list-v3/skip-list/filters/UnreadFilter.ts, test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
`hasUnreadCount` makes more sense since it corresponds to whether notification is actually shown in the tile.
=> RoomListStore: Unread filter should only filter rooms having unread counts

src/components/viewmodels/roomlist/useFilteredRooms.tsx, test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
Previously we would only reset the active primary filter if it was incompatible with the secondary filter.
=> RoomListViewModel: Reset any primary filter on secondary filter change

src/Lifecycle.ts
In lifecycle, no pickle key seems to be ever created when logging in through SSO since the pickle key creation is done in `setLoggedIn` which is not called after `attemptDelegatedAuthLogin`. Thus when using SSO login, the indexed DB will be stored in plaintext on disk.
This aims to try to generate and load a pickle key in `onSuccessfulDelegatedAuthLogin`.
Testing strategy:
- On an element-desktop build with `keytar`
- Sign out/Sign in through SSO
- Check the indexed DB in the dev tools, mx_access_token should be encrypted and not in plaintext
I am still unsure on how to write unit tests about this as the OIDC native flow tests all seems to call `setLoggedIn` manually but I do not think that this code is actually reachable in the actual app when doing SSO, only `doSetLoggedIn` is.
I would …
=> Generate/load pickle key on SSO

src/components/views/rooms/UserIdentityWarning.tsx
As specified in https://github.com/element-hq/element-meta/issues/2792 , use "Dismiss" instead of "Ok" for this prompt, since the user has no other choice.
=> Use 'Dismiss' to close pinned identity changes, instead of 'Ok'

src/RoomNotifs.ts, src/stores/notifications/NotificationState.ts, src/stores/notifications/RoomNotificationState.ts, test/unit-tests/stores/notifications/RoomNotificationState-test.ts, test/unit-tests/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm-test.ts, test/unit-tests/stores/room-list/algorithms/list-ordering/NaturalAlgorithm-test.ts
The PR's goal is to put the notification business logic into the `RoomNotificationState`.  The existing `symbol`, `count` and `level` attributes are fairly high level and need to be interpreted to determine which notifications are a mention, an activity etc. In order to have this model as source of truth.
The first usage will be in the [new room list](https://www.figma.com/design/vlmt46QDdE4dgXDiyBJXqp/Left-Panel-2025?node-id=101-13076&t=x5XhFYuXIIqw4OzU-4). The final goal is to have the UI uses this model (room list, thread...) instead of having the different pieces of UI doing their own stuff. 
**State of the art (not all are listed)**
- [`StatelessNotificationBadge`](https://github.com/element-hq/element-web/blob/4a381c2a105c4f26d8e6975ee53c75b7ad204ad7/src/components/views/rooms/Notifi …
=> Room notification state: add clearer methods, documentation and deprecation

src/utils/SessionLock.ts, test/unit-tests/utils/SessionLock-test.ts
If a previous session terminated uncleanly, and then the clock is wound back, we could be waiting a very long time for the previous session's claim to expire.
We can fix this by simply treating a future claim the same as "now", and waiting for the normal stale timeout.
We also reduce the "stale" timeout from 30 seconds to 15 seconds, to reduce the amount of time we sit looking at a spinner.
Fixes: https://github.com/element-hq/element-web/issues/28168
=> Fix bug which caused startup to hang if the clock was wound back since a previous session

src/stores/room-list-v3/RoomListStoreV3.ts, src/stores/room-list-v3/skip-list/filters/UnreadFilter.ts, test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
- `UnreadFilter` matches rooms that are marked as unread.
- `RoomListStoreV3` re-inserts rooms that are marked as unread/read into the skip list.
=> RoomListStore: Unread filter should match rooms that were marked as unread

playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts, playwright/e2e/left-panel/room-list-panel/room-list.spec.ts, test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
- Moves a playwright test from `room-list.spec.ts` to `room-list-filter-sort.spec.ts` since it's related to filters.
- Two jest tests related to sorting are moved to a separate block.
=> New Room List: Move tests that are in the wrong location

playwright/e2e/crypto/dehydration.spec.ts
Task https://github.com/element-hq/element-web/issues/26468
The *Security & Privacy* tab will be removed in https://github.com/element-hq/element-web/pull/29088
This PR migrates the dehydrated e2e test using this tab.
=> e2e test: check dehydrated devices with Encryption tab instead of Security & Privacy tab

playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
Switch to another room to avoid the notification to be cleared.
Failed runs:
- https://github.com/element-hq/element-web/actions/runs/14091571994/job/39469412291
- https://github.com/element-hq/element-web/actions/runs/14091330003/job/39468619311
=> test e2e room list: fix flaky test of activity decoration

playwright/e2e/crypto/crypto.spec.ts, playwright/e2e/crypto/utils.ts
Task https://github.com/element-hq/element-web/issues/26468
Key backup section will be removed in https://github.com/element-hq/element-web/pull/29088. Use the *encryption* tab instead of the *security & privacy* tab
=> e2e test: use encryption tab in `enableKeyBackup` instead of security & settings tab

scripts/fetchdep.sh
on a push to a branch.
We previously checked out develop js-sdk even when building / testing mster. This would have worked usually, except when we have non-backwards compat changes on the js-sdk which we sometimes do with unstable interfaces (like sliding sync).
Alternative to https://github.com/element-hq/element-web/pull/29596
=> Make fetchdep check out matching branch name

src/BasePlatform.ts
The intention here is to reduce the effectiveness of notification spam by reducing the amount of noise a properly moderated room can generate.
=> Hide an event notification if it is redacted

src/components/views/messages/EditHistoryMessage.tsx, src/components/views/messages/TextualBody.tsx
Regressed by https://github.com/element-hq/element-web/pull/29586
=> Fix missing ambiguous url tooltips on Element Desktop

src/components/structures/AutoHideScrollbar.tsx, src/components/structures/ContextMenu.tsx, src/components/views/dialogs/ReportRoomDialog.tsx, src/components/views/location/MapFallback.tsx, src/components/views/messages/EventTileBubble.tsx, src/components/views/room_settings/AliasSettings.tsx, src/components/views/rooms/RoomContextDetails.tsx, src/components/views/rooms/RoomKnocksBar.tsx, src/components/views/settings/tabs/room/PeopleRoomSettingsTab.tsx, src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
Split out of https://github.com/element-hq/element-web/pull/28914
The `ReactHTML`, `ReactChild`, `ReactNodeArray`, `VFC` types got removed
=> Prepare for React 19 upgrade

docs/SUMMARY.md
jitsi.md was linked both here and in the 'setup' section and I think it's more relevant to setup. The duplicate links are now breaking the deploy for some reason. We probably shouldn't have both.
=> Remove duplicate jitsi link

res/css/views/verification/_VerificationShowSas.pcss
Emoji label was truncated during emoji SAS in languages with long word. 
Closes https://github.com/element-hq/customer-success/issues/450
| Before  | After |
| ------------- | ------------- |
| <img width="649" alt="Screenshot 2025-04-01 at 17 08 15" src="https://github.com/user-attachments/assets/73a7526c-2d24-4267-8e0f-77494ff00e16" />| <img width="649" alt="Screenshot 2025-04-01 at 17 38 46" src="https://github.com/user-attachments/assets/9d3cdf56-54f4-4259-a1e5-fbdf4068f0bd" />|
=>  Fix truncated emoji label during emoji SAS

playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts, src/components/views/rooms/RoomListPanel/RoomList.tsx
Previously, if a filter was applied and the number of rooms in the filtered result was greater than the numeric index of the active room (from before), the scroll position of the list would be maintained even though the active room is no longer in the list. It's a bit more polished to just scroll to the top in this case.
=> Room List: Scroll to top of the list when active room is not in the list

src/stores/room-list-v3/skip-list/filters/MentionsFilter.ts, test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Uses the new `isMention` which is true only for mentions and not for any highlight (invites etc..)
Would have written a playwright test but secondary filters are not yet implemented in the UI.
=> New Room List: Fix mentions filter matching rooms with any highlight

src/components/viewmodels/roomlist/useFilteredRooms.tsx, test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
When you change to a different space, you don't want the old active filters to follow you.
=> RoomListViewModel: Reset primary and secondary filters on space change

playwright/e2e/crypto/crypto.spec.ts
Task https://github.com/element-hq/element-web/issues/26468
Require https://github.com/matrix-org/matrix-js-sdk/pull/4772
- In the encryption tab, we can't set up key storage and the recovery key without verifying the device.
- The passphrase is not available in the flow of key backup setup in the encryption tab
=> test e2e: use encryption tab instead of Security & Settings tab in crypto.spec.ts

src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
1. Login
2. Choose to enter a recovery key
3. Click the "Upload" button and pick a recovery key file.
Expected: The continue button should be enabled
Actual: The continue button is disabled
The problem: the code isn't waiting for a setState statement to complete before checking the state.
- [x[ New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
=> Continue button is disabled when uploading a recovery key file

scripts/docker-package.sh
*wearing a Nordeck hat* - I hope the source branch is sufficient to auth that fact.
~~Pending clarification how to handle CLA between Nordeck and Element.~~ Corporate CLA signed, see source branch.
=> Don't crash the build when trying to docker-package from a shallow clone of a commit

src/components/viewmodels/avatars/RoomAvatarViewModel.tsx, test/unit-tests/components/viewmodels/avatars/RoomAvatarViewModel-test.tsx
Fix public icon issue in https://github.com/element-hq/element-web/issues/29722 
In the video below, the public icon is rendered on DM *Florian Duros* which is a bug:
https://github.com/user-attachments/assets/da208429-23df-4a1d-85fc-619bf3cca634
=> New room list: fix public room icon visibility when filter change

src/Searching.ts, src/components/structures/RoomSearchView.tsx, src/components/structures/RoomView.tsx, src/components/views/rooms/RoomSearchAuxPanel.tsx, src/i18n/strings/en_EN.json, test/unit-tests/components/structures/RoomSearchView-test.tsx
This is a continuation of https://github.com/element-hq/element-desktop/pull/2251.
For a recap of the context:
I sometimes use tantivy's search syntaxes in the message search: https://docs.rs/tantivy/0.12.0/tantivy/query/struct.QueryParser.html
The problem is that message search queries are sent to tantivy while typing them, thus an error pop-up can appear while typing the search request if the syntax is invalid.
The screen below is an example of what happens when I type "term1 in the message search, when I am actually trying to type "term1 term2" but the pop-up appeared too quick for me to finish writing:
With this PR, this error will display in the RoomSearchAuxPanel instead like below, allowing to continue typing the search request:
=> print better errors in the search view instead of a blocking modal

test/unit-tests/components/structures/MatrixChat-test.tsx
Fix flaky MatrixChat tests:
- `should persist login credentials` & `should store clientId and issuer in session storage`: moved the last item setted in secret storage in first position in `waitFor`
- `should log and return to welcome page with correct error when login state is not found`
Failures:
- https://github.com/element-hq/element-web/actions/runs/14445140839/job/40503877623 
- https://github.com/element-hq/element-web/actions/runs/14440956114 
- https://github.com/element-hq/element-web/actions/runs/14442109741
- https://github.com/element-hq/element-web/actions/runs/14440459480
- https://github.com/element-hq/element-web/actions/runs/14440100161
=> Fix flaky MatrixChat tests

test/unit-tests/HtmlUtils-test.tsx, test/unit-tests/components/structures/MatrixChat-test.tsx, test/unit-tests/components/structures/TimelinePanel-test.tsx, test/unit-tests/components/views/rooms/RoomHeader/RoomHeader-test.tsx, test/unit-tests/components/views/rooms/RoomHeader/__snapshots__/RoomHeader-test.tsx.snap, test/unit-tests/components/views/settings/tabs/room/NotificationSettingsTab-test.tsx, test/unit-tests/utils/notifications-test.ts
Split out from #29582 
This refactors several tests to stop mocking `SettingsStore.getValue` and instead use the actual setting store, with a reset between tests to avoid cross contamination.
For example:
```ts
jest.spyOn(SettingsStore, "getValue").mockImplementation((feature) => feature === "feature_group_calls");
// or worse
jest.spyOn(SettingsStore, "getValue").mockImplementation(() => false);
```
Is a bit annoying because it breaks some expectations and accidentally overwrites defaults, and the second example actually makes it really hard to tell what you're disabling.
Instead, I want to start using 
```ts
beforeEach(() => {
// For configuration
SdkConfig.put({
features: {
feature_group_calls: true,
}
});
// For settings
SettingsStore.setValue("showImages", null, SettingLevel.DEVICE, …
```
=> Refactor several unit tests to use SettingsStore directly.

src/components/viewmodels/avatars/RoomAvatarViewModel.tsx, src/components/views/avatars/RoomAvatarView.tsx, src/components/views/avatars/WithPresenceIndicator.tsx, src/hooks/useCall.ts, test/unit-tests/components/viewmodels/avatars/RoomAvatarViewModel-test.tsx, test/unit-tests/components/views/avatars/RoomAvatarView-test.tsx, test/unit-tests/components/views/avatars/__snapshots__/RoomAvatarView-test.tsx.snap
When changing the filters, the decorations weren't recomputed and an incorrect decoration can appears on the wrong room.
- Call decoration
- Presence indicator
=> New room list: fix incorrect decoration

src/components/viewmodels/roomlist/RoomListItemViewModel.tsx, src/components/views/rooms/NotificationDecoration.tsx, src/components/views/rooms/RoomListPanel/RoomListItemView.tsx, src/stores/notifications/RoomNotificationState.ts, test/unit-tests/components/viewmodels/roomlist/RoomListItemViewModel-test.tsx, test/unit-tests/components/views/rooms/NotificationDecoration-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemView-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListItemView-test.tsx.snap, test/unit-tests/stores/notifications/RoomNotificationState-test.ts
In order to avoid to rerender all the room list item when a room item is selected or if there is a notification, we can add a `memo`.
We need to listen to the room name and the notification changes to render the correct value.
=> New room list: avoid extra render for room list item

playwright/e2e/settings/roles-permissions-room-settings-tab.spec.ts, src/components/views/settings/PowerLevelSelector.tsx, test/unit-tests/components/views/settings/PowerLevelSelector-test.tsx, test/unit-tests/components/views/settings/tabs/room/RolesRoomSettingsTab-test.tsx
closes https://github.com/element-hq/element-web/issues/26297
=> feat: warn self change on roles settings

src/components/viewmodels/roomlist/useStickyRoomList.tsx, src/stores/spaces/SpaceStore.ts, test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
This issue happens when you are in space `X` with active room `R` and you switch to another space `Y` that also includes room `R` but `R` is not the active room in that space. In this case there's a brief delay between being told that the space has changed and that the active room has changed. This means that you might see a new list with the tile for old room (R) selected and then later a different tile being selected.
=> New Room List: Prevent potential scroll jump/flicker when switching spaces

playwright/e2e/left-panel/room-list-panel/room-list.spec.ts, src/components/viewmodels/roomlist/RoomListViewModel.tsx, src/components/viewmodels/roomlist/useRoomListNavigation.ts, test/unit-tests/components/viewmodels/roomlist/useRoomListNavigation-test.ts
Add support of these keyboard shortcuts in the new room list:
In another PR, the support to navigate the room list with `UP arrow` and `DOWN arrow`will be added.
=> New room list: add partial keyboard shortcuts support

res/css/views/rooms/RoomListPanel/_RoomListItemView.pcss
It needed min-width: 0 to allow the div to get smaller than the size necessary to display its content, apparently.
=> Fix the buttons not being displayed with long preview text

src/stores/room-list-v3/RoomListStoreV3.ts, test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
- Invites should be removed from the list when they're declined.
- Kicked rooms should remain in the list until they're explicitly forgotten.
=> RoomListStore: Remove invite rooms on decline

docs/labs.md, src/HtmlUtils.tsx, test/unit-tests/HtmlUtils-test.tsx
[MSC3765](https://github.com/matrix-org/matrix-spec-proposals/pull/3765) has been merged so this could move out of labs now – if the product team is ok with it, of course.
Requires: https://github.com/matrix-org/matrix-js-sdk/pull/4767
=> Move rich topics out of labs / stabilise MSC3765

.gitignore
As of #29089, `modules.ts` is no longer auto-generated, so should not be
gitignored. Indeed, having a copy sitting around in your working copy can
produce unexpected results, and removing it from the ignorelist at least gives
maintainers a hint about what might be going wrong.
=> Un-gitignore `modules.ts`

playwright/e2e/crypto/dehydration.spec.ts, playwright/e2e/login/login-consent.spec.ts, playwright/e2e/settings/encryption-user-tab/encryption-tab.spec.ts, src/components/structures/auth/CompleteSecurity.tsx, src/components/structures/auth/SetupEncryptionBody.tsx, src/components/views/dialogs/ResetIdentityDialog.tsx, src/components/views/settings/encryption/ResetIdentityBody.tsx, src/components/views/settings/encryption/ResetIdentityPanel.tsx, src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx, src/i18n/strings/en_EN.json, src/stores/SetupEncryptionStore.ts, test/components/views/dialogs/security/ResetIdentityDialog-test.tsx, test/components/views/dialogs/security/SetupEncryptionDialog-test.tsx, test/unit-tests/components/structures/auth/CompleteSecurity-test.tsx, test/unit-tests/components/views/settings/encryption/ResetIdentityPanel-test.tsx, test/unit-tests/stores/SetupEncryptionStore-test.ts
Fixes https://github.com/element-hq/element-web/issues/29227
This adds `IdentityResetDialog`, which wraps `IdentityResetBody` in a dialog, and launches it from `SetupEncryptionBody`, instead of doing the reset directly there.  In the new flow, only the user's cryptographic identity is reset -- recovery is no longer set up at the same time.
This is mostly work by @uhoreg , rebased and refactored a bit here.
~I recommend reviewing commit-by-commit.~
=> Update identity reset UI (Make consistent with EX)

src/components/views/right_panel/RoomSummaryCard.tsx, test/unit-tests/components/views/right_panel/RoomSummaryCard-test.tsx
Closes https://github.com/element-hq/element-web/issues/29879
Regression due to https://github.com/element-hq/element-web/pull/29850
In https://github.com/element-hq/element-web/pull/29850, the search input became controlled and its value is updated after the user has finished to type ([debounce in `RoomView`](https://github.com/element-hq/element-web/blob/f25fbdebc7091a5b296d3b0b55f706ef4896349b/src/components/structures/RoomView.tsx#L1814)).
This PR add a local state and set the new value right after the user type.
=> Remove lag in search field

playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts, src/stores/room-list-v3/RoomListStoreV3.ts, src/stores/room-list-v3/skip-list/RoomSkipList.ts, test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts, test/unit-tests/stores/room-list-v3/skip-list/RoomSkipList-test.ts
When somebody changes their display name, `m.room.member` state event and read receipts are sent to all rooms including tombstoned or upgraded rooms. Previously, the RLS would add the room associated with such events into the skiplist regardless of whether they should be shown in the list or not. This would sometime cause old upgraded rooms to show in the list. 
This PR prevents such rooms from being added into the skip list:
- Remove the old `addRoom` method.
- Introduces `reInsertRoom` method which will only insert the room if the room is already in the skiplist. This is the method that will be used most frequently.
- Introduces `addNewRoom` method that adds new rooms that are not in the skiplist. This method will throw an error if the room is already in the skiplist.
=> New Room List: Prevent old tombstoned rooms from appearing in the list

src/DeviceListener.ts, test/unit-tests/DeviceListener-test.ts
Part of https://github.com/element-hq/element-web/issues/29231
Tidy up key backup status in `DeviceListener` a little, making it easier to find out about key backup status, which we will do in later changes.
Includes a small change to behaviour: always cache the answer, instead of only caching it when the answer was `true`. I can't see a way that this will cause problems, but if the reviewer can, it is simple to change it back to only caching positive answers.
=> Cache the key backup status whether enabled or not

.github/workflows/triage-labelled.yml
Automate adding crypto team issues to their project.
Removes verticals team as they no longer exist.
=> Automate adding crypto team issues to their project based on label

src/components/viewmodels/roomlist/RoomListItemViewModel.tsx, test/unit-tests/components/viewmodels/roomlist/RoomListItemViewModel-test.tsx
Closes https://github.com/element-hq/element-web/issues/29862
This PR fixes a bug where the message preview is not re-calculated when the space or the filter change. Before, it the new room doesn't have a preview, we don't set the message preview. The previous message preview was displayed.
[Screencast_20250512_154418.webm](https://github.com/user-attachments/assets/10052575-fb3d-4bcc-a1f0-4a777c45a55b)
[Screencast_20250512_145229.webm](https://github.com/user-attachments/assets/fa6c8d09-1b7f-4d8d-a43c-b75e1de774da)
=> New room list: fix outdated message preview when space or filter change

src/accessibility/KeyboardShortcuts.ts
Closes https://github.com/element-hq/element-web/issues/29640
Regression due to https://github.com/element-hq/element-web/pull/29374
The go to home shortcut (`ctrl + option + h`) doesn't work on macos. The `alt/option`  is modifier on azerty/qwerty/xxx macos layout. `option + h`  produces `Ì` on an azerty layout.
The proposal is to change the shortcut on macos to be `ctrl + shift + h`. `cmd + shift + h` is already used by safari to jump on the home page.
But  `ctrl + shift + h` is already used by toggle action events. So I propose to change this shortcut to `ctrl + shift + j`. Go to home shortcut is in my opinion more important and vastly used than the toggle action events which is more a debug thing.
=> Fix go home shortcut on macos and change toggle action events shortcut

src/languageHandler.tsx
The types wrongly say only strings may be returned, but in reality objects can be too, when it goes wrong.
Review commit-by-commit
=> Guard against counterpart.translate returning non-string values

test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
This wasn't testing what it thought it was testing because the primary filters aren't present at all after selecting a secondary filter that's not compatible with them, so it was just asserting that some other filter (which had the same index as the old one) was disabled. It breaks if the primary filters get reordered.
@MidhunSureshR says it should be removed, and I agree as it can't test the thing it claims to.
=> Remove old filter test

src/components/structures/MatrixChat.tsx, src/dispatcher/actions.ts, src/dispatcher/payloads/AfterForgetRoomPayload.ts, src/stores/room-list-v3/RoomListStoreV3.ts, test/unit-tests/components/structures/MatrixChat-test.tsx, test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
- Adds an action `after_forget_room` to indicate when a room has been successfully forgotten. Similar to `after_leave_room`.
- RLS removes such rooms from the skiplist on this event.
=> RLS: Remove forgotten room from skiplist

res/apple-app-site-association
This was an old app variant that we've now deleted in favour of making custom TestFlight builds.
=> Remove the Apple site association for Element X PR

src/components/views/rooms/RoomHeader/RoomHeader.tsx
To avoid locking the user into the popup due to focus lock clash
Fixes #29985
=> Close call options popup menu when option has been selected

playwright/e2e/oidc/oidc-native.spec.ts
```
Error: expect.toBeVisible: Error: strict mode violation: getByText('Element') resolved to 2 elements:
1) <h3 class="_typography_6v6n8_153 _font-heading-md-semibold_6v6n8_112">…</h3> aka getByRole('heading', { name: 'Element: Chrome for Windows' })
2) <p class="_typography_6v6n8_153 _font-body-md-regular_6v6n8_50 text-ellipsis overflow-hidden">…</p> aka getByText('Element', { exact: true })
```
The devices section in OIDC frontend has changed to include a heading
with the device name. The device name and the client name both contain
"Element", so playwright fails.
=> Fix flaky OIDC test by matching text exactly

src/components/structures/RoomView.tsx, src/i18n/strings/en_EN.json, test/unit-tests/components/structures/RoomView-test.tsx, test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
For https://github.com/element-hq/element-web/issues/29969
- It's not clear to me how the membership event could change without the UI changing but nevertheless this PR adds an explicit check to ensure that users don't ignore themselves. 
- `onDeclineButtonClicked` should set `rejecting` state to true so that the UI reflects an ongoing decline.
=> Add sanity checks to prevent users from ignoring themselves

src/@types/global.d.ts, src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx, src/i18n/strings/en_EN.json, src/settings/Settings.tsx, src/vector/platform/ElectronPlatform.tsx, test/test-utils/test-utils.ts, test/unit-tests/vector/platform/ElectronPlatform-test.ts
Fixes https://github.com/element-hq/element-desktop/issues/2380
Requires https://github.com/element-hq/element-desktop/pull/2379
https://github.com/user-attachments/assets/4238641d-a33f-4bfe-81fd-702115c99f0f
=> Add ability to prevent window content being captured by other apps (Desktop)

src/SlashCommands.tsx, src/i18n/strings/en_EN.json, test/unit-tests/SlashCommands-test.tsx
Similar to https://github.com/element-hq/element-web/pull/30101 , warn the user if they might be being scammed by verifying another device via a `/verify` command.
Part of https://github.com/element-hq/element-meta/issues/2751
=> Warn user before doing a manual verification via slash command

src/components/views/dialogs/ManualDeviceKeyVerificationDialog.tsx, test/unit-tests/components/views/dialogs/ManualDeviceKeyVerificationDialog-test.tsx
~~We can't use MatrixClientContext inside a dialog at the moment.~~
We can't use MatrixClientContext inside a dialog, outside of BaseDialog, at the moment.
=> Fix #30118 - TypeError in manual verify - by using MatrixClientPeg

src/stores/spaces/SpaceStore.ts
Otherwise the list of rooms shown in the home space will be incorrect.
=> Spacestore should emit event after rebuilding home space

playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts, playwright/e2e/left-panel/room-list-panel/room-list-panel.spec.ts, playwright/e2e/left-panel/room-list-panel/room-list.spec.ts, src/components/structures/RoomView.tsx, src/components/views/rooms/RoomListPanel/RoomListPanel.tsx, src/i18n/strings/en_EN.json, test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
The old room list had a nav element but it was missed in the new one, so add it and albel the sections. Also remove the test ID and use this instead.
=> Use nav for new room list and label sections

test/test-utils/utilities.ts, test/unit-tests/components/views/settings/AddRemoveThreepids-test.tsx, test/unit-tests/components/views/settings/__snapshots__/AddRemoveThreepids-test.tsx.snap
Closes https://github.com/element-hq/element-web/issues/27678
=> test: use `forceCloseAllModals` instead of `closeCurrentModal`

src/components/viewmodels/right_panel/UserInfoPowerlevelViewModel.tsx, src/components/views/right_panel/UserInfo.tsx, src/components/views/right_panel/user_info/UserInfoPowerLevels.tsx, test/unit-tests/components/viewmodels/right_panel/user_info/UserInfoPowerLevelsViewModel-test.tsx, test/unit-tests/components/views/right_panel/UserInfo-test.tsx, test/unit-tests/components/views/right_panel/user_info/UserInfoPowerLevels-test.tsx
Part of task https://github.com/element-hq/element-web/issues/29633 to mvvm right panel
Part 2 of splitting userInfo into three components :
UserInfoAdminToolsContainer
UserInfoPowerLevel (this PR)
UserInfoView
- Remove PowerLevelsSection from  right_panel userinfo
- Create new component UserInfoAdminPowerLevels and corresponding VM
- Updated userInfo-test.tsx to remove reference to powerselector components
- Create UserInfoAdminPowerLevelsViewModel-test et UserInfoAdminPowerLevels-test
=> Mvvm split user info, create powerlevels component

src/DeviceListener.ts
Follow-up to https://github.com/element-hq/element-web/pull/30230: the comment referenced the wrong function, and Rich asked to re-add the logging.
=> fix typo in comment and reinstate logging of variables

developer_guide.md
The link was going to two archived repositories. In the meantime, the linked document was moved into the same repository. This PR updates the link.
=> Fix link to e2e docs

playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts, playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
Closes https://github.com/element-hq/element-web/issues/30220
Closes https://github.com/element-hq/element-web/issues/30223
=> Fix e2e flakes in new room list

.github/workflows/triage-stale.yml
Only the playwright tests are automatically updated, and are therefore safe to auto-close.
=> Flaky test issue auto-closer: only close playwright test issues

src/components/views/rooms/MemberList/MemberListView.tsx, test/unit-tests/components/views/rooms/memberlist/MemberListView-test.tsx
Notes: Fix a bug (#30253) where pressing Enter in the right panel member search would refresh the page.
Fixes #30253
=> Fix: Prevent page refresh on Enter key in right panel member search

playwright/e2e/left-panel/room-list-panel/room-list.spec.ts, playwright/pages/ElementAppPage.ts
Closes https://github.com/element-hq/element-web/issues/30221
Closes  https://github.com/element-hq/element-web/issues/30223
Closes https://github.com/element-hq/element-web/issues/30222
The flaky behavior is in the code that scrolls the list to the bottom:
1. Playwright's [mouse.wheel](https://playwright.dev/docs/api/class-mouse#mouse-wheel) returns before the scrolling is completed.
2. Visibility assertion does not check if the element is visible to the user. For that we would use [toBeInViewport](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-in-viewport).
This PR introduces a more reliable scroll method ( :crossed_fingers: ).
=> Fix flaky tests in `playwright/e2e/left-panel/room-list-panel/room-list.spec.ts`

res/css/structures/_LeftPanel.pcss
Add a background color to override the default left panel color of the old room list. This is needed for https://github.com/element-hq/element-desktop/pull/2446.
When we will delabse the new room list, we will able to clean all these background color overrides.
=> Add a background color to left panel for macos titlebar in element desktop

test/unit-tests/components/structures/MatrixChat-test.tsx
- Can't reproduce locally
- Can't reproduce in the CI when only running this particular test file multiple times
- Can't reproduce in a test PR running all the tests though it still seems to flake in other unrelated PRs
When the test flakes, [a toast for unsupported browser](https://github.com/element-hq/element-web/blob/develop/src/SupportedBrowser.ts#L90) is shown. Further debugging would require having some tooling to output the stack trace of how the app reached that function. 
We can't spend any more time on this, so disabling this test for now.
=> Disable flaky jest test: `<MatrixChat /> › Multi-tab lockout › waits for other tab to stop during startup`

res/css/structures/_LeftPanel.pcss
https://github.com/element-hq/element-web/pull/30328 tries to fix the grey background on the titlebar on ED. Somehow the fix is working on ED in dev but doesn't work when built.
=> Force ED titlebar color for new room list

.storybook/preview.tsx
This PR:
- Add the tooltip provider to the stories as a decorator
- Sort alphabetically the stories
=> Storybook: add tooltip provider and sort stories

src/components/views/rooms/EventTile.tsx
A forthcoming change to the js-sdk will add a new event shield reason. To avoid a compile-time failure, add a `default` case to the code handling those reasons.
=> Allow for unknown event shield reasons

src/components/views/rooms/EventTile.tsx, src/i18n/strings/en_EN.json, test/unit-tests/components/views/rooms/EventTile-test.tsx
The js-sdk now exposes a new event shield reason, which we should handle correctly.
=> Support `EventShieldReason.MISMATCHED_SENDER`

test/unit-tests/components/structures/MatrixChat-test.tsx
a couple of cleanups in MatrixChat which may make it more robust, but at the very least will make it log less spam.
Possible this will help with https://github.com/element-hq/element-web/issues/30337 and/or https://github.com/element-hq/element-web/issues/29708
=> MatrixChat test robustness fixes

test/unit-tests/components/structures/MatrixChat-test.tsx
Now that we have better logging for our tests (https://github.com/element-hq/element-web/pull/30405), I'd like to re-enable this test so we can try and understand what makes it fail.
related: https://github.com/element-hq/element-web/issues/30337
=> Re-enable matrixchat test

test/unit-tests/components/structures/MatrixChat-test.tsx
Add a sleep to let these tests clean up.
Hopefully: fixes #30337, fixes #29708
=> Hacky fix to the MatrixChat flakiness

src/components/views/messages/DownloadActionButton.tsx, src/i18n/strings/en_EN.json, test/unit-tests/components/views/messages/DownloadActionButton-test.tsx
...when downloading encrypted attachments (regressed by https://github.com/element-hq/element-web/pull/30330).
Also adds tests for the tooltips and fix the tests so they don't pollute mocks / dialogs.
=> Put the 'decrypting' tooltip back

playwright/e2e/audio-player/audio-player.spec.ts
Fixes https://github.com/element-hq/element-web/issues/27451
Switching to the `Replying` state was racing with the media message, causing it to not be a reply
=> Fix race condition in flaky reply chain test

playwright/e2e/crypto/device-verification.spec.ts, playwright/e2e/crypto/utils.ts, res/css/views/dialogs/security/_AccessSecretStorageDialog.pcss, src/components/views/dialogs/security/AccessSecretStorageDialog.tsx, src/i18n/strings/en_EN.json, test/unit-tests/components/views/dialogs/AccessSecretStorageDialog-test.tsx
Improve one of the cases for Web described in https://github.com/element-hq/element-meta/issues/2888
When prompting the user for a recovery key in order to verify (either on login or later), hide the key by default and allow the user to show it:
We do this by using the Compound `PasswordInput` component.
The designs for this are here: https://www.figma.com/design/ZodBLtGnKmRTGJo5SGLnH3/ER-137--Excluding-Insecure-Devices?node-id=102-43729&t=QmewENUd7f6Tmw9U-1
This PR does not bring us fully into line with the designs, but I think it is a step forward:
* Improvement: hides the recovery key and allows showing it
* Improvement: when the [localazy PR](https://github.com/element-hq/element-web/pull/30407) is merged, shows the correct title "Enter your recovery key" instead of just "Recovery …
=> Hide recovery key when prompting for verification

src/components/views/elements/AppTile.tsx
15f1291cbcbb5920f87fd0ea73dba27ce12d91b1 was really close to making widgets just work again in React development mode following the upgrade to React 19, but I forgot to test one thing: that persistent widgets (such as Element Call) still reuse the same iframe across their entire lifecycle as expected. The solution is to not manually destroy the iframe when AppTile is being unmounted; even if it turns out that the widget isn't actually persistent, React will still destroy it automatically for us.
=> Fix widget persistence in React development mode

src/RoomInvite.tsx, src/utils/MultiInviter.ts
As far as I can tell, the last time most of this code was changed was when Promises were the new hotness and `async` was but a twinkle in ECMA's eye. It is, therefore, somewhat opaque by modern standards.
This refactor aims to be a non-functional update of the code to use loops and `async/await` rather than recursive function invocations and explicit promise chains.
Suggest review commit-by-commit.
=> Refactor MultiInviter

src/hooks/room/useRoomCall.tsx
It would previously say no permission if you had no perms for an EC call but had perms for a legacy call.
Fixes https://github.com/element-hq/element-web/issues/30502
=> Fix call permissions check confusion around element call

src/RoomInvite.tsx, src/utils/MultiInviter.ts, src/utils/RoomUpgrade.ts, test/unit-tests/RoomInvite-test.ts
I'm going to add another option, so an options object is going to be more flexible.
To make it easier to see what we're changing, also move `inviteUsersToRoom` to `RoomUpgrade`.
=> Update `MultiInviter` to take an options object

src/stores/widgets/StopGapWidgetDriver.ts, test/unit-tests/stores/widgets/StopGapWidgetDriver-test.ts
=> Element Call widget driver: allow state keys to have a `_m.call` suffix

src/components/utils/ListView.tsx, src/components/viewmodels/memberlist/MemberListViewModel.tsx, src/components/views/rooms/MemberList/MemberListView.tsx, test/unit-tests/components/views/utils/ListView-test.tsx
Space/Enter keys fire the onClick so this feels like extra code for no benefit handling this in the ListView.
=> Remove onSelectItem and space/enter handing from ListView

src/components/views/rooms/MessageComposer.tsx, src/i18n/strings/en_EN.json, test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
Add missing tooltip and aria-label to lock icon next to composer
=> Fix: add missing tooltip and aria-label to lock icon next to composer

playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
Fixes https://github.com/element-hq/element-web/issues/29875
Wait for unread room to display before focusing it with the keyboard
=> Fix flakey e2e test: should select the next unread room - 

test/unit-tests/components/views/rooms/RoomHeader/RoomHeader-test.tsx
Relates to https://github.com/element-hq/element-web/pull/30373
particularly the error [here](https://github.com/element-hq/element-web/actions/runs/17267624334/job/49003487404?pr=30373).
```
● RoomHeader › group call enabled › close lobby button is shown if there is an ongoing call but we are viewing the lobby
TypeError: Cannot read properties of undefined (reading 'length')
46 |         call ?? undefined,
47 |         CallEvent.Participants,
> 48 |         useCallback((state) => state ?? call?.participants ?? [], [call]),
|                    ^
49 |     );
50 | };
51 |
at areHookInputsEqual (node_modules/react-dom/cjs/react-dom-client.development.js:5478:36)
at updateCallback (node_modules/react-dom/cjs/react-dom-client.development.js:6595:28)
at Object.useCallback …
```
=> Fix Jest test: Mock CallStore.getCall rather than individual hooks like useParticipants

src/settings/SettingsStore.ts, src/settings/controllers/ServerSupportUnstableFeatureController.ts
The function was supposed to return an i18ned string but lacked a _t
=> Fix i18n of message when a setting is disabled

src/settings/Settings.tsx
Update it to look for the stable-suffixed version too.
This will only be relevant until the next spec release but may as well fix it.
Requires https://github.com/matrix-org/matrix-js-sdk/pull/4983
=> Fix stable-suffixed MSC4133 support

docker/docker-entrypoint.d/18-load-element-modules.sh
Bash is great. So great in fact, that if your glob expression doesn't match any files then the loop will run once with your glob expression *as* the only item.
This causes Element Web to fail to run when the `/modules` directory is present, as it thinks it has found a module under `*`. This sets `nullglob` which works as you'd expect by skipping the for loop if a glob expression doesn't match.
=> Ensure container starts if it is mounted with an empty /modules directory.

src/SecurityManager.ts, src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx, src/utils/WellKnownUtils.ts
Support for these two `.well-known/matrix/client` settings (`secure_backup_required` and `secure_backup_setup_methods`) has been removed from everywhere in Element Web except in a rather obscure corner of the code. There are many other problems with this area  (https://github.com/element-hq/element-web/issues/29171) but removing support for the outdated option is an easy step, and doing so means we can update the documentation about these options.
=> Remove remaining support for outdated .well-known settings

playwright/e2e/crypto/event-shields.spec.ts, playwright/e2e/crypto/toasts.spec.ts, playwright/e2e/crypto/utils.ts
Fixes: https://github.com/element-hq/element-web/issues/28836 (I hope)
The test seems to be failing because the `viewRoomById` call (which works by replacing the URL) is racing with the application's redirect to `/#/home` after verification completes. If we wait for the redirect to happen first, we should be able to avoid the race.
Review commit-by-commit.
=> Fix flaky shields playwright test

src/hooks/room/useRoomCall.tsx
This just removes the 'beta' lebelling: it does not take it out of labs by default just yet.
=> Remove 'beta' pill from Element Call option

src/vector/platform/ElectronPlatform.tsx, test/unit-tests/vector/platform/ElectronPlatform-test.ts
as otherwise they won't be shown and will be reset out of existence
=> Hold Electron toasts until after the client starts

src/components/views/rooms/RoomListPanel/RoomListPrimaryFilters.tsx, test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx, test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPrimaryFilters-test.tsx.snap
Closes https://github.com/element-hq/element-web/issues/30772
The tests need to be updated because when `offsetLeft` isn't mocked its value is `0`. Previously it wasn't considered at wrapping when to sibling elements had the same `offsetLeft`, so without mocking all the list was displayed.
=> Avoid flicker of the room list filter on resize

src/components/views/dialogs/VerificationRequestDialog.tsx, test/unit-tests/components/views/dialogs/VerificationRequestDialog-test.tsx, test/unit-tests/components/views/dialogs/__snapshots__/VerificationRequestDialog-test.tsx.snap
Part of https://github.com/element-hq/element-meta/issues/2898
We were passing on `this.props.verificationRequest` to `EncryptionPanel` but we should be passing on the request in `this.state`. This would not cause a problem in practice because the `EncryptionPanel` immediately overwrites the request if you supply a `verificationRequestPromise`.
=> Fix theoretical bug where VerificationRequestDialog uses an outdated request

src/shared-components/hooks/useListKeyDown.test.ts, src/shared-components/hooks/useListKeyDown.ts, src/shared-components/rich-list/RichItem/RichItem.module.css, src/shared-components/rich-list/RichItem/RichItem.tsx, src/shared-components/rich-list/RichItem/__snapshots__/RichItem.test.tsx.snap, src/shared-components/rich-list/RichList/RichList.tsx, src/shared-components/rich-list/RichList/__snapshots__/RichList.test.tsx.snap
https://github.com/element-hq/customer-success/issues/501
Fixing https://element-io.atlassian.net/browse/PSB-918
The report was on the previous list in the invite dialog however the new one has some a11y flaws.
https://github.com/user-attachments/assets/b9295501-35a8-4e9f-aea2-bcf66f6804e3
=> Fix a11y issue on list in invite dialog

src/components/viewmodels/roomlist/useFilteredRooms.tsx, test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
Resolves https://github.com/element-hq/wat-internal/issues/289
Reverts the behaviour introduced in https://github.com/element-hq/element-web/pull/29672
=> New Room List: Don't clear filters on space change

src/components/views/room_settings/RoomProfileSettings.tsx, src/components/views/settings/AvatarSetting.tsx, src/components/views/settings/UserProfileSettings.tsx, src/i18n/strings/en_EN.json, test/unit-tests/components/views/settings/AvatarSetting-test.tsx
- Previously, `avatarElement` would be an `<AccessibleButton>` with a nested `<BaseAvatar>` if `avatarUrl` wasn't available. Otherwise, it would be a lone `<AccessibleButton>` rendered as an `img`. This seems unnecessary, so I've changed it to always be a button with an avatar inside it.
- There was a broken aria reference: the accessible button had an  `aria-labelledby` that had an id which no actual element in the DOM had. We no longer need a labelled by for the button since it takes its accessible name from the base avatar.
- Add `tabIndex` to the buttons so that it can be selected through the keyboard.
- Added `aria-haspopup` and  `aria-label` to `uploadAvatarBtn` so that screen readers indicate that this button opens a menu.
- `avatarAltText` prop is renamed to `avatarAcessibleName` …
=> Improve accessibility of the `<AvatarSetting> component

src/ContentMessages.ts, src/components/views/messages/MImageBody.tsx, src/utils/Image.ts, src/utils/MediaEventHelper.ts, test/unit-tests/Image-test.ts, test/unit-tests/utils/MediaEventHelper-test.ts
Fixes https://github.com/element-hq/element-web/issues/30889
=> Improve handling of animated images, add support for AVIF animations
