element-hq/element-web

package.json
yarn.lock

Port https://github.com/vector-im/element-web/pull/16347 to release

[Release] Upgrade matrix-widget-api

---

README.md

Add configuration security best practices to the README.

---

README.md

jenkins is dead. long live the king.

README: remove Jenkins reference

---

docs/config.md

or: remove the virtual room mapping config option
as per https://github.com/matrix-org/matrix-react-sdk/pull/5639

VoIP virtual rooms, mkII

---

element.io/app/config.json
element.io/develop/config.json

The hostSignup dialog will be configured to a host setup wizard at EMS for the Element Home product.

Add hostSignup config for element.io clients

---

README.md
babel.config.js

Fixes https://github.com/vector-im/element-web/issues/9175
See also https://github.com/matrix-org/matrix-react-sdk/pull/5721

Add Edge to the supported tier

---

yarn.lock

I think this is what is causing https://github.com/vector-im/element-web/issues/16589

Update velocity-animate dependency

---

docs/config.md

**Requires https://github.com/matrix-org/matrix-react-sdk/pull/5658**

Docs for `loginForWelcome`

---

.github/PULL_REQUEST_TEMPLATE.md

Echo of [Synapse's file](https://github.com/matrix-org/synapse/blob/develop/.github/PULL_REQUEST_TEMPLATE.md)
To remind contributors they need to sign-off their commits or PRs before submitting them.
`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

Create bare-bones `PULL_REQUEST_TEMPLATE.md`

---

README.md
docs/kubernetes.md

This is the cleaned version of kubernetes config I use to run it in my own environment.
It simply shows users how they can get it running and how to get the config operational in a way that works.
This is intended as a basic "getting started" example.

Add example for deployment into Kubernetes

---

.github/ISSUE_TEMPLATE/suggestion-or-feature-request.md

Like https://github.com/vector-im/element-android/pull/2997
Effectively make the issues more readable, doesn't change the look of em much (bold == 4-nested headings), only adds a bit of margin around the headers.
`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

Change ISSUE_TEMPLATE bold lines to proper headers

---

src/vector/platform/ElectronPlatform.tsx

Fixes vector-im/element-web#16620
Related pull request
* vector-im/element-desktop#173
* matrix-org/matrix-react-sdk#5793

Add user settings for warn before exit

---

element.io/develop/config.json

Switch develop to not-staging Scalar by default

---

yarn.lock

Following up on matrix-org/matrix-react-sdk#5836

Remove velocity-animate from lockfile

---

src/vector/rageshakesetup.ts

Chrome updated its UI and renamed that option

Rename blackboxing to new option ignore list

---

docs/labs.md

See https://github.com/matrix-org/matrix-react-sdk/pull/5873

Labs documentation for DND mode

---

docs/config.md

Docs for https://github.com/matrix-org/matrix-react-sdk/pull/5886

Document option for obeying asserted identity

---

package.json
yarn.lock

The limit depth option has been available in a released version for a while now.

Switch back to release version of `sanitize-html`

---

package.json
webpack.config.js

----
See https://github.com/matrix-org/matrix-react-sdk/pull/5989
----

Add required webpack+jest config to load Safari support modules

---

docs/labs.md

Companion to https://github.com/matrix-org/matrix-react-sdk/pull/6213

Labs: feature_report_to_moderators

---

Dockerfile

Upstreamed whitespace fix from a fork, to be aligned with the other indented line :)

Fix whitespace in Dockerfile

---

package.json
yarn.lock

Update matrix-widget-api to fix build issues

---

src/vector/platform/ElectronPlatform.tsx

Requires https://github.com/matrix-org/matrix-react-sdk/pull/6220

Improve typing of Event Index Manager / Seshat

---

package.json

Needed for matrix-org/matrix-react-sdk#6262 CI to pass

Mock context-filter-polyfill for app-tests

---

package.json
yarn.lock

Requires https://github.com/matrix-org/matrix-react-sdk/pull/6358

Remove node-canvas devDependency

---

Dockerfile

I was using this on top of your container for some time, so why not upstream it ;)

Don't run nginx as root in docker

---

src/vector/platform/ElectronPlatform.tsx

Requires https://github.com/matrix-org/matrix-react-sdk/pull/6345

Improve and consolidate typing

---

src/vector/mobile_guide/index.html

Part of the fix for #10569, together with:
- matrix-org/matrix-js-sdk#1782
- matrix-org/matrix-react-sdk#6365

Standardise casing of identity server

---

.github/PULL_REQUEST_TEMPLATE.md

See https://github.com/matrix-org/matrix-js-sdk/pull/1787

Update PR template for new changelog generation

---

webpack.config.js

**Review with https://github.com/matrix-org/matrix-react-sdk/pull/6453**
Notes: none
element-desktop notes: none

Update webpack path for new voice message worker location

---

src/vector/platform/ElectronPlatform.tsx

Fixes https://github.com/vector-im/element-web/issues/18266

Dismiss electron download toast when clicking Open

---

docs/labs.md

**Review with https://github.com/matrix-org/matrix-react-sdk/pull/6437**
----
**Code reviewer**: This is up for review to get the early checkmark while we check the design requirements. A changelog will be provided before merging.
----
Notes: Remove voice messages from labs, enabling them for everyone.

Remove voice messages labs flag docs

---

.github/workflows/issues_to_projects.yaml

Add github workflow to put issues tagged design on the design board

---

package.json
src/vector/index.html
webpack.config.js
yarn.lock

Fixes https://github.com/vector-im/element-web/issues/18393
***Requires https://github.com/matrix-org/matrix-react-sdk/pull/6553***

Properly handle react-sdk's recorder worklet

---

.github/ISSUE_TEMPLATE/bug-desktop.yml
.github/ISSUE_TEMPLATE/bug-web.yml

Tidy issue templates

---

docs/labs.md

For https://github.com/matrix-org/matrix-react-sdk/pull/6390
Notes: none

[Labs] Document hidden read receipts

---

.github/workflows/triage-incoming.yml
.github/workflows/triage-needs-info.yml

The Action token may or may not work, no way to test without trying
Signed-off-by: Ekaterina Gerasimova <kittykat3756@gmail.com>

Add Actions for moving tasks on triage workboard

---

CONTRIBUTING.md

Notes: none
Signed-off-by: Zane Schaffer <hello@zanes.house>

Fix dead link in contribution.md

---

package.json
yarn.lock

See https://github.com/matrix-org/matrix-js-sdk/pull/1840
Type: task
---

Use changelog generator from npm

---

webpack.config.js

---
A reviewer can add one of: `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

Fix wrong variables in webpack config

---

README.md

Another place we reference this
---

Update README to require node 14

---

.env.example
README.md
src/vector/devcss.ts
src/vector/index.ts
webpack.config.js

In #18318, I noticed some typos and phrasing I thought was a bit confusing, so I'm proposing some changes here. Additionally there was a small bug related to defaulting to the `light` theme (we were defaulting to `dark`).
I realize phrasing is a lot about personal preference, so I'll be happy to close this PR and open a new one that only fixes the typos and the bug, if requested.
---

Hot reload follow up

---

.github/workflows/issues_to_projects.yaml

1/ O-Frequent/P-High: All issues
2/ O-Intermediate/P-Medium issues which match S-Critical, S-Major or S-Minor
---

Issue triage: update automation for design team

---

.github/workflows/issues_to_projects.yaml
.github/workflows/triage-priority-bugs.yml

Issue triage: update automation for new labels

---

docs/config.md

Documents keys added in https://github.com/matrix-org/matrix-react-sdk/pull/6597
---
* Documentation for sentry config ([\#18608](https://github.com/vector-im/element-web/pull/18608)). Contributed by [novocaine](https://github.com/novocaine).

Documentation for sentry config

---

src/vector/app.tsx
webpack.config.js

Fixes https://github.com/vector-im/element-web/issues/18649
---

Fix CI using invalid NODE_ENV

---

.github/workflows/triage-priority-bugs.yml

Fix workflow column name as we renamed it

---

.env.example
webpack.config.js

Disable HMR error page by default

---

yarn.lock

Fix invalid yarn.lock

---

yarn.lock

Lock matrix-widget-api to 0.1.0-beta.16

---

.github/workflows/issues_to_projects.yaml

Move A-Spaces issues to Delight project board GHA

---

element.io/develop/config.json

Configure sentry for Element Web's develop environment using support added in https://github.com/matrix-org/matrix-react-sdk/pull/6597
---

Configure sentry on develop

---

.env.example

Encourage false positives of the error dialog to result in tickets

---

docs/translating-dev.md

Fix broken readme link in https://github.com/vector-im/element-web/blob/develop/docs/translating-dev.md#adding-new-strings (no attached issue)
---

Fix broken readme link

---

src/vector/index.ts
src/vector/localstorage-fix.ts

This commit gets rid of log-level data in localStorage which in some
extreme cases could fill up the entire localStorage making the app
unusable
Followup to https://github.com/matrix-org/matrix-js-sdk/pull/1880
---

Remove accidentally persisted log-level data

---

webpack.config.js

Type: task
Requires https://github.com/matrix-org/matrix-react-sdk/pull/6862
---

Convert `/src/usercontent` to TS

---

nginx/conf.d/default.conf

I meant to include this in https://github.com/vector-im/element-web/pull/19203 
---

Remove superfluous index.htm

---

README.md

Make caching recommendation similar to what we do, see internal change https://github.com/matrix-org/matrix-ansible-private/issues/3597
---

Suggest setting Cache-Control: no-cache on / for self-hosters

---

.github/ISSUE_TEMPLATE/bug-desktop.yml
.github/ISSUE_TEMPLATE/bug-web.yml

Improvements to bug issue templates

---

.github/workflows/sentry-sourcemaps.yaml

Fix indentation

---

.github/workflows/sentry-sourcemaps.yaml

Add missing job name for workflow

---

.github/workflows/sentry-sourcemaps.yaml

This allows the sourcemap generation to be triggered by https://github.com/matrix-org/matrix-react-sdk/pull/7062
---

Listen to repository dispatch event in sourcemaps job

---

yarn.lock

This affects release builds only, for some reason.
---

Fix widget-api lockfile reference to avoid dependency conflicts

---

.github/workflows/triage-move-labelled.yml

Update workflow name to be correct

---

.github/workflows/triage-move-labelled.yml

Workflow: move voice message issues to their board

---

docs/labs.md

related to: https://github.com/matrix-org/matrix-react-sdk/pull/7084
---

Add docs for maximised widgets labs feature

---

.github/workflows/triage-move-unlabelled.yml

Previous check doesn't really work. I've tested this as much as I can without pushing it.
---

Workflow: do a better check on X-Needs-Info for unlabelling

---

.github/workflows/triage-move-labelled.yml

Try sending the priority design issues to the beta board
---

Update design team workflow to use beta board

---

.github/workflows/triage-priority-bugs.yml

Move high priority issues which have an E2EE label to the crypto team
org level old style project board.
---

Move P1 issues to crypto team board

---

.github/workflows/triage-move-labelled.yml

Keep automation for old board too as we haven't moved the team yet
---

Move Spaces issues to new Delight board

---

.github/workflows/triage-move-labelled.yml

Fix conditional check before moving design issues

---

.github/workflows/triage-move-labelled.yml

Voice-Messages are moving to org-level beta board so add automation to
send issues there (will remove old board automation after the move).
---

Actions: use new voice message board for issues

---

.github/workflows/triage-move-labelled.yml
.github/workflows/triage-priority-bugs.yml

Issue automation workflow updates

---

.github/workflows/triage-move-review-requests.yml

Attempt to add PRs that require Design review to the Design board automatically.
Fixes https://github.com/vector-im/element-meta/issues/65
---

Review requests workflow

---

.github/workflows/triage-move-review-requests.yml

Move workflow env sections into steps for PR workflow

---

src/vector/platform/ElectronPlatform.tsx

Improve platform types

---

scripts/copy-res.js

Fixes https://github.com/vector-im/element-web/issues/20030#issuecomment-985482869
Signed-off-by: Linerly <linerly@protonmail.com>
---
* Add support for the Indonesian language ([\#20032](https://github.com/vector-im/element-web/pull/20032)). Fixes #20030. Contributed by @Linerly.

Add support for the Indonesian language

---

docs/config.md

For work in https://github.com/matrix-org/matrix-react-sdk/pull/6936
---

Add analyticsOwner flag

---

src/vector/platform/WebPlatform.ts

Push https://github.com/vector-im/element-web/pull/20061 to the RC
---

Normalize the local app version when checking for updates

---

element.io/develop/config.json

Add map_style_url to develop.element.io

---

README.md

Update outdated unit test info in README.md

---

.github/workflows/triage-move-labelled.yml

- Remove automation for v1 board as v2 board is now in use
- Update naming for the workflow because there's only one board now
- Add Z-IA issues to Delight workboard
---

Update issue automation for the Delight team

---

.github/workflows/triage-move-labelled.yml

Add automation to move message bubbles issues to message bubbles board

---

.github/workflows/triage-move-labelled.yml
.github/workflows/triage-move-review-requests.yml

Fix graphql warning for wrong types in workflows

---

package.json
yarn.lock

update olm to 3.2.8

---

scripts/copy-res.js

https://translate.element.io/languages/vi/element-web/ has been professionally translated by an Element customer
Signed-off-by: Ben Parsons <benp@element.io>
---
* Include Vietnamese language ([\#20029](https://github.com/vector-im/element-web/pull/20029)).

Include Vietnamese language

---

src/vector/platform/ElectronPlatform.tsx
src/vector/platform/WebPlatform.ts

Fixes https://github.com/vector-im/element-web/issues/20036
To review alongside with https://github.com/matrix-org/matrix-react-sdk/pull/7355
- Open thread on native notification click
- Allow notification stacking on WebPlatform
---

Open thread on native notification click

---

docs/config.md

Signed-off-by: Kerry Archibald <kerrya@element.io>
---

add docs for UIFeature.TimelineEnableRelativeDates

---

src/@types/global.d.ts
src/vector/platform/ElectronPlatform.tsx

Abstract electron download path behind an opaque ID

---

.github/workflows/triage-move-review-requests.yml

Print out requested teams in review-request workflow

---

.github/workflows/triage-move-review-requests.yml

In review-request action, treat requested_teams as an array

---

.github/workflows/triage-move-review-requests.yml

Supply team name to review-request action

---

docs/labs.md

Required for: https://github.com/vector-im/element-web/issues/20432
---

Remove maximised widget feature docs

---

scripts/fetch-develop.deps.sh

This is important for branch testing, especially via HTTPS.
---

Disable Git interactive auth when fetching deps

---

test/app-tests/joining-test.tsx
test/app-tests/loading-test.tsx

Requires https://github.com/matrix-org/matrix-js-sdk/pull/2100
Will fix test failures in https://github.com/matrix-org/matrix-react-sdk/pull/7470
---

Fix app tests for new startClient method

---

.github/workflows/triage-move-labelled.yml
.github/workflows/triage-move-unlabelled.yml

Required for: https://github.com/vector-im/element-web/issues/20432
Fixes: https://github.com/vector-im/element-web/issues/20485
---

Remove Z-Maximised-Widgets label from issue automation.

---

.github/workflows/triage-move-unlabelled.yml

Fix logic for removing Z-Labs tag with issue automation

---

element.io/app/config.json

Point app.element.io at the production Posthog instance. 
---
* Enable posthog on app.element.io ([\#20539](https://github.com/vector-im/element-web/pull/20539)). Contributed by @novocaine.

Enable posthog on app.element.io

---

test/app-tests/loading-test.tsx

Requires https://github.com/matrix-org/matrix-js-sdk/pull/2107
---

Expect /capabilities after startClient in app tests

---

docs/labs.md

Remove the documentation of the Polls labs feature

---

package.json

Before:
```
...
2022-01-20 17:11:43.404 [element-js] <s> [webpack.Progress] 59% building 11/13 modules 2 active /home/andy/code/public/element-web/element-web/node_modules/worker-loader/dist/cjs.js!/home/andy/code/public/element-web/element-web/node_modules/babel-loader/lib/index.js??ref--5!/home/andy/code/public/element-web/matrix-react-sdk/src/workers/indexeddb.worker.ts
2022-01-20 17:11:43.415 [element-js] <s> [webpack.Progress] 61% building 11/13 modules 2 active /home/andy/code/public/element-web/element-web/node_modules/worker-loader/dist/cjs.js!/home/andy/code/public/element-web/element-web/node_modules/babel-loader/lib/index.js??ref--5!/home/andy/code/public/element-web/matrix-react-sdk/src/workers/indexeddb.worker.ts
2022-01-20 17:11:43.433 [element-js] <s> [webpack.Progress] 64% …
```

Quieten webpack-dev-server output so yarn start is less noisy

---

docs/config.md
docs/labs.md
element.io/develop/config.json

New config for maps

---

docs/labs.md

Added by https://github.com/matrix-org/matrix-react-sdk/pull/7618
---

Add labs docs for right panel default open

---

docs/labs.md

Requires https://github.com/matrix-org/matrix-react-sdk/pull/7612
---

De-labs Message Bubbles layout

---

.github/ISSUE_TEMPLATE/bug-desktop.yml

See vector-im/element-android#4963

Add case for local or non public homeserver.

---

.github/ISSUE_TEMPLATE/bug-desktop.yml
.github/ISSUE_TEMPLATE/bug-web.yml

Fix validation error in issue templates

---

docs/jitsi.md

and also rephrase a bit I was failing to understand
Fixes https://github.com/vector-im/element-web/issues/20552
---

Update jitsi doc to specify minimum version

---

.github/ISSUE_TEMPLATE/config.ylm

Move security vulnerability link into the config
Add questions/support link
Remove link to open a blank issue
---

Update new issue page on GitHub

---

docs/config.md

Document use of .well-known for tile server and jitsi

---

docs/config.md
src/vector/app.tsx

---
* Support a config option to change the default device name ([\#20790](https://github.com/vector-im/element-web/pull/20790)).

Support a config option to change the default device name

---

docs/config.md

Document `uisi_autorageshake_app` config option

---

src/vector/platform/ElectronPlatform.tsx

Fixes https://github.com/vector-im/element-web/issues/21032
Type: task
Requires https://github.com/matrix-org/matrix-react-sdk/pull/7782
Requires https://github.com/vector-im/element-desktop/pull/320
---

Switch to IPC channel for `getDesktopCapturerSources`

---

element.io/app/config.json

https://github.com/vector-im/element-web/pull/21076 to release branch
---

Add map_style_url to config for app.element.io

---

config.sample.json

Fixes https://github.com/vector-im/element-web/issues/21075
---

Provide sample config for the map_style_url

---

docs/config.md

Deprecate Piwik/Matomo support

---

webpack.config.js

Tweak webpack config around stubbing node modules 

---

docs/labs.md

Docs for https://github.com/matrix-org/matrix-react-sdk/pull/7815
---

Docs for labs flag: Show only current profiles

---

docs/labs.md

https://github.com/matrix-org/matrix-react-sdk/pull/7919
---

labs doc for feature_location_share_pin_drop

---

package.json
yarn.lock

Install types for ua-parser-js

---

package.json

Signed-off-by: Kerry Archibald <kerrya@element.io>
---

add svg mock to jest config

---

docs/labs.md

Added Threaded Messaging

---

.github/workflows/triage-labelled.yml

Fixes #21177
Signed-off-by: Danielle Kirkwood <daniellek@element.io>
---

Add FTUE and WTF label automations to project boards

---

docs/labs.md

https://github.com/matrix-org/matrix-react-sdk/pull/7997
---

add feature_location_share_live doc

---

.eslintrc.js

Specified React version 🔧

---

.github/ISSUE_TEMPLATE/config.yml

Remove duplicate security policy link from new issues page

---

.github/workflows/triage-labelled.yml
.github/workflows/triage-unlabelled.yml

Add voice rooms to labs labels

---

element.io/app/config.json
element.io/develop/config.json

Update Posthog URLs

---

package.json

See https://github.com/matrix-org/matrix-react-sdk/pull/8132
---

Fix style lint on Windows

---

docs/feature-flags.md

Update location of Settings.ts in labs docs

---

.github/workflows/triage-unlabelled.yml

Type: task
Closes https://github.com/vector-im/element-web/issues/21556.
---

Fix typo in labs label workflow

---

.github/workflows/triage-labelled.yml
.github/workflows/triage-unlabelled.yml

Update name of video rooms label

---

.github/workflows/triage-labelled.yml

Fix label triage automation

---

docs/labs.md

Try to clarify what the previews are
---

Improve wording in the labs docs page

---

README.md
docs/choosing-an-issue.md

Add 'Choosing an issue to work on' doc

---

docs/translating.md

Signed-off-by: Oliver Gramberg <oliver.gramberg@gmx.de>

Removed line with broken link (no replacement to be found)

---

docs/config.md

To help reduce questions about where to find available settings.
Context: https://matrix.to/#/!fLeHeojWgBGJlLNdLC:matrix.org/$Gi5CDJV18ToOFkt6TJ1QfPaSIles3ywAkOTV6XfKQ34?via=matrix.org&via=element.io&via=vector.modular.im
---

Point at Settings.tsx for locating available settings

---

.github/workflows/triage-unlabelled.yml

Fixes CI error notifications when removing labels from issues which are archived on the Issue Triage board.
Doesn't fix the adding of labels, but that's more complicated and a work in progress as of writing.
---

Update unlabel workflow to check for card archive-ness

---

sonar-project.properties

Ignore decoder-ring for Sonar coverage

---

.github/workflows/sonarqube.yml

Reverts vector-im/element-web#22239

Revert "Sonarcloud check out upstream develop not fork develop"

---

.github/workflows/static_analysis.yaml

Consolidate i18n check into a reusable workflow

---

src/vector/jitsi/index.ts

Depends on https://github.com/matrix-org/matrix-react-sdk/pull/8659
Closes https://github.com/vector-im/element-web/issues/22283
---
* Stop Jitsi if we time out while connecting to a video room ([\#22301](https://github.com/vector-im/element-web/pull/22301)). Fixes #22283.

Stop Jitsi if we time out while connecting to a video room

---

scripts/copy-res.js

Evidence of it working:
Closes https://github.com/vector-im/element-web/issues/22327
---
* Make Lao translation available ([\#22358](https://github.com/vector-im/element-web/pull/22358)). Fixes #22327.

Make Lao translation available

---

test/unit-tests/vector/getconfig-test.ts
test/unit-tests/vector/platform/WebPlatform-test.ts

unit test getVectorConfig

---

package.json
yarn.lock

matrix-mock-request to 2.0

---

.gitignore

Add /coverage to .gitignore

---

.github/workflows/triage-labelled.yml

We are not focusing on IA issues as part of this quarter, thus removing the board automation
---

Remove Z-IA issues to delight board automation

---

.github/workflows/triage-assigned.yml

Put web app team issues in the board

---

.github/workflows/issue_closed.yml

For duplicate issues, ensure the close type is right (not planned), update it if not
For all closed (completed) issues, cascade the closure onto any referenced rageshakes
For all closed (not planned) issues, comment on rageshakes to move them into the canonical issue if one exists
Example of it running
https://github.com/t3chguy/element-web/issues/6
https://github.com/matrix-org/element-web-rageshakes/issues/13416
https://github.com/t3chguy/element-web/runs/6751230301?check_suite_focus=true
---

Clean up closed issues (duplicates and rageshakes)

---

.github/workflows/sonarqube.yml

Switch to composite actions for pr_details and sonarqube

---

.github/workflows/build_develop.yml

Skip running jobs on fork `develop` where they lack secrets

---

.github/workflows/triage-assigned.yml

Workflow: Move WAT issues to In Progress rather than Ready when assigned

---

docs/labs.md

For https://github.com/matrix-org/matrix-react-sdk/pull/8866
---

Add docs `feature_exploring_public_spaces`

---

src/vector/jitsi/index.ts

Notes: none
(relevant notes are in the react-sdk side)
---

Add support for switching layouts in the Jitsi wrapper

---

tsconfig.module_system.json

Add node to the tsconfig settings for the module system

---

src/favicon.ts
src/vector/init.tsx
src/vector/platform/IPCManager.ts
src/vector/platform/VectorBasePlatform.ts
src/vector/platform/WebPlatform.ts
src/vector/rageshakesetup.ts
src/vector/routing.ts
test/unit-tests/vector/getconfig-test.ts
test/unit-tests/vector/platform/PWAPlatform-test.ts
test/unit-tests/vector/platform/WebPlatform-test.ts

Write additional tests

---

.github/workflows/build_develop.yml

Upload artifact from develop build job

---

package.json
scripts/analyse_unused_exports.js
scripts/prune_code.js
yarn.lock

Towards https://github.com/vector-im/element-web/issues/21969
---

Add a script to check for dead code

---

docs/labs.md

For [matrix-react-sdk/pull/8842](https://github.com/matrix-org/matrix-react-sdk/pull/8842)
---

Add docs for feature_favourite_messages

---

.github/workflows/triage-labelled.yml

The design team would like to see all of their issues on their board for triage now
---
This PR currently has none of the required changelog labels.

Update issue automation for the design team

---

.github/workflows/triage-labelled.yml

Moves `S-Major` and `S-Critical` threads issues to the delight board
---

Move major and critical threads to delight board

---

src/components/views/auth/VectorAuthFooter.tsx
src/components/views/auth/VectorAuthHeaderLogo.tsx

---
* Improve auth aria attributes and semantics ([\#22948](https://github.com/vector-im/element-web/pull/22948)).

Improve auth aria attributes and semantics

---

webpack.config.js

Required for customisations that are using the React SDK.
Notes: none
---

Add webpack react-sdk resolve alias

---

src/vector/platform/ElectronPlatform.tsx

Fixes https://github.com/vector-im/element-web/issues/22953
Fixes https://github.com/vector-im/element-web/issues/22970
---

Disable url tooltips whilst they are very broken

---

.github/workflows/build_develop.yml

Add concurrency to develop builds

---

docs/labs.md

Fixes https://github.com/vector-im/element-web/pull/22447#discussion_r939036888
---

Remove forgotten line out of labs docs

---

package.json
yarn.lock

To be merged in lockstep with https://github.com/matrix-org/matrix-react-sdk/pull/8885
---

Upgrade matrix-widget-sdk

---

.github/workflows/static_analysis.yaml

Tweak tsc-strict config

---

.github/workflows/triage-labelled.yml

Add issue automation for search feature

---

src/vector/jitsi/index.ts

This is a refactoring - see https://github.com/matrix-org/matrix-react-sdk/pull/9224 for the full details.
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/9224
---

Simplify the Jitsi wrapper

---

CONTRIBUTING.md
code_style.md

* https://github.com/vector-im/element-web/pull/23153
* https://github.com/matrix-org/matrix-js-sdk/pull/2621
* https://github.com/matrix-org/matrix-react-sdk/pull/9220
* https://github.com/matrix-org/eslint-plugin-matrix-org/pull/30
---

Add 2022 code style

---

.github/workflows/triage-labelled.yml

The threads board has been closed and is now replaced by the Delight board
---

Remove threads board automation

---

scripts/docker-package.sh

Partially reverts https://github.com/t3chguy/element-web/commit/d86e897ba6b65597c76f271877e34ff9572643e8
Fixes https://github.com/vector-im/element-web/issues/23173
---

Fix if condition for deciding how to structure docker version file

---

.github/workflows/triage-labelled.yml

 Fix indentation in automation

---

release.sh
release_config.yaml

Requires https://github.com/matrix-org/matrix-js-sdk/pull/2616
---

Simplify releases: consolidate scripts

---

.github/workflows/build_develop.yml

Don't bother keeping old develop.tar.gz's around

---

README.md

Adds the same example as for nginx for apache to copy & paste
Signed-off-by: Sebastian Wagner <swagner@intevation.de>
---

Readme: Add header configuration for apache

---

docs/config.md

Add docs for
- #4575
Signed-off-by: Dirk Klimpel dirk@klimpel.org
---

Explain to load different configs depending on the domain in `config.md`

---

yarn.lock

It looks like it wasn't saved correctly after the last release.
---

Fix the lockfile

---

yarn.lock

Follow-up to https://github.com/vector-im/element-web/pull/23343. I would like this to please end…
---

Fix the lockfile, take 4

---

docs/config.md
docs/labs.md

Documentation for https://github.com/matrix-org/matrix-react-sdk/pull/9311
---

New group call experience: Documentation

---

src/components/views/auth/VectorAuthHeaderLogo.tsx
src/components/views/auth/VectorAuthPage.tsx
test/unit-tests/components/views/auth/VectorAuthFooter-test.tsx
test/unit-tests/components/views/auth/VectorAuthHeaderLogo-test.tsx
test/unit-tests/components/views/auth/VectorAuthPage-test.tsx
test/unit-tests/components/views/auth/__snapshots__/VectorAuthFooter-test.tsx.snap
test/unit-tests/components/views/auth/__snapshots__/VectorAuthHeaderLogo-test.tsx.snap
test/unit-tests/components/views/auth/__snapshots__/VectorAuthPage-test.tsx.snap
test/unit-tests/vector/platform/WebPlatform-test.ts

Improve coverage

---

scripts/fetch-develop.deps.sh
scripts/genflags.sh
scripts/get-version-from-git.sh
scripts/layered.sh
scripts/make-icons.sh
scripts/normalize-version.sh

Fixes https://github.com/vector-im/element-web/issues/23430
---

Make bash scripts exit on error rather than continue

---

res/css/structures/ErrorView.pcss

Fixes https://github.com/vector-im/element-web/issues/23376
---
* Make ErrorView & CompatibilityView scrollable ([\#23468](https://github.com/vector-im/element-web/pull/23468)). Fixes #23376.

Make ErrorView & CompatibilityView scrollable

---

src/vector/platform/WebPlatform.ts

Fixes https://github.com/vector-im/element-web/issues/23471
---

Trim /version file response

---

Dockerfile

Required to fix https://github.com/vector-im/element-web/actions/runs/3240370027/jobs/5311324820
---

Fix dockerhub builds

---

.github/ISSUE_TEMPLATE/enhancement.yml

Add a link to discussions for cross-platform or new feature requests
---

Update enhancement issue template

---

.github/workflows/triage-labelled.yml

Add automation for a PS feature team

---

webpack.config.js

For https://github.com/matrix-org/matrix-js-sdk/pull/2762
---

Stub out crypto imports in node

---

.github/workflows/triage-labelled.yml

Add issue automation for the VoIP team

---

docs/config.md

See https://github.com/matrix-org/matrix-react-sdk/pulls/weeman1337
---

Document voice_broadcast.chunk_length

---

.github/workflows/triage-move-review-requests.yml

Stop using deprecated ProjectNext API in favour of the new ProjectV2 one
---

Update PR automation

---

package.json
sonar-project.properties
yarn.lock

Supports relative output, which is necessary as the sonar action runs in docker with different base paths
---

Update to @casualbot/jest-sonar-reporter

---

.github/workflows/triage-labelled.yml
.github/workflows/triage-unlabelled.yml

and tidy up some of the inconsistencies between triage-labelled.yml and triage-unlabelled.yml.
---

Add A-Element-Call to labs automation

---

.github/workflows/tests.yaml

Optimise Jest run in CI

---

src/vector/index.ts
src/vector/jitsi/index.ts

Make SonarCloud happier

---

docs/config.md

Document new config options
Related https://github.com/matrix-org/matrix-react-sdk/pull/9559
---

Add way to create a user notice via config.json

---

.github/workflows/static_analysis.yaml

Fix branch matching for the strict tsc CI

---

.github/workflows/build_develop.yml

Attempt to unwedge develop

---

package.json
webpack.config.js

Remove prop-types

---

docs/config.md

With https://github.com/matrix-org/matrix-react-sdk/pull/9657
---
* add docs for UIFeature.BulkUnverifiedSessionsReminder ([\#23875](https://github.com/vector-im/element-web/pull/23875)). Contributed by @kerryarchibald.

add docs for UIFeature.BulkUnverifiedSessionsReminder

---

package.json
yarn.lock

Downgrade to style-loader 2 to regain Webpack 4 compatibility

---

.github/workflows/triage-labelled.yml

"PN-" prefixed IDs are no longer working, update to new IDs
---

Update project board IDs for automation

---

docs/betas.md
docs/labs.md

Update docs links

---

.git-blame-ignore-revs

commit https://github.com/vector-im/element-web/commit/7921a6cbf86b035d2b0c1daecb4c24beaf5a5abc
---

Add prettier formatting to .git-blame-ignore-revs

---

code_style.md

Updates to match Prettier formatting.
Removed some complex formatting rules, that are handled by Prettier.
---

Align code_style.md with prettier

---

test/app-tests/loading-test.tsx

**Requires https://github.com/matrix-org/matrix-js-sdk/pull/3003**
**Requires https://github.com/matrix-org/matrix-react-sdk/pull/9818**
---

Use Identity Server v2 API for tests

---

package.json
yarn.lock

This reverts commit 07bd0f180c671caa70ec03bc16805ad9229935ab.
---

Revert "Update dependency worker-loader to v3 (#24033)"

---

webpack.config.js

This reverts commit f5fea0be045dae40348a7572a77c1ac42f258ed9.
---
This PR currently has none of the required changelog labels.

Revert "Explicitly set worker-loader's publicPath to webapp"

---

.github/workflows/build_develop.yml

As things in `/bundles/` have relative refs to `../fonts` etc so need those resources there.
---

Stow more things in element-web-develop.element.io

---

.github/workflows/triage-assigned.yml

Old board has been archived, updating automation to move issues to the new board.
Fixes #24215
---

Update automation for new app team board

---

.github/workflows/triage-labelled.yml

That won't be needed anymore
---

Remove delight automation

---

docs/config.md

Documentation for https://github.com/matrix-org/matrix-react-sdk/pull/9909
---

Document updated default `uisi_autorageshake_app`

---

CONTRIBUTING.md

Also a few little tidy-ups.
---

Document the decoder ring

---

.github/workflows/triage-assigned.yml

-   [ ] <del>Tests written for new code (and old code if feasible)</del>
-   [ ] <del>Linter and other CI checks pass</del>
-   [ ] <del>Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md))</del>
---

Include Janne in WAT assignment automation

---

docs/labs.md

This corresponds to https://github.com/matrix-org/matrix-react-sdk/pull/9403
---
* Description of QR code sign in labs feature ([\#23513](https://github.com/vector-im/element-web/pull/23513)). Contributed by @hughns.

Description of QR code sign in labs feature

---

CONTRIBUTING.md

Add some advice on good PR titles

---

element.io/app/config.json
element.io/develop/config.json

Notes: Remove ad for Element Home
---

Remove Element Home ad links

---

.github/workflows/triage-labelled.yml
.github/workflows/triage-unlabelled.yml

Don't remove Z-Labs from A-Jump-To-Date

---

webpack.config.js

Update webpack hash function for greater OSSL compat

---

yarn.lock

Attempting to understand why https://github.com/vector-im/element-web/pull/24131 is failing by upgrading small pieces at a time.
---

yarn upgrade all jest packages

---

.editorconfig
.github/workflows/pending-reviews.yaml

Pull reviews bot automation for Web App Team room

---

yarn.lock

Depend on a non-broken version of matrix-react-sdk

---

CHANGELOG.md

Remove items incorrectly included in changelog for 1.11.24

---

.github/workflows/build_develop.yml

Type: Defect
---
* Fix cloudflare action pointing at commit hash instead of tag ([\#24777](https://github.com/vector-im/element-web/pull/24777)). Contributed by @justjanne.

Fix cloudflare action pointing at commit hash instead of tag

---

package.json
yarn.lock

Remove unused dev dependency

---

.github/workflows/build_develop.yml

+ Uniq checks by name
+ Better failure summary
https://github.com/lewagon/wait-on-check-action/compare/master...t3chguy:wait-on-check-action:master
---

Use forked wait-on-check-action

---

CHANGELOG.md

Update changelog for v1.11.26 now the security issue is public

---

code_style.md

(... and other minor cleanups)
We recently agreed as a team that we would aim to inclde more comments in our code. This is my attempt at writing up some principles on what that means in practice.
For reference, the discussion document was https://docs.google.com/document/d/1qbjbwGQZxHwd3wsMLV0qyJQ6q8k4eQcbgTAC-AsOtgQ.
---

`code_style.md`: Add notes on comments

---

.github/workflows/dockerhub.yaml

Fix concurrency conflict

---

package.json
src/vector/app.tsx
yarn.lock

Type: Task
Related: https://github.com/matrix-org/matrix-react-sdk/pull/10440
Fixes the current build failures due to the changed API
---

Replace newTranslatableError with UserFriendlyError

---

.github/workflows/tests.yaml
jest.config.ts
package.json
yarn.lock

Configure the Github Actions Reporter with `silent: false`, keeping it from swallowing failure reasons.
Much the same as https://github.com/matrix-org/matrix-js-sdk/pull/3269.
---

Improve output in github actions for jest tests

---

.github/workflows/triage-move-review-requests.yml

Fix github actions deprecations warnings

---

src/async-components/structures/CompatibilityView.tsx

Add missing rel noreferrer noopener attributes

---

babel.config.js
package.json
webpack.config.js
yarn.lock

Strip data-testid in production builds

---

code_style.md

Incorporate results of the Web Weekly discussion
closes https://github.com/vector-im/element-web/issues/25122
PSF-2000
---

Improve CSS class naming style guide

---

.github/workflows/triage-assigned.yml
.github/workflows/triage-labelled.yml

Move from using GraphQL to actions
---

Update issue automation

---

docs/labs.md

For https://github.com/matrix-org/matrix-react-sdk/pull/10601
---

Delabs reaction message previews

---

tsconfig.json
tsconfig.module_system.json

Enable ES2020 to match matrix-react-sdk

---

docs/config.md

Document UIFeature.locationSharing to hide location sharing

---

test/app-tests/loading-test.tsx

For https://github.com/matrix-org/matrix-react-sdk/pull/10720
---

Remove unused property

---

src/async-components/structures/CompatibilityView.tsx
src/components/views/auth/VectorAuthFooter.tsx
src/favicon.ts
src/vector/index.ts
src/vector/platform/VectorBasePlatform.ts
tsconfig.json

The 2nd commit is a minor bug that was identified by stricter tsconfig
---

Improve quality of Typescripting

---

test/app-tests/loading-test.tsx

Fix https://github.com/vector-im/element-web/issues/24769
(hopefully)
---

Wait for login screen to appear in loading-test

---

Dockerfile

Fixes https://github.com/vector-im/element-web/issues/17444
---

Increase yarn timeout

---

.github/workflows/pending-reviews.yaml

Track release blockers in Matrix room header

---

docs/config.md

Document help_url and help_encryption_url

---

docs/labs.md

Remove `feature_favourite_messages` as it is has been abandoned for now

---

src/vector/platform/WebPlatform.ts

---
* Fix error when generating error for polling for updates ([\#25609](https://github.com/vector-im/element-web/pull/25609)).

Fix error when generating error for polling for updates

---

docs/labs.md

For https://github.com/matrix-org/matrix-react-sdk/pull/11104
---

Deprecate new breadcrumbs

---

.github/cfp_headers

Align develop.e.io cloudflare pages headers with other deploys

---

scripts/layered.sh

Requires https://github.com/matrix-org/matrix-react-sdk/pull/11186
---

Tweak branch matching to allow not applying outside of PRs for matrix-analytics-events

---

tsconfig.json

Requires https://github.com/matrix-org/matrix-react-sdk/pull/11194
---

Enable strictNullChecks and noImplicitAny

---

tsconfig.json

Requires https://github.com/matrix-org/matrix-react-sdk/pull/11200
---

Enable strictPropertyInitialization

---

package.json
tsconfig.json
yarn.lock

Requires https://github.com/matrix-org/matrix-react-sdk/pull/11201
---

Enable strictFunctionTypes

---

.github/workflows/update-topics.yaml

Utility automation for updating topics as part of release process

---

src/vector/rageshakesetup.ts

Update logging ignore list comment

---

config.sample.json

Closes https://github.com/vector-im/element-web/issues/25635
---

Remove rageshake server from config.sample.json

---

docs/jitsi.md

As of https://github.com/matrix-org/matrix-react-sdk/pull/8062 / https://github.com/vector-im/element-web/pull/21429 this should have been snake case rather than camelCase
---
* Correct Jitsi preferred_domain property ([\#25813](https://github.com/vector-im/element-web/pull/25813)). Contributed by @benbz.

Correct Jitsi preferred_domain property

---

element.io/app/config.json
element.io/develop/config.json

Avoid using deprecated config.json key casing

---

docs/labs.md

For https://github.com/matrix-org/matrix-react-sdk/pull/11345
---

Document 'feature_new_room_decoration_ui'

---

docs/labs.md

For https://github.com/vector-im/element-web/issues/25910
Review alongside https://github.com/matrix-org/matrix-react-sdk/pull/11359
---

Remove feature_right_panel_default_open

---

src/vector/app.tsx
test/app-tests/loading-test.tsx

Remove redundant `makeRegistrationUrl` prop

---

webpack.config.js

For https://github.com/vector-im/element-web/issues/25883
---

Allow external assets loading

---

docs/labs.md

Remove `Exploring public spaces` from labs.md

---

package.json
yarn.lock

This reverts commit 83b940605e7802748f3b9b074c588c1065b9cd2c. because it breaks the build.
---

Revert "Update react-types (#25256)"

---

src/languageHandler.tsx

Fix broken tsc from localazy changes

---

.github/workflows/triage-labelled.yml

Automatically add labeled issues to tech debt project

---

.github/workflows/triage-labelled.yml

Remove trailing ||

---

.github/workflows/build.yml
package.json

Fixes https://github.com/vector-im/element-web/issues/26078
---

Run build workflow in CI on the windows & macos also

---

.github/workflows/docs.yml
.gitignore
book.toml
docs/SUMMARY.md

Closes https://github.com/vector-im/element-web/issues/26236
Requires https://github.com/vector-im/element-desktop/pull/1273
Requires https://github.com/matrix-org/matrix-react-sdk/pull/11750
---

Set up mdbook in github pages

---

.github/workflows/triage-labelled.yml

Add automation to move Element-R issues to crypto board

---

.github/workflows/build_debian.yaml

For https://github.com/vector-im/element-web/issues/2777
---

Iterate build_debian.yaml workflow

---

.github/workflows/docs.yml
.gitignore
book.toml
docs/app-load.md

And switch app-load.md from graphviz to mermaid
---

Add mdbook-mermaid

---

.github/workflows/dockerhub.yaml

Only update repo description once

---

.github/workflows/localazy_download.yaml
docs/translating.md

Run Localazy Download on a schedule 3 times a week instead of during release process

---

.github/release-drafter.yml
.github/release.yml
.github/workflows/release-drafter.yml
.github/workflows/release-gitflow.yml
.github/workflows/release.yml

Requires https://github.com/matrix-org/matrix-js-sdk/pull/3852
Fixes https://github.com/vector-im/wat-internal/issues/23
Example run https://github.com/t3chguy/element-web/actions/runs/6790491908
Example release https://github.com/t3chguy/element-web/releases/tag/v2.0.0
---

New release automations

---

docs/SUMMARY.md
docs/release.md

For https://github.com/vector-im/wat-internal/issues/76
---

Add documentation around releases

---

.github/workflows/sync-labels.yml

Enable label sync workflow

---

.github/workflows/build_debian.yaml
.github/workflows/build_develop.yml
.github/workflows/docs.yml
.github/workflows/pending-reviews.yaml
.github/workflows/release_prepare.yml
.github/workflows/sync-labels.yml
.github/workflows/triage-assigned.yml
.github/workflows/triage-labelled.yml
.github/workflows/triage-move-review-requests.yml
scripts/issues-burndown.pl
scripts/issues-no-state.pl
scripts/layered.sh

Update org in GH workflows and scripts
---

Update org in scripts and workflows

---

.github/CODEOWNERS

Update to org to element-hq in CODEOWNERS
---

Update to org to element-hq in CODEOWNERS

---

.github/CODEOWNERS
.github/workflows/pending-reviews.yaml

Update teams names in CODEOWNERS and workflows
---

Update teams names in CODEOWNERS and workflows

---

.github/workflows/build.yml
.github/workflows/downstream-artifacts.yml
.github/workflows/end-to-end-tests.yaml
.github/workflows/static_analysis.yaml
.github/workflows/tests.yaml

Requires https://github.com/matrix-org/matrix-react-sdk/pull/12087
---

Run Playwright tests on merge queue

---

src/vector/index.html

Fixes https://github.com/element-hq/element-web/issues/26839
---
* Fix CSS stacking context order determinism ([\#26840](https://github.com/element-hq/element-web/pull/26840)). Fixes #26839.

Fix CSS stacking context order determinism

---

CONTRIBUTING.md

Update reference from cypress to playwright

---

.github/workflows/build_debian.yaml
.github/workflows/build_develop.yml
.github/workflows/tests.yaml

Requires https://github.com/matrix-org/matrix-js-sdk/pull/4011
---

Use Github Artifacts v4

---

package.json
yarn.lock

-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md))
---

Bump @matrix-org/react-sdk-module-api from 2.2.1 to 2.3.0

---

.github/workflows/release.yml
.github/workflows/release_prepare.yml

Add waits for post-release steps for improved visibility

---

docs/theming.md

To match the changes in https://github.com/matrix-org/matrix-react-sdk/pull/12209
Requires https://github.com/matrix-org/matrix-react-sdk/pull/12209
---

Update custom avatar theme documentation

---

src/vector/platform/ElectronPlatform.tsx

Requires https://github.com/matrix-org/matrix-react-sdk/pull/12257
---

Improve client metadata used for OIDC dynamic registration

---

src/vector/platform/ElectronPlatform.tsx

Requires https://github.com/matrix-org/matrix-react-sdk/pull/12253
---

Fix Native OIDC for Element Desktop

---

.github/workflows/triage-incoming.yml

Auto-add new issues to the new triage project

Auto-add new issues to the new triage project

---

.github/workflows/release.yml

Requires https://github.com/element-hq/element-desktop/pull/1541

Trigger Element Desktop release drafter upon release of Element Web

---

code_style.md

Add code style rule for multiple return types

---

.github/workflows/dockerhub.yaml

---
* Sign Docker images using cosign ([\#26817](https://github.com/element-hq/element-web/pull/26817)).

Sign Docker images using cosign

---

.eslintrc.js
src/vector/index.ts
src/vector/init.tsx
src/vector/jitsi/index.ts
src/vector/mobile_guide/index.ts
src/vector/platform/ElectronPlatform.tsx
src/vector/platform/WebPlatform.ts
src/vector/rageshakesetup.ts

For https://github.com/element-hq/element-web/issues/27064

Conform to no-floating-promises

---

.github/labels.yml

See https://github.com/element-hq/element-web/pull/27387

Add `Z-Flaky-Test-Disabled` label to labels.yml

---

src/vector/index.ts
src/vector/init.tsx

Ensure we do not load matrix-react-sdk is a manner which can white-screen

---

src/@types/global.d.ts
src/vector/platform/ElectronPlatform.tsx

For https://github.com/element-hq/element-desktop/pull/1757

Add Electron IPC APIs for authenticated media

---

.modernizr.json
sonar-project.properties
src/vector/modernizr.js

It will get minified by webpack anyway, we may as well have vaguely sensible diffs if we change it.

Unminify modernizr

---

src/serviceworker/index.ts

Inspecting the production-ized `sw.js` output, it appears as though Webpack is doing two things:
1. Functions like `getAccessToken` and `askClientForUserIdParams` are inlined (they're only used once anyways)
2. When it inlines, it assumes `self` is `e`, which is the `FetchEvent` rather than `ServiceWorkerGlobalScope` we need it to be.
We can seemingly avoid the `e` optimization by using `global`, though I'm not confident that this is the only issue which causes https://github.com/element-hq/element-web/issues/27759 - while testing a local 'production' build of Element Web, I was *sometimes* getting good behaviour from the service worker. It's possible that Webpack is uncertain about `self` and sometimes does the right thing, which may be causing the perceived behaviour. 
All told, I'd …

Switch from `self` to `global` for service worker

---

scripts/package.sh

Fixes https://github.com/element-hq/element-web/issues/27903

Fix permissions in release tarballs

---

scripts/fetch-develop.deps.sh
scripts/layered.sh

Switch to element's react-sdk fork

---

element.io/develop/config.json

enable Element Call on develop.element.io

---

element.io/develop/config.json

Depends on https://github.com/element-hq/matrix-react-sdk/pull/42

Add "Registration.mobileRegistrationHelper" config setting on develop.

---

.github/workflows/pending-reviews.yaml

Disable pending reviews jobs for now

---

docs/release.md

Fix dependency dashboard issue number

---

src/vector/index.html

For https://github.com/element-hq/matrix-react-sdk/pull/123

Update prefetch composer icons to Compound

---

package.json
yarn.lock

For https://github.com/element-hq/matrix-react-sdk/pull/151

Update to Compound v7

---

src/SlashCommands.tsx
test/test-utils/test-utils.ts

Second batch: remove deprecated calls on `MatrixClient`

---

src/components/views/elements/AppTile.tsx

Fixes https://github.com/element-hq/element-web/issues/28240

Close right panel chat when minimising maximised voip widget

---

playwright/e2e/audio-player/audio-player.spec.ts

Fixes https://github.com/element-hq/element-web/issues/27451

Stabilise audio-player reply button clicking in playwright

---

.editorconfig
.prettierignore
jest.config.ts
playwright/.gitignore
sonar-project.properties

Small tweaks & improvements

---

element.io/app/config.json

(cherry picked from commit 79c9563)

Enable Element Call by default on release instances

---

src/components/views/context_menus/MessageContextMenu.tsx

Fixes https://github.com/element-hq/element-web/issues/23780

Show developer jump to event button on all events with associations

---

package.json
src/components/views/rooms/RoomHeader.tsx
src/hooks/room/useRoomCall.tsx
src/utils/room/placeCall.ts
yarn.lock

Requires https://github.com/matrix-org/matrix-analytics-events/pull/116
For https://github.com/element-hq/element-web/pull/28313#issuecomment-2442235999

Wire up analytics for Legacy/EC/Jitsi voip options

---

src/vector/platform/WebPlatform.ts

Move navigator message listener registration to be synchronously attached

---

res/css/_components.pcss
res/css/views/rooms/_EventPreview.pcss
res/css/views/rooms/_PinnedMessageBanner.pcss
src/components/views/rooms/EventPreview.tsx
src/components/views/rooms/EventTile.tsx
src/components/views/rooms/PinnedMessageBanner.tsx
src/components/views/rooms/ThreadSummary.tsx
src/i18n/strings/en_EN.json
test/test-utils/threads.ts
test/unit-tests/components/views/rooms/PinnedMessageBanner-test.tsx
test/unit-tests/components/views/rooms/__snapshots__/PinnedMessageBanner-test.tsx.snap

Fixes https://github.com/element-hq/element-web/issues/27890
Review commit-by-commit

Show message type prefix in thread root & reply previews

---

package.json
src/stores/widgets/StopGapWidgetDriver.ts
yarn.lock

Depends on:
- https://github.com/matrix-org/matrix-js-sdk/pull/4492
- https://github.com/matrix-org/matrix-widget-api/pull/100
-   [x] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.

Let widget driver send error details

---

src/components/structures/TimelinePanel.tsx

Subset of https://github.com/element-hq/element-web/pull/28256

Refactor TimelinePanel to avoid race conditions in React 18 between state updates

---

src/@types/global.d.ts
src/utils/login.ts
src/vector/init.tsx
src/vector/routing.ts
test/unit-tests/utils/login-test.ts
test/unit-tests/vector/__snapshots__/init-test.ts.snap
test/unit-tests/vector/init-test.ts
test/unit-tests/vector/routing-test.ts

Subset of https://github.com/element-hq/element-web/pull/28256

Update type and usage of window.matrixChat to be better React 18 friendly

---

res/css/views/emojipicker/_EmojiPicker.pcss
res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss

For https://github.com/element-hq/element-web/issues/28426

Update search placeholder to Compound Design Token for placeholder text

---

res/css/views/messages/_MessageActionBar.pcss

Fixes https://github.com/element-hq/element-web/issues/28469

Fix download button size in message action bar

---

package.json
res/css/views/emojipicker/_EmojiPicker.pcss
res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
res/themes/dark/css/_dark.pcss
res/themes/legacy-dark/css/_legacy-dark.pcss
res/themes/legacy-light/css/_legacy-light.pcss
res/themes/light/css/_light.pcss
yarn.lock

Switch out color/text/placeholder for color/text/secondary
Fixes https://github.com/element-hq/element-web/issues/28426

Upgrade to compound-design-tokens v2

---

src/components/views/elements/MiniAvatarUploader.tsx
src/components/views/settings/AvatarSetting.tsx
src/i18n/strings/en_EN.json
test/unit-tests/components/views/elements/MiniAvatarUploader-test.tsx
test/unit-tests/components/views/settings/AvatarSetting-test.tsx

Fixes https://github.com/element-hq/element-web/issues/11478

Check that the file the user chose has a MIME type of `image/*`

---

src/components/views/messages/MPollBody.tsx

Fixes https://github.com/element-hq/element-web/issues/27223

Filter out redacted poll votes to avoid crashing the Poll widget

---

src/@types/matrix-js-sdk.d.ts
src/ContentMessages.ts
src/components/views/messages/MImageBody.tsx
src/utils/image-media.ts

Implements https://github.com/matrix-org/matrix-spec-proposals/pull/4230

Send and respect MSC4230 is_animated flag

---

package.json
webpack.config.js
yarn.lock

of matrix-widget-api and other libs
Fixes https://github.com/element-hq/element-web/issues/21975

Add source-map-loader for easier debugging

---

src/vector/index.ts

Fixes https://github.com/element-hq/element-web/issues/4890

Add Modernizr warning when running in non-secure context

---

src/components/views/auth/LoginWithQR.tsx
src/components/views/settings/devices/LoginWithQRSection.tsx
src/components/views/settings/tabs/user/SessionManagerTab.tsx
test/unit-tests/components/views/settings/devices/LoginWithQRSection-test.tsx

Happened in Synapse already https://github.com/element-hq/synapse/issues/17619

Remove redundant MSC implementation for io.element.rendezvous

---

src/components/views/dialogs/BaseDialog.tsx
test/unit-tests/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
test/unit-tests/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap

Add `Close` tooltip to dialog.

Add `Close` tooltip to dialog

---

src/utils/pillify.tsx
src/utils/react.tsx
src/utils/tooltipify.tsx

Fixes https://github.com/element-hq/element-web/issues/28732

Fix pill rendering in dev mode

---

playwright/e2e/app-loading/guest-registration.spec.ts
playwright/e2e/crypto/complete-security.spec.ts
playwright/e2e/crypto/decryption-failure-messages.spec.ts
playwright/e2e/crypto/dehydration.spec.ts
playwright/e2e/crypto/device-verification.spec.ts
playwright/e2e/crypto/event-shields.spec.ts
playwright/e2e/crypto/logout.spec.ts
playwright/e2e/crypto/utils.ts
playwright/e2e/forgot-password/forgot-password.spec.ts
playwright/e2e/login/login.spec.ts
playwright/e2e/login/overwrite_login.spec.ts
playwright/e2e/login/soft_logout.spec.ts
playwright/e2e/login/utils.ts
playwright/e2e/oidc/index.ts
playwright/e2e/register/email.spec.ts
playwright/e2e/register/register.spec.ts
playwright/element-web-test.ts
playwright/pages/bot.ts
playwright/pages/crypto.ts
playwright/plugins/homeserver/index.ts
playwright/plugins/homeserver/synapse/index.ts

Subset of https://github.com/element-hq/element-web/pull/28860

Prepare for switch to testcontainers in playwright

---

.github/workflows/static_analysis.yaml
knip.ts
package.json
src/Lifecycle.ts
src/utils/arrays.ts

knip replaces it has better configuration
https://github.com/nadeesha/ts-prune#-ts-prune-is-going-into-maintanence-mode

Remove ts-prune as it has been archived over a year ago

---

playwright/e2e/crypto/invisible-crypto.spec.ts
playwright/e2e/integration-manager/kick.spec.ts
playwright/e2e/read-receipts/reactions-in-threads.spec.ts
playwright/e2e/timeline/timeline.spec.ts
playwright/services.ts
playwright/testcontainers/synapse.ts

Fixes https://github.com/element-hq/element-web/issues/27441
Fixes https://github.com/element-hq/element-web/issues/28850
Fixes https://github.com/element-hq/element-web/issues/28870
Fixes https://github.com/element-hq/element-web/issues/28986
Fixes https://github.com/element-hq/element-web/issues/28792

Fix flaky playwright tests

---

debian/control
package.json

Update package description to match the upcoming change to the desktop package description for https://github.com/element-hq/element-desktop/issues/2108

Update package description

---

src/MatrixClientPeg.ts
src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
src/stores/SetupEncryptionStore.ts
src/utils/device/dehydration.ts

Minor cleanups to `initialiseDehydration`

---

.github/CODEOWNERS

Also, add `/playwright/e2e/crypto`.

Fix CODEOWNERS for `src/components/views/settings/encryption`

---

playwright/e2e/crypto/dehydration.spec.ts
src/utils/device/dehydration.ts

Per https://github.com/element-hq/element-web/issues/29387, this is redundant

Device dehydration: remove .well-known check

---

src/components/viewmodels/roomlist/RoomListViewModel.tsx
src/components/viewmodels/roomlist/useSorter.ts
test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx

- Viewmodel provides a sort function that the view can use to resort the list
- Viewmodel provides a state (`activeSortOption`) that tracks the currently active sorting method so that the view can render one of the sort options as selected.

RoomListViewModel: Provide a way to resort the room list and track the active sort method

---

.eslintignore

This was causing my lint tasks to take quite a bit longer locally.

Do not eslint playwright files.

---

playwright/e2e/crypto/toasts.spec.ts
playwright/e2e/crypto/utils.ts
src/components/views/dialogs/UserSettingsDialog.tsx
src/components/views/settings/encryption/ResetIdentityPanel.tsx
src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx
src/toasts/SetupEncryptionToast.ts

This hopefully addresses @richvdh 's comments on #29138 which came in after it had been merged.

Doc improvements from #29138

---

src/LegacyCallHandler.tsx
src/components/views/messages/TextualBody.tsx
src/settings/controllers/NotificationControllers.ts
src/utils/pillify.tsx
src/utils/pushRules/monitorSyncedPushRules.ts
src/utils/pushRules/updatePushRuleActions.ts
test/unit-tests/LegacyCallHandler-test.ts
test/unit-tests/components/structures/LoggedInView-test.tsx
test/unit-tests/components/views/messages/TextualBody-test.tsx
test/unit-tests/components/views/settings/Notifications-test.tsx
test/unit-tests/utils/pillify-test.tsx

Requires https://github.com/matrix-org/matrix-js-sdk/pull/4763

Reuse PushProcessor from MatrixClient

---

src/components/views/messages/MFileBody.tsx

Fixes https://github.com/element-hq/element-web/issues/29587

Fix MFileBody fileName not considering `filename`

---

res/css/views/rooms/RoomListPanel/_RoomListItemView.pcss

Replace mouse cursor by a pointer when the user hovers the list.
https://github.com/user-attachments/assets/269eeaab-89ac-435c-a956-368f9e5ee498

New room list: add cursor pointer on room list item

---

src/NodeAnimator.tsx

Split out from https://github.com/element-hq/element-web/pull/28914

Update types for React 19 update

---

src/components/views/dialogs/UserSettingsDialog.tsx
src/components/views/settings/encryption/ResetIdentityPanel.tsx
src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx
src/i18n/strings/en_EN.json
src/toasts/SetupEncryptionToast.ts
test/unit-tests/components/views/settings/encryption/ResetIdentityPanel-test.tsx
test/unit-tests/components/views/settings/encryption/__snapshots__/ResetIdentityPanel-test.tsx.snap
test/unit-tests/components/views/settings/tabs/user/EncryptionUserSettingsTab-test.tsx
test/unit-tests/toasts/SetupEncryptionToast-test.tsx

Catch errors after syncing recovery

---

src/Modal.tsx

Fixes https://github.com/element-hq/element-web/issues/29692

Ensure forceCloseAllModals also closes priority/static modals

---

test/unit-tests/components/views/settings/SetIdServer-test.tsx

Fix flakes in `SetIdServer` testsuite (https://github.com/element-hq/element-web/actions/runs/14398213231/job/40377893946)
Ran it multiple times without failures.

test: fix flaky SetIdServer test

---

src/vector/platform/ElectronPlatform.tsx

Tests in https://github.com/element-hq/element-desktop/pull/2248

Fix getOidcCallbackUrl for Element Desktop

---

src/theme.ts
test/unit-tests/theme-test.ts

Fixes https://github.com/element-hq/element-web/issues/29663

Fix custom theme support for short hex & rgba hex strings

---

src/components/views/rooms/MemberList/MemberListHeaderView.tsx

Closes https://github.com/element-hq/element-web/issues/29734
We don't want submit buttons.

Fix unwanted form submit behaviour in memberlist

---

src/components/viewmodels/right_panel/RoomSummaryCardTopicViewModel.tsx
src/components/views/right_panel/RoomSummaryCard.tsx
test/unit-tests/components/viewmodels/right_panel/RoomSummaryCardTopicViewModel-test.tsx

Task https://github.com/element-hq/element-web/issues/29633
Linked to MVVM RoomSummaryCard PR https://github.com/element-hq/element-web/pull/29674

MVVM RoomSummaryCard Topic

---

test/unit-tests/toasts/SetupEncryptionToast-test.tsx

Part of https://github.com/element-hq/element-web/issues/29231
Tidy up the tests for SetupEncryptionToast before we add some more in later changes.

Tidy SetupEncryptionToast tests

---

src/BasePlatform.ts
src/i18n/strings/en_EN.json
src/vector/platform/WebPlatform.ts
test/unit-tests/vector/platform/WebPlatform-test.ts

Fixes https://github.com/element-hq/element-web/issues/29865

Add error toast when service worker registration fails

---

src/stores/room-list-v3/RoomListStoreV3.ts
test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts

Otherwise we might end up adding new space rooms to the room list.

RoomListStoreV3: Only add new rooms that pass `VisibilityProvider` check

---

src/models/Call.ts
test/unit-tests/models/Call-test.ts

Closes https://github.com/element-hq/element-web/issues/29426

Clean up some unused code related to calls

---

playwright/e2e/crypto/backups-mas.spec.ts
playwright/e2e/oidc/oidc-native.spec.ts

@t3chguy fixed an issue where playwright fails with the following error: 
This commit is not on develop so cherry picking it here.

Cherry pick fix for oidc failures in playwright

---

src/stores/room-list-v3/skip-list/sorters/RecencySorter.ts
test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts

For https://github.com/element-hq/element-web/issues/30050

RoomListStore: Sort low priority rooms to the bottom of the list

---

config.sample.json
docs/config.md
docs/kubernetes.md
element.io/app/config.json
element.io/develop/config.json

It does not seem like any service is reachable here.

docs: Remove scalar for riot.im

---

package.json
yarn.lock

So the shared components screenshot generator works

Update playwright-common package

---

src/components/views/polls/pollHistory/PollHistoryList.tsx

Related to https://github.com/element-hq/element-web/issues/30164

fix: replace hardcoded string in poll history dialog

---

res/css/views/verification/_VerificationShowSas.pcss

Fixes https://github.com/element-hq/element-web/issues/30353

Fix line wrap around emoji verification

---

test/unit-tests/components/views/dialogs/ModalWidgetDialog-test.tsx
test/unit-tests/components/views/dialogs/security/InitialCryptoSetupDialog-test.tsx
test/unit-tests/components/views/dialogs/security/ResetIdentityDialog-test.tsx
test/unit-tests/components/views/dialogs/security/SetupEncryptionDialog-test.tsx

I think these tests got misfiled. All the other jest tests are under `test/unit-tests`.

Move test files into `test/unit-tests`

---

playwright/e2e/share-dialog/share-by-url.spec.ts

Closes https://github.com/element-hq/element-web/issues/30224

Fix e2e test: share-by-url flakiness

---

res/css/_font-sizes.pcss

... to let people know that these things shouldn't be used any more.

Add some comments in `_font-sizes.pcss`

---

README.md

Fix minor type setting issue in `README.md` (missing space)

---

test/unit-tests/TextForEvent-test.ts

For https://github.com/matrix-org/matrix-js-sdk/pull/4984

Update m.topic tests

---

test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap
test/unit-tests/components/views/spaces/__snapshots__/QuickSettingsButton-test.tsx.snap
yarn.lock

I give up waiting for renovate to create the PR

Upgrade compound-web for AXE fix

---

.storybook/preview.tsx

Storybook: load story when language is set

---

docs/MVVM-v1.md
docs/MVVM.md

Update mvvm doc with our last mvvm architecture

Update mvvm doc

---

.storybook/main.ts

Use https://storybook.js.org/docs/sharing/storybook-composition#compose-published-storybooks to include compound web storybook

Add compound web storybook to EW storybook

---

playwright/e2e/widgets/jitsi.spec.ts
src/components/views/elements/AppTile.tsx

<del>Unfortunately I don't think playwright or jest can write a test for something successfully opening a new tab.</del> Now with test!
Fixes https://github.com/element-hq/element-desktop/issues/2527

Fix jitsi widget popout
