skins/base/css/molecules/MessageTile.css
skins/base/views/molecules/MessageTile.js

I'm not sure if we want to use `:hover`?

Show timestamp when you hover over a message

---

docs/conferencing.md
skins/base/css/organisms/RoomView.css
skins/base/css/templates/Login.css
skins/base/views/organisms/RoomList.js
skins/base/views/organisms/RoomView.js
skins/base/views/pages/MatrixChat.js
skins/base/views/templates/Login.js
src/CallHandler.js
src/ConferenceHandler.js
src/controllers/molecules/RoomHeader.js
src/controllers/molecules/voip/CallView.js
src/controllers/organisms/RoomList.js
src/controllers/organisms/RoomView.js
src/controllers/pages/MatrixChat.js

This PR adds conferencing support to vector for HSes running https://github.com/matrix-org/matrix-appservice-verto (which matrix.org is)
Conferencing from the end-user's perspective:
- Group chats may now have an "Ongoing conference call" notification on them.
- Placing a voice or video call to the group chat room will no longer produce an error but will connect the client to a conference for that room.
- Even if there is no "ongoing" notification, you can start a conference by just doing a voice/video call to the group chat room. This will invite a special conference user (part of the Verto AS) to mediate the conference call and provide ACLs on the conference call (so when you leave the group chat room, you get booted from the conference call). Semantics are the same as 1:1 calling …

Add conferencing support

---

src/skins/vector/skindex.js
src/skins/vector/views/organisms/CasLogin.js
src/skins/vector/views/templates/Login.js
src/vector/index.js

Initial and basic CAS login.
Flow is:
- User clicks login with CAS
- Vector requests CAS server URL from HS
- Vector redirects user to CAS server
- CAS redirects back to Vector with ticketId
- Vector sends ticket ID to HS
- HS verifies ticket ID with CAS
- Login Success
Doesn't do anything with logout yet.
Also, the CAS login page will only be shown if CAS is the first login flow returned from the HS
Tested locally and works.
No doubt plenty of room for improvement on this works but it's a starting point and I'm happy to be given pointers for improvements before it get's merged!
Related to:
https://github.com/matrix-org/synapse/pull/295
https://github.com/matrix-org/matrix-js-sdk/pull/20
https://github.com/matrix-org/matrix-react-sdk/pull/19
Signed-off-by: Steven Hammerton …

Add support for CAS auth

---

src/skins/vector/views/molecules/voip/IncomingCallBox.js

This was caused by an \<img> being the first thing in the \<div> rather than
the \<audio>. This caused a conflict because the "not in call" render was just
\<div>\<audio />\</div> and "in call" render was \<div>\<img /> \<audio />\</div>
React can't tell in this case that the \<audio> tags are the "same" so was
clobbering it (which meant that on inbound calls we would call play() on an
audio tag which would then immediately be clobbered by another audio tag).
Fixes #228

Fix inbound audio

---

src/components/login/PostRegistration.js
src/components/login/Registration.js
src/skins/vector/views/pages/MatrixChat.js

This adds in a new component `PostRegistration` which contains the UI for post-registration steps.
This uses `ChangeDisplayName` and `ChangeAvatar` as they are, hence some logic leaking through into this component (getting the current avatar).
Related: https://github.com/matrix-org/matrix-react-sdk/pull/35

Re-add in post registration steps

---

src/skins/vector/css/atoms/ImageView.css
src/skins/vector/css/atoms/MemberAvatar.css
src/skins/vector/css/common.css
src/skins/vector/css/molecules/EventTile.css
src/skins/vector/css/molecules/MemberInfo.css
src/skins/vector/css/molecules/MemberTile.css
src/skins/vector/css/molecules/MessageComposer.css
src/skins/vector/css/molecules/RoomDropTarget.css
src/skins/vector/css/molecules/RoomHeader.css
src/skins/vector/css/molecules/RoomSettings.css
src/skins/vector/css/molecules/RoomTile.css
src/skins/vector/css/molecules/SearchBar.css
src/skins/vector/css/molecules/ServerConfig.css
src/skins/vector/css/organisms/CreateRoom.css
src/skins/vector/css/organisms/MemberList.css
src/skins/vector/css/organisms/RightPanel.css
src/skins/vector/css/organisms/RoomDirectory.css
src/skins/vector/css/organisms/RoomSubList.css
src/skins/vector/css/organisms/RoomView.css
src/skins/vector/css/templates/Login.css

...juggling font-size appropriately (as Open Sans is physically larger for the same point size as Myriad Pro, irritatingly), and fix some really weird baseline CSS bugs in read receipts that were introduced. Hopefully this doesn't re-introduce the intermittent baseline offset bug for the initials on Chrome & FF

switch to Open Sans

---

src/components/views/rooms/MessageContextMenu.js
src/skins/vector/css/molecules/EventTile.css

Fixes https://github.com/vector-im/vector-web/issues/367 . Specifically:
- Add "Cancel Sending" to all `NOT_SENT` and `QUEUED` messages.
- Make all `SENDING` `NOT_SENT` and `QUEUED` messages appear at the end of the timeline.
- Make the distinction between `NOT_SENT` and `SENDING` clearer by making `NOT_SENT` text red as it was before. It was removed because:
> M-matthew> kegan: i did it deliberately to match the ribot design [...] ribot are concerned that bright red is too vicious, and i'm inclined to agree
I've reverted this because it is incredibly confusing otherwise:
> you sit there like a lemon waiting for something to send which never will
> M-matthew> if you feel that strongly about it feel free to back it out
We need **some indication**. Whether this is red text, an exclamation …

Make unsent messages behave better

---

src/VectorConferenceHandler.js

Because invites do not have RoomMembers because we don't have an m.room.member
event for them, just a user ID, and we want to detect conf users at invite
time.
Fixes https://github.com/vector-im/vector-web/issues/510
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/54

Pass a userId rather than a RoomMember to isConferenceUser

---

src/components/structures/RoomSubList.js
src/skins/vector/css/organisms/RoomList.css
src/skins/vector/css/organisms/RoomSubList.css

Part of the fix for https://github.com/vector-im/vector-web/issues/348
`alwaysShowHeader` has been added to force the title to be shown even if there are 0 elements. Required so people can actually click the archived header.
`showSpinner` has been added to make a spinner spin if there are 0 elements. Required so people know a request is ongoing whilst getting archived rooms.
`onHeaderClick` has been added so we can call the JS SDK when the archived room header is clicked.
`startAsHidden` has been added to allow the initial collapsed/expanded state to be modified. Required because the archived section should be *collapsed* by default as we don't yet have the rooms until you try to expand it.
Also added a `TODO` questioning the naming of `props.collapsed` - it's terribly confusing because I …

Add more props to RoomSubList

---

src/components/structures/RoomDirectory.js
src/vector/index.js

Fixes https://github.com/vector-im/vector-web/issues/81
This does three things:
- Flip the `enableGuest` flag to enable guest functions in React SDK.
- Show icons on rooms which guests can join / guests can read.
- Conditionally join or peek a room when clicked on the room directory page depending on whether the guest can join or not.
Perversely this will actually run fine without the sister React SDK PR (as everything is gated behind `enableGuest`) so isn't dependent on https://github.com/matrix-org/matrix-react-sdk/pull/82

Enable guest access

---

src/components/views/settings/Notifications.js

The bug was the bad declaration of .m.rule.call.

Fixed call push notifications settings that always stayed OFF

---

config.json
src/components/structures/RoomSubList.js
vector/index.html

Requires https://github.com/matrix-org/matrix-react-sdk/pull/68

Use unread count for room highlight state

---

src/components/views/settings/Notifications.js

otherwise the room_message rule takes precedence over content / display name rules etc and prevents bings.

Add vector rules with the appropriate kind

---

src/vector/index.js

Always parse the hash of a URL as we do elsewhere by looking for a query string part, otherwise we end up passing the query into showscreen which then spreads havok.
Fixes https://github.com/vector-im/vector-web/issues/848

Always parse the hash of a URL as we do elsewhere

---

src/vector/index.js

(in this case, for keypair invite signing urls)

Pass through params for other URLs

---

README.md

* Change to use auto-list numbering everywhere.
* Move 'deployment' section up above development and removed duplicate information from 'Getting Started'
* Clarify that `npm start` doesn't terminate
* Reference the bugs that make our build process suck

Make the README more idiot-proof

---

src/components/structures/RoomDirectory.js

(more hacks to work around the fact that we can't get this data from the HS)
Fixes https://github.com/vector-im/vector-web/issues/1016

Display room metadata from room previews when we come from the public room directory

---

README.md

Casual users of /develop shouldn't need to do the whole
clone-three-repositories thing.

Update README to include `npm install` in react-sdk

---

src/components/views/settings/Notifications.js

The Matrix CS API, and synapse now supports setting the actions for default
rules. Doing that makes managing the rules much simpler from a vector
persepctive since the ON/LOUD/OFF toggle buttons can be implemented by
setting the actions and enabling/disabling the default rules rather than
overidding them.
Overriding the default rules was difficult because it was not possible
to intermingle the evaluation of user-specified rules with the default
rules. So even though you could add a rule with the same conditions as a
default rule, it would evaluate before *all* the other default rules.
Also creating new rules under a im.vector namespace creates challenges
if we want vector to cooperate with other matrix clients that want to
provide a similar set of toggle switches for the push rules.

Update the actions of default rules instead of overriding.

---

webpack.config.js

Hopefully, this fixes #1046 without any side-effects.
It relies on the fact that the languages files are pretty simple - in
particular, they don't require any other modules. So we can tell webpack just
to suck them in as they are, rather than parsing them and causing an explosm.

Tell webpack not to parse the highlight.js languages

---

src/components/views/settings/Notifications.js
src/skins/vector/css/vector-web/views/settings/Notifications.css

This is mostly groundwork for email notifications check box, but this makes it trivial to list the pushers on a user's account so adding this too because it could be a useful feature.
Requires https://github.com/matrix-org/synapse/pull/716 to work but will just display an error message on older servers.
Requires https://github.com/matrix-org/matrix-js-sdk/pull/125 (already merged).

Get and display a user's pushers in settings

---

src/components/views/settings/Notifications.js
src/notifications/VectorPushRulesDefinitions.js

* An absent rule is the same as a rule with 'enabled == false', and is not
necessarily 'OFF' (particularly in the case of the bot rule, which is
inverted).
* If we don't understand the rule, then don't tick any of the radio buttons,
and instead show it in the 'external' section.
Fixes https://github.com/vector-im/vector-web/issues/1348

Improve handling of notification rules we can't parse

---

package.json
src/vector/index.js
webpack.config.js

This makes it possible to gather a few performance stats

Include react-addons-perf for non-production builds

---

package.json
src/components/structures/RoomDirectory.js

Gemini's habit of reflowing everything everytime anything changes at all makes
for an unresponsive app. Turn it off everywhere we use gemini.

Don't relayout scrollpanels every time something changes

---

src/components/views/settings/Notifications.js

This line would NPE otherwise:
https://github.com/vector-im/vector-web/blob/8fb521c83c431542281f699708ddd864afb99f3e/src/components/views/settings/Notifications.js#L709

Fix NPE when loading the Settings page which infini-spinnered

---

package.json
src/vector/index.js
vector/config.json

issue #1344
If you don't like the use of es7 features and/or fetch, let me know. I just wanted to throw something together quickly so I could package vector-web for the Arch Linux AUR.

serve config.json statically instead of bundling it

---

src/components/structures/RoomDirectory.js

This doesn't really attempt to unravel the different code paths that joining a room can take (apart from commenting it a little). It just fixes this bug for now.

Fix RoomDirectory to join by alias whenever possible.

---

src/components/structures/RoomDirectory.js

With the react-sdk update, this does nothing functionally since the room ID would just
have been ignored, but update this to correctly supply only one of ID/alias.

Update for react-sdk dbkr/fix_peeking branch

---

karma.conf.js

If olm is not installed, the webpack build for the karma tests gives an ugly
error. None of the tests currently care if olm is installed or not, so fix this
for now by just ignoring the olm module.

Karma: fix warning by ignoring olm

---

src/skins/vector/css/matrix-react-sdk/views/rooms/EventTile.css

When encryption is enabled, we (currently) highlight messages from validated
senders in green, and encrypted messages from unvalidated senders in red.
This is a fix from matthew to "make it look less like fanfold printer paper".

CSS fix for rooms with crypto enabled

---

package.json

https://github.com/vector-im/vector-web/pull/1675 still didn't work, so let's have another go.

package.json: add olm as optionalDependency

---

src/components/structures/RoomDirectory.js

Hidden behind shift-click: ultimately this should be expanded upon to be able to delete any of the aliases rather than just the default, but this is a start that will let us do some moderation without doing it manually with cURL.
Also tidies up RoomDirectory a bit by passing the room objects around so we don't have to look them up by in the data structure later.

Add ability to delete an alias from room directory

---

src/components/structures/RoomDirectory.js

Fixes regression introduced by https://github.com/vector-im/vector-web/pull/1680

Fix joining rooms by typing the alias

---

src/skins/vector/css/matrix-react-sdk/views/messages/MTextBody.css

I found 30 to be a nice maximum size since you have a nice size window, but it won't take up the whole chat.

#1664 Set a maximum height for codeblocks

---

webpack.config.js

Fixes an error when matrix-js-sdk is symlinked into node_modules, which meant
that we would (try to) use the version of olm from js-sdk instead of
vector-web (https://github.com/vector-im/vector-web/issues/1765).

webpack: always use the olm from vector-web

---

src/skins/vector/css/common.css
src/skins/vector/css/matrix-react-sdk/views/rooms/EventTile.css
src/skins/vector/css/matrix-react-sdk/views/rooms/LinkPreviewWidget.css
src/skins/vector/img/icon-link.svg

Fixed #1751, PR to `matrix-react-sdk` to follow
===
Signed-off-by: Stefan Pearson <stefan@ribot.co.uk>

Presentation for inline link

---

package.json
src/components/structures/RoomDirectory.js

The latest gemini-scrollbar makes relayoutOnUpdate redundant, so update to it
and remove the properties.

Remove relayoutOnUpdate prop on gemini-scrollbar

---

src/components/views/globals/MatrixToolbar.js
src/skins/vector/css/vector-web/views/globals/MatrixToolbar.css

For some reason, Chrome doesn't seem to make the central div in the
notifications warning wide enough, so it ends up wrapping. Fix this by making
the central div expand across the available space, instead of letting the
container for the close button do it.
Fixes https://github.com/vector-im/vector-web/issues/1687

Fix notifications warning layout

---

src/components/structures/RoomSubList.js

`selectedRoom` is *not* required, and we often don't have one, so get warnings.

Fix a warning from RoomSubList

---

test/app-tests/loading.js

1. fix the 'Clean load' tests which had been broken by
https://github.com/matrix-org/matrix-react-sdk/pull/399: make sure we clear
localStorage between tests.
2. Test the session rehydration properly by setting the localStorage rather
than setting up the MatrixClientPeg before loading the app.
3. Add some tests for the auto-guest-registration flows.

More app-loading tests

---

src/vector/index.js

loginToken handling is now done by the session loader, so we need to pass in
the queryparams to MatrixChat.
Also, MatrixChat no longer automatically reloads the page to drop the
querystring, so we have to do that ourselves (doing it in index.js allows
tokenlogin to be tested).
Corresponds to https://github.com/matrix-org/matrix-react-sdk/pull/406.

Support for refactored login token handling

---

src/vector/index.js
test/app-tests/loading.js

1. Check that localstorage is correctly updated on successful login (test for https://github.com/matrix-org/matrix-react-sdk/pull/404)
2. Check that the saved HS isused for guest registration (test for https://github.com/matrix-org/matrix-react-sdk/pull/405)
3. Test loginToken handling (test for https://github.com/matrix-org/matrix-react-sdk/pull/406 / https://github.com/vector-im/vector-web/pull/1946)
Includes the changes in https://github.com/vector-im/vector-web/pull/1946.

More tests for the loading process:

---

test/app-tests/loading.js
test/test-utils.js

This was causing flaky tests, as sometimes the joining test would inherit an
"mx_is_guest" setting from a previous test run.

Make sure that we clear localstorage before *all* tests

---

src/vector/index.js

Fixes https://github.com/vector-im/vector-web/issues/1933

Don't redirect to mobile app if verifying 3pid

---

src/skins/vector/css/matrix-react-sdk/views/rooms/MessageComposer.css

This breaks the opacity animation (so remove the transition) but the extra border was making the border on the composer too thick.

Don't show border on composer when not in RTE mode

---

src/skins/vector/css/matrix-react-sdk/views/rooms/EventTile.css

This adds back avatars for the event messages restyled in #1748. A companion branch matrix-org/matrix-react-sdk:wmwragg/chat-message-presentation also needs to be merged.
Signed-off-by: William Wragg wm.wragg@gmail.com

Added event/info message avatars back in

---

package.json

The react checks are useful on /develop, to catch programming errors earlier,
and the original reason for turning them off (so that we could meaningfully
compare performance between /develop and /beta) is no longer so
relevant.
This reverts commit b5f029d10e8a3b7a0d03cc65504de00ac0c4d1f4.

Turn react consistency checks back on in develop builds

---

src/components/views/dialogs/ChangelogDialog.js
src/skins/vector/css/vector-web/views/dialogs/ChangelogDialog.css

This makes it easier to distinguish multiline commit messages from separate commits

Improve readability of the changelog dialog

---

jenkins.sh

Use the latest version of olm, as provided by jenkins, rather than the most
recent release.

jenkins.sh: install olm from jenkins artifacts

---

src/component-index.js
src/components/structures/RoomDirectory.js
src/components/views/directory/NetworkDropdown.js
src/skins/vector/css/vector-web/structures/RoomDirectory.css
src/skins/vector/css/vector-web/views/directory/NetworkDropdown.css
vector/config.sample.json

Adds the network selector to filter down the room directory by what network the room is on. Currently works by having a hardcoded list of regexes that it tests all the room aliases against, awaiting a better interface on the server.

Directory network selector

---

src/components/structures/RoomDirectory.js
src/skins/vector/css/vector-web/structures/RoomDirectory.css
test/app-tests/joining.js

This now seems to be working apart from the fact that synapse hits the end of pagination at rooms with 15 members. This means if you select Gitter rooms, you don't get any because the gitter rooms have 9 and 4 people in them currently. If you search for them first, it works as expected.
Also, guests aren't allowed to use the POST API.
Bullet 3 of https://github.com/vector-im/vector-web/issues/2178
Requires https://github.com/matrix-org/matrix-react-sdk/pull/483
Requires https://github.com/matrix-org/matrix-js-sdk/pull/211
Requires https://github.com/matrix-org/synapse/pull/1121
Requires https://github.com/matrix-org/synapse/pull/1126

Paginate Room Directory

---

src/components/views/dialogs/ChangelogDialog.js

Link to the HTML commit page instead of API JSON, and open in new window instead of replacing the Vector tab.
Fixes #2056

Fix changelog links

---

src/components/views/globals/GuestWarningBar.js
src/components/views/login/VectorCustomServerDialog.js

Rather than a mix of 'sign in/out' and 'log in/out'
Fixes https://github.com/vector-im/vector-web/issues/2378

Use 'Sign In' / 'Sign Out' universally

---

README.md
src/components/structures/RoomDirectory.js
src/components/views/directory/NetworkDropdown.js
vector/config.sample.json

Use the 3rd party location lookup API to accept third-party locations
in their native form and look up the corresponding portal room for
that location.
Also give the network dropdown some placeholder text.
Fixes https://github.com/vector-im/vector-web/issues/2374
Requires https://github.com/matrix-org/matrix-react-sdk/pull/502
Requires https://github.com/matrix-org/matrix-js-sdk/pull/217

Add native joining of 3p networks to room dir

---

src/components/structures/RoomDirectory.js

Always show the scrollpanel otherwise we stop paginating if there
are no matching rooms in the first request (as per comment).
Fixes no freenode rooms being shown.

Don't stop paginating if no rooms match

---

src/skins/vector/css/vector-web/structures/RoomDirectory.css

Seemed to only be broken on firefox

Correct text alignment on room directory search

---

.npmignore
package.json

We ended up including all sorts of stuff in our published packages. Let's take
the opposite approach and include useful stuff rather than exclude unuseful
stuff.

Don't include the world in the published packages

---

webpack.config.js

If olm isn't installed, webpack prints out scary warnings (though it still
actually succeeds). Let's avoid scaring people by quietly removing it from the
list of things to process.

Avoid errors if olm is missing

---

.gitignore
README.md
package.json
scripts/package.sh

To match conventions from other projects and match the release
script which expects releasde artefacts in dist/

Rename the package script/output dir to 'dist'

---

package.json
src/vector/index.js
src/vector/platform/WebPlatform.js
src/vector/platform/index.js

Provide WebPlatform for functionality specific to the web version of vector.
Currently the only platform is Web. This will change with Electron.
Requires https://github.com/matrix-org/matrix-react-sdk/pull/531

Implement Platforms

---

src/vector/platform/WebPlatform.js

Except display notification which was already accidentally included in a
previous PR

Add Notification support to the Web Platform

---

src/components/views/globals/NewVersionBar.js
src/skins/vector/css/common.css
src/vector/index.js
src/vector/platform/VectorBasePlatform.js
src/vector/platform/WebPlatform.js
src/vector/updater.js

* Allow platforms to specify release notes
* Make web update checking much, much simpler (ie. not manually using XMLHTTPRequest)

Move 'new version' support into Platform

---

package.json
webpack.config.js

Advantages:
* blocks while a rebuild is in progress so you're less likely to reload the old version
* serves from memory rather than disk, so we no longer need to turn off the cachebuster to avoid filling the disk with bundles. Empirically, seems to last a plausible amount of time without OOMing; there's no real reason to believe it would use any more memory than webpack itself.
* That in turn means we no longer need the hack to stop chrome caching old sourcemaps (because the sourcemap now has a cachebuster in its name).
* one fewer process for parallelshell to (fail to) manage.
* in future, we could consider the fancy hot-reload functionality.

Use webpack-dev-server instead of http-server

---

electron/src/electron-main.js
electron/src/vectormenu.js
package.json

* Implement the squirrel install / uninstall hooks (so we have
a start menu entry / desktop shortcut)
* Wait longer before checking for update
* Set the window icon
* Add a 'file' menu
* Bump electron-builder
* Add the icon url for the control panel entry

Slight grab-bag of fixes for electron on Windows

---

electron/src/electron-main.js

Otherwise we pop up stack traces in dialog boxes if it fails to
to poll for updates or something.

Catch unhandled errors in the electron process

---

src/skins/vector/css/matrix-react-sdk/views/rooms/RoomSettings.css

The popup appears next to the `Manage Integrations` button if there was a problem contacting Scalar

Add some CSS for  scalar error popup

---

electron/src/electron-main.js

Otherwise everyone that builds electron vector will end up with
their apps auto-updatin to our version when we release an update.
Coming next: A way to manage our electron release process to make
sure we never ship a build with auto-update disabled.

Make auto-update configureable

---

src/components/views/dialogs/ChangelogDialog.js
src/components/views/globals/NewVersionBar.js

Remove the 'vector' from the start of the version (otherwise the
tarballs are called vector-vector-[...].tar.gz). The jenkins
script already creates these files, so update accordingly.

Fix changelog dialog to  read new version format

---

src/vector/index.js

Sometimes window.onload would run before loadApp had finished (specifically, if
the browser had to wait for config.json to load). Avoid the race by moving all
of the onload logic into loadApp.

Fix a race which took us to the directory on load sometimes

---

src/vector/index.js
src/vector/platform/ElectronPlatform.js
src/vector/platform/VectorBasePlatform.js
src/vector/platform/WebPlatform.js

So we can have a sensible device name on Electron

Move getDefaultDeviceName into the Platforms

---

electron/config.json
package.json

Which has the update URL in it

Add electron config

---

package.json

Which uses a new enough build of chromium that it accepts our SSL
certs.

Update to electron 1.4.8

---

electron/src/electron-main.js

Avoids it sitting there for a short period with no spinner while
it parses the js.

Only show window when ready

---

electron/src/electron-main.js
src/vector/platform/ElectronPlatform.js
src/vector/platform/WebPlatform.js

* Dismiss the notification when it's clicked
* Accept the room object: we need it to view_room
* Desktop app: Un-minimise when notification clicked
* Desktop App: Set App User Model ID so notifications work on
Windows 8!
Requires https://github.com/matrix-org/matrix-react-sdk/pull/582

Fix clicking on notifications

---

src/vector/platform/ElectronPlatform.js

Currently, Linux builds get identified as "function toUpperCase() { [native code] }inux", which I don't think is the correct capitalization of "linux"

Add missing brackets to call to toUpperCase

---

electron/src/electron-main.js

MATE desktop env (and presumably other GNOMEs don't support ICOs,
so use a PNG.
Fixes https://github.com/vector-im/riot-web/issues/2705

Use a PNG for the icon on non-Windows

---

test/app-tests/loading.js

The 'loading' tests only worked when run with the other tests and
failed if you just ran the file by itself, because the skin was
loading in the 'joining' tests, but not here.

Make the 'loading' tests work in isolation

---

test/app-tests/loading.js

Promises are now not being resolved within the same tick, so give
another tick for the UI to update after all the HTTP calls have
flushed through. This is fairly terrible, but I can't immediately
see a better way of doing this.

Fix broken tests

---

README.md
src/components/structures/RoomDirectory.js
src/components/views/directory/NetworkDropdown.js

As per https://github.com/matrix-org/synapse/pull/1676
The existing local config system still exists and is used for
remote home server directories (since /thirdparty/protocols
doesn't support listing remote home servers, and also because
people are using it).

Support room dir 3rd party network filtering

---

src/vector/olm-loader.js
webpack.config.js

16M is somewhat excessive: configure olm to use a bit less.
Requires changes to the olm library to do anything useful, but will be harmless
without them.
Partial fix to vector-im/riot-web#2726.

Configure olm memory size

---

README.md
config.sample.json
src/components/structures/RoomDirectory.js
src/components/views/directory/NetworkDropdown.js
src/utils/DirectoryUtils.js
test/app-tests/joining.js

This removes the ability for the client to filter remote room
directories by network, since the /thirdparty/protocols API does
not yet work for remote servers. They would only get the main list
now though anyway, so there is no point in us continuing to support
it.

Remove the client side filtering from the room dir

---

README.md

GitHub Flavoured MarkDown parsed this as
`sudo npm install nativefier -g nativefier https://riot.im/app/` which
is incorrect.

README.md: fix GFMD for nativefier

---

scripts/redeploy.py

Hopefully this will fix the problem whereby we can overwrite the live
deployment.

Redeploy script: put each build in a separate directory

---

README.md
package.json

Not sure if this is the right place to put it, but I think it'd be useful to spell out the installation steps for Debian to make it easier to install. Even though Debian users are typically aware of these installation steps, it makes it easier if there are easy copy/paste commands to get the app installed.

add Debian Stretch install steps to readme

---

README.md
electron/src/squirrelhooks.js
src/vector/index.js

rather than file:///, which crashes browsers in horrible ways c.f. https://twitter.com/agumonkey/status/812060535567040512.  This was already worked around on sydent.

make electron send email validation URLs with a nextlink of riot.im

---

webpack.config.js

In order to better support a world where old build artifacts are available
(which is necessary to support bundle.js splitting), collect all the webpack
artifacts for the build into a single directory. Then we'll be able to clear
out old builds after a few weeks, knowing they won't be in use any more.

Put parent build hash in webpack output filenames

---

src/skins/vector/css/matrix-react-sdk/views/elements/DirectorySearchBox.css
src/skins/vector/css/matrix-react-sdk/views/rooms/RoomTile.css
src/skins/vector/css/vector-web/fonts.css
src/skins/vector/css/vector-web/views/elements/ImageView.css

https://github.com/vector-im/riot-web/pull/2961 put the CSS in a subdirectory,
which meant that links from CSS to images and fonts were broken. Fix them up.

Fix links to fonts and images from CSS

---

electron/src/electron-main.js

Hopefully fix https://github.com/vector-im/riot-web/issues/2847

Include current version in update check explicitly

---

scripts/redeploy.py

... so that people using old versions of the master chunk can still load other
webpack chunks.

Update redeploy script to keep old bundles

---

scripts/deploy.py
scripts/redeploy.py

Creates a new deploy script, hopefully suitable for deploying riot.im/app.
Currently the deploy process is:
```
(cd packages && wget https://github.com/vector-im/riot-web/releases/download/v$VERSION/vector-v$VERSION.tar.gz)
(cd deploys && tar xvf ../packages/vector-$VERSION.tar.gz)
ln -s `readlink -f config.json` deploys/vector-$VERSION/
ln -snf deploys/vector-v$VERSION staging # (or beta)
```
(where the middle of that is `deploy.sh`).
This will become:
```
./deploy.py https://github.com/vector-im/riot-web/releases/download/v$VERSION/vector-v$VERSION.tar.gz
ln -snf deploys/vector-v$VERSION staging # (or beta)
```

Deploy script

---

electron/src/electron-main.js

From https://github.com/vector-im/riot-web/issues/2962
This allows all the shortcuts to still work, and the menu bar can
be un-hidden with the alt key.

Auto-hide the electron menu bar

---

src/vector/platform/ElectronPlatform.js

Merge the notification part of https://github.com/vector-im/riot-web/pull/2960
* Show and focus the window when the notification is clicked,
rather than just restoring it.
* Implement requestNotificationPermission and return a resolved
promise (although in practice it should never be called)

Fixes to electron desktop notifs

---

electron/src/electron-main.js
electron/src/tray.js

From https://github.com/vector-im/riot-web/pull/2960
Makes riot minimise to the tray on windows / linux.

Add electron tray icon

---

electron/src/electron-main.js

So launching a new instance will focus the old one, meaning that
if you have Riot minimised to the tray and launch it via the
desktop shortcut / start menu, you don't end up with more & more
copies of the app.
This doesn't really prevent you from running multiple copies of
the app to fake multi account support since they share a data
directory anyway.

Make riot desktop single instance

---

src/skins/vector/css/themes/_base.scss
src/skins/vector/css/themes/_dark.scss

This has to be relative, because we don't know if riot is going to be mounted at the top-level of the domain or not (it's not, on riot.im).
Links are relative to the final location of the CSS, which is under `bundles/<hash>`, so need `../..`.

Fix link to image for event options menu

---

package.json

so GNOME doesn't get confused by the hidden windows
From https://github.com/vector-im/riot-web/pull/2960

Add StartupWMClass

---

test/app-tests/loading.js

This seeks to fix the intermittent failure of the "MatrixClient rehydrated from
stored credentials" tests.
The problem appears to be that the 'load_completed' is sometimes taking a while
to come through from the dispatcher - or rather, it is taking a long time to
get *sent* to the dispatcher: the chain of `q().then().catch().done()` in
componentDidMount can take a while to happen.
As a workaround, give the test a few goes when waiting for us to start
syncing. It's not ideal to be poking into the internal state of MatrixChat like
this, but it'll do for now.

Hopefully, fix intermittent test failure

---

src/skins/vector/css/matrix-react-sdk/structures/_RoomView.scss

This will ensure that errors, unsent messages, etc. will be allowed enough height to display their contents from within the status bar without being chopped.
Fixes #3041

Increase the max-height of the expanded status bar

---

config.sample.json
src/vector/index.js
src/vector/rageshake.js

The aim of this PR is to implement all the logic behind storing console logs and sending them to a remote endpoint. It does not handle any of the UI surrounding this yet, in attempts to keep the size of this PR down.
This PR:
- Store console logs in-memory by monkey-patching `console`.
- Periodically flush logs to IndexedDB if available.
- Purge logs on startup (refresh) if they exceed a certain size (currently 50MB).
- POST logs to a configured endpoint along with some input text.
This PR does not:
- Have any UI for people to send bug reports.

Implement bug reporting logic

---

package.json

Otherwise Chrome thinks you're working on a new file every time
you refresh and therefore closes source tabs and removes
breakpoints which is very annoying. It also allegedly makes
webpack-dev-server run out of memory because it has to remember
all the different files.

Don't use hash-named directory for dev server

---

README.md

to make it clear you need to do all the things in 'building from
source', including the build-react-sdk dance if you're building
develop.

Tweak desktop instructions

---

src/skins/vector/css/matrix-react-sdk/views/elements/_AddressTile.scss

CSS tweak for https://github.com/matrix-org/matrix-react-sdk/pull/653
Makes email addresses the name width as Matrix IDs so names can be displayed to the left of them

CSS tweak for email address lookup

---

src/vector/platform/ElectronPlatform.js
src/vector/platform/WebPlatform.js

this is a brute force fix to lots of emitted sync events causing tonnes of:
"WebPlatform.js:58 Failed to set badge count: Error setting badge. Message: Too many badges requests in queue."
it's an open question as to why we are seeing so many sync events, though, which seem to outnumber the number of /sync responses.

only recalculate favicon if it changes

---

src/skins/vector/css/matrix-react-sdk/views/avatars/_BaseAvatar.scss

Fix for https://github.com/vector-im/riot-web/issues/3051

Set BaseAvatar_image bg colour = #fff

---

src/skins/vector/css/matrix-react-sdk/structures/login/_Login.scss

This is so they do not expand outside of the login area. (280px = 300px - 2px - 18px, 2px for borders, 18px for padding)

Fix the width of input fields within login/reg box

---

src/components/views/login/VectorLoginHeader.js
src/skins/vector/css/matrix-react-sdk/structures/login/_Login.scss

This is to allow team logos to be shown when a user registers with a team email.

Allow a custom login logo to be displayed on login

---

src/skins/vector/css/matrix-react-sdk/structures/login/_Login.scss

This box can be used to provide useful hints during registration/login.

Add CSS for a support box in login

---

.travis.yml
scripts/jenkins.sh

Do `npm install` on js-sdk rather than `npm run build`, which will hopefully
mean that `browserify` gets installed before we try to run it.
The README says we should use `npm install` for the react-sdk too, so let's do
that, and bring the travis and jenkins builds into sync with the README.

Fix jenkins build

---

src/skins/vector/css/matrix-react-sdk/structures/login/_Login.scss

Icons with width > height will now only assume a max-height of 100% as opposed to a height of 100%. This is so they don't overflow the width of 300px.
Before:
After:

Handle icons with width > height

---

src/components/views/directory/NetworkDropdown.js

For https://github.com/vector-im/riot-web/issues/3086

Allow mxc: URLs for icons in the NetworkDropdown

---

src/components/structures/BottomLeftMenu.js
src/components/structures/RightPanel.js
src/components/structures/RoomSubList.js
src/components/structures/SearchBox.js
src/components/views/elements/ImageView.js
src/components/views/globals/MatrixToolbar.js
src/components/views/rooms/SearchBar.js

Changed most button-like divs to actually behave as such (via the new AccessibleButton element). Also made filtering rooms more keyboard friendly.
Signed-off-by: Jani Mustonen <janijohannes@kapsi.fi>

Better user interface for screen readers and keyboard navigation

---

scripts/rageshake.go

Example logs (`-0` is most recent, `-3` is oldest):
```
$ ls -l
-rw-r--r--  1 kegan  staff   909 26 Jan 11:46 bugreport-20170126-114615-0.log.gz
-rw-r--r--  1 kegan  staff   524 26 Jan 11:46 bugreport-20170126-114615-1.log.gz
-rw-r--r--  1 kegan  staff  1761 26 Jan 11:46 bugreport-20170126-114615-2.log.gz
-rw-r--r--  1 kegan  staff   998 26 Jan 11:46 bugreport-20170126-114615-3.log.gz
-rw-r--r--  1 kegan  staff   198 26 Jan 11:46 bugreport-20170126-114615.log.gz
$ zless bugreport-20170126-114615.log.gz 
everything is awful.
Number of logs: 4
Version: UNKNOWN
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
$ zless bugreport-20170126-114615-0.log.gz 
2017-01-26T10:52:37.374Z I Initialised rageshake: See …
```

Bug report server script

---

scripts/rageshake.go

rageshake: Abide by Go standards

---

scripts/rageshake.go

And remove the long filenames now that there is a directory above them.

Store bug reports in separate directories

---

scripts/rageshake.go

Set via environment variables on startup.

rageshake: Add file server with basic auth

---

src/components/structures/BottomLeftMenu.js
src/components/structures/LeftPanel.js

The bottom left menu now uses the same teamToken that the rest of the components use. This will require changes to react-sdk: https://github.com/matrix-org/matrix-react-sdk/pull/684

Use the teamToken threaded through from react sdk

---

src/skins/vector/css/_common.scss

For https://github.com/matrix-org/matrix-react-sdk/pull/691

Style for split-out interactive auth

---

src/skins/vector/css/matrix-react-sdk/structures/_RoomStatusBar.scss
src/skins/vector/css/matrix-react-sdk/structures/_RoomView.scss

Also, make sure the typing avatars line up with the arrow to jump to the bottom of the timeline.
Also, get rid of any height jumps when a call starts. border 1px hidden does not add any height to an element, it is effectively the same as none.
Fixes https://github.com/vector-im/riot-web/issues/3096, https://github.com/vector-im/riot-web/issues/3037

Reposition certain icons in the status bar

---

src/skins/vector/css/matrix-react-sdk/views/avatars/_BaseAvatar.scss

This seemingly doesn't do anything and upsets things when avatars overlap (i.e. for the new typing avatars).
See https://github.com/matrix-org/matrix-react-sdk/pull/699

Remove z-index property on avatar initials

---

test/app-tests/joining.js

This test assumed that `/sync` would be called immediately after rendering
`<MatrixChat />` but this isn't true in an IndexedDB world: it bounces via
`store.startup()` first.
It looks like the tests resolve this by adding `q.delay(1)` so that's what
I've done: in the future it would be better to extend `HttpBackend` to have
a `waitFor(req) Promise` function so we can removing timing from the tests.

Fix broken tests caused by adding IndexedDB support

---

res/vector-icons/manifest.json

They are not at the root of the web server, they are at the same
path as the manifest

Fix icon paths in manifest

---

src/components/views/context_menus/RoomTagContextMenu.js

From the room tag context menu.
Also fix the room tag context menu, which was missing sdk and
modal imports. Switch over the import while we're at it.

Allow forgetting rooms you're banned from

---

src/vector/rageshake.js

Also bump the client-side timeout on the upload from 3 mins to 5 mins, to see
if it helps people on slower connections.

More aggressive rageshake log culling

---

src/skins/vector/css/matrix-react-sdk/views/elements/_MemberEventListSummary.scss

This is so that it stays put when the MELS is toggled.
Added style for a line that appears below "collapse" to indicate start of events.
Not possible to put "collapse" next to the expanded events because of read receipts.
Complements https://github.com/matrix-org/matrix-react-sdk/pull/683

Float the toggle in the top right of MELS

---

src/skins/vector/css/_common.scss

This was causing https://github.com/vector-im/riot-web/issues/3226

Set padding-bottom: 0px for .mx_Dialog spinner

---

src/skins/vector/css/matrix-react-sdk/structures/_RoomView.scss

This is to keep things vertically balanced.
Fixes https://github.com/vector-im/riot-web/issues/3269

Hide statusAreaBox_line entirely when inCall

---

src/components/structures/RoomSubList.js

So that RoomTile does less, and if other things should happen onClick, they happen in the same place as the `view_room` for clarity.

`view_room` dispatch from `onClick` RoomTile

---

src/skins/vector/css/matrix-react-sdk/structures/_MatrixChat.scss
src/skins/vector/css/vector-web/structures/_HomePage.scss

Fix for vector-im/riot-web#3298
This seems to not have any side-effects.

Height:100% for welcome pages on Safari

---

src/components/structures/RoomSubList.js
src/components/views/context_menus/RoomTileContextMenu.js

This does two things:
- Fixes an incorrect import that was causing Direct Chat toggle to not be editable https://github.com/vector-im/riot-web/issues/3355
- Use props.list in RoomSubList when calculating whether to show IncomingCallDialog. Fixes https://github.com/vector-im/riot-web/issues/2956

Fix the people section

---

src/components/views/context_menus/MessageContextMenu.js
src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss

Fixes part of https://github.com/vector-im/riot-web/issues/3390
Also: The "Redact" option in the MessageContextMenu no longer appears for redacted events.
Screenshots:
(before)
(after)

Better CSS for redactions

---

AUTHORS.rst
src/skins/vector/css/themes/_dark.scss

fixes #3433 
`-webkit-filter::invert` (generated) seems to default to `invert(1)`
`whereas filter::invert` is [documented](https://developer.mozilla.org/en/docs/Web/CSS/filter) to default to `invert(0)` (no inversion)

dark theme invert inconsistent across browsers

---

src/components/views/context_menus/RoomTileContextMenu.js
src/components/views/rooms/DNDRoomTile.js
src/components/views/rooms/RoomDropTarget.js
src/skins/vector/css/vector-web/views/rooms/_RoomDropTarget.scss

- Alter CSS due to removed mx_RoomDropTarget_avatar. The avatar was removed because it didn't particularly add anything and we needed space for "Drop here to tag as direct chat", which is quite long.
- Use guessAndSetDMRoom as a convenience method for guessing the DM member and setting the state.
- Do evil hacks to make DNDRoomTile do dragging of RoomTiles to and from the People section. Dragging a DM to and from Rooms/Favourites/Low Priority now works as one would expect. This is still not ideal however because edge cases exist where you have more than one tag set and then you drag a DM from "Favourites" to "Rooms" and the tile ends up in "People". This would require setting multiple tags, and breaks the 1-1 mapping between tags and sections even further. Ultimately the UI needs a …

Fix people section again

---

src/components/views/settings/Notifications.js

Fixes https://github.com/vector-im/riot-web/issues/3518

Don't show phone number as target for email notifs

---

src/vector/index.js

As this makes it work out of the box with react-perf chrome
extension (which doesn't do a whole lot other than save you having
to remember the commands, but is still quite nice).

Rename ReactPerf to Perf

---

src/components/structures/RoomSubList.js

In the worst case, `tsOfNewestEvent` will return `MAX_SAFE_INTEGER`, instead of `undefined`, as may be the case of some events that were redacted and persisted in indexdb before changes were made to how events are redacted locally. (The important change is that events are now not stripped of their `origin_server_ts`).
Fixes https://github.com/vector-im/riot-web/issues/3529.

Do not assume getTs will return comparable integer

---

src/vector/index.html
src/vector/index.js
src/vector/indexedbd-worker.js
webpack.config.js

Provides a worker script for the js-sdk indexeddb webworker mode (https://github.com/matrix-org/matrix-js-sdk/pull/412) and enables it using https://github.com/matrix-org/matrix-react-sdk/pull/792
https://github.com/vector-im/riot-web/issues/3252

Add support for indexeddb sync in webworker

---

test/app-tests/joining.js

Depending on timing, the first `httpBackend.flush()` could end up just flushing
a '/presence' call rather than the initial sync. The fix to that is simply to
not set the expectation on /presence.
While we're there, split out the flushes of /publicRooms and
/thirdparty/protocols, so that we can be sure that they happen.
There is probably still a bunch of flakiness there, but this should fix one
particular instance.

Fix a flaky test

---

src/vector/rageshake.js

*apparently* it's possible for your indexeddb transaction to complete in the
background, so that the `oncomplete` handler is never called. Make sure that
the oncomplete handler is set *before* doing the work.

rageshake: fix race when collecting logs

---

src/components/views/dialogs/BugReportDialog.js
src/vector/index.js
src/vector/rageshake.js
src/vector/submit-rageshake.js

A series of commits which amount to factoring out the upload logic for
rageshaking to a separate file, so that we can load it asynchronously rather
than having to drag it all in at startup.

Factor out rageshake upload to a separate file

---

src/vector/submit-rageshake.js

This is a more sensible encoding for uploading logfiles, and will allow us to compress the logfiles in future.
browser-request doesn't give us enough flexibility to do this properly, so we use XMLHttpRequest directly.
See https://github.com/matrix-org/rageshake/blob/caf57b60cbfda2652fa577397aaebb4df04449f7/README.md#post-apisubmit for the API details.
(builds on top of https://github.com/vector-im/riot-web/pull/3645. The actual changes are in 0561c8c.)

Use multipart-form encoding for rageshake uploads

---

package.json
src/component-index.js
src/components/structures/LeftPanel.js
src/components/structures/RoomSubList.js
src/components/structures/RoomSubListHeader.js
src/components/structures/SearchBox.js
src/skins/vector/css/matrix-react-sdk/views/elements/_AccessibleButton.scss
src/skins/vector/css/themes/_base.scss
src/skins/vector/css/themes/_dark.scss

This is effectively two PRs which ended up getting very entangled:
1. Implements quick-search in SearchBox (listening for Ctrl/Cmd-K), and arrow-key based navigation through the resulting room list in LeftPanel.
2. Splits a RoomSubListHeader out of RoomSubList, and switch to re-sorting/refreshing the list only on demand via pokes from RoomList using ConstantTimeDispatcher, rather than constantly having RoomList constantly replace the whole list property.
The latter is slightly controversial, as it deliberately short-circuits React from working out when to re-render the list, given we have no suitable properties to use (short of constantly generating new lists).  It also technically doesn't need ConstantTimeDispatcher; it could also be done by calling the method directly on a reference to …

Optimise RoomList and implement quick-search functionality on it.

---

src/vector/index.js

Addresses #3624.
This stores the flag in localStorage, after checking if localStorage is available. If localStorage is not available, the user will be prompted just like before this commit.
Signed-off-by: Travis Ralston <travpc@gmail.com>

Remember acceptance for unsupported browsers.

---

src/components/views/elements/ImageView.js

depends on matrix-org/matrix-react-sdk#802
fixes #2778 and #2970
Notes:
Right clicking "Download this file" and clicking what comes up in Electron lets you send it to Browser/Image Viewer and obviously "Open in new tab" works in browsers. Though this will not work for Encrypted Images in [only] Electron, but will in browsers which support data URIs.

fix ImageView Download functionality

---

webpack.config.js

Fixes:
```
ERROR in ./~/olm/olm.js
Module not found: Error: Cannot resolve module 'fs' in C:\Users\t3chg\WebStormProjects\riot-web\node_modules\olm
@ ./~/olm/olm.js 18:39-52
```

Fix Webpack conf

---

src/vector/platform/ElectronPlatform.js

https://developer.gnome.org/notification-spec/ lists HTML tags which cause special behaviour, but KDE/Plasma for instance simply removes anything that looks like a HTML Tag, https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md#linux says that all Electron supported Linux notification systems (via libnotify) follow this markup spec. Examples of how this issue manifests below:
After fix (different message, this data would previously be in italics):
---
Tested on Windows for sanity's sake
Tested on KDE Neon (KDE/Plasma) 16.04
Needs testing on some other DMs/Distros
Sample test data:
+ `<i>Foo</i>`
+ `<hello>`

Escape HTML Tags from Linux Notifications (electron)

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_RoomHeader.scss

This was causing the "save" button in RoomSettings to be obscured when room names were set to long strings without spaces
Fixes https://github.com/vector-im/riot-web/issues/1729

Prevent long room names/topics from pushing UI of the screen

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss

Addresses #1772
Partnered with https://github.com/matrix-org/matrix-react-sdk/pull/820
Signed-off-by: Travis Ralston <travpc@gmail.com>

CSS to make h1 and h2 the same size as h1.

---

electron/src/electron-main.js

This lost me a fair bit of time trying to figure out why Riot was
starting and then immediately quitting.

Warn when exiting due to single-instance

---

package.json

https://travis-ci.org/vector-im/riot-web/builds/227340622
avoidwork/filesize.js#87
3.5.7 and 3.5.8 ver released <24h ago and broke stuff for us
Signed-off-by: Michael Telatynski 7t3chguy@gmail.com

Pin filesize ver to fix break upstream

---

scripts/package.sh
src/vector/platform/ElectronPlatform.js
src/vector/platform/VectorBasePlatform.js
src/vector/platform/WebPlatform.js

Remove leading v in /version file, for SemVer and to match Electron ver

---

electron/package.json

so that electron-builder packages it as Riot rather than riot-web

Re-add productName

---

src/components/structures/BottomLeftMenu.js
src/components/structures/RoomSubList.js
src/components/structures/RoomSubListHeader.js
src/skins/vector/css/_components.scss
src/skins/vector/css/matrix-react-sdk/views/elements/_RoleButton.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_RoomList.scss
src/skins/vector/css/vector-web/structures/_LeftPanel.scss

Implements https://github.com/vector-im/riot-web/issues/3609
Adds RoleButton to reduce duplication as we now have up to 3 copies of the same button.
Requires https://github.com/matrix-org/matrix-react-sdk/pull/859

Make left panel better for new users (mk II)

---

src/component-index.js
src/components/views/globals/PasswordNagBar.js

This will tell the user that they need to set a password to return to their account.
Part of https://github.com/vector-im/riot-web/issues/3602

Implement PasswordNagBar

---

res/vector-icons/manifest.json

for #334
even though app complains about being run in mobile web it is possible to use
and in certain scenarios it might be the best option so this will at least improve that
tested both using Lighthouse and my Android M device

add to manifest

---

src/vector/rageshake.js

... 50MB turned out to be quite a lot.

Reduce rageshake log size to 1MB

---

electron_app/src/electron-main.js

Add 'copy link address' to link context menu in electron app
Fixes https://github.com/vector-im/riot-web/issues/2712

Desktop: 'copy link address'

---

test/app-tests/joining.js
test/mock-request.js

Give the client a bit longer to get started.
I also pulled in some mock-request updates from js-sdk, and did a few more updates (which I'll probably backport), though none of that turned out to be strictly necessary.

Attempt to deflakify joining test

---

src/components/structures/RoomDirectory.js

Give the RoomDirectory and unmounted guard, and use it to avoid some setState
warnings. Also, cancel the filterTimeout (no point in leaving it around).
There are still plenty of other opportunities to setState after unmount, but
the filterTimeout was causing noise in the test.

Fix some setState-after-unmount in roomdirectory

---

.travis.yml
README.md
release.sh
scripts/fetch-develop.deps.sh
scripts/jenkins.sh

So we can run the automated tests against the correct branches

Script to fetch corresponding branches of dependent projects

---

.gitignore
electron_app/src/electron-main.js
electron_app/src/tray.js
src/vector/platform/ElectronPlatform.js
src/vector/platform/VectorBasePlatform.js
src/vector/platform/WebPlatform.js

supersedes #3835
thus for #3554
+ make Electron Tray icon mimic the Favicon (has notifications count badge)
+ make Electron Tray Tooltip mimic document.title (has info like [offline])
+ add electron_app to .gitignore, missed it when renaming
+ tidy up tray.js
+ move Favico.js stuff into VectorBasePlatform as now Electron uses it too, no point doing the generation in the other process as that just means the electron package will have two copies of the library.
Screenshots below shows favicon still working on WebPlatform, and the tray icon behaviour too:

Electron Tray Improvements

---

package.json

add menu category for linux build of app

---

config.sample.json
res/home.html
scripts/copy-res.js
src/components/structures/BottomLeftMenu.js
src/components/structures/HomePage.js
src/components/structures/LeftPanel.js

counterpart to https://github.com/matrix-org/matrix-react-sdk/pull/922

Implement default welcome page and allow custom URL /w config

---

package.json

most dists of riot-web inc Arch have these cats + Chat and IRCClient,
though the latter isn't exactly correct so missing it
builds on comments from #3975

Add `Chat` to Linux app categories

---

electron_app/src/electron-main.js
electron_app/src/webcontents-handler.js

split all webContents.on's into the new file, keeping main cleaner
add handlers for editable fields, with Cut Copy Paste Undo Redo etc
add Copy Image feature to all images, working on not only the download
buttons now
fixes #3156

add moar context menus [Electron]

---

src/components/structures/HomePage.js

, default to welcome page if either the teamToken or teamServerURL is undefined.
For https://github.com/matrix-org/matrix-react-sdk/pull/925

Allow team server config to be missing

---

src/components/views/globals/PasswordNagBar.js
src/skins/vector/css/vector-web/views/globals/_MatrixToolbar.scss

- Change the nag bar to read "To return to your account in future you need to set a password"
- Underline "Set a password"
- Make the whole thing clickable

Rejig the PaswordNagBar

---

src/components/views/messages/MessageTimestamp.js
src/skins/vector/css/matrix-react-sdk/structures/_FilePanel.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss

Linked to: https://github.com/matrix-org/matrix-react-sdk/pull/903

Kieran gould/12hourtimestamp

---

src/skins/vector/css/matrix-react-sdk/views/dialogs/_ConfirmUserActionDialog.scss

#3927 
Changed it to look like this:
This is consistent with the "Create new room" dialog, which also has a dark text input box. I noticed their font sizes are slightly different (14px vs 15px), should this be the case?

Fixed an input field's background color in dark theme

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss

Part of addressing vector-im/riot-web#4046
Partner PR: https://github.com/matrix-org/matrix-react-sdk/pull/969
See: https://github.com/vector-im/riot-web/issues/4046#issuecomment-304909444

Smaller font size on timestamp to better fit in the available space

---

scripts/fetch-develop.deps.sh

... so that when the git clone fails, it doesn't plough on regardless.

scripts/fetch-develop.deps.sh: set -e

---

electron_app/src/electron-main.js
src/vector/platform/ElectronPlatform.js

depends on matrix-org/matrix-react-sdk/pull/985
so that flashFrame is only triggered by **loud** notifications
it started really annoying me

electron flashFrame was way too annoying

---

webpack.config.js

matrix-js-sdk now loads olm from global.Olm instead of requiring it
(https://github.com/matrix-org/matrix-js-sdk/pull/446), so we no longer need to
define it as an external.

No need to make olm an external

---

.travis.yml
README.md

Don't try to build with node 6.0

---

.travis.yml
scripts/fetch-develop.deps.sh

* tell git to checkout the right branch, rather than cloning and then changing.
* clone with depth 1 under travis, to save time.
* less pushd/popd, which print out confusing text - use `cd` in a subshell
instead. (and just avoid it where possible).
* add some markers to the output to let travis roll it up.

Various tweaks to fetch-develop-deps

---

src/skins/vector/css/matrix-react-sdk/structures/_RoomStatusBar.scss
src/skins/vector/css/matrix-react-sdk/structures/_RoomView.scss
src/skins/vector/css/matrix-react-sdk/views/elements/_MemberEventListSummary.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_LinkPreviewWidget.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_MessageComposer.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_TopUnreadMessagesBar.scss
src/skins/vector/css/vector-web/structures/_LeftPanel.scss
src/skins/vector/css/vector-web/structures/_RightPanel.scss

for #109, depends on matrix-org/matrix-react-sdk#986
I started with the styles from https://github.com/vector-im/riot-web/issues/109#issuecomment-284862682, and tweaked it and added a bunch more things, such as:
- tweak spacing for emotes so that the avatars don't collide
- shrunk spacing for URL previews
- shrunk bottom bar (left panel buttons, composer, right panel invite button)
- shrunk notification bar and unread messages bar
- shifted e2e icons and read receipts to be aligned with the new message positions
There may be other things that need tweaking, but I've been using this for most of the day without noticing anything weird.

add styles for compact layout

---

scripts/copy-res.js

the copy-res.js did throw "(node:8688) DeprecationWarning: Calling an asynchronous function without callback is deprecated." before

Fix DeprecationWarning

---

electron_app/package.json
electron_app/src/tray.js

fixes 
Might not be the best way, probably worth @dbkr looking it over.
I hate Windows.

to make the windows volume mixer not explode as it can't resize icons.

---

src/components/structures/HomePage.js
test/app-tests/joining.js
test/app-tests/loading.js

This time the test wasn't being flaky, but it does inspect a lot of the internal of RoomView, which has had some modifications recently. I've updated the test to reflect this and it passes locally.
Also, fix a bug in HomePage with an undeclared "error" which should be "err".
Let's see what Travis thinks of this!.... Oh wait, there isn't a luke/fix-tests branch on react-sdk? ...

Fix tests for new-guest-access

---

src/vector/platform/WebPlatform.js

This is utterly frustrating. ES6 template strings support `undefined` values fine:
```js
> s = {}
{}
> console.log(`hello ${s.world}`)
hello undefined
```
Yet our translation library `counterpart` does not support this (specifically one of its deps, `sprintf` doesn't), and instead unceremoniously crashes the app: https://github.com/alexei/sprintf.js/blob/bfeab902cbf32d570409676da2624dfa8788c43a/src/sprintf.js#L45
Meaning when I added i18n support for this and converted from ES6 template strings to `_t()`, it could crash if any of these values were `undefined`. I'm going to have to check all existing `%(value)s` for null guards or patch `sprintf` to not suck.

Fix #4191: add defaults to avoid throwing

---

test/app-tests/joining.js
test/app-tests/loading.js

By adding more gaffer tape / putting back the old gaffer tape.

Fix Tests in ILAG

---

src/components/views/messages/MessageTimestamp.js
src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss

Tested visually against any unintended changes to the alignment of e2e icons, with timestamps on 12h and 24h mode.
(Will assign once we've got bandwidth following ILAG landing)

Align message timestamp centrally about the avatar mid-point

---

src/skins/vector/css/matrix-react-sdk/views/dialogs/_ChatInviteDialog.scss

for https://github.com/matrix-org/matrix-react-sdk/pull/1050
- Remove address selector header
- Adjust dialog content so that the error message ("No results" or otherwise) doesn't cause a change in height

Update CSS for ChatInviteDialog

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss
src/skins/vector/css/themes/_base.scss
src/skins/vector/css/themes/_dark.scss
src/skins/vector/img/icon_copy_message.svg
src/skins/vector/img/icon_copy_message_dark.svg

Currently using the edit button's image as a placeholder, it needs its own icon.
Paired with https://github.com/matrix-org/matrix-react-sdk/pull/1040
See issue #1974 
Should I have a go at creating one myself, or is there someone responsible for creating the icons?

Added styling for copy to clipboard button

---

docs/translating-dev.md

Path to the  en_EN.json and the import were outdated.

Update import and directory path in the Translations dev guide

---

src/components/structures/RoomSubList.js

Fixes https://github.com/vector-im/riot-web/issues/4281

Don't show the tooltips when filtering rooms

---

src/components/views/dialogs/SetPasswordDialog.js
src/skins/vector/css/_components.scss
src/skins/vector/css/vector-web/views/dialogs/_SetEmailDialog.scss

This is so that the user can reset their password.
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1090

Ask for email address after setting password for the first time

---

test/app-tests/loading.js

* Do we show the last room correctly on resume?
* Do we show the home page if we have no last room?
* If we follow a login link, and re-log-in, do we correctly vape the mx_last_room_id (#4283)
This will fail until the corresponding matrix-react-sdk PR lands.

Test that we handle stored mx_last_room_id correctly

---

test/app-tests/loading.js

If you go straight to a /#/login link, we shoudn't go registering guest
accounts or reanimating the saved creds.
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1092

Check that we don't register a guest account on /#/login

---

test/app-tests/loading.js

This used to exist to reproduce the functionality in the window.onload handler
in vector/index.js -- which got removed in 8b0390f. Having it here is confusing
at best.

Remove onload simulator from loading test

---

test/app-tests/loading.js
test/mock-request.js

- just to check it keeps working.
Requires https://github.com/matrix-org/matrix-react-sdk/pull/1098

Add a test for the login flow when there is a teamserver

---

test/app-tests/joining.js
test/mock-request.js

Attempts to deflakify the joining test

---

src/components/views/messages/DateSeparator.js
src/skins/vector/css/_components.scss
src/skins/vector/css/matrix-react-sdk/structures/_RoomView.scss
src/skins/vector/css/vector-web/views/messages/_DateSeparator.scss

Date separator style was just define don any h2 in the message
list, so got picked up by any h2s in markdown too. Give date
separators their own class.
Fixes https://github.com/vector-im/riot-web/issues/4328

Fix h2 in markdown being weird

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss

The border for non hovered codeblocks is the same colour as the background, and there so the content doesn't move when the border is added.

Add border on hover for code blocks

---

src/vector/index.js
test/app-tests/loading.js

Update the vector-web tests to handle the refactorathon that happened in https://github.com/matrix-org/matrix-react-sdk/pull/1102.
Mostly this is just making it look at the `view` state rather than the individual boolean flags.
One other tweak merits explanation: we now implement the initial couldn't-register-as-guest login with an explicit switch to the LOGIN view, which means that the URL gets updated to #/login.

Tweak tests to match updates to matrixchat

---

test/app-tests/loading.js

Add a test for the 'log in as user' functionality, as well as the 'return to
app' functionality.

Test 'return-to-app' functionality

---

electron_app/src/tray.js

fixes that `trayIcon.setImage(newFavicon);` sometimes threw:
```
(node:10936) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Error processing argument at index 0, conversion failure from C:\Users\t3chg\AppData\Local\Temp\win32_riot_icon.ico
```
because even though the API claims it accepts a string sometimes it just fails to want to causing a desync between the number of Unread rooms and the number of Unread rooms in the Favicon.
Also pre-build the defaultIcon for reuse

explicit convert to nativeImage to stabilise trayIcon on Windows [Electron]

---

electron_app/src/electron-main.js
src/vector/index.js
src/vector/platform/ElectronPlatform.js
src/vector/rageshake.js

... so that we get to see what happened in the last 30s.

Attempt to flush the rageshake logs on close

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_Autocomplete.scss

- Fix https://github.com/vector-im/riot-web/issues/2230 by adding text-overflow: ellipsis to pill spans
- Add padding to pills
- Make sure to only apply horizontal margin of pill children at one level of the DOM tree

Add some style improvements to autocompletions

---

src/skins/vector/css/matrix-react-sdk/views/messages/_MEmoteBody.scss

as we do with MTextBody.
So that people can do multi-line emotes...

Apply white-space: pre-wrap to mx_MEmoteBody

---

.travis.yml
src/components/views/context_menus/MessageContextMenu.js

also use `this.closeMenu();` over the explicit direct call as the wrapper exists and is a little clearer
fixes

fix Quote not closing contextual menu

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_Autocomplete.scss

- Don't auto-complete the names (section headings) of auto-completions
- Only truncate if the pills are within a certain class of element
Required for https://github.com/matrix-org/matrix-react-sdk/pull/1178

Truncate auto-complete pills properly

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_MessageComposer.scss

Use `word-break: break-word` to split long words.
Fixes https://github.com/vector-im/riot-web/issues/4414

Fix long words causing MessageComposer to widen

---

src/components/structures/HomePage.js

Also add missing return in error-handling path

Give HomePage an unmounted guard

---

src/components/structures/RoomSubList.js
src/components/structures/SearchBox.js

This is for ctrl+k room filtering and switching
codep https://github.com/matrix-org/matrix-react-sdk/pull/1212

Implement the focus_room_filter action

---

package.json
test/app-tests/loading.js

Rather than a fixed delay, use matrix-react-test-utils to wait for the
login component to appear. Hopefully this will deflakify some tests.

loading tests: wait for login component

---

test/app-tests/joining.js

It won't do much to help with the vm stopping for 300ms, but it should make the
code and logs clearer.

use flushAllExpected in joining test

---

package.json
test/app-tests/joining.js

Just give the client longer to get started (it seems to be taking a long time
to get started talking to indexeddb)

Deflake the joining test

---

src/components/views/rooms/DNDRoomTile.js

Because bluebird doesn't support fail
Fixes https://github.com/vector-im/riot-web/issues/4642

Use `catch` instead of `fail` to handle room tag error

---

src/skins/vector/css/matrix-react-sdk/views/elements/_RichText.scss
src/skins/vector/css/themes/_base.scss

So that they can appear correctly in the body of a text message.

Make some adjustments to mx_UserPill and mx_RoomPill

---

scripts/deploy.py
scripts/redeploy.py

Riot will attempt to load `config.$domain.json` prior to `config.json` to allow for different configuration options depending on if you're hitting `riot.im/develop` or `scalar-staging.riot.im/develop`.
The redeploy script didn't know this. Changed the CLI options from looking like:
```
python redeploy.py --config ../../config.json
```
to looking like:
```
python redeploy.py --config config.json=../../config.json --config config.scalar-staging.riot.im.json=../../scalar-staging/config.json
```
Without this, every time /develop deploys a new version, the scalar-staging config JSON disappears from /develop (since it was never added back in to the untarballed files, unlike config.json).

Support multiple config.json symlinks in redeploy.py

---

test/app-tests/loading.js
test/test-utils.js

Chrome seems to take ages (like, 1500ms regularly) to clear out the indexeddbs,
and that's causing test timeouts. Bump the timeout to hack around it.
Also: clear both dbs in parallel (can't hurt, right?) and improve diagnostics
on the process.

Increase the timeout for clearing indexeddbs

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss

also fix header colours, which now inherit the font colour of the event tile (so all headers have the correct colour when sending or when the event tile is highlighted for a mention)
fixes vector-im/riot-web#4656
fixes vector-im/riot-web#4421

Make pills, emoji translucent when sending

---

src/skins/vector/css/matrix-react-sdk/views/elements/_MemberEventListSummary.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss

- add some comments
- decrease size of info events and MELS (#4363.2)
- reduce spacing between paragraphs, lists, etc (#4363.3 & 4)
Assigning to @ara4n so that he can decide if he likes the changes or not. ;)  The reduced size of info event I think should be fine.  I'm not so sure about the reduced spacing between some elements, because, at least for paragraphs, it comes into effect or not depending on how the user entered the paragraphs (see discussion starting at https://github.com/vector-im/riot-web/issues/4363#issuecomment-310660402).

tweak compact theme

---

.gitignore

This gitignore update allows the .idea directory to exist in subdirectories. This is useful because it allows the for IntelliJ products to work in subdirectories without littering the git change-list. An example where this occurs is opening the electron-app directory in Webstorm.

update gitignore to allow .idea directory to exist in subdirs

---

README.md

The URL for the signing key changed and hence pointed to a wrong direction. Probably better to merge directly in `master`?

Fix signing key url in readme

---

src/components/views/context_menus/MessageContextMenu.js

codep matrix-org/matrix-react-sdk#1289

Quote using innerText

---

src/components/structures/RoomDirectory.js
src/components/structures/RoomSubList.js
src/components/views/context_menus/MessageContextMenu.js
src/components/views/context_menus/RoomTileContextMenu.js
src/components/views/elements/ImageView.js
src/components/views/globals/NewVersionBar.js
src/components/views/globals/PasswordNagBar.js
src/components/views/rooms/DNDRoomTile.js
src/components/views/settings/Notifications.js

paired with https://github.com/matrix-org/matrix-react-sdk/pull/1255

un-i18n Modal Analytics

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_MemberDeviceInfo.scss

Buttons with short text stay as they are, buttons with long text don't get overflowed, but just grow and wrap on a new line if needed, still remaining aligned with others (helpful for translations that don't have short enough equivalent for button labels)
Screenshot (short English labels, longer Russian labels):
It would be nice to get those into a device context menu eventually, the same as message actions are now under the message context menu.
Same as the #4703 but based on `develop` branch as @t3chguy and @lukebarnard1 suggested.
Signed-off-by: Andrei Shevchuk <andrei@shevchuk.co>

Make member device info buttons fluid and stackable with flexbox

---

src/components/structures/RightPanel.js

because we shouldn't have a dispatch AND have a property that do vaguely similar things. Ideally, the dispatch would send a userId and RP would do async work to get the member/avatar/displayname.

Remove userId property on RightPanel

---

src/components/structures/RoomSubList.js

+ missing roomsublist badge for invites
+ missing room badge for invites if i18n!=English
***Requires https://github.com/matrix-org/matrix-react-sdk/pull/1343***

fix two room list regressions

---

src/components/structures/LoginBox.js
src/skins/vector/css/matrix-react-sdk/structures/_LoginBox.scss

For some languages the register and/or login buttons are to small, which causes the text to overflow. With this fix the buttons expand to fit the text content and if needed wrap to two lines if both buttons can't fit into one line. Issue: https://github.com/vector-im/riot-web/issues/4804
Signed-off-by: Lion Marlon n0stradamos@mail.ru

Fix overflowing login/register buttons on some languages issue #4804

---

scripts/deploy.py

Just don't bother replacing that bundle. Continue redloying the
resr as other assests (eg translation files) may have changed.

Redeploy script: don't bail if bundle exists

---

package.json
src/components/views/messages/DateSeparator.js
src/skins/vector/css/vector-web/views/messages/_DateSeparator.scss

Reverts vector-im/riot-web#4939
Turns out react-sticky is a bit crap and the headers jiggle abut all over the place on a mac scrolling on the touch pad. Reverting until we can figure out how to do it better.

Revert "Implement sticky date separators"

---

src/components/structures/RoomSubList.js

as things are assuming it's optional but it isn't which is causing
a ton of warnings.

Make isInvite default to false

---

src/components/structures/LeftPanel.js
src/components/structures/RoomSubList.js

See https://github.com/matrix-org/matrix-react-sdk/pull/1375

Avoid re-rendering RoomList on room switch

---

package.json
src/components/views/context_menus/GenericTextContextMenu.js

generic contextual menu for tooltip/responses

---

electron_app/src/electron-main.js

an int obviously has no `isStarted` method - DUH

fix really dumb blunder/typo preventing system from going to sleep.

---

test/app-tests/joining.js

It's no longer reset when the join request completes, so don't
assert it. (The important test is later, asserting that the room
object is non-null).

Fix test for new behaviour of 'joining' flag

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss

Apply 0.7 opacity to flair, but keep name and aux at 0.5
codep https://github.com/matrix-org/matrix-react-sdk/pull/1401

Alter opacity for flair

---

package.json

Otherwise you can make broken releases on case insensitive file
systems

Clean on prepublish

---

src/components/structures/RightPanel.js

To reduce repetition of code, simplify the process of adding header buttons and remove the need for many handler functions.

Refactor right panel header buttons

---

src/components/structures/RightPanel.js
src/i18n/strings/en_EN.json
src/skins/vector/css/matrix-react-sdk/views/rooms/_EntityTile.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_MemberList.scss
src/skins/vector/css/vector-web/structures/_RightPanel.scss

This step needs to be taken before adding a room to a group summary
codep https://github.com/matrix-org/matrix-react-sdk/pull/1429

Implement "Add room to group" feature

---

src/components/structures/RightPanel.js

This is redundant and throws a warning

Remove `key` prop pass-thru on HeaderButton

---

src/skins/vector/css/_components.scss
src/skins/vector/css/matrix-react-sdk/views/elements/_EditableItemList.scss

CSS for https://github.com/matrix-org/matrix-react-sdk/pull/1444/files

Factor out EditableItemList component from AliasSettings

---

src/skins/vector/css/themes/_dark.scss

This fixes https://github.com/vector-im/riot-web/issues/5013 and https://github.com/vector-im/riot-web/issues/4416 by only showing the border when the code block is hovered, and that the border is actually visible. The !important is needed to override the default border behaviour.

Bring back dark theme code block border

---

src/components/views/settings/Notifications.js
src/i18n/strings/en_EN.json

***Requires https://github.com/matrix-org/matrix-react-sdk/pull/1362***
*Fixes ~https://github.com/vector-im/riot-web/issues/4987~ https://github.com/vector-im/riot-web/issues/3814*

allow hiding of notification body for privacy reasons

---

src/components/views/directory/NetworkDropdown.js

Sorting of networks within a protocol based on name

---

src/components/structures/RightPanel.js
src/i18n/strings/de_DE.json
src/i18n/strings/en_EN.json
src/i18n/strings/gl.json
src/i18n/strings/hu.json
src/i18n/strings/it.json
src/i18n/strings/nl.json
src/i18n/strings/pt.json
src/i18n/strings/pt_BR.json
src/i18n/strings/ru.json
src/i18n/strings/uk.json
src/i18n/strings/zh_Hant.json
src/skins/vector/css/_components.scss
src/skins/vector/css/matrix-react-sdk/structures/_GroupView.scss

And also change "Add room to this group" to "Add rooms..."

CSS for Modifying GroupView UI matrix-org/matrix-react-sdk#1475

---

src/vector/index.js

Rather than through a languageHandler object. This way our
translation script knows about it.

Use _t as _t

---

src/skins/vector/css/_common.scss
src/skins/vector/css/matrix-react-sdk/views/dialogs/_ChatInviteDialog.scss

The "groups will be public" warning was apparently the first thing
long enough to reach the right hand edge

Add padding-right to Dialogs

---

src/components/structures/LeftPanel.js
src/components/structures/RightPanel.js
src/components/structures/RoomDirectory.js
src/skins/vector/css/_common.scss
src/skins/vector/css/matrix-react-sdk/structures/_RoomView.scss

Use CSS to stop greyed Right/LeftPanel UI from being interactable

---

src/components/views/settings/Notifications.js

This task was mostly to familiarize myself with a piece of Riot. 
* Most changes are to variable declarations
* Some functions changed to arrow functions
* Fixed typo

Leverages ES6 in Notifications

---

src/skins/vector/css/matrix-react-sdk/structures/_GroupView.scss

Part of https://github.com/matrix-org/matrix-react-sdk/pull/1559

Prevent group name looking clickable for non-members

---

package-lock.json
src/skins/vector/css/matrix-react-sdk/views/rooms/_AppsDrawer.scss

This is especially noticeable / needed when widget content is loading, or there is an error (as there is no separator between the widget title content and the main body).

Add back bottom border to widget title bar

---

src/components/structures/RightPanel.js
src/skins/vector/css/matrix-react-sdk/views/groups/_GroupRoomList.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_EntityTile.scss

See matrix-org/matrix-react-sdk#1563

Implement simple GroupRoomInfo

---

src/skins/vector/css/matrix-react-sdk/views/elements/_RichText.scss

Unsure if there's a better way than the `!important`s here :(

CSS for room notification pills

---

src/components/structures/RightPanel.js
src/components/views/elements/InlineSpinner.js
src/skins/vector/css/_components.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_MemberInfo.scss
src/skins/vector/css/vector-web/views/elements/_InlineSpinner.scss

For https://github.com/matrix-org/matrix-react-sdk/pull/1566

Add toggle to alter visibility of room-group association

---

src/skins/vector/css/matrix-react-sdk/views/dialogs/_CreateGroupDialog.scss

Add CSS for CreateGroupDialog to give group ID input suffix and prefix style

---

src/components/structures/RoomDirectory.js
src/skins/vector/css/vector-web/structures/_RoomDirectory.scss

instead of a space.
CSS applies to the room list in GroupView, so will fix the weirdness where the perms are sandwiched.

Use margin to separate "perms" in the room directory

---

src/components/structures/RightPanel.js

(in RightPanel), otherwise the store will happily send requests to the server for the `undefined` group.
Should fix https://github.com/vector-im/riot-web/issues/5513
Related: https://github.com/matrix-org/matrix-react-sdk/pull/1576

Do not init a group store when no groupId specified

---

src/skins/vector/css/matrix-react-sdk/structures/_GroupView.scss
src/skins/vector/css/matrix-react-sdk/structures/_MyGroups.scss
src/skins/vector/css/themes/_base.scss
src/skins/vector/css/themes/_dark.scss

For https://github.com/matrix-org/matrix-react-sdk/pull/1580

CSS for improving group creation UX, namely setting long description

---

src/components/views/rooms/RoomTooltip.js
src/skins/vector/css/_components.scss
src/skins/vector/css/matrix-react-sdk/views/elements/_ToolTip.scss
src/skins/vector/css/matrix-react-sdk/views/elements/_ToolTipButton.scss

Implement general-purpose tooltip "(?)"-style

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_AppsDrawer.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_RoomHeader.scss

.mx_RoomHeader_wrapper height needs to be increased to prevent max height of child elements from overflowing allocated space (.mx_RoomHeader_topic.max-height: 42px + .mx_RoomHeader_name.height: 31px == 73px total). Wrapper element height is currently set to 70px.
Setting a column width on the room topic causes overflow to be wrapped to another column (right) and hidden (by existing "overflow: hidden", directive).

Fix wrapping of long room topics (and overlap with apps)

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_AppsDrawer.scss

Mixed content warnings should be centered in the app panel.
Before:
After:

Center mixed content warnings in panel.

---

src/vector/index.js

This is so we correctly detect the browser language.
Fixes https://github.com/vector-im/riot-web/issues/5632
Signed-off-by: Travis Ralston <travpc@gmail.com>

Exclude the default language on page load

---

src/vector/index.js

* https://github.com/matrix-org/matrix-react-sdk/pull/1617
This PR contains a fix for https://github.com/vector-im/riot-web/issues/5623 in addition to one other fix. The config has to be loaded (and set) before calling `SettingsStore` otherwise all settings at the `config` level are ignored. Further, it helps to call `getValue` instead of `getValueAt` if we want the config to be respected.
The other included fix is to make sure the config is loaded prior to checking the user agent. This is so the default theme check reacts correctly, as per the above.
Visibility of what is going on in the diff might be a bit unclear, so going commit by commit may be better. The summary is the flow is now: load config -> check if mobile -> set theme -> rest of loading stuff

Make sure the SettingsStore is ready to load the theme before loading it

---

src/skins/vector/css/_components.scss
src/skins/vector/css/matrix-react-sdk/structures/_SearchBox.scss
src/skins/vector/css/matrix-react-sdk/structures/_TagPanel.scss
src/skins/vector/css/themes/_base.scss
src/skins/vector/css/vector-web/structures/_RoomSubList.scss

For https://github.com/matrix-org/matrix-react-sdk/pull/1639

CSS for new TagPanel

---

src/vector/index.html
src/vector/index.js

Fixes #5662.  (Trivial two-line change.)
Signed-off-by: Aidan Gauland <aidalgol@fastmail.net>

Set html lang attribute from language setting

---

src/components/structures/RoomSubList.js

I was being bitten by this enough for me to want to fix it. This implementation really ought to be improved such that it doesn't tend towards being broken the more it is used.
I'm not convinced we should be trusting that the client has the correct state in it (and is therefore in a position to calculate a new `order`). If a different implementation didn't rely on the client having the correct client state, then let's do that.
One example would be to do a linked list where the tag on the room refers to the previously tagged room. This however has the potential for error if the client removes an item and then fails to reinsert it. This is probably a better weirdness than what we have currently, though.

Implement renumeration of ordered tags upon collision

---

.github/ISSUE_TEMPLATE.md

It's not good to put potentially sensitive security issues in the public bug tracker, so advice to use security@matrix.org instead

Instructions on security issues

---

src/skins/vector/css/matrix-react-sdk/views/rooms/EventTile.css

This solves that the word "Options" is copied to your clipboard.
part of the problem: https://github.com/vector-im/riot-web/issues/893

Hide Options button from copy to clipboard

---

src/components/views/messages/MessageTimestamp.js

Reverts vector-im/riot-web#3046
This is adding a visible '&nbsp;'...

Revert "Add a &nbsp; after timestamp"

---

src/components/views/context_menus/MessageContextMenu.js
src/components/views/elements/ImageView.js
src/components/views/messages/DateSeparator.js
src/components/views/messages/MessageTimestamp.js
src/i18n/strings/en_EN.json
src/skins/vector/css/_components.scss
src/skins/vector/css/matrix-react-sdk/views/elements/_Quote.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_Autocomplete.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_QuotePreview.scss

+ ~Distinction between replies and quoting unclear.~
+ ~CSS Needs splitting off into own file~
Twinned with https://github.com/matrix-org/matrix-react-sdk/pull/1660

Implement Rich Quoting/Replies

---

README.md
config.sample.json
test/app-tests/joining.js
test/app-tests/loading.js

Twinned with https://github.com/matrix-org/matrix-react-sdk/pull/1625

move piwik whitelists to conf and add piwik config.json info to readme

---

src/components/views/messages/DateSeparator.js
src/components/views/messages/MessageTimestamp.js

Requires https://github.com/matrix-org/matrix-react-sdk/pull/1702
Fixes https://github.com/vector-im/riot-web/issues/4605

fix&refactor DateSeparator and MessageTimestamp

---

.travis.yml
package.json
src/components/structures/RoomSubList.js
src/components/views/rooms/DNDRoomTile.js
src/skins/vector/css/matrix-react-sdk/views/rooms/_RoomTile.scss
src/skins/vector/css/themes/_base.scss
src/skins/vector/css/themes/_dark.scss
src/skins/vector/css/vector-web/structures/_RoomSubList.scss
src/skins/vector/themes/status/css/_status.scss

Includes themeing
See matrix-org/matrix-react-sdk#1711

Swap RoomList to react-beautiful-dnd

---

src/skins/vector/css/_components.scss
src/skins/vector/css/matrix-react-sdk/views/messages/_MFileBody.scss
src/skins/vector/css/matrix-react-sdk/views/messages/_MImageBody.scss

Add explicit cursor:pointer so calculated CSS includes it for
- usercontent.riot.im styling

Split MImageBody into MFileBody to match JS Classes.

---

src/skins/vector/css/matrix-react-sdk/views/rooms/_MessageComposer.scss

specifically when trailing whitespace is not wrapped onto the next
line of the block.
Fixes #6077

Fix horizontal scrollbar under certain circumstances

---

src/components/structures/LeftPanel.js
src/components/structures/RoomSubList.js
src/components/views/context_menus/RoomTileContextMenu.js
src/components/views/rooms/DNDRoomTile.js
src/skins/vector/css/vector-web/structures/_LeftPanel.scss

- Moves RoomTileContextMenu over to new async action to set room tags.
- Adds a DragDropContext that handles drag and drop for TagPanel and RoomList. This is to
allow the future feature of dragging between the two components.
- Prevents RoomTiles from being dragged elsewhere for the time being.
See matrix-org/matrix-react-sdk#1719

Make room tagging flux-y

---

src/components/structures/LeftPanel.js
src/skins/vector/css/vector-web/structures/_LeftPanel.scss

A previous PR (#6134) assumed that the TagPanel feature
would always be enabled, leading to strangeness when it
wasn't: #6136.
(FTR the original layout bug was #6133)

Fix LeftPanel size being incorrect when TagPanel disabled

---

src/components/structures/LeftPanel.js
src/skins/vector/css/matrix-react-sdk/structures/_MyGroups.scss

for adding groups to the TagPanel.
Codep. https://github.com/matrix-org/matrix-react-sdk/pull/1751

Implement riot-web side of dragging GroupTile avatars to TagPanel

---

src/components/structures/RoomSubList.js

Otherwise, the DND tile will expect to be within a Droppable,
which is not supported by react-beautiful-dnd. This was causing
errors when receiving an invite.
Fixes #6144

Only use DNDRoomTile for editable sub lists

---

src/skins/vector/css/themes/_base.scss
src/skins/vector/css/themes/_dark.scss
src/skins/vector/themes/status/css/_status.scss

The alternative is to specify yet another colour that we have to
worry about when applying tinting, which is currently quite
fragile and requires changes to many parts of the app, including
all themes that don't require the colour to be tinted.
By using translucent black, we effectively take the secondary
accent colour of the LeftPanel and make it more black.
Note: This does not preserve the previous colour we were using,
although the alternative above does allow for this.
Also, this simplifies the same bg colour for the other themes.
Partially fixes https://github.com/vector-im/riot-web/issues/6159

Use translucent black for RoomSubList bg to fix tinting

---

src/components/views/rooms/RoomDropTarget.js
src/skins/vector/css/matrix-react-sdk/views/rooms/_RoomList.scss
src/skins/vector/css/vector-web/views/rooms/_RoomDropTarget.scss

so that the correct background colour can be used to surround both.
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1753

Fix RoomDropTarget and emptySubListTip to have containers

---

src/skins/vector/css/matrix-react-sdk/views/elements/_Dropdown.scss

If not enough space was dedicated to a dropdown,
it would previously make option text overlap.
With this patch, each option can potentially span
multiple lines. This is weird, but it's a better
degradation than making option text overlap.
Of course, a proper fix is to dedicate proper attention to each "not enough space dropdown" and allow for enough space to avoid this. But until that's done, it's better to degrade in a nicer way.
Signed-off-by: Slavi Pantaleev <slavi@devture.com>

Make dropdowns with long options degrade more gracefully

---

src/skins/vector/css/matrix-react-sdk/structures/_UserSettings.scss

The media dropdown would sometimes contain options
with long text, which can't possibly fit in 200px.
(e.g. `Monitor of Built-in Audio Digital Stereo (HDMI)`)
Dedicating some more space resolves the problem.
This is somewhat of a continuation to #6244.
Before #6244, the options just overlap in a really ugly way.
After #6244 they span multiple lines, which is better, but still not perfect.
With this, it should hopefully be ideal.
Final result:
Signed-off-by: Slavi Pantaleev <slavi@devture.com>

Make media dropdown wider

---

scripts/copy-res.js

It was common, at least for me, to experience a crash produced
when running the `matrix-react-sdk/scripts/gen-i18n.js` script
because when writing en_EN.json (via the script or otherwise)
choikdar would receive an event and cause the file to be read,
but the file would be empty when clearly it wasn't.
This would happen even when doing an atomic write in gen-i18n.
The fix adds a debounce as a workaround.

Fix crash; fs event received /w langauge file empty

---

src/skins/vector/css/matrix-react-sdk/structures/_TagPanel.scss

so that the user can drag groups to an empty TagPanel
fixes https://github.com/vector-im/riot-web/issues/6276

Make sure mx_TagPanel_tagTileContainer occupies full height

---

src/components/views/rooms/RoomTooltip.js
src/skins/vector/css/matrix-react-sdk/views/elements/_ToolTipButton.scss
src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss

See https://github.com/matrix-org/matrix-react-sdk/pull/1791

Changes for E2E "fudge-button"

---

src/vector/index.js

A bug in firefox means "disabled" isn't honoured when set in the
HTML. Doing `a.disabled = false` does work however, and Chrome
also appears to honour this.
Fixes https://github.com/vector-im/riot-web/issues/6075

Fix themeing bug with Firefox where "disabled" ignored

---

src/components/structures/RightPanel.js

by not reusing the same function and invoking separate conditions
to decide what the function does but instead using different
functions.
Also, show the GroupMemberList after inviting a member, otherwise
we might end up looking at the member we were already looking at
instead of the updated list of members.
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1796

Fix bug where cannot send group invite on GroupMemberInfo phase

---

src/skins/vector/css/matrix-react-sdk/structures/_TagPanel.scss

With the caveat that this will give a solid background
to group avatars with transparency when they are selected.
fixes https://github.com/vector-im/riot-web/issues/6225
fixes https://github.com/vector-im/riot-web/issues/6190

Fix gap between avatar and border

---

README.md
src/vector/index.html
webpack.config.js

And make it configurable, albeit only at buuld time, as hopefully
explained in the README.

Remove og:image with status.im URL

---

src/components/views/rooms/DNDRoomTile.js

because otherwise beautiful dnd spends a lot of time requesting
animation frames pointlessly.
a continuation of https://github.com/matrix-org/matrix-react-sdk/pull/1801

Implement a simple shouldComponentUpdate for DNDRoomTile

---

src/components/structures/LeftPanel.js

so as to prevent interaction with TagPanel.
Fixes https://github.com/vector-im/riot-web/issues/6184

Ensure entire LeftPanel is faded when settings open

---

src/components/structures/RoomSubList.js

so that the notification count is updated.
Previously we relied on a force update from RoomList, which was
removed as part of the optimisations in
https://github.com/matrix-org/matrix-react-sdk/pull/1801

Force update RoomSubList after reading a room

---

res/home.html

The translations Room is also used for the non Web Versions of Riot so it made sense to change the name (the alias still exists)
Signed-Off-By: Marcel Radzio <mtrnord1 [at] gmail.com>

Rename the Riot-Web Translations Room

---

src/components/views/dialogs/ChangelogDialog.js

closes #6479
This accidentally still worked because of the github redirection thing

change vector-web repo to riot-web in changelog

---

scripts/copy-res.js

In removing 'media' here, it changed the meaning of the copy so
the contents of vector-icons (rather than the dir itself) got
copied to webapp/
Fixes https://github.com/vector-im/riot-web/issues/6571

Fix favicon

---

release.sh

It was assuming the version was always $1 which meant there was no
way to pass options (eg. -x to skip changelog generation) through
to the underlying release script without breaking the wrapper
script.

Fix args in the release wrapper script

---

electron_app/src/webcontents-handler.js

These won't work outside of the electron app so there is zero point
in trying to open them in an external browser or offerring to copy
them to the clipboard

Hide URL options for e2e blob: URL images

---

electron_app/src/electron-main.js

Fixes two instances where `--hidden` could have failed:
+ instance is already running, another `riot --hidden` call happens, hidden is ignored.
+ window state keeper calls something like maximise to restore previous state, electron treats this as wanting the window to be wanted to be shown.
FIXES https://github.com/vector-im/riot-web/issues/6803 && https://github.com/vector-im/riot-web/issues/6633
Remainder is linting, removing debug and tidying other aspects of the code

[electron] Fix desktop app --hidden flag

---

res/themes/status/css/_status.scss

add override for colour of room tile text within memberinfo (unreadable)

---

package.json

Because 0.18.3 is broken (https://github.com/punkave/sanitize-html/issues/241
/ https://github.com/punkave/sanitize-html/issues/242

Pin sanitize-html to 0.18.2

---

package.json

1.18.4 is now out which makes it work with webpack again

Unpin sanitize-html

---

src/vector/index.js

Other part of https://github.com/vector-im/riot-web/issues/7378

Don't show mobile guide if deep linking

---

README.md

Signed-off-by: Aaron Raimist <aaron@raim.ist>
Fixes #6738

Document how to turn off Piwik and bug reports (#6738)

---

package.json

Using `start:init` on matrix-react-sdk side the reskindex never gets build in the react-sdk. This didn't show up when using `start` as that generated it just at a later point. The correct script which also generates the index file is `build` on the matrix-react-sdk side

Fix reskindex on matrix-react-side not being called if using build script

---

src/vector/index.js

This if checks if we got a Firefox using a variable that is undefined everywhere except in Firefox. In Firefox because of how it renders the DOM ensure that css is always loaded before it loads/runs the js code. Therefor onload 1. never triggers and 2. we can just call setTheme.

Fix Tinter.setTheme to not fire using Firefox

---

src/vector/platform/ElectronPlatform.js

Workaround temporarily by not closing notifs on win32 as per
comment.
Fixes https://github.com/vector-im/riot-web/issues/7512
NB. This PR is against the release branch

Stop electron crashing

---

package-lock.json
package.json

The newer version of fsevents compiles successfully with Node 11, while the current version seems to fail during install.
This change does move chokidar to a new major version. The breaking change listed in the [change log](https://github.com/paulmillr/chokidar/blob/master/CHANGELOG.md) seems to only affect Windows-style paths, which don't apply here.
Signed-off-by: J. Ryan Stinnett <jryans@gmail.com>

Update chokidar to transitively get newer fsevents

---

package-lock.json
package.json
webpack.config.js

Paired with (**please review all 3**):
* https://github.com/matrix-org/matrix-js-sdk/pull/775
* https://github.com/matrix-org/matrix-react-sdk/pull/2263
----
This was introduced in https://github.com/matrix-org/matrix-react-sdk/pull/2250 but can be pulled out due to https://github.com/matrix-org/matrix-js-sdk/pull/770. See https://github.com/vector-im/riot-web/issues/7634 for more information about the future.

Remove the request-only stuff we don't need anymore

---

package.json

This simplifies some testing scenarios, such as running a development install of Riot on one machine and testing on another.
Signed-off-by: J. Ryan Stinnett <jryans@gmail.com>

Allow Webpack dev server to listen to all interfaces

---

src/vector/index.js
src/vector/rageshakesetup.js

Some of the js-sdk logging was going missing due to js-sdk's
loglevel library being initialised before the rageshake logging.
Fix by doing the rageshake setup within an import, as commented.

Fix missing js-sdk logging

---

.travis.yml
package-lock.json
package.json
src/components/structures/VectorHomePage.js
src/components/views/login/VectorCustomServerDialog.js
src/components/views/login/VectorLoginFooter.js
src/components/views/login/VectorLoginHeader.js
src/vector/index.js
src/vector/indexeddb-worker.js
src/vector/platform/ElectronPlatform.js
src/vector/platform/VectorBasePlatform.js
src/vector/platform/WebPlatform.js
src/vector/url_utils.js
test/all-tests.js
test/app-tests/joining.js
test/app-tests/loading.js
test/skin-sdk.js
test/test-utils.js

Reverts vector-im/riot-web#7490
This breaks the modernizr tests and causes riot to just show the "your browser can't run riot" screen.

Revert "Run lint on travis builds and use modern node versions"

---

.travis.yml
package-lock.json
package.json
src/components/structures/VectorHomePage.js
src/components/views/login/VectorCustomServerDialog.js
src/components/views/login/VectorLoginFooter.js
src/components/views/login/VectorLoginHeader.js
src/vector/index.js
src/vector/indexeddb-worker.js
src/vector/platform/ElectronPlatform.js
src/vector/platform/VectorBasePlatform.js
src/vector/platform/WebPlatform.js
src/vector/url_utils.js
test/all-tests.js
test/app-tests/joining.js
test/app-tests/loading.js
test/skin-sdk.js
test/test-utils.js

Creating another PR so I can fix it

Re-apply "Run lint on travis builds and use modern node versions"

---

CONTRIBUTING.rst

The JS SDK's CONTRIBUTING file is a bit simpler to read. The Synapse version previously used includes mentions of Python lint tools that don't apply here.
Signed-off-by: J. Ryan Stinnett <jryans@gmail.com>

Link to CONTRIBUTING from JS SDK

---

electron_app/src/electron-main.js
electron_app/src/preload.js
src/vector/index.js
src/vector/platform/ElectronPlatform.js
src/vector/platform/VectorBasePlatform.js
src/vector/platform/WebPlatform.js
test/app-tests/joining.js
test/app-tests/loading.js
webpack.config.js

* Turn off node integration in the electron renderer process
* Enable the chromium sandbox to put the renderer into its own process
* Expose just the ipc module with a preload script
* Introduce a little IPC call wrapper so we can call into the
renderer process and await on the result.
* Use this in a bunch of places we previously used direct calls
to electron modules.
* Convert other uses of node, eg. use of process to derive the
platform (just look at the user agent)
* Strip out the desktopCapturer integration which doesn't appear
to have ever worked (probably best to just wait until
getDisplayMedia() is available in chrome at this point:
https://github.com/vector-im/riot-web/issues/4880).
Requires https://github.com/matrix-org/matrix-react-sdk/pull/2372

Run the Desktop app in a sandbox

---

README.md

Since this section is just after the "Untar the tarball on your web server" instructions, I had assumed that this was a Debian package for the server. It is not completely uncommon to have packages for web apps, for example phpmyadmin is packaged for Debian.
This makes it clear that this is a desktop app, and will avoid confusion (particularly because riot-web probably won't run on a server, #7918).
Signed-off-by: Remi Rampin <remirampin@gmail.com>

Make clear that the Debian package is for desktop

---

src/vector/index.html
src/vector/index.js
src/vector/indexeddb-worker.js

Looks like this was broken in the webpack 4 upgrade due to the
worker script setter and the bundle being re-ordered in index.html.
* Remove the loop: we only use two scripts now, so import them
explicitly
* Remove outdated olm import code.
* Stop generating a script import for each theme: we were pulling
in 3 js files that did absolutely nothing.
* Fix worker 'onmessage' scope (set it as a global rather than
trying to make it an ES6 module which it isn't).
* Fail hard if the indexeddb worker script isn't set to avoid
this happening again.

Fix the IndexedDB worker

---

res/themes/status/css/_status.scss

Added `$accent-color-alt` to all themes.
Should fix build fail:
https://travis-ci.org/matrix-org/matrix-react-sdk/builds/470534213?utm_source=github_status&utm_medium=notification
Related PR in matrix-react-sdk: https://github.com/matrix-org/matrix-react-sdk/pull/2379

Added new colour var to all themes

---

docs/shortcuts.md

I'm sure I don't know all of them.

Start documenting keyboard shortcuts

---

src/vector/rageshakesetup.js

This was originally added in #7755, which pulled in the original source for the
module, breaking ancient browsers without support for classes (#8082).
The issue fixed here is currently live on all riot.im versions, so we may want to merge to other branches as well.

Fix SdkConfig import to use transformed module

---

src/vector/rageshakesetup.js

This was originally added in #7755, which pulled in the original source for the
module, breaking ancient browsers without support for classes (#8082).
This is the same as #8109, but this one targets `develop`.

Develop branch: Fix SdkConfig import to use transformed module

---

electron_app/src/webcontents-handler.js
src/vector/rageshakesetup.js

Fixes #7937 
Changes the labels all the match casing of Chrome.
Fixes a small typo in a comment.

Correct the copying of e-mail addresses in the electron app

---

scripts/fetch-develop.deps.sh

Attempt both the PR author's branch and the PR's target branch. This resolves
issues on experimental where we need matrix-react-sdk to also be experimental.

Try fetching more branches for PRs

---

package-lock.json
package.json

This resolves an issue where the auto-updater on Mac with a standard
(ie. non-admin) user account would leave the app in a broken,
unlaunchable state (although it's not obvious what change in
electron-builder fixes this).
Fixes https://github.com/vector-im/riot-web/issues/8215

Update electron builder

---

src/vector/platform/ElectronPlatform.js

Apparently I couldn't decide whether I was writing indexOf(...) > -1
or .includes()
Fixes https://github.com/vector-im/riot-web/issues/8230

Fix literal &lt/&gt in notifications

---

README.md
test/app-tests/loading.js

Team servers are an obsolete feature that complicates many critical parts of the app.
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/2511

Remove support for team servers

---

webpack.config.js

Completely disable other themes for now (#8277)

---

scripts/copy-res.js
src/vector/index.js
webpack.config.js

In the same way as we now do images/fonts

Cache-bust olm.wasm

---

test/app-tests/joining.js

Disable room directory test because it doesn't work

---

res/home.html

Fixes https://github.com/vector-im/riot-web/issues/8367
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/2562
Guest: 
Logged in:

Hide sign in / create account for logged in users

---

README.md
electron_app/src/vectormenu.js

Fixes #7721
This creates two menu items which looks bad but [setting the second one to `visible: false` seems to disable it too](https://github.com/electron/electron/issues/15496#issuecomment-460001112). 😡 
Hopefully someone will actually solve https://github.com/electron/electron/issues/15496 upstream

Allow Electron to zoom with CommandOrControl+=

---

test/app-tests/loading.js

for https://github.com/matrix-org/matrix-react-sdk/pull/2588

fix app tests after force enabling lazy loading + removing feature flag

---

README.md

It's possible this git fixed in the CI scripts but not the README.
Running `npm install` undoes the npm linking, so this needs to be
run before fetch-develop-deps.

Fix order of fetch-develop-deps / npm install

---

scripts/make-icons.sh

This commit detects if the macos-only utility `iconutil` is available in
the PATH, if it is, then the icns is built as usual. However if it
isn't (such as on a linux system), then it checks for `png2icns` and
uses it if possible.
Signed-off-by: Abel Luck <abel@guardianproject.info>

Make scripts/make-icons.sh work on linux

---

package.json
scripts/copy-res.js
src/vector/index.html
webpack.config.js

React-SDK PR: https://github.com/matrix-org/matrix-react-sdk/pull/2658
For i18n, I changed the copy-res.js script to generate content-hashed filenames and include those in languages.json, which then gets a content-hashed filename with file-loader.
Fixes https://github.com/vector-im/riot-web/issues/4136

Cache busting for icons & language files

---

README.md

This the recommended way to define a default server (instead of the existing HS
and IS URL options). It will use `.well-known` discovery to find the URLs.
See https://github.com/vector-im/riot-web/issues/8763.

Document and recommend `default_server_name`

---

scripts/package.sh

Jenkins seems to use a different layout of the repos than other environments.
The sub-projects are cloned inside of the `riot-web` workspace. To account for
this, we need to adjust the Riot language file path.

Fix language file path for Jenkins

---

electron_app/package.json
electron_app/src/electron-main.js
src/vector/platform/ElectronPlatform.js
src/vector/platform/VectorBasePlatform.js

Also moves the Autolaunch platform stuff into the BasePlatform otherwise Preferences Settings would crash given a non-VectorBasePlatform Platform.
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/2688
Fixes part of https://github.com/vector-im/riot-web/issues/8904

Allow configuration of whether closing window closes or minimizes to tray

---

.travis.yml

karma seems to be giving priority to a location where an old version is installed.
In react-sdk done as part of https://github.com/matrix-org/matrix-react-sdk/pull/2676

set chrome path for travis CI explicitly

---

electron_app/src/electron-main.js

Supports an override config at:
```
%APPDATA%\Riot on Windows
$XDG_CONFIG_HOME/Riot or ~/.config/Riot on Linux
~/Library/Application Support/Riot on macOS
```
(or replace `Riot` with `Riot-$PROFILE` if you specify a `--profile`)
Moves electron-config to $appData/electron-config.json which will affect _very_ few users as its Electron only and hasn't made it into master yet.
Fixes https://github.com/vector-im/riot-web/issues/8949

Add support for localConfig at $appData/config.json.

---

scripts/package.sh
webpack.config.js

So languagehandler can pull the languages json from there
https://github.com/matrix-org/matrix-react-sdk/pull/2730

Set a require alias for the webapp directory

---

package-lock.json
package.json
scripts/jenkins.sh

It would be nice if it were actually an optional dependency and you
could just not install olm and get a Riot without olm, but you can't:
what you get is a broken Riot, so having it as an optional dep isn't
helping anyone.
Also whatever other package-lock changes npm has decided are
necessary today.

Change olm dependency to normal dep

---

electron_app/src/vectormenu.js

Fixes #8945
Should there also be a second menu item that links to the matrix.org FAQ?

Update Electron help menu link

---

.travis.yml

We don't support Node 8 anymore. Also the build is broken.

Remove node 8.x from the build matrix

---

scripts/fetch-develop.deps.sh

Currently, people with push access to the main Riot repos can push matching
branch names to Riot and the SDKs, and CI will test all the branches together.
This change allows contributors to access the same ability when submitting
several matching PRs from their fork of each repo.
Part of https://github.com/vector-im/riot-web/issues/9041
See also `matrix-react-sdk` PR https://github.com/matrix-org/matrix-react-sdk/pull/2807

Support CI for matching branches on forks

---

scripts/fetch-develop.deps.sh

If you try to clone a repo that doesn't exist via `https`, `git` will prompt for
auth credentials and hang forever. Using `git` avoids this and fails immediately
instead, which is what we want for a missing repo.
Part of https://github.com/vector-im/riot-web/issues/9221

Switch to `git` protocol for CI dependencies

---

test/app-tests/loading.js

`Promise.defer` is deprecated in Bluebird and it logs loudly each time it's
called. This cleans up testing logs significantly by converting away from it.

Convert away from `Promise.defer`

---

test/app-tests/loading.js

This changes the way tests wait for login to complete from a timer-based system
(which can cause intermittent failures) to an action-based system. The lifecycle
code dispatches the action `on_logged_in` when login completes which we can wait
for in the tests as a much better indication that work is done.
Required for https://github.com/matrix-org/matrix-react-sdk/pull/2826
Part of https://github.com/vector-im/riot-web/issues/9271

Use `on_logged_in` action in tests

---

README.md
src/components/views/auth/VectorAuthFooter.js

Our organization needs a imprint and privacy statement right on the login page, and some links to organization pages as well.
I've added a possibility to customize those links through the `config.json`:
``` python
"branding": {
"welcomeBackgroundUrl": "themes/org/bg.jpg",
"authHeaderLogoUrl": "themes/org/orglogo.svg",
"authFooterLinks": [
{"text": "Our Organization", "url": "https://best-org-ever.edu"},
{"text": "Some subdepartment", "url": "https://subdepartment.best-org-ever.edu"},
{"text": "Impressum", "url": "/legal/impressum.html"},
{"text": "Datenschutz", "url": "/legal/datenschutz.html"},
{"text": "github", "url": "https://github.com/vector-im/riot-web"}
]
},
```
Fixes #9127.

Configure auth footer links through Riot config

---

electron_app/src/webcontents-handler.js

https://github.com/vector-im/riot-web/pull/9326 to release

Add "Save image as..." button to context menu on images

---

test/app-tests/loading.js

The new storage consistency work expects a crypto store exist together with
local storage. This updates the loading tests to create them together.
Needed for https://github.com/vector-im/riot-web/issues/9109
Used in https://github.com/matrix-org/matrix-react-sdk/pull/2841

Setup crypto store for restore session tests

---

electron_app/src/electron-main.js

Fixes https://github.com/vector-im/riot-web/issues/9123
The value used here is a function which returns a promise, not a flag.

Fix autolaunch setting appearing toggled off

---

src/vector/index.js
src/vector/mobile_guide/index.js

See #9360
This is to prevent it from always working. Cookies without an expiration are supposed to expire at the end of the session, however the nature of mobile browsers means that the session is unlikely to ever end.

Add expiration to mobile guide cookie

---

README.md

The repo (https://github.com/iskrisis/vector-electron-desktop) very clearly states not to use it anymore.

Remove vector-electron-desktop from README

---

README.md
electron_app/src/electron-main.js

A custom user data directory can now be specified using the "profile-dir" command line argument.
This PR solves https://github.com/vector-im/riot-web/issues/6175.

Add support for custom profile directory

---

README.md

- change mentions of https://riot.im/packages to https://packages.riot.im
- add instructions to remove old, now-untrusted riot.im signing key
- update language and move from `apt-get` to the simpler `apt`
Signed-off-by: axel simon `<axelsimon at axelsimon.net>`

update installation instructions with new repo

---

scripts/deploy.py

nargs options are arrays and we assume it's an array later, so it
would iterate over each char of the string if left as the default

Fix default for --include arg

---

scripts/package.sh

Just in case you have a local config, remove it before packaging so it's not used as the default config for others.

Remove config.json from package dir

---

scripts/ci_package.sh

Take the useful part of the jenkins script and put it in a script
that makes a package with the git hashes as its version.

Change jenkins script to package script

---

scripts/package.sh

The script has a set -e so don't fail if there's nothing to rm
This raises the question of whether we want to be copying config.json from the root to webapp/ at all (which we do in copy-res.js) - I don't think we want it in the general case and for the electron build we can put it straight into webapp/ instead.
Either way I think we want this though.

Don't fail if there's no local config to remove

---

electron_app/riot.im/config.json

Add new scalar staging url

---

README.md
config.sample.json
docs/labs.md

Related to https://github.com/matrix-org/matrix-react-sdk/pull/2937

Add reactions feature to config sample

---

src/vector/platform/VectorBasePlatform.js

This avoids a canvas permission prompt from appearing on page load for users in
Firefox's resist fingerprinting mode. The prompt will still happen once you log
in and receive a notification, but at least this prevents it from happening
during the initial app experience.
Fixes https://github.com/vector-im/riot-web/issues/9605

Delay creating the `Favico` instance

---

.dockerignore
Dockerfile
README.md
scripts/docker-link-repos.sh

https://github.com/vector-im/riot-web/pull/9426 to release

Add Dockerfile

---

README.md
config.sample.json
src/i18n/strings/en_EN.json
src/vector/index.js
test/app-tests/joining.js
test/app-tests/loading.js

**Reviewer**: This is generally best reviewed as the final diff rather than the individual commits. Note that there's a TODO comment in the diff which has the intention of being followed up by a later PR - the PRs for this work item are getting a bit large, so this is being put up for review with a known deficiency. 
The TODO comment affects those who happen to use https://riot.im/develop/#/login?hs_url=https://matrix.org instead of the other options. It may also affect people's ability to claim 3pid validations.
See https://github.com/vector-im/riot-web/issues/9290
Fixes https://github.com/vector-im/riot-web/issues/8826
**Please review with https://github.com/matrix-org/matrix-react-sdk/pull/2941** (the implementation)
----
Implements the process described here: …

Validate default homeserver config before loading the app

---

src/vector/index.js

**Reviewer**: Note that this is pointed at the .well-known feature branch, not develop. This is intentional as the feature branch is still unsafe to merge to develop.
We don't actually need to do anything because the app transparently handles this.
See https://github.com/vector-im/riot-web/issues/9290

Clarify comment on is_url and hs_url handling

---

Dockerfile
scripts/docker-link-repos.sh

Fixes https://github.com/vector-im/riot-web/issues/9701 (by not timing out, allowing us to use Docker Hub again)
Fixes https://github.com/vector-im/riot-web/issues/9606 (the rules are already set up, we just need to have something to build 😄)
We force yarn to use a longer network timeout because Docker Hub's limited machines are not capable of downloading the resources fast enough. The tests I've performed on this branch have not failed due to network timeouts, so the value is presumed high enough. 
**Note**: Docker Hub is slow, our builds easily take 20-40 minutes to complete.

Make Dockerfile work for develop and other branches

---

src/vector/index.js

**Reviewer**: Note that this is pointed at the .well-known feature branch, not develop. This is intentional as the feature branch is still unsafe to merge to develop.
See https://github.com/vector-im/riot-web/issues/9290
Paired with https://github.com/matrix-org/matrix-react-sdk/pull/2971

Flag the validated config as the default config

---

src/vector/mobile_guide/index.html
src/vector/mobile_guide/index.js

**Reviewer**: Note that this is pointed at the .well-known feature branch, not develop. This is intentional as the feature branch is still unsafe to merge to develop.
See https://github.com/vector-im/riot-web/issues/9290

Show resolved homeserver configuration on the mobile guide

---

Dockerfile

`nginx:latest` is based on Debian Stretch and is listed as being 45MB,
while `nginx:alpine` is based on Alpine 3.9 and is just 7MB.
Basing the riot-web Docker image on `nginx:alpine` should
make it 38MB smaller compared to the current situation.
The nginx version seems to be "latest mainline" on both (currently 1.15.12),
judging by each Dockerfile:
- https://github.com/nginxinc/docker-nginx/blob/e5123eea0d29c8d13df17d782f15679458ff899e/mainline/stretch/Dockerfile
- https://github.com/nginxinc/docker-nginx/blob/e5123eea0d29c8d13df17d782f15679458ff899e/mainline/alpine/Dockerfile
Signed-off-by: Slavi Pantaleev <slavi@devture.com>

Base Docker image on nginx:alpine, not the larger nginx:latest

---

src/i18n/strings/en_EN.json
src/vector/index.js

**Requires https://github.com/matrix-org/matrix-react-sdk/pull/3043**
Fixes https://github.com/vector-im/riot-web/issues/9835
This is a temporary measure for https://github.com/vector-im/riot-web/issues/9828
Only applies if the user appears to be logged in. If the user is not logged in, we scream loudly.
A note on the messaging: The errors being displayed to users come from deep within the js-sdk, which is not easily translated. Instead of trying to wrestle a homeserver URL into the error, I've just stuck a sentence into the error box to hopefully make it clear that it's not the user's fault.
*Pretend that says "Homeserver URL does not appear to be a valid homeserver" instead of "Unexpected error"*

Use the user's pre-existing HS when config validation fails

---

README.md
config.sample.json

See https://github.com/matrix-org/matrix-react-sdk/pull/3049

Add docs for defaultCountryCode

---

res/welcome.html

Fixes https://github.com/vector-im/riot-web/issues/9546
**Requires https://github.com/matrix-org/matrix-react-sdk/pull/3066**

Hide guest functions on the welcome page if not logged in

---

README.md
src/i18n/strings/en_EN.json
src/vector/index.js
test/app-tests/loading.js

Also warn about deprecated config option usage.
See https://github.com/matrix-org/matrix-react-sdk/pull/3067

Do not fail on server liveliness checks during startup

---

electron_app/src/electron-main.js
src/vector/getconfig.js
src/vector/index.js
src/vector/platform/ElectronPlatform.js
src/vector/platform/VectorBasePlatform.js

+ in Electron get config via IPC from main process which has access to the "local" config.json override file and can make people happy :D
+ Remove bunch of duplicated code,
+ and move comments around to put them in the right place
Fixes https://github.com/vector-im/riot-web/issues/9476

Move config-getting to VectorBasePlatform

---

src/i18n/strings/en_EN.json
src/vector/getconfig.js
src/vector/index.js

Fixes https://github.com/vector-im/riot-web/issues/9519
**Requires https://github.com/matrix-org/matrix-react-sdk/pull/3154**

Display a red box of anger for config syntax errors

---

src/vector/index.html

Fixes https://github.com/vector-im/riot-web/issues/10162

Add e2e/warning.svg to preload

---

README.md
docs/config.md

The main README is very busy with too much information in one file. This
attempts to clean up one portion by moving configuration docs to a separate
file.
Fixes https://github.com/vector-im/riot-web/issues/9965
Used by https://github.com/matrix-org/matrix-react-sdk/pull/3158

Extract configuration docs to separate file

---

.buildkite/pipeline.yaml
package.json
scripts/compare-file.js

see https://github.com/matrix-org/matrix-react-sdk/pull/3209

Verify i18n in CI

---

config.sample.json
docs/config.md
test/app-tests/joining.js
test/app-tests/loading.js

Fixes https://github.com/vector-im/riot-web/issues/10229
**Review with https://github.com/matrix-org/matrix-react-sdk/pull/3213**

Remove unused disable_identity_server config flag

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/user-interface-or-usability-bug-report.md
src/vector/rageshakesetup.js

See https://github.com/matrix-org/matrix-react-sdk/pull/3207

Require descriptions in mxSendRageshake and remove infinite loop in issue templates

---

package.json

Every time I run `yarn install:electron`, it complains with:
```
yarn run v1.13.0
$ install-app-deps
• please use as subcommand: electron-builder install-app-deps
```
So, let's convert it to a subcommand.

Convert install-app-deps to subcommand

---

config.sample.json
docs/labs.md
electron_app/riot.im/config.json
riot.im/develop/config.json

Part of https://github.com/vector-im/riot-web/issues/10282

Remove edits and reactions feature flags from docs and config

---

electron_app/src/electron-main.js
electron_app/src/preload.js
package.json

The APIs related to custom protocols went through some changes for Electron 5.x,
so adjusts Riot's usages to match.
I have scanned the Electron 5.x release notes, and I can't see anything else
that requires immediate changes. Things appear to be working well after the
upgrade.
Fixes https://github.com/vector-im/riot-web/issues/10296
Fixes https://github.com/vector-im/riot-web/issues/9562

Upgrade to Electron 5

---

electron_app/src/electron-main.js
src/vector/platform/ElectronPlatform.js

Fixes https://github.com/vector-im/riot-web/issues/10376
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/3278

Allow setting electron autoHideMenuBar and persist it

---

src/vector/index.js

Fixes https://github.com/vector-im/riot-web/issues/10548

Load config.json before loading language so default can apply

---

electron_app/build/linux/after-install.tpl
package.json

This tweaks Linux packages for Riot to SUID `chrome-sandbox` after install. This
is required as of Electron 5 for certain distros, such as Debian.
This change has also been provided to `electron-builder` upstream, so ideally
they'll include it in the future and this becomes redundant.
Fixes https://github.com/vector-im/riot-web/issues/10509

Set SUID bit on chrome-sandbox for Debian

---

config.sample.json
electron_app/riot.im/config.json
riot.im/app/config.json
riot.im/develop/config.json

Add and prioritize the new "_matrix/integrations/v1" widget urls
As per MSC1961, add to the whitelisted integrations_widget_urls
the new paths. This allows us to switch Scalar over to use the
new path as default.
Note, the legacy "scalar-staging.riot.im" is these days just a redirect
to scalar-staging.vector.im, so there is no addition for that. It still
needs Riot side whitelisting though for existing widgets.
Refs: https://github.com/matrix-org/matrix-doc/pull/1961
Provide our common integrations_widget_urls defaults for sample config
Closes: #10454

Change integrations_widgets_urls default configuration

---

README.md

Clarify that HTTPS is not just needed for VoIP

---

yarn.lock

Yarn deps can be a bit fiddly when targeting specific versions. This tweaks the
lock file to only pull in a single React version.
For others who may need to do something like this again, I recommend deleting
specific package entries from `yarn.lock` and re-running `yarn install`. That
should make it pick the right thing while also leaving other packages as they
were.
(Note that riot-web still pulls in React 15 temporarily as a side effect of depending on released versions of React SDK. This will resolved itself during the next release.)

Tweak lock file to pull in only one React version

---

electron_app/src/originMigrator.js

For some reason this was trying to close the same window twice
when the app was reloaded after an SSO login. Possibly also a
problem on electron < 6 - presumably a race condition.
Merging to release branch

Fix origin migrator for SSO logins

---

src/vector/index.js

Fixes https://github.com/matrix-org/internal-config/issues/644
I scanned the project for any other logs which record the query parameters and did not find any others.

Don't log query parameters as they may contain secrets

---

src/vector/platform/ElectronPlatform.js

It's still not 100% clear whether storage is always persistent on
Electron, but we seem to be getting reports of it being deleted in
the wild on Electron, so let's try calling the API to request
persistent storage. It won't pop up a dialog on Electron. In the
worst case it will give us some logging so we know what the API calls
return.
We could do this on non-desktop too but it's a bit of a mess because
Firefox prompts the user but Chrome makes a decision itself based on
how much the user visits the site.

Request persistent storage on Electron

---

yarn.lock

Reverts vector-im/riot-web#11050
It looks like this is causing breakage for certain people on Firefox, somehow

Revert "Run yarn upgrade"

---

README.md

Copying the config sample is mentioned in the 'Getting Started' and the 'Building From Source' sections. However, when setting it up from the 'Building From Source' section, and then skipping to 'Setting up a dev environment' in step 6, the config won't have been copied yet. Therefore adding this step to the 'Setting up a dev environment' part as well.

Add config.json copy instruction to 'Development' as well

---

config.sample.json

Requires: https://github.com/matrix-org/matrix-react-sdk/pull/3046
See: https://github.com/vector-im/riot-web/issues/8449

add settingDefaults to sample config

---

package.json

The (rarely used) `start:js:prod` script for running production mode locally
failed to set Webpack into production mode, so things like minification would be
skipped.

Enable Webpack production mode for start:js:prod

---

scripts/copy-res.js

"Türk" means Turkish as nationality and "Türkçe" means Turkish as language.

Fix the label of Turkish language

---

package.json
scripts/electron-package.sh
scripts/electron_afterSign.js
yarn.lock

Notarise the mac app in the electron build process

Notarise the macOS app

---

package.json

Adding `"darkModeSupport": true` to the configuration adds an item to the Info.plist in the Mac app which allows the titlebar of Riot to change with the System theme (light, dark).
In `electron-builder`:
```ts
if (this.platformSpecificBuildOptions.darkModeSupport) {
appPlist.NSRequiresAquaSystemAppearance = false
}
```
Source: https://github.com/electron-userland/electron-builder/blob/faba9e365a0a4d2402d91ca9bd5a5288cb78f0f7/packages/app-builder-lib/src/macPackager.ts#L313-315
Electron info: https://electronjs.org/docs/tutorial/mojave-dark-mode-guide
Before:
After:

Add darkModeSupport to allow dark themed title bar.

---

docs/config.md

This updates the discussion of identity servers in the config docs to match what
was shipped in the privacy sprint.
Fixes https://github.com/vector-im/riot-web/issues/10982

Update config docs about identity servers

---

README.md

This removes `fetch-develop.deps.sh` from the docs, as it's designed more for
use on CI environments and ends up causing confusion when used for anything
else.
Fixes https://github.com/vector-im/riot-web/issues/11247

Remove mention of CI scripts from docs

---

electron_app/src/electron-main.js

Calls often transition from connected to connected after transitioning
into the connected state (when the ICE layer connects) so we ended up
creating two wake locks and then only stopping one of them.
Don't make another wake lock if we already have one.
Hopefully fixes https://github.com/vector-im/riot-web/issues/6814

Fix bug preventing display from sleeping after a call

---

src/vector/platform/ElectronPlatform.js

The menu bar is at the top of the screen on Mac so this setting
does absolutely nothing.
Option added in https://github.com/vector-im/riot-web/pull/10503

Remove the 'auto hide menu bar' option on Mac

---

src/vector/index.js

Fixes https://github.com/vector-im/riot-web/issues/11370
**Requires https://github.com/matrix-org/matrix-react-sdk/pull/3615**

Trigger a theme change on startup, not just a tint change

---

docs/labs.md
riot.im/develop/config.json

Part of https://github.com/vector-im/riot-web/issues/11407

Add cross-signing labs flag to develop and document

---

electron_app/src/electron-main.js

Specifically for the desktop app to prevent the warning about too many homeservers defined.

Let the user's homeserver config override the build config

---

src/vector/index.js

A thesis presented in two parts. This part has the absolute minimum
logic changes to the themeing code in vector/index.js because I know
how subtle and fragile this code is. However, it also looks like it's
completely duplicated from react-sdk, so in the next part I'm going
to remove that logic and make it use the logic in react-sdk, then we
can see what breaks.
Requires https://github.com/matrix-org/matrix-react-sdk/pull/3637

Use new theme API in react-sdk

---

src/vector/index.js

Following on from matrix-org/matrix-react-sdk#3637
this removes the code dealing with themes in vector/index.js and uses the
code from react-sdk. The two did almost exactly the same thing but in
subtley different ways.
This code can be incredibly subtle though, so doing this a separate
PR.
Based on https://github.com/vector-im/riot-web/pull/11442

De-dup theming code

---

package.json
scripts/electron_afterSign.js
scripts/electron_winSign.js

We can actually just supply a custom signing module here to do our
signing rather than manually signing things in the afterSign hook.
This means all 4 executable files get signed (the main exe, the
stub exe, Update.exe and the installer).

Sign all of the Windows executable files

---

src/vector/mobile_guide/index.html
src/vector/mobile_guide/index.js

Remove mention of vector.im as default identity server on mobile guide

---

config.sample.json
electron_app/riot.im/config.json
riot.im/app/config.json
riot.im/develop/config.json

Ideally you would update enable_presence_by_hs_url work based on the homeserver name instead of the client URL but this is a quick fix
Fixes #11564

Update riot.im enable_presence_by_hs_url for new matrix.org client URL

---

.dockerignore
Dockerfile
scripts/docker-link-repos.sh
scripts/docker-write-version.sh

Fixes https://github.com/vector-im/riot-web/issues/10426
The problem with the docker image for develop was that the dependencies pointing at develop are empirically not working - it's pulling in the latest release still even though we are saying to use the develop branch. To fix this, we just pull in develop by default if we're building develop.

Fix Docker build for develop and publish a /version file

---

scripts/copy-res.js

Enabled (riot-web % / react-sdk %):
* Lithuanian: 100% / 48.1% translated
* Hindi: 69.6% / 36.5% translated
* Ukrainian: 100% / 28.5% translated
* Icelandic: 43.5% / 27.7% translated
They aren't the highest languages, but they are more than our lowest translated & enabled languages.

Enable more languages

---

README.md

I've added a note about Desktop just to clarify that we don't officially support random versions of Electron.

Clarify which versions of what we support

---

package.json
yarn.lock

It was added because js-sdk still depended on it
It no longer does 🎉

Remove babel-plugin-transform-async-to-bluebird

---

package.json

For https://github.com/matrix-org/matrix-react-sdk/pull/3723
**Note: This is set to merge against `travis/sourcemaps` because it breaks things.**

Remove now-retired package.json property

---

electron_app/src/electron-main.js

electron-main: Provide a better error message if Seshat isn't installed.

---

electron_app/src/updater.js
src/components/views/auth/VectorAuthFooter.js
src/components/views/auth/VectorCustomServerDialog.js

**This is against `travis/sourcemaps` for safety.**
Split from https://github.com/vector-im/riot-web/pull/11679
ES6 exports == happy development and webpack.
----
This PR and others in the series have their overview covered here: https://gist.github.com/turt2live/a3fc7c9712b8ef0f1f758611aa33382d

Convert components to ES6 exports

---

src/components/structures/VectorEmbeddedPage.js
src/components/views/auth/VectorAuthFooter.js
src/components/views/auth/VectorAuthHeaderLogo.js
src/components/views/auth/VectorAuthPage.js
src/components/views/auth/VectorCustomServerDialog.js
src/vector/index.js
src/vector/indexeddb-worker.js
src/vector/platform/ElectronPlatform.js
src/vector/platform/VectorBasePlatform.js
src/vector/platform/WebPlatform.js
src/vector/rageshakesetup.js
test/app-tests/joining.js
test/app-tests/loading.js

**This is against `travis/sourcemaps` for safety.**
Split from https://github.com/vector-im/riot-web/pull/11679
We compile directly for accuracy of sourcemaps.
----
This PR and others in the series have their overview covered here: https://gist.github.com/turt2live/a3fc7c9712b8ef0f1f758611aa33382d

Import from src/ for the react-sdk and js-sdk

---

electron_app/src/electron-main.js

Old URL is not accessible anymore and shows 404.

Updates URL for Electron Command Line Switches

---

res/sw.js
scripts/copy-res.js
src/vector/index.html

As discussed in https://github.com/vector-im/riot-web/issues/11646
---
Fixes https://github.com/vector-im/riot-web/issues/11646

Add stub service worker so users can install on desktop with Chrome

---

docs/labs.md
riot.im/develop/config.json

Part of https://github.com/vector-im/riot-web/issues/11799
See also https://github.com/matrix-org/matrix-react-sdk/pull/3831

Enable and document presence in room list feature flag

---

src/components/views/auth/VectorAuthFooter.js

The blog url was pointing to medium.com, where the top post said you are now using https://blog.riot.im/ so I propose to update the url in the app as well if this is correct.

Updated blog url

---

riot.im/develop/config.json

develop is a web deploy and therefore unlikely to have to node
module available

Disable event indexing on develop

---

Dockerfile

Support application/wasm in Docker image

---

test/app-tests/loading-test.js

We may no longer see a spinner for some login paths with the changes to add a
complete security step.
Part of https://github.com/vector-im/riot-web/issues/11214
Used by https://github.com/matrix-org/matrix-react-sdk/pull/3847

Remove spinner check

---

src/vector/rageshakesetup.js

Error was "s is not a function" because of how `require` works.

Fix rageshake post-sourcemaps

---

webpack.config.js

This was happening implicitly in our dev setups and the CI build
because of the comment on the last line.

Fix webpack to babel js-sdk & react-sdk but no other deps

---

webpack.config.js

Adds 'src' to react-sdk & js-sdk babel test path so we don't run node
modules inside js & react sdk through babel

Fix build to not babel modules inside js/react sdk

---

webpack.config.js

Without doing something like this it's hard to use `yarn link`ed resources.
Original: https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$DiLRt2GxD0itluoQwi1Yx9m9zvQGUQwpZWyQLrnWRIc?via=matrix.org&via=t2bot.io&via=maunium.net

Fix webpack config (by stealing Dave's config)

---

docs/config.md

Part of https://github.com/vector-im/riot-web/issues/11992

Add docs for admin report content message

---

.buildkite/pipeline.yaml

Fixes https://github.com/vector-im/riot-web/issues/11866
Described as an implicit dependency to simplify adding more stages later

BuildKite: Only deploy to /develop if everything else passed

---

riot.im/app/config.json
riot.im/develop/config.json

The old link redirected to the new one so there's no rush shipping these configs
Fixes https://github.com/vector-im/riot-web/issues/10362

Update cookie policy urls on /app and /develop config.json

---

Dockerfile

Fixes not having certain OS capabilities to build some packages.

Use debian to build the Docker image

---

Dockerfile
scripts/docker-link-repos.sh
scripts/docker-write-version.sh

Our Docker scripts use Bash-style conditionals that aren't supported by the
default Debian shell.
As a result, we weren't calculating the right branches for the SDKs on develop.

Use bash in Docker scripts

---

electron_app/src/electron-main.js
src/vector/platform/ElectronPlatform.js

This is the Riot side of patches for the event indexer UI, react-sdk side can be found here https://github.com/matrix-org/matrix-react-sdk/pull/3672. 
It only implements a method to get the index disk usage which we plan on presenting to users.
Part of https://github.com/vector-im/riot-web/issues/11984

ElectronPlatform: Add the indexSize method.

---

docs/labs.md
riot.im/develop/config.json

It's the default now: https://github.com/matrix-org/matrix-react-sdk/pull/3906
**Review with https://github.com/matrix-org/matrix-react-sdk/pull/3906**

Remove docs for new invite dialog labs feature

---

webpack.config.js

This changes Webpack to only output errors, warnings, or new compilations.
This has the effect of hiding the massive list of modules. The giant list was
actually _hiding_ warnings because they appear first and scroll off the
terminal.

Change to minimal Webpack output

---

babel.config.js
package.json

**Review with https://github.com/matrix-org/matrix-react-sdk/pull/3957**

Update babel targets

---

src/vector/app.js
src/vector/index.html
src/vector/index.js

Fixes https://github.com/vector-im/riot-web/issues/3632

Embed CSP meta tag and stop using script-src unsafe-inline

---

docs/shortcuts.md

Add the one missing Ctrl+` shortcut to the list of shortcuts.

Add top left menu shortcut

---

release.sh

This scripts the SDK dep handling to simplify the release process.
**Note:** Targetting the release branch.
See also https://github.com/matrix-org/matrix-react-sdk/pull/4076
See also https://github.com/matrix-org/matrix-js-sdk/pull/1212

Automate SDK dep upgrades for release

---

README.md

This updates and rewrites the supported environments portion of the README. It
also adds a new experimental support tier to clarify how we'll handle things
like installed PWAs and mobile web.
See also https://github.com/matrix-org/matrix-react-sdk/pull/4078 which ensures experimental environments are clearly identified.

Add experimental support tier

---

release.sh

We now want to do post-processing after the JS SDK release script, so we can't
use `exec` here.

Remove exec so release script continues

---

docs/shortcuts.md

This documents shortcuts for jumping to the start / end of the composer
contents.
Part of https://github.com/vector-im/riot-web/issues/12438
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/4108

Document start / end composer shortcuts

---

README.md

This clarifies that the "supported" tier is for browser and the official app on
desktop OSes only.
Fixes https://github.com/vector-im/riot-web/issues/12421

Clarify supported tier means desktop OSes

---

scripts/electron_afterSign.js

This makes it a bit more friendly to build macOS Electron builds without a
notarisation config set up by only warning when it is missing.

Relax macOS notarisation check to print a warning

---

scripts/electron_afterSign.js
scripts/electron_winSign.js

This allows Windows builds to complete when the singing token is not present.

Change Windows signing to warning when missing token

---

test/app-tests/loading-test.js

Part of https://github.com/vector-im/riot-web/issues/12207
Depends on https://github.com/matrix-org/matrix-js-sdk/pull/1233

Update loading test for JS SDK IDB change

---

electron_app/src/webcontents-handler.js

Electron 8.0.2 and later (which we're now using) resolves this issue with
`will-navigate`.

Remove will-navigate comment after Electron fix

---

electron_app/src/webcontents-handler.js

Stopgap solution until we switch to riot-desktop in 1.6 which will have a `riot://` protocol handler, see https://github.com/vector-im/riot-web/issues/8247
Electron 8.0.2 fixed will-navigate in sandboxed windows, we assumed it was broken, now we need it to stay that way.

Fix SSO flows for electron 8.0.2 by re-breaking will-navigate

---

scripts/docker-write-version.sh

Turns out it helps to use the right syntax.
Fixes https://github.com/vector-im/riot-web/issues/12009

Fix Docker image version for develop builds

---

package.json

Update dependency to electron version 7.1.14 to resolve issue where riot-web
has troubles syncing messages, and throws a "**CRASHING**:seccomp-bpf
failure in syscall 0230" error.  
See https://github.com/electron/electron/issues/22291 for more details.

Update electron to v7.1.14

---

config.sample.json
docs/config.md
src/vector/app.js
src/vector/initial-load.ts
src/vector/jitsi/index.html
src/vector/jitsi/index.scss
src/vector/jitsi/index.ts
webpack.config.js

Effectively fixes https://github.com/vector-im/riot-web/issues/11074
Effectively fixes https://github.com/vector-im/riot-web/issues/7112
Fixes https://github.com/vector-im/riot-web/issues/6930
Fixes Jitsi widgets not working for guests (https://github.com/vector-im/riot-web/issues/8933)
Fixes https://github.com/vector-im/riot-web/issues/5048
**Requires https://github.com/matrix-org/matrix-react-sdk/pull/4234**
Previously we were relying on an integration manager to be defined, functional, and alive in order to join Jitsi calls. This commit changes this so we aren't reliant on an integration manager for Jitsi calls at all, and gives people the option of choosing a Jitsi server via the config.json.
This side is just the wrapper/shell: the logic is mostly in the react-sdk (to be linked via …

Use a local widget wrapper for Jitsi calls

---

scripts/docker-write-version.sh

This (should) fix the version script for Docker builds by testing the branch
with a regex instead of single char glob.
Fixes https://github.com/vector-im/riot-web/issues/12777

Fix version for Docker builds

---

src/vector/jitsi/index.ts

We should always have conference information, and if we don't then the widget is invalid.
Soft dependency on https://github.com/matrix-org/matrix-react-sdk/pull/4252

Remove useless app preloading from Jitsi widget wrapper

---

src/vector/jitsi/index.ts

Reverts vector-im/riot-web#12836
Turns out we need the config information to be able to load the Jitsi widget info. Will find a better solution.

Revert "Remove useless app preloading from Jitsi widget wrapper"

---

src/vector/jitsi/index.ts

Fixes https://github.com/vector-im/riot-web/issues/12839 by not using the app load order that doesn't detect the right platform anyways.
**Requires https://github.com/matrix-org/matrix-react-sdk/pull/4266**

Fix Jitsi wrapper being large by getting the config from elsewhere

---

src/vector/platform/WebPlatform.js

Let the notifications go into browser/OS notification trays so users can click on them from there if they miss the initial notification. Modern Chrome uses OS notifications so the user is in control of the the notification with the OS. This also aligns with the Electron platform version.

Don't immediately remove notifications from notification trays

---

src/vector/jitsi/index.ts

See diff for info. This keeps tripping people up.
We use the fragment to avoid sending conference information to the web server where possible.

Add a console warning that errors from Jitsi Meet are fine

---

docs/jitsi-dev.md
docs/jitsi.md

**Review with https://github.com/matrix-org/matrix-react-sdk/pull/4348**

Mention Jitsi support at the .well-known level in Jitsi docs

---

package.json
scripts/build-jitsi.sh

On a freshly install of the development environment, the build:jitsi try to create a file in ./webapp with the cURL command. However, ./webapp folder doesn't exist and the build script crash. 
```
$ curl -s https://jitsi.riot.im/libs/external_api.min.js > ./webapp/jitsi_external_api.min.js
2020-04-10 13:41:05.148 [res] /bin/sh: ./webapp/jitsi_external_api.min.js: No such file or direc
error Command failed with exit code 1.
```
This patch makes sure the appropriate folder is created if it doesn't already exist

fix build:jitsi scripts crash caused by a missing folder

---

electron_app/src/electron-main.js
src/i18n/strings/en_EN.json
src/vector/platform/ElectronPlatform.js

Fixes https://github.com/vector-im/riot-web/issues/12920
Requires https://github.com/matrix-org/matrix-react-sdk/pull/4392
Requires https://github.com/vector-im/riot-desktop/pull/68
Matches browser default shortcuts for forward/back and also Slack

Add riot-desktop shortcuts for forward/back matching browsers&slack

---

docs/labs.md

The documentation mentions that Labs features can be manipulated by
opening the Settings menu and selecting Labs.  This feature is normally
disabled, so for most users this is not the case.
Add a link to the `config.md` file and a note that the Labs features
must be enabled in order to manipulate them.
Fixes https://github.com/vector-im/riot-web/issues/13148

docs: labs: add a pointer to config.md

---

README.md

On Linux, it's common that the system limit the number of files that can be monitored. If
this limit is too low then the build script will fail.
Signed-off-by: Danny Colin <contact@dannycolin.com>

Add instruction to resolve the inotify watch limit issue

---

docs/config.md
src/components/views/auth/VectorAuthPage.js

This will allow the administrator of a Riot Web instance to set `welcomeBackgroundUrl` to an array. If they do, which one is displayed will be chosen at random on a per-visit basis. This allows them to add some variety to their branding.
**NOTE:** I was informed by [t3chguy that `Array.isArray()` is preferable to `instanceof Array`, so I went with that](https://iddqd.social/_matrix/media/r0/download/iddqd.social/uEtrywuxrjUbBfDAZxukSEaM). Any other critiques of my code are welcome.
Signed-off-by: Bob Arctor neetzsche@protonmail.com

Allow Riot Web to randomly pick welcome backgrounds

---

src/@types/global.d.ts

Clean-up for after https://github.com/matrix-org/matrix-react-sdk/pull/4443

Use matrix-react-sdk type extensions as a base

---

docs/jitsi.md

We should remove this at release time, but if we forget it should be vaguely worded well enough.
People keep assuming it'll just work even though the feature hasn't launched yet. The original theory was that a release was around the corner, but it's since been pushed back several times.

Clarify that the .well-known method for Jitsi isn't available yet

---

docs/feature-flags.md

This adds further detail around the various additional release channels we have
for desktop. It also expands on the current state of enabling a feature by
default.

Expand feature flag docs to cover additional release channels

---

docs/labs.md
riot.im/develop/config.json

This includes changes from a previous PR which hadn't made it over to release yet.
See https://github.com/matrix-org/matrix-react-sdk/pull/4488

Remove feature flag docs from docs on release

---

src/vector/platform/WebPlatform.js

This tweak's the OS name in the default device name for macOS devices to match
Apple's current branding.
Fixes https://github.com/vector-im/riot-web/issues/13459

Tweak default device name on macOS

---

res/decoder-ring/datatypes.js
res/decoder-ring/decoder.js
res/decoder-ring/index.html
scripts/copy-res.js
webpack.config.js

Land second
fixes: https://github.com/vector-im/riot-web/issues/13359

Developer tool: convert rageshake error locations back to sourcecode locations

---

electron_app/riot.im/config.json
riot.im/app/config.json
riot.im/develop/config.json

The cross-signing feature flag was changed to a setting, so these values are
outdated and can be removed.
See also https://github.com/matrix-org/matrix-react-sdk/pull/4416

Remove unused feature flag from config

---

src/vector/index.html

If our CSP was less strict or `prefetch-src` better supported then we could use real prefetches which would have the correct network priority set but alas we cannot yet.
Fixes https://github.com/vector-im/riot-web/issues/10828

Prefetch the formatting button mask svg images

---

README.md

The link before just sent you to the matrix sdk repository, now it sends you to the development section.

Added Anchor Link to the development of matrix sdk

---

src/vector/index.html

Google Translate manipulates the DOM which is fundamentally incomaptible with
React and causes exceptions to be thrown when React tries to manipulate the DOM
based on its VDOM and the DOM methods throw exceptions because the DOM structure
is not what React thinks it is.
Riot has an i18n system, although it doesn't cover all strings and all languages.
Fixes https://github.com/vector-im/riot-web/issues/13557
Alternative to: https://github.com/vector-im/riot-web/pull/13658

Add notranslate class to matrixchat to prevent translation by Google Translate

---

src/vector/platform/ElectronPlatform.js

Fixes https://github.com/vector-im/riot-web/issues/12155
Requires https://github.com/matrix-org/matrix-react-sdk/pull/4585

Pass screenAfterLogin through SSO in the callback url

---

webpack.config.js

> Note, that you must set this plugin before postcss-simple-vars and postcss-nested.
https://github.com/postcss/postcss-mixins

Fix postcss order to allow mixin variables to work

---

config.sample.json
docs/labs.md
riot.im/develop/config.json

Impelemts setting for https://github.com/matrix-org/matrix-react-sdk/pull/4531

Add labs flag for alternate message layouts

---

config.sample.json
docs/labs.md
riot.im/develop/config.json

Reverts vector-im/riot-web#13351
Replacement of https://github.com/vector-im/riot-web/pull/13199
**For https://github.com/matrix-org/matrix-react-sdk/pull/4424**
*This has already been approved, pending review of the react-sdk side*

Add font scaling labs setting.

---

src/@types/global.d.ts
src/vector/platform/ElectronPlatform.tsx
src/vector/platform/VectorBasePlatform.ts
src/vector/platform/WebPlatform.ts

~~Requires https://github.com/matrix-org/matrix-react-sdk/pull/4614~~
Supersedes https://github.com/vector-im/riot-web/pull/13737
Subset of https://github.com/matrix-org/matrix-react-sdk/pull/4609

Convert platforms to Typescript

---

yarn.lock

This is needed to resolve conflicts between the  @types/react inside @types/react-dom and the top level @types/react.
Needed to land https://github.com/matrix-org/matrix-react-sdk/pull/4635/

Fix @types/react conflict in matrix-react-sdk

---

src/vector/platform/ElectronPlatform.tsx
src/vector/platform/VectorBasePlatform.ts
src/vector/platform/WebPlatform.ts

Fixes https://github.com/vector-im/riot-web/issues/13861
Requires https://github.com/matrix-org/matrix-react-sdk/pull/4668

Give contextual feedback for manual update check instead of banner

---

src/vector/platform/ElectronPlatform.tsx
src/vector/platform/VectorBasePlatform.ts
src/vector/platform/WebPlatform.ts

Fixes https://github.com/vector-im/riot-web/issues/11042
Staged atop https://github.com/vector-im/riot-web/pull/13862
Requires https://github.com/matrix-org/matrix-react-sdk/pull/4669
Later will defer it until the first of the following:
+ tomorrow morning (8am)
+ the user clicks `Check for update` in settings
+ an even newer update comes out

Allow deferring of Update Toast until the next morning

---

res/welcome.html
src/i18n/strings/en_EN.json

Fixes https://github.com/vector-im/riot-web/issues/13784

Get rid of welcome.html's Chat with Riot Bot button

---

src/vector/platform/ElectronPlatform.tsx
src/vector/platform/VectorBasePlatform.ts

due to fragmentAfterLogin going back to `#/login` and https://github.com/vector-im/riot-web/issues/11643
Requires https://github.com/matrix-org/matrix-react-sdk/pull/4685

Fix login loop where the sso flow returns to `#/login`

---

src/vector/platform/ElectronPlatform.tsx

The react-sdk side of this can be found at https://github.com/matrix-org/matrix-react-sdk/pull/4788, while the Riot-desktop side is at https://github.com/vector-im/riot-desktop/pull/102.
Requires a Seshat release with https://github.com/matrix-org/seshat/pull/67.

ElectronPlatform: Add support to set and get the index user version.

---

docs/theming.md

Changes are in https://github.com/matrix-org/matrix-react-sdk/pull/4814

Document fonts in custom theme

---

docs/labs.md
riot.im/develop/config.json

See https://github.com/matrix-org/matrix-react-sdk/pull/4919

Update documentation and remove labs flag for new room list

---

config.sample.json
docs/labs.md
riot.im/develop/config.json

Just a quick fire pr to remove font-scaling from labs. No review requested yet as font-scaling needs to be reviewed after the new room list lands.
requires: https://github.com/matrix-org/matrix-react-sdk/pull/4899
requires: https://github.com/vector-im/riot-desktop/pull/112

Remove font scaling from labs

---

src/vector/platform/ElectronPlatform.tsx

Fixes https://github.com/vector-im/riot-web/issues/14517

Use the right protocol for SSO URLs

---

docs/config.md

See [this comment[(https://github.com/vector-im/riot-web/pull/14581#discussion_r461553693).

Fix typo in https://

---

src/vector/mobile_guide/index.js

Related to https://github.com/vector-im/riot-web/issues/14751
Should not be merged until the URL exists, ops should get to it soon.

Update mobile config intercept URL

---

Dockerfile

History is at: https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$4Se7Bpo2lakGZLGxnsXA8WQlCHtMLrJRs8qiNshzBKA?via=matrix.org&via=privacytools.io&via=mozilla.org
(Transcript below)
In short, trying to build an Arm binary of the Docker image for riot-web on either a Raspberry Pi 3 or a MacBook via Docker buildx, there are no pre-built binaries available for `canvas`, and building it causes `webpack` to run out of memory. These two commits seem to rectify these issues.
Chat transcript
---
Matt Cengia (he/him/his)
> Hey folks, I'm trying to get Riot installed, via Docker, onto a Raspberry Pi 3. When I try to build the Docker image, either on my RPi, or on an emulated Arm container on my Mac via docker buildx, I get an error about 'canvas'. I'm building v1.6.7, and when I try to build the …

Fix arm docker build

---

config.sample.json
docs/config.md
docs/feature-flags.md
element.io/app/config.json
element.io/develop/config.json

**Requires https://github.com/matrix-org/matrix-react-sdk/pull/5124**
See https://github.com/matrix-org/matrix-react-sdk/pull/5124

Settings v3: Update documentation and configs for new feature flag behaviour

---

src/async-components/structures/CompatibilityView.tsx
src/vector/mobile_guide/index.html
src/vector/static/incompatible-browser.html

The old app-id shows a big warning that it will no longer be maintained,
so avoid linking to it (especially for self-hosted element-web installs).
Signed-off-by: Christoph Settgast <csett86@web.de>

Link to Element in F-Droid as well

---

README.md

There still one or two links pointing to Riot specific stuff, as there exists no equivalent for Element, at least as far as i know.
These are:
- [https://packages.riot.im/riot-release-key.asc](https://github.com/Weasy666/element-web/blame/develop/README.md#L49)
- [https://matrix.to/#/#riot-dev:matrix.org](https://github.com/Weasy666/element-web/blame/develop/README.md#L195)
- [https://translate.riot.im/engage/element-web/?utm_source=widget](https://github.com/Weasy666/element-web/blame/develop/README.md#L339)

Update links in README.md to point to Element

---

docs/labs.md

**Requires https://github.com/matrix-org/matrix-react-sdk/pull/5133**
Per the diff, we are embarking on a prototyping stage for communities v2 and are not currently accepting issues relating to the functionality.
A "compatible homeserver" is one which manages several bits of the functionality we are prototyping outside of Element.

Add docs for communities v2 prototyping feature flag

---

docs/e2ee.md

This adds notes on configuring the new `.well-known` setting to require Element
users to set up secure backup before continuing into the app.
Part of https://github.com/vector-im/element-web/issues/14954
Used by https://github.com/matrix-org/matrix-react-sdk/pull/5130

Document .well-known E2EE secure backup setting

---

package.json
src/vector/jitsi/index.html
src/vector/jitsi/index.ts
yarn.lock

This PR adds the Element Web parts for supporting Synapse OpenID token based auth for Jitsi widgets. This auth enables locking Jitsi widgets to particular homeserver users and rooms. The whole flow is described here: https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification
The auth flow is only used when the Jitsi server has a well-known file indicating the requirement of auth.
Blocked by:
* React-SDK PR side for the Jitsi widget code PR: https://github.com/matrix-org/matrix-react-sdk/pull/5173
* https://github.com/matrix-org/matrix-react-sdk/pull/5172 
Replaces #15111 (to match react-sdk branch)

Support usage of Jitsi widgets with "openidtoken-jwt" auth 

---

CONTRIBUTING.rst
scripts/fetch-develop.deps.sh

Also cleans up a Riot reference as well
Part of https://github.com/vector-im/element-web/issues/15098

Remove references to Travis CI

---

docs/e2ee.md

Part of https://github.com/vector-im/element-web/issues/15238
Relates to https://github.com/matrix-org/matrix-react-sdk/pull/5242

Document config for preferring Secure Backup setup methods

---

package.json
res/sw.js
scripts/copy-res.js
src/vector/index.html
src/vector/index.ts
webpack.config.js
yarn.lock

Service Worker
Fixes https://github.com/vector-im/element-web/issues/12591

Replace dummy sw.js with pre-caching and runtime-caching workbox SW

---

package.json

This just fixes logging when using `yarn start` to have the right prefix

Rebrand the webpack pipeline for Element

---

src/vector/jitsi/index.ts

See https://github.com/matrix-org/matrix-react-sdk/pull/5223

Jitsi widget wrapper updates for hangup button

---

src/vector/jitsi/index.html
src/vector/jitsi/index.scss

We think users will be expecting to follow a series of icons into their conference, so we'll remind them here of what is going on with a giant icon.
This does not change depending on the call type because the jitsi widget doesn't understand the call type anyways - it's always a video conference.

Give the Jitsi widget an icon to help with discovery

---

package.json
res/sw.js
scripts/copy-res.js
src/vector/index.html
src/vector/index.ts
src/vector/platform/WebPlatform.ts
webpack.config.js
yarn.lock

Due to how we handle updates and versioning it became quite problematic, the solution will need more experimentation.
Reverts https://github.com/vector-im/element-web/pull/15196 https://github.com/vector-im/element-web/pull/15271 https://github.com/vector-im/element-web/pull/15345
`sw.js` will be registered over `service-worker.js`, replacing it.

Remove workbox

---

config.sample.json

`riot-bot` is no longer recommended these days, and it causes confusion to have
in the sample config.
Fixes https://github.com/vector-im/element-web/issues/15357

Remove riot-bot from sample config

---

docs/customisations.md
src/customisations/README.md

https://github.com/matrix-org/matrix-react-sdk/pull/5327 adds a concept of
"customisation points" to keep custom functionality contained. This adds some
general guidance on how to use them.

Document customisation points

---

package.json
src/vector/jitsi/index.ts
yarn.lock

As part of changing to the `events` package, the API surface changed slightly.
Depends on https://github.com/matrix-org/matrix-widget-api/pull/6
Related to https://github.com/vector-im/element-web/issues/15493

Adjust for new widget messaging APIs

---

release.sh

In practice, the upgrades are always fine, and this editor prompt just adds
delays.

Skip editor confirmation of upgrades
