element-hq/element-web

- src/skins/vector/views/molecules/MessageContextMenu.js
> Hook up delete button on contextual menu (#56)

- src/skins/vector/views/templates/Register.js
Requires react SDK PR https://github.com/matrix-org/matrix-react-sdk/pull/23
Fixes #176
> Fix #176 Password complexity error message

- src/skins/vector/views/organisms/Notifier.js
Fixes #159. This is the same fix we applied to angular to fix this problem in SYWEB-21.
> Add a tag to notifications so they can clobber.

- src/skins/vector/views/pages/MatrixChat.js
This fixes #26 and #27. Requires https://github.com/matrix-org/matrix-react-sdk/pull/24
> Add linkify handlers

- src/controllers/molecules/voip/CallView.js
- src/skins/vector/views/molecules/RoomHeader.js
- src/skins/vector/views/molecules/voip/VideoView.js
> Exit full screen programatically when the remote side hangs up

- src/vector/index.js
Update the CAS login flow to allow the HS to do all the interaction with CAS and use the HS token login
> Replace CAS login with token login

- package.json
- src/controllers/organisms/RoomList.js
A quick and hacky fix to issue #169.
> Don't mark rooms as unread on m.room.member changes

- src/skins/vector/css/common.css
One line commit to fix and then separate commit for legibility.
> Sort out dialog z index so read receipts avatars are behind the dialog background

- src/vector/index.js
Required for https://github.com/matrix-org/matrix-react-sdk/pull/59
> Pass through the starting query params from the URL

- src/components/structures/LeftPanel.js
- src/components/structures/RoomSubList.js
- src/skins/vector/css/molecules/voip/IncomingCallbox.css
- vector/index.html
and fix various issues with when the video preview and callview are shown
> position the inbound call box correctly

- src/skins/vector/img/leave.svg
> fix leave.svg so that it can be tinted

- src/skins/vector/css/matrix-react-sdk/views/rooms/RoomPreviewBar.css
Requires https://github.com/matrix-org/matrix-react-sdk/pull/86 - sorta mostly matches Zeplin invite preview bar.
> Add css for room preview bar.

- src/skins/vector/css/matrix-react-sdk/views/rooms/MemberTile.css
- src/skins/vector/css/matrix-react-sdk/views/rooms/PresenceLabel.css
CSS for the fix for https://github.com/vector-im/vector-web/issues/613
See https://github.com/matrix-org/matrix-react-sdk/pull/88
> CSS for email invite memberlist fix

- src/skins/vector/css/matrix-react-sdk/structures/RoomView.css
> Shift read marker down by 5px

- src/skins/vector/css/matrix-react-sdk/views/avatars/BaseAvatar.css
For https://github.com/matrix-org/matrix-react-sdk/pull/95
> CSS for BaseAvatar

- src/components/views/settings/Notifications.js
https://github.com/vector-im/vector-web/issues/692
In order to do that, the rules definitions have been updated to support "dont_notify" hs default push rules.
> Added notif settings for "Messages sent by bot" 

- src/component-index.js
- src/components/views/globals/GuestWarningBar.js
- src/skins/vector/css/matrix-react-sdk/structures/MatrixChat.css
- src/skins/vector/css/matrix-react-sdk/structures/RoomView.css
- src/skins/vector/css/vector-web/views/globals/GuestWarningBar.css
So we can use it for a guest access warning
> CSS that changes the connection lost bar into a more general 'warning bar'

- src/components/structures/RoomDirectory.js
Requires https://github.com/matrix-org/matrix-react-sdk/pull/129
> Don't trigger room join from room directory: always peek / show join prompt bar

- src/component-index.js
- src/components/views/globals/NewVersionBar.js
- src/vector/index.js
- src/vector/updater.js
Polls every 10 minutes then shows a big bar (like desktop notif bar) if there is a new version. Requires the sister PR https://github.com/matrix-org/matrix-react-sdk/pull/133 in order for it to display the bar.
> Add a version update checker and NewVersionBar to show on the UI.

- src/components/structures/RightPanel.js
Requires https://github.com/matrix-org/matrix-react-sdk/pull/139
Fixes https://github.com/vector-im/vector-web/issues/779
> Rate limit UI updates to avoid browser death

- src/skins/vector/css/matrix-react-sdk/structures/RoomView.css
- src/skins/vector/css/matrix-react-sdk/views/rooms/TopUnreadMessagesBar.css
- src/skins/vector/img/scrollup.svg
Support for adding a new 'Scroll up' bar in react-sdk, as per https://github.com/matrix-org/matrix-react-sdk/pull/160.
> Styling and imgs to support new read_marker semantics

- vector/index.html
Signed-off-by: Andrew Johnson <ajohnson@draster.com>
> Added audio/source tags for message notifications.

- src/components/views/globals/GuestWarningBar.js
Revert https://github.com/vector-im/vector-web/issues/818 now that https://github.com/vector-im/vector-web/issues/759 is fixed.
> Re-enable upgrade registration.

- vector/index.html
Identical to https://github.com/vector-im/vector-web/pull/1098
Sister PR of https://github.com/matrix-org/matrix-react-sdk/pull/194
> Add audio tag for message notifications

- src/components/views/settings/Notifications.js
- src/skins/vector/css/vector-web/views/settings/Notifications.css
Expose the enableAudioNotifications setting in the user settings panel.
Requires https://github.com/matrix-org/matrix-react-sdk/pull/207
> Add setting for audio notifications

- src/components/views/globals/GuestWarningBar.js
Has to be synced with https://github.com/matrix-org/matrix-react-sdk/pull/220
> use new start_login_from_guest dispatch for cancellable logins from guest accounts

- src/components/views/globals/GuestWarningBar.js
reverts start_login_from_guest stuff
> fix notif spam when logging in from a guest session by correctly logging out first.

- src/vector/index.js
It looks like % characters in the hash-fragment are meant to be interpreted as
a URI-encoding, so we should decode them.
(Fixes https://github.com/vector-im/vector-web/issues/1221)
> URI-decode the hash-fragment

- src/components/structures/RoomDirectory.js
SimpleRoomHeader and RoomHeader are now separate things
(https://github.com/matrix-org/matrix-react-sdk/pull/252), so update Vector
accordingly.
> RoomDirectory: use SimpleRoomHeader instead of RoomHeader

- src/skins/vector/css/matrix-react-sdk/structures/RoomStatusBar.css
Depends upon https://github.com/matrix-org/matrix-react-sdk/pull/251
> Prettier, animated placeholder :D

- src/components/views/elements/ImageView.js
- src/skins/vector/css/matrix-react-sdk/views/rooms/MemberInfo.css
> Show full-size avatar on MemberInfo avatar click

- src/components/views/settings/Notifications.js
- src/notifications/NotificationUtils.js
- src/notifications/PushRuleVectorState.js
- src/notifications/VectorPushRulesDefinitions.js
- src/notifications/index.js
- test/all-tests.js
- test/unit-tests/notifications/PushRuleVectorState-test.js
Factor some things out of the mega Notifications component, and add a dummy
unit test to show willing
> Start Notifications component refactor

- src/components/views/settings/Notifications.js
instead take brand from a prop
Requires https://github.com/matrix-org/matrix-react-sdk/pull/299
> Don't use SdkConfig

- src/skins/vector/css/matrix-react-sdk/views/rooms/EventTile.css
- src/skins/vector/css/matrix-react-sdk/views/rooms/MemberDeviceInfo.css
Adds the CSS required to support https://github.com/matrix-org/matrix-react-sdk/pull/300
> CSS support for device verification

- package.json
- src/skins/vector/css/matrix-react-sdk/views/elements/RichText.css
- src/skins/vector/css/matrix-react-sdk/views/rooms/MessageComposer.css
- src/skins/vector/css/vector-web/structures/RoomDirectory.css
- src/vector/index.js
Styling for matrix-org/matrix-react-sdk#292, should be ready to merge as-is.
> Rich Text Editor

- karma.conf.js
As we now use draft-js: https://github.com/facebook/fbjs/issues/133#event-617440260
> Fix karma tests

- src/skins/vector/css/matrix-react-sdk/views/rooms/MemberDeviceInfo.css
(support for https://github.com/matrix-org/matrix-react-sdk/pull/315)
> CSS for unverify button

- src/skins/vector/css/matrix-react-sdk/views/rooms/MemberDeviceInfo.css
- src/skins/vector/css/matrix-react-sdk/views/rooms/MemberInfo.css
A bunch of updates to the device info:
* format as a table
* make the buttons green, because the old way was super confusing
* instead make the status indicator red/orange/green.
> CSS for device blocking

- src/skins/vector/css/matrix-react-sdk/views/rooms/EntityTile.css
Requires https://github.com/matrix-org/matrix-react-sdk/pull/342
As per https://github.com/vector-im/vector-web/issues/1740
> CSS for offline user colours

- package.json
> Bump dependency versions

- src/skins/vector/css/common.css
- src/skins/vector/css/matrix-react-sdk/views/settings/DevicesPanel.css
CSS for https://github.com/matrix-org/matrix-react-sdk/pull/370
> CSS for device management UI

- src/skins/vector/css/matrix-react-sdk/views/messages/UnknownBody.css
> Fix UnknownBody styling for #1901

- src/skins/vector/css/common.css
- src/skins/vector/css/matrix-react-sdk/structures/UserSettings.css
(Inc some generic CSS for error & danger fields)
> CSS for deactivate account dialog

- test/app-tests/joining.js
ReplaceUsingAccessToken was, uh, replaced with replacedUsingCreds
> Fix unit tests

- package.json
- src/vector/index.js
Pass a default device name into react-sdk
(builds on https://github.com/matrix-org/matrix-react-sdk/pull/413)
> Make up a device display name

- README.md
(Note that this is a PR against master, since people tend to read the README on master)
> Update encryption info in README

- src/skins/vector/css/matrix-react-sdk/views/rooms/Autocomplete.css
Implements most of vector-im/vector-web#1761
> Update autocomplete design

- package.json
Olm 1.0.0 made broken OlmAccounts.
> Bump to olm 1.1.0

- src/skins/vector/css/matrix-react-sdk/views/rooms/MemberDeviceInfo.css
- src/skins/vector/css/matrix-react-sdk/views/rooms/MemberInfo.css
CSS to make the deviceinfo stuff a little bit closer to the designs
> e2e device CSS

- src/components/views/context_menus/RoomTagContextMenu.js
- src/skins/vector/img/icon_context_person.svg
- src/skins/vector/img/icon_context_person_on.svg
- src/skins/vector/img/icons-people.svg
on context menu
Requires https://github.com/matrix-org/matrix-react-sdk/pull/449
https://github.com/vector-im/vector-web/issues/2099
> Support toggling DM status of rooms

- src/components/structures/BottomLeftMenu.js
- src/skins/vector/css/vector-web/structures/LeftPanel.css
This should close #2135
Signed-off-by: William Wragg wm.wragg@gmail.com
> Added back the Directory listing button, with new tootlip

- package.json
Depends on matrix-org/matrix-js-sdk#205
> Update the version of olm to 1.3.0

- src/components/views/settings/IntegrationsManager.js
- src/skins/vector/css/matrix-react-sdk/views/settings/IntegrationsManager.css
Reverts vector-im/vector-web#2280
Because it is broken and doesn't show the full iframe.
> Revert "improve lipstick and support scalar logout"

- src/components/structures/RoomDirectory.js
- src/skins/vector/css/matrix-react-sdk/views/elements/DirectorySearchBox.css
- src/skins/vector/css/vector-web/structures/RoomDirectory.css
- src/skins/vector/css/vector-web/views/directory/NetworkDropdown.css
- src/skins/vector/img/icon-return.svg
- test/app-tests/joining.js
Vector side of https://github.com/matrix-org/matrix-react-sdk/pull/496/files
Requires https://github.com/matrix-org/matrix-react-sdk/pull/496
> Directory search join button

- package.json
Fixes https://github.com/vector-im/vector-web/issues/2357
In addition, https://github.com/matrix-org/matrix-react-sdk/pull/500 will make sure failures like this are obvious.
> Update linkify version

- src/components/structures/RoomDirectory.js
Fixes https://github.com/vector-im/vector-web/issues/2250
> Room directory: indicate when there are no results

- src/skins/vector/css/vector-web/views/directory/NetworkDropdown.css
Dropdown resized by 2px when opened
> Prevent network dropdown resizing slightly

- package.json
To pull in https://github.com/SoapBox/linkifyjs/pull/166
Fixes https://github.com/vector-im/vector-web/issues/2376
> Update to linkify 2.1.3

- src/components/structures/RoomDirectory.js
Also add more null checking.
Fixes https://github.com/vector-im/vector-web/issues/2435
> Fix join button for 'matrix' networks

- src/skins/vector/css/common.css
Some dialogs put a spinner in the button... need to line them up.
> Centre images in dialog buttons

- src/vector/index.js
This allows Vector to load from file:// URIs without breaking if
there is no config file (because we explicitly look for 404s, and
file:// URIs don't return 404s).
> Use the defaults if given a blank config file

- src/vector/index.js
We should still error if given a 5xx with an empty body.
> Better support no-config when loading from file

- src/skins/vector/css/matrix-react-sdk/views/elements/MemberEventListSummary.css
matrix-org/matrix-react-sdk#544
> Add CSS for mlist truncation

- src/vector/platform/ElectronPlatform.js
- src/vector/platform/WebPlatform.js
Support for https://github.com/matrix-org/matrix-react-sdk/pull/542
> Support for get_app_version

- src/vector/platform/WebPlatform.js
Fixes https://github.com/vector-im/vector-web/issues/2593
> Add a cachebuster to /version

- webpack.config.js
Fixes https://github.com/vector-im/vector-web/issues/2601
> Make sure we only pack one copy of react-dom

- scripts/package.sh
Fixes https://github.com/vector-im/vector-web/issues/2607
> Include config.sample.json in dist tarball

- config.sample.json
So the join button works for them
> Add Freenode & Mozilla domains

- src/skins/vector/css/matrix-react-sdk/views/rooms/MemberDeviceInfo.css
CSS for https://github.com/matrix-org/matrix-react-sdk/pull/574
> CSS updates for s/block/blacklist for e2e

- package.json
Unsure whether we want to go through doing a complete
s/vector/riot/ - I'm not sure there's a whole lot of point.
> Update name & repo to reflect renamed repository

- release_config.yaml
Read by release script in js-sdk
> Add signing ID in release_config.yaml

- src/skins/vector/css/matrix-react-sdk/structures/UserSettings.css
Requires https://github.com/matrix-org/matrix-react-sdk/pull/597
> CSS for the delete threepid button

- README.md
This is based on what I had to do to get the desktop app running, as per the advice in https://github.com/vector-im/riot-web/issues/2792. I am not familiar with `npm`, so please change this pull request if there is a more appropriate way of achieving the same result.
> Update desktop build instructions fixes #2792

- electron/src/electron-main.js
- src/vector/platform/ElectronPlatform.js
- src/vector/platform/WebPlatform.js
Requires https://github.com/matrix-org/matrix-react-sdk/pull/608
Requires https://github.com/matrix-org/matrix-js-sdk/pull/317
> Enable screen sharing easter-egg in desktop app

- electron/src/vectormenu.js
Let electron handle it rather than doing it ourselves
> Use the role for 'toggle dev tools'

- .travis.yml
- scripts/jenkins.sh
> Build the js-sdk in the CI script

- src/skins/vector/css/matrix-react-sdk/views/elements/DirectorySearchBox.css
- src/skins/vector/css/matrix-react-sdk/views/rooms/RoomTile.css
- src/skins/vector/css/vector-web/fonts.css
- src/skins/vector/css/vector-web/views/elements/ImageView.css
- webpack.config.js
Hopefully this will allow some interesting deployment shenanigans.
> Add another layer of directory to webpack chunks

- karma.conf.js
* allow the imgs to be served from the karma server to avoid 404s
* Use the source-map-loader for js
> A couple of tweaks to the karma config

- src/skins/vector/css/matrix-react-sdk/structures/_RoomStatusBar.scss
Requires https://github.com/matrix-org/matrix-react-sdk/pull/631
Fixes https://github.com/vector-im/riot-web/issues/2237
Looks like:
> CSS for avatars that appear when users are typing

- .eslintignore
- .eslintrc.js
- package.json
- test/.eslintrc.js
An early start that gets some linting in place (basically https://github.com/matrix-org/matrix-react-sdk/pull/634 for riot-web).
> Add eslint config

- src/components/structures/RightPanel.js
- src/components/structures/SearchBox.js
- src/skins/vector/css/vector-web/structures/_RightPanel.scss
should fix https://github.com/vector-im/riot-web/issues/2827
> make TopRightMenu more intuitive

- package.json
Looks like this is causing pickle errors on packaged builds.
> Bump olm version

- src/skins/vector/css/_components.scss
- src/skins/vector/css/matrix-react-sdk/views/dialogs/_ConfirmUserActionDialog.scss
For https://github.com/matrix-org/matrix-react-sdk/pull/694
> CSS for kick/ban confirmation dialog

- src/skins/vector/css/matrix-react-sdk/views/rooms/_RoomSettings.scss
For https://github.com/matrix-org/matrix-react-sdk/pull/698
> CSS for un-ban button in RoomSettings

- src/skins/vector/css/matrix-react-sdk/views/dialogs/_ConfirmUserActionDialog.scss
For https://github.com/matrix-org/matrix-react-sdk/pull/710
> CSS for ban / kick reason prompt

- src/components/views/settings/Notifications.js
- src/notifications/VectorPushRulesDefinitions.js
For those unfortunate people that get pinged constantly.
Fixes https://github.com/vector-im/riot-web/issues/2773
> Expose notification option for username/MXID

- src/vector/index.js
Passes in a function to make a register URL rather than just
passing in the URL base
Requires https://github.com/matrix-org/matrix-react-sdk/pull/729
Requires https://github.com/matrix-org/matrix-js-sdk/pull/380
> Support InteractiveAuth based registration

- src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss
For https://github.com/matrix-org/matrix-react-sdk/pull/739
> CSS for redacted EventTiles

- src/components/views/context_menus/MessageContextMenu.js
- src/components/views/elements/ImageView.js
Closes #277
Closes #1805
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/763
> Confirm redactions with a dialog

- src/skins/vector/css/_components.scss
- src/skins/vector/css/matrix-react-sdk/structures/login/_Login.scss
- src/skins/vector/css/matrix-react-sdk/views/elements/_Dropdown.scss
- src/skins/vector/css/matrix-react-sdk/views/login/_InteractiveAuthEntryComponents.scss
- test/app-tests/loading.js
Changes from https://github.com/vector-im/riot-web/pull/3381
> Support for phone number registration/signin, mk2

- src/skins/vector/css/matrix-react-sdk/structures/_UserSettings.scss
This is based off the branch with msisdn support, so probably makes sense to leave reviewing this until after that's merged. [Now merged]
> CSS for adding phone number in UserSettings

- test/app-tests/joining.js
- test/app-tests/loading.js
This is an attempt to reduce flakiness (see https://github.com/matrix-org/matrix-react-sdk/pull/781 also)
> Fix tests to reflect recent changes

- src/skins/vector/css/matrix-react-sdk/views/rooms/_TopUnreadMessagesBar.scss
see matrix-org/matrix-react-sdk#789
> Adjust CSS for matrix-org/matrix-react-sdk#789

- src/skins/vector/css/_components.scss
- src/skins/vector/css/matrix-react-sdk/views/messages/_MEmoteBody.scss
For https://github.com/matrix-org/matrix-react-sdk/pull/791
> Add CSS to make Emote sender cursor : pointer

- src/vector/platform/ElectronPlatform.js
- src/vector/platform/WebPlatform.js
Implement reload in Platforms to support
https://github.com/matrix-org/matrix-react-sdk/pull/798
Fixes https://github.com/vector-im/riot-web/issues/3597
> Make the clear cache button work on desktop

- src/components/views/dialogs/BugReportDialog.js
- src/vector/submit-rageshake.js
There are a few phases to doing a rageshake, so it's nice to get some feedback.
Also, load submit-rageshake asynchronously.
Also, fix some callbacks to check the unmounted guard.
Builds on top of https://github.com/vector-im/riot-web/pull/3646. The actual changes are 7449137, 43c2d87 and a51898c.
> Progress updates for rageshake uploads

- package.json
- src/vector/submit-rageshake.js
Builds on top of https://github.com/vector-im/riot-web/pull/3646. The actual changes are in eae7e06.
> Compress uploaded rageshakes.

- src/components/structures/SearchBox.js
Cancel quick-search on Escape, clearing it and returning focus to composer
for #3671
> Cancel quicksearch on ESC

- electron/src/electron-main.js
Useful for autostarting Riot hidden
for #3167 
> add command line arg (--hidden) for electron app

- src/vector/platform/ElectronPlatform.js
fixes #3292 for all cases apart from Minimized (maximized) in Linux. In Windows this works and will be reported upstream in electron.
> Electron forgets it was maximized when you click on a notification

- src/skins/vector/css/matrix-react-sdk/structures/_UserSettings.scss
- src/skins/vector/css/matrix-react-sdk/structures/login/_Login.scss
matrix-org/matrix-react-sdk#833
> Modify CSS for matrix-org/matrix-react-sdk#833

- src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss
goes with https://github.com/matrix-org/matrix-react-sdk/pull/842
Fixes https://github.com/vector-im/riot-web/issues/3128
> Fix emote RRs alignment

- src/components/structures/RoomDirectory.js
- src/skins/vector/css/matrix-react-sdk/views/rooms/_RoomHeader.scss
- src/skins/vector/css/vector-web/structures/_RoomDirectory.scss
By adding an icon next to the title.
Requires https://github.com/matrix-org/matrix-react-sdk/pull/848
> Improve Room Directory Look & Feel

- src/skins/vector/css/_components.scss
- src/skins/vector/css/matrix-react-sdk/views/dialogs/_SetMxIdDialog.scss
Codep. : https://github.com/matrix-org/matrix-react-sdk/pull/849
> CSS for new SetMxIdDialog

- src/components/structures/RoomSubList.js
class seems to be referring to Modal but does not import it
> import Modal

- src/vector/submit-rageshake.js
> Include MXID and device id in rageshakes

- src/components/structures/RoomDirectory.js
This may have led to the room list not refreshing on error of deleting alias
> Fix scope of callback

- electron/package.json
got mismatched after a release -> develop merge
> match primary package.json

- config.sample.json
Not sure why this was like this - has vector.im/bugs *ever* worked?
> Fix bug report endpoint in config.sample.json.

- scripts/electron-package.sh
- scripts/issues-burndown.pl
- scripts/issues-no-state.pl
- scripts/jenkins.sh
- scripts/package.sh
user facing tarballs
for #3613
> change vector->riot on the surface

- src/components/views/dialogs/SetPasswordDialog.js
- src/components/views/globals/PasswordNagBar.js
- src/skins/vector/css/_components.scss
- src/skins/vector/css/vector-web/views/dialogs/_SetPasswordDialog.scss
Until https://github.com/matrix-org/matrix-react-sdk/pull/881, ChangePassword will not know about the cached password (so it won't hide "Current Password" yet).
> Implement dialog to set password

- src/skins/vector/css/matrix-react-sdk/structures/login/_Login.scss
(For login and registration) 
for https://github.com/matrix-org/matrix-react-sdk/pull/897
first iteration of fixing https://github.com/vector-im/riot-web/issues/3895
> CSS for putting country dd on same line as phone input

- electron_app/riot.im/config.json
Also remove unused room dir stuff
> Add config for riot-bot on desktop app build

- src/skins/vector/css/matrix-react-sdk/structures/login/_Login.scss
- src/skins/vector/css/matrix-react-sdk/views/elements/_Dropdown.scss
For https://github.com/vector-im/riot-web/issues/3895
> CSS for left_aligned Dropdowns, and adjustments for Country dd in Login

- test/app-tests/loading.js
Two changes:
1. wait longer for /sync to arrive in the loading tests, via an
`expectAndAwaitSync` method.
2. https://github.com/matrix-org/matrix-react-sdk/pull/773 made it possible for
MatrixChat to not show its syncing spinner despite `loading` being
false. Update `awaitSyncingSpinner` accordingly, so that it doesn't fail
when it happens to check MatrixChat at just taht moment.
> More riot-web test deflakification

- src/components/views/dialogs/SetPasswordDialog.js
Requires https://github.com/matrix-org/matrix-react-sdk/pull/915
> autoFocus new password input in SetPasswordDialog

- src/components/structures/BottomLeftMenu.js
- src/components/structures/RoomSubList.js
- src/skins/vector/css/_components.scss
- src/skins/vector/css/matrix-react-sdk/views/elements/_RoleButton.scss
- src/skins/vector/css/matrix-react-sdk/views/rooms/_RoomList.scss
- src/skins/vector/css/vector-web/structures/_LeftPanel.scss
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/924
Mostly commits from https://github.com/vector-im/riot-web/pull/3804 but also part of https://github.com/vector-im/riot-web/pull/3745 for the callouts
> Make left panel better for new users (mk III)

- karma.conf.js
- test/skin-sdk.js
- test/unit-tests/notifications/ContentRules-test.js
- test/unit-tests/notifications/PushRuleVectorState-test.js
As https://github.com/matrix-org/matrix-react-sdk/pull/931
> Don't include src in the test resolve root

- electron_app/src/electron-main.js
- src/vector/platform/ElectronPlatform.js
for #2886
depends on matrix-org/matrix-react-sdk/pull/918
> Prevent Power Save when in call (Electron)

- docs/translating.md
Primarily spelling, wording, and grammar. A little bit of formatting too.
> Update translating.md: Minor suggestions

- src/components/views/context_menus/MessageContextMenu.js
> managed to eat the eventStatus check, can't redact a local-echo etc

- test/app-tests/loading.js
I didn't try to fix the typical "don't get stuck in a spinner whilst joining over federation"
> Fix some tests that expect Directory (they should expect HomePage)

- .travis.yml
- README.md
... in an attempt to stop us breaking the ability to build against new/old
versions.
> Make travis run the build with several versions of node

- src/components/views/messages/MessageTimestamp.js
Partner PR: https://github.com/matrix-org/matrix-react-sdk/pull/971
> Show 12hr time on hover too

- src/components/views/messages/DateSeparator.js
Partner PR: https://github.com/matrix-org/matrix-react-sdk/pull/991
Before:
After:
> Support 12hr time on DateSeparator

- src/skins/vector/css/matrix-react-sdk/structures/_UserSettings.scss
for matrix-org/matrix-react-sdk/pull/850
> styling for webrtc settings

- res/home.html
- src/i18n/strings/en_EN.json
Also remove newline in translation string.
> Add missing translation for room directory

- electron_app/src/electron-main.js
- package.json
> provide react devtools in electron dev runs

- src/skins/vector/css/matrix-react-sdk/views/rooms/_EventTile.scss
move the message menu button up a bit so that it's centred.
Signed-Off-By: Hubert Chathi <hubert@uhoreg.ca>
> adjust alignment of message menu button in compact layout

- scripts/fetch-develop.deps.sh
when figuring out what branch we're on
> Chop off 'origin/'

- src/components/structures/HomePage.js
As we are not always at the root of the web server.
> Remove '/' from homepage URL

- package.json
> change electron -> electron_app which was previously missed

- src/components/views/context_menus/MessageContextMenu.js
> change dispatcher forward_event signature

- src/components/views/globals/PasswordNagBar.js
- src/i18n/strings/en_EN.json
- src/skins/vector/css/matrix-react-sdk/structures/_UserSettings.scss
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1123
Fixes https://github.com/vector-im/riot-web/issues/4229
> Give _t to PasswordNagBar, add CSS for UserSettings password warning

- src/skins/vector/css/matrix-react-sdk/structures/_UserSettings.scss
Now looks like red text 
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1126
> CSS for redeisng of password warning

- src/components/views/elements/ImageView.js
- src/i18n/strings/en_EN.json
- src/i18n/strings/en_US.json
Should have been handled in #3722 but was missed.
It's this button:
> Change missed 'Redact' to 'Remove' in ImageView.

- src/skins/vector/css/matrix-react-sdk/views/rooms/_MessageComposer.scss
depends on matrix-org/matrix-react-sdk/pull/1192
> remove unused class

- src/components/views/context_menus/MessageContextMenu.js
Goes with https://github.com/matrix-org/matrix-react-sdk/pull/1176
> Take RTE out of labs

- src/components/structures/HomePage.js
* Don't log errors with no context
* i18nify the "Couldn't load home page" message
> more HomePage tweaks

- src/vector/index.js
Initially try to load `config.$domain.json` and only if that fails, load
`config.json`. Configs are not muxxed in any way, it either entirely uses
the domain config, or entirely uses `config.json`.
> Allow Riot to load up different configs depending on the domain

- src/skins/vector/css/matrix-react-sdk/views/rooms/_MessageComposer.scss
Part of fixing https://github.com/vector-im/riot-web/issues/4580
> Apply CSS to <pre> tags to distinguish them from each other

- src/components/structures/RoomSubList.js
- src/components/views/context_menus/RoomTileContextMenu.js
- src/components/views/rooms/DNDRoomTile.js
bluebird promises don't support .fail, so some operations didn't work quite
right. We should use .catch instead.
> Fix a couple of minor errors in the room list

- src/skins/vector/css/matrix-react-sdk/views/rooms/_MessageComposer.scss
for https://github.com/matrix-org/matrix-react-sdk/pull/1248
> CSS required for composer autoscroll

- package.json
Hopefully to fix #4675 and friends
> Update draft-js from 0.8.1 to 0.10.1

- electron_app/src/electron-main.js
> electron support for mouse forward/back buttons in Windows

- package.json
See matrix-org/matrix-react-sdk#1269
> Update draft-js from 0.10.1 to 0.11.0-alpha

- src/skins/vector/css/matrix-react-sdk/views/avatars/_BaseAvatar.scss
- src/skins/vector/css/matrix-react-sdk/views/elements/_RichText.scss
codep matrix-org/matrix-react-sdk#1277
> Adjust CSS for optional avatars in pills

- README.md
scripts/fetch-develop-deps.sh vs scripts/fetch-develop.deps.sh
> Fix typo with scripts/fetch-develop-deps.sh in Building From Source

- src/skins/vector/css/matrix-react-sdk/structures/login/_Login.scss
CSS for https://github.com/matrix-org/matrix-react-sdk/pull/1284
> Add Login Page LanguageDropdown CSS

- src/components/structures/LeftPanel.js
Conflicts:
src/components/structures/LeftPanel.js
Pulls in https://github.com/vector-im/riot-web/pull/3654/commits/053beae035e55aed96dcf8c0899f13310f2ef52c by @ara4n 
partialy fixes #4658
> move focus-via-up/down cursors to LeftPanel

- README.md
Signed-off-by: Hubert Chathi <hubert@uhoreg.ca>
> another s/vector/riot/ in README

- src/components/views/login/VectorLoginFooter.js
Signed-off-by: Andrew (anoa) <anoa@openmailbox.org>
> Update vector-im to riot-im on Login

- scripts/copy-res.js
See https://github.com/matrix-org/matrix-react-sdk/pull/1358
Requires https://github.com/matrix-org/matrix-react-sdk/pull/1358
> Fix plurals in translations

- package.json
- src/components/views/messages/DateSeparator.js
- src/skins/vector/css/vector-web/views/messages/_DateSeparator.scss
Codep matrix-org/matrix-react-sdk#1353
> Implement sticky date separators

- res/home.html
Fixes https://github.com/vector-im/riot-web/issues/5008
(feel free to change authorship - it's a simple change and I won't be offended)
> Fix alias on home page for identity room

- src/skins/vector/css/matrix-react-sdk/structures/_UserSettings.scss
Required for https://github.com/matrix-org/matrix-react-sdk/pull/1389
This just applies styling to the button in UserSettings to unignore someone.
> CSS for unignore button in UserSettings

- src/skins/vector/css/matrix-react-sdk/views/rooms/_RoomSettings.scss
- Fix typo for integs error button error
- CSS to fix ugly integrations button
Codep matrix-org/matrix-react-sdk#1399
> Fix ugly integ button

- src/skins/vector/css/matrix-react-sdk/structures/_GroupView.scss
codep matrix-org/matrix-react-sdk#1402
> CSS for GroupView: Add a User

- src/skins/vector/css/matrix-react-sdk/structures/_GroupView.scss
CSS for https://github.com/matrix-org/matrix-react-sdk/pull/1408
> Redesign membership section of GroupView

- src/skins/vector/css/matrix-react-sdk/structures/_GroupView.scss
For https://github.com/matrix-org/matrix-react-sdk/pull/1415
> CSS for "X" in top right of features users/rooms

- src/components/structures/BottomLeftMenu.js
- src/skins/vector/css/matrix-react-sdk/structures/_MyGroups.scss
- src/skins/vector/img/icons-groups.svg
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1435
> Add button to get to MyGroups

- src/skins/vector/css/_components.scss
- src/skins/vector/css/matrix-react-sdk/views/dialogs/_QuestionDialog.scss
- src/skins/vector/css/matrix-react-sdk/views/groups/_GroupRoomList.scss
- src/skins/vector/css/matrix-react-sdk/views/rooms/_EntityTile.scss
For https://github.com/matrix-org/matrix-react-sdk/pull/1438
> CSS for "remove" button on GroupRoomTile

- src/components/structures/RoomSubList.js
> Fix bug that made sub list placeholders not show for ILAG etc.

- scripts/copy-res.js
So we can see which i18n file is invalid when it fails
> Say which translation file failed

- src/i18n/strings/be.json
- src/i18n/strings/nb_NO.json
> Remove trailing comma in JSON

- README.md
Possibly helps resolve #1698
I'm not married to the wording here, so feel free to change/close as not needed. Many people try and set this to their homeserver, leading to all kinds of fun problems.
> Clarify what an integrations server is

- src/skins/vector/css/matrix-react-sdk/structures/_MyGroups.scss
Until it actually does something
> Hide the join group button

- src/skins/vector/css/matrix-react-sdk/structures/_UserSettings.scss
- src/skins/vector/css/matrix-react-sdk/views/rooms/_RoomHeader.scss
see https://github.com/matrix-org/matrix-react-sdk/pull/1478
> CSS for remove avatar buttons

- src/skins/vector/css/matrix-react-sdk/structures/_RoomStatusBar.scss
css for https://github.com/matrix-org/matrix-react-sdk/pull/1466
> CSS for lonely room message

- src/components/views/elements/ImageView.js
Adds https://github.com/vector-im/riot-web/issues/340
> Don't use MXIDs on the lightbox if possible

- electron_app/riot.im/config.json
as we now disable labs in release Riot
> Disable labs in electron

- package.json
got bumped in react-sdk, missed here
> bump version to prevent eslint errors

- src/skins/vector/css/matrix-react-sdk/structures/_GroupView.scss
SVG was swallowing pointer events
> Make the 'add rooms' button clickable

- src/skins/vector/css/_common.scss
rather than the css color name
> Add div.warning and use the scss var

- package.json
Requires https://github.com/matrix-org/matrix-react-sdk/pull/1502/files
> Add script to prune unused translations

- src/components/views/login/VectorCustomServerDialog.js
- src/i18n/strings/en_EN.json
And therefore got replaced by the key by the i18n script
> Custom server text was i18ned by key

- src/components/structures/RightPanel.js
> Highlight group members icon in group member info

- src/components/views/dialogs/DevtoolsDialog.js
> Devtools: make filtering case-insensitive

- config.sample.json
Signed-off-by: Simon Körner <github@lubiland.de>
> fix comma error of features example

- src/components/structures/RightPanel.js
This required slight rework of how RightPanel uses the group store, and now it knows an unfortunate amount about the group store. Food for thought on stores in general, I think.
Now with mini react PR! https://github.com/matrix-org/matrix-react-sdk/pull/1544
fixes vector-im/riot-web#5429
> Use correct group store state when rendering "Invite to this community"

- src/components/structures/RightPanel.js
> Fix instanceof check, was checking against the Package rather than class

- src/skins/vector/css/matrix-react-sdk/structures/_MyGroups.scss
and also attempt to fix GroupTile flex weirdness.
> CSS for Your Communities scrollbar

- src/skins/vector/css/matrix-react-sdk/views/rooms/_RoomHeader.scss
- src/skins/vector/css/themes/_base.scss
See https://github.com/matrix-org/matrix-react-sdk/pull/1486
> CSS for pinned indicators

- src/skins/vector/css/_components.scss
- src/skins/vector/css/matrix-react-sdk/views/dialogs/_ChatInviteDialog.scss
- src/skins/vector/css/matrix-react-sdk/views/dialogs/_GroupAddressPicker.scss
Also, make chat invite error looks slightly more normal
> CSS for adding rooms to a group with visibility

- src/skins/vector/css/matrix-react-sdk/structures/_GroupView.scss
Part of showing the group inviter profile: https://github.com/matrix-org/matrix-react-sdk/pull/1585
> Adjust CSS for GroupView

- src/skins/vector/css/matrix-react-sdk/views/rooms/_AppsDrawer.scss
Needed for - https://github.com/matrix-org/matrix-react-sdk/pull/1548
> Don't display widget iframes whilst loading.

- src/skins/vector/css/matrix-react-sdk/views/rooms/_AppsDrawer.scss
Make app tile margins consistent.
> Fix app tile margins.

- src/components/structures/BottomLeftMenu.js
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1603
> Make groups a fully-fleged baked-in feature

- src/vector/index.js
see https://github.com/matrix-org/matrix-react-sdk/pull/1613
> Use SettingsStore to get the default theme

- src/components/structures/RightPanel.js
Add aria-labels to improve accessibility
> Add some aria-labels to RightPanel

- src/skins/vector/css/_components.scss
- src/skins/vector/css/matrix-react-sdk/views/groups/_GroupPublicityToggle.scss
- src/skins/vector/css/matrix-react-sdk/views/groups/_GroupUserSettings.scss
See https://github.com/matrix-org/matrix-react-sdk/pull/1634
> CSS required for moving group publication toggles to UserSettings

- src/components/structures/RightPanel.js
Part of https://github.com/matrix-org/matrix-react-sdk/pull/1635/commits/7ec4010881c58ec9fb655a3f01403e8a80380391
> getGroupStore no longer needs a matrix client

- src/components/structures/LeftPanel.js
- src/components/structures/RoomSubList.js
- src/components/structures/SearchBox.js
Required because https://github.com/matrix-org/matrix-react-sdk/pull/1641
> Update imports for accessing KeyCode

- src/skins/vector/css/matrix-react-sdk/views/rooms/_AppsDrawer.scss
- src/skins/vector/img/maximize.svg
- src/skins/vector/img/minimize.svg
As requested in https://github.com/vector-im/riot-web/issues/5395
> Widget title bar max / min visual cues. 

- AUTHORS.rst
@t3chguy thank you for this workaround! :)
Fixes #1953
> Fixes #1953 by adding oivoodoo as author

- src/components/views/dialogs/DevtoolsDialog.js
fixes https://github.com/vector-im/riot-web/issues/5557
> add dark theme styling to devtools input box

- electron_app/riot.im/config.json
> add missing config.json entry such that scalar-staging widgets work

- scripts/copy-res.js
> Corrected language name

- package.json
> Change author

- src/components/views/context_menus/MessageContextMenu.js
- src/skins/vector/css/matrix-react-sdk/views/rooms/_QuotePreview.scss
Fixes https://github.com/vector-im/riot-web/issues/5975
Fixes https://github.com/vector-im/riot-web/issues/5966
> Iterative fixes on Rich Quoting

- README.md
https://github.com/matrix-org/matrix-react-sdk/blob/master/src/components/views/messages/MFileBody.js#L116
Signed-off-by: Ander Punnar <ander@kvlt.ee>
> default url, not domain

- src/skins/vector/css/matrix-react-sdk/structures/_GroupView.scss
> Fix long group name pushing settings cog into void

- src/components/structures/BottomLeftMenu.js
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1744
> Move groups button to TagPanel

- src/skins/vector/css/themes/_dark.scss
My eyes can't stand it anymore. Fixes https://github.com/vector-im/riot-web/issues/5735
> Separate the middle panel from the room list

- src/skins/vector/css/matrix-react-sdk/structures/_TagPanel.scss
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1759
> CSS for new global TagPanel filter

- src/skins/vector/css/matrix-react-sdk/structures/_TagPanel.scss
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1764
> CSS for changing "R" to "X" for clearing group filter

- src/components/views/context_menus/TagTileContextMenu.js
Fixes https://github.com/vector-im/riot-web/issues/6188
> Fix un-tinted "View Community" icon in TagTile context menu

- scripts/copy-res.js
Bulgarian is now at 100% for both riot-web and matrix-react-sdk.
It has also been tested by building it manually and verifying that it looks good.
> Add Bulgarian to the list of languages

- src/skins/vector/css/matrix-react-sdk/structures/_MyGroups.scss
See https://github.com/matrix-org/matrix-react-sdk/pull/1777
> CSS for my groups microcopy

- src/skins/vector/css/matrix-react-sdk/structures/_GroupView.scss
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1802
> Add change delay warning in GroupView settings

- src/components/structures/LeftPanel.js
And https://github.com/matrix-org/matrix-react-sdk/pull/1805
> Take TagPanel out of labs

- config.sample.json
See https://github.com/matrix-org/matrix-react-sdk/pull/1806
> Add disable-presence-by-hs option to sample config

- src/components/structures/HomePage.js
Part of fixing the same as https://github.com/vector-im/riot-web/issues/6294 but for the home page
Similar to https://github.com/matrix-org/matrix-react-sdk/pull/1810
> Force gemini on HomePage

- src/skins/vector/css/matrix-react-sdk/structures/_GroupView.scss
For https://github.com/matrix-org/matrix-react-sdk/pull/1817/
> Add CSS for new group admin radio button

- scripts/copy-res.js
Looks like this just got missed
Fixes https://github.com/vector-im/riot-web/issues/6586
> Copy media from react-sdk

- package.json
> Update to electron 2.0.1

- electron_app/src/webcontents-handler.js
Fixes https://github.com/vector-im/riot-web/issues/6762
> Fix right click menu in electron

- config.sample.json
For https://github.com/matrix-org/matrix-react-sdk/pull/2062
> Sample config for jitsi integration URL

- .gitignore
- package-lock.json
- src/vector/index.js
Reverts vector-im/riot-web#7115
Turns out this breaks everything because sanitizeHtml is no longer a function (?)
> Revert "Remove package-lock.json for now"

- res/themes/status/css/_status.scss
See https://github.com/matrix-org/matrix-react-sdk/pull/2108
> CSS for user limit error

- CHANGELOG.md
> Small typo in release notes v0.16.3

- src/vector/mobile_guide/index.js
On mobile guide
Part of https://github.com/vector-im/riot-web/issues/7378
> Don't show custom server bit on matrix.org

- webpack.config.js
> Disable webpack-dev-server auto reload

- src/vector/getconfig.js
- src/vector/index.js
- src/vector/platform/WebPlatform.js
>  Fix riot-web Promise.defer warnings (#7409)

- release.sh
Reverts vector-im/riot-web#7429
> Revert "also commit the lock file when bumping version as it is now committed to the repo"

- package.json
Tested auto update on both windows (ia32) and mac, seems to work!
Edit: now tested on 64 bit windows too
> Update to latest electron builder

- res/themes/status/css/_status.scss
goes with changes in https://github.com/matrix-org/matrix-react-sdk/pull/2238
> Redesign: apply changes from dharma theme to status theme

- scripts/copy-res.js
Fixes #7599 
Thank you @kava2108 (and others)!!! 🎉
> Add Japanese (#7599)

- res/themes/status/css/_status.scss
See https://github.com/matrix-org/matrix-react-sdk/pull/2277
> Add $accent-color-50pct as a CSS variable to the Status theme

- src/vector/index.js
- webpack.config.js
Added new WIP themes to webpack config for bleeding edge testing.
> Added new WIP themes to webpack config

- test/app-tests/loading.js
See [the react-sdk PR](https://github.com/matrix-org/matrix-react-sdk/pull/2340) for some context.
> Update the tests to match https://github.com/matrix-org/matrix-react-sdk/pull/2340

- src/vector/rageshakesetup.js
Signed-off-by: J. Ryan Stinnett <jryans@gmail.com>
> Clarify line number instructions

- webpack.config.js
* A partial fix for some paths on Windows dev machines
* Only references from CSS files need adjustment
> Fix up some broken image paths

- webpack.config.js
This is needed when developing on Windows.
> Convert slashes in public paths

- res/themes/status/css/_StatusLogin.scss
- src/components/views/auth/VectorAuthFooter.js
- src/components/views/auth/VectorAuthHeader.js
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/2477
> Reorganize simple auth components

- src/components/views/auth/VectorAuthFooter.js
They aren't needed in the redesign.
> Remove dots between footer links

- src/vector/index.js
Another instance of detecting the file: protocol
Fixes https://github.com/vector-im/riot-web/issues/8235
> Fix registration nextLink on desktop

- src/components/views/auth/VectorAuthFooter.js
See https://github.com/matrix-org/matrix-react-sdk/pull/2496
> Add target="_blank" to footer links

- src/vector/index.html
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/2521.
Fixes https://github.com/vector-im/riot-web/issues/8284.
> Tweak auth overflow on Windows and Linux

- res/home.html
Fixes https://github.com/vector-im/riot-web/issues/8331.
> Fix home page link target

- README.md
**Main changes**:
- adding syntax coloring
- formatted so links and words or commands
Signed-off-by: Julien Jerphanion <git@jjerphan.xyz>
> README.md : Syntax Coloring

- README.md
Addresses question from https://github.com/vector-im/riot-web/issues/8494#issuecomment-462118858.
> Document `embeddedPages` configuration

- README.md
- src/components/views/auth/VectorAuthHeaderLogo.js
- src/components/views/auth/VectorAuthPage.js
Fixes https://github.com/vector-im/riot-web/issues/8526
> Support configurable welcome background and logo

- karma.conf.js
- test/app-tests/loading.js
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/2611
> Repair app loading tests after welcome page

- res/welcome.html
Fixes https://github.com/vector-im/riot-web/issues/8622
> Add snipping lines to welcome page without guests

- electron_app/src/electron-main.js
Fixes https://github.com/vector-im/riot-web/issues/8234
also includes a couple of trivial lint/mistake fixes
> Allow disabling update mechanism

- package-lock.json
- package.json
This includes a fix for detecting the version of Chrome used to run tests.
> Nudge karma to 3.1.2

- electron_app/riot.im/config.json
https://github.com/matrix-org/internal-config/pull/595
> Add modular.im hosting link to electron app config

- scripts/electron-package.sh
As per comment
https://github.com/vector-im/riot-web/issues/9074
> Don't copy the 32 bit linux deb

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
Signed-off-by: Mikaela Suomalainen <mikaela+git@mikaela.info>
> Update version number in issue templates

- README.md
My wording is atrocious as ever, so any suggestions welcome
> Document some desktop app things

- .buildkite/pipeline.yaml
It mostly truncates the log anyway but what are you gonna do
> Add log grouping to buildkite

- .buildkite/pipeline.yaml
**Review with https://github.com/matrix-org/matrix-react-sdk/pull/2813**
> Use medium agents for the more resource intensive builds

- electron_app/src/webcontents-handler.js
Fixes https://github.com/vector-im/riot-web/issues/9324
Requires https://github.com/matrix-org/matrix-react-sdk/pull/2848
**Please review with https://github.com/matrix-org/matrix-react-sdk/pull/2848**
> Add "Save image as..." button to context menu on images

- electron_app/src/webcontents-handler.js
Fixes https://github.com/vector-im/riot-web/issues/9350
> Don't try to save files the user didn't want to save

- package.json
- yarn.lock
Fixes https://github.com/vector-im/riot-web/issues/9497
> Use packages.matrix.org for Olm

- scripts/redeploy.py
Hopefully fairly self-explanatory
> Convert redeploy.py to buildkite

- scripts/redeploy.py
Otherwise it thinks they have failed, as per comment.
> Respond quickly to buildkite pokes

- .gitignore
- karma.conf.js
- package.json
- yarn.lock
See matrix-org/matrix-react-sdk#2944
> Remove karma junit output

- docs/labs.md
corresponding PR: https://github.com/matrix-org/matrix-react-sdk/pull/2952
> add description of new labs feature for message editing

- package.json
- scripts/copy-res.js
requires https://github.com/matrix-org/matrix-react-sdk/pull/2995
> remove emojione

- README.md
- config.sample.json
- src/vector/platform/ElectronPlatform.js
- src/vector/platform/WebPlatform.js
See https://github.com/matrix-org/matrix-react-sdk/pull/2598
**Disclaimer**: The branch name impersonates Matthew because it needs to match the react-sdk PR.
> Low bandwidth mode

- electron_app/src/webcontents-handler.js
Fixes https://github.com/vector-im/riot-web/issues/10113
> Fix Electron vector: links

- config.sample.json
- docs/labs.md
- electron_app/riot.im/config.json
Port https://github.com/vector-im/riot-web/pull/10363 to release branch
> Remove edits and reactions feature flags from docs and config

- electron_app/src/electron-main.js
Fixes https://github.com/vector-im/riot-web/issues/3734
> Add --help to electron app

- package.json
- yarn.lock
> Bump matrix-react-test-utils for React 16 compatibility

- package.json
Upgrade to last Electron 6.0.3
https://electronjs.org/releases/stable#release-notes-for-v603
Good version for linux fixes
> Upgrade to Electron 6.0.3

- docs/shortcuts.md
I'm probably missing some still
> Document more shortcuts

- docs/config.md
**See https://github.com/matrix-org/matrix-react-sdk/pull/3500**
There's no sample config changes because we don't want to encourage people using this setting. It is for very limited scenarios only: unfederated servers.
> Document permalinkPrefix setting

- docs/config.md
- webpack.config.js
Related to https://github.com/vector-im/riot-web/issues/10946
> Custom themes MVP

- docs/memory-profiles-and-leaks.md
> Document troubleshooting for memory leaks and getting profiles

- docs/labs.md
- riot.im/develop/config.json
**Review with https://github.com/matrix-org/matrix-react-sdk/pull/3519**
> Remove docs for CIDER feature

- config.sample.json
This was missed in https://github.com/vector-im/riot-web/pull/11112
> Update sample config for new matrix.org CS API URL

- src/components/views/auth/VectorAuthFooter.js
- src/components/views/auth/VectorCustomServerDialog.js
Fixes https://github.com/vector-im/riot-web/issues/11250
> Fix skinning replaces being broken since being rewritten as React FC's

- package.json
- yarn.lock
> Add dependency to eslint-plugin-react-hooks as react-sdk did

- electron_app/src/electron-main.js
Fixes https://github.com/vector-im/riot-web/issues/11308
> Fix close window behaviour on Macos

- package.json
- yarn.lock
To include https://github.com/electron/electron-notarize/pull/14
> Upgrade electron-notarize

- docs/config.md
- docs/feature-flags.md
This records the feature flag process we intend to use with Riot and also how
that interacts with other teams and configuration.
Fixes https://github.com/vector-im/riot-web/issues/11116
> Document feature flag process

- src/vector/platform/VectorBasePlatform.js
See diff for why this arcane magic is needed.
Fixes https://github.com/vector-im/riot-web/issues/11347
Upstream bug: https://github.com/ejci/favico.js/issues/152
> Perform favicon updates twice in Chrome

- docs/labs.md
- riot.im/develop/config.json
Part of https://github.com/matrix-org/matrix-react-sdk/pull/3632
> Merge the `feature_user_info_panel` flag into `feature_dm_verification`

- scripts/electron_afterSign.js
'Exception' isn't a thing: Error is
> Fix error/exception in electron signing script

- electron_app/build/entitlements.mac.plist
Fixes https://github.com/vector-im/riot-web/issues/11151
> Add entitlements file for mic & camera permissions on macOS

- src/vector/index.html
Preload icon used in https://github.com/matrix-org/matrix-react-sdk/pull/3633
> preload warning triangle

- docs/theming.md
Mostly just c+ped from Bruno's PR: https://github.com/matrix-org/matrix-react-sdk/pull/3503
> Add doc for custom themes

- package.json
- yarn.lock
> Add eslint-plugin-jest because we inherit js-sdk's eslintrc and it wants

- docs/labs.md
Expand on the development state of cross-signing in the labs docs.
Fixes https://github.com/vector-im/riot-web/issues/11492
See also https://github.com/matrix-org/matrix-react-sdk/pull/3668
> Clarify that cross-signing is in development

- riot.im/app/config.json
This removes unused settings from the app config and standardises the order to match develop.
> Clean up and standardise app config

- scripts/copy-res.js
By request: https://matrix.to/#/!yvhoprZiKmhjxKfNHa:matrix.org/$E_5Waedui4X866edAWmYVAjg6vv-vwAXRHN4h0DKY6s?via=matrix.eclabs.de&via=matrix.org&via=dodsorf.as
> Update Lithuanian language name

- package.json
- src/vector/index.js
- yarn.lock
...which for some reason was still kicking around
> Remove draft-js dependency

- electron_app/src/webcontents-handler.js
Backport of https://github.com/vector-im/riot-desktop/pull/19
> Add accelerators to context menu options like cut&paste in electron

- scripts/docker-write-version.sh
Fixes https://github.com/vector-im/riot-web/issues/11642
> Fix version file for Docker images

- docs/labs.md
- riot.im/develop/config.json
This should hopefully be short-lived.
**Review with https://github.com/matrix-org/matrix-react-sdk/pull/3792**
> Add docs for feature_ftue_dms flag

- docs/labs.md
- riot.im/develop/config.json
For https://github.com/matrix-org/matrix-react-sdk/pull/3693
> Add docs for feature_bridge_state flag

- docs/labs.md
- riot.im/develop/config.json
https://github.com/vector-im/riot-web/pull/11829 to release branch
> Enable and document presence in room list feature flag

- webpack.config.js
See commits for individual parts.
> Fix indentation on webpack config and make sourcemapped files legible

- docs/labs.md
See https://github.com/matrix-org/matrix-react-sdk/pull/3854
> Update labs documentation for feature_ftue_dms given new scope

- webpack.config.js
https://github.com/vector-im/riot-web/pull/11944 to release branch
> Fix webpack to babel js-sdk & react-sdk but no other deps

- electron_app/riot.im/config.json
- riot.im/app/config.json
- riot.im/develop/config.json
Fixes https://github.com/vector-im/riot-web/issues/10362
Per https://github.com/vector-im/riot-web/pull/11998#issuecomment-577329852
> Fix the remainder of the cookie links

- electron_app/src/electron-main.js
- src/vector/platform/ElectronPlatform.js
This PR expands the electron platform to have the ability to load file events from the event index. Needed  by https://github.com/matrix-org/matrix-react-sdk/pull/3858.
> ElectronPlatform: Add the ability to load file events from the event index

- babel.config.js
For https://github.com/matrix-org/matrix-react-sdk/pull/3961
> Switch back to legacy decorators

- docs/labs.md
Docs for https://github.com/matrix-org/matrix-react-sdk/pull/4013
> Document padlock flag

- src/vector/platform/ElectronPlatform.js
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/4092
The above referenced PR runs this same code but on all platforms instead
> Use Persistent Storage where possible

- src/components/structures/VectorEmbeddedPage.js
- src/components/views/auth/VectorAuthFooter.js
Part of https://github.com/matrix-org/matrix-react-sdk/pull/4113
> Use noreferrer in addition to noopener for edge case browsers

- src/vector/platform/ElectronPlatform.js
> Notify electron of language changes

- scripts/docker-link-repos.sh
> docker: optimize custom sdk builds

- src/vector/platform/ElectronPlatform.js
This depends on https://github.com/vector-im/riot-desktop/pull/47.
> ElectronPlatform: Add support to remove events from the event index.

- package.json
- src/vector/index.js
- yarn.lock
Depends on https://github.com/matrix-org/matrix-react-sdk/pull/4217
> Remove remainders of gemini-scrollbar and react-gemini-scrollbar

- electron_app/src/vectormenu.js
- src/i18n/strings/en_EN.json
- src/vector/platform/ElectronPlatform.js
Requires https://github.com/matrix-org/matrix-react-sdk/pull/4243
Fixes https://github.com/vector-im/riot-web/issues/12246
> Register Mac electron specific Cmd+, shortcut to User Settings

- electron_app/riot.im/config.json
- riot.im/app/config.json
- riot.im/develop/config.json
Until we update its tutorial videos to the current interface
Fixes https://github.com/vector-im/riot-web/issues/12893
> Remove welcome user from config

- docs/review.md
Just thought 'layers of their PR' was a little hard to conceptualise if you're not thinking in layers.
> Some grammar and clarifications

- src/vector/platform/ElectronPlatform.js
https://github.com/vector-im/riot-web/issues/13017#issuecomment-608392766
> Fix Electron mac-specific shortcut being registered on Web too.

- README.md
> Fix broken yarn install link in README.md

- src/vector/index.ts
Fixes https://github.com/vector-im/riot-web/issues/13163
> Allow rageshake to fail in init

- electron_app/riot.im/config.json
- riot.im/app/config.json
Fixes https://github.com/vector-im/riot-web/issues/13178
> Enable cross-signing / E2EE by default for DM on release

- docs/labs.md
For https://github.com/matrix-org/matrix-react-sdk/pull/4416
> Update cross-signing feature docs and document fallback procedures

- test/app-tests/loading-test.js
- tsconfig.json
> Fix tests post-js-sdk-filters change

- docs/config.md
This were the missing options from the config.sample.json file which were not yet documented in config.md. Happy to hear suggestions about phrasing improvements :)
Fixes https://github.com/vector-im/riot-web/issues/13089
> Document more config options in config.md (fixes #13089)

- tsconfig.json
To allow for importing of json in typescript like emojibase compact.json in https://github.com/matrix-org/matrix-react-sdk/pull/4452
> add config option to tsc resolveJsonModule

- docs/labs.md
- riot.im/develop/config.json
See https://github.com/matrix-org/matrix-react-sdk/pull/4467
> Remove encrypted message search feature flag

- config.sample.json
- docs/labs.md
- riot.im/develop/config.json
Reverts vector-im/riot-web#13199
> Revert "Add font scaling labs setting."

- docs/labs.md
- riot.im/develop/config.json
See https://github.com/matrix-org/matrix-react-sdk/pull/4487
> Remove docs and config for invite only padlocks

- docs/theming.md
For https://github.com/matrix-org/matrix-react-sdk/pull/4503
> Update docs with custom theming changes

- src/vector/platform/ElectronPlatform.js
- src/vector/platform/VectorBasePlatform.js
- src/vector/platform/WebPlatform.js
- test/app-tests/loading-test.js
See https://github.com/matrix-org/matrix-react-sdk/pull/4593
*Note: this is specifically requesting review from @JorikSchellekens for the experience of code review. Others are welcome to review as always, however.*
> Move dispatcher references in support of TypeScript conversion

- res/welcome.html
- src/vector/index.html
I fixed the [requested changes](https://github.com/vector-im/riot-web/pull/12142#discussion_r400916868) from the original PR. https://github.com/vector-im/riot-web/pull/12142
>  Add media queries and mobile viewport (#12142)

- src/vector/platform/ElectronPlatform.tsx
- src/vector/platform/WebPlatform.ts
discards the `new_version` dispatch
> Replace New Version Bar with a Toast

- res/welcome.html
- src/i18n/strings/en_EN.json
https://github.com/vector-im/riot-web/pull/13842 to RC
> Get rid of welcome.html's Chat with Riot Bot button to release

- src/@types/global.d.ts
- src/vector/init.tsx
- src/vector/platform/PWAPlatform.ts
Fixes https://github.com/vector-im/riot-web/issues/13840
> Add PWA Platform with PWA-specific badge controls

- docs/labs.md
https://github.com/matrix-org/matrix-react-sdk/pull/4655
> Remove cross-signing from labs

- src/vector/platform/ElectronPlatform.tsx
depends on https://github.com/vector-im/riot-desktop/pull/95
> make IPC calls to get pickle key

- src/vector/platform/ElectronPlatform.tsx
- src/vector/platform/VectorBasePlatform.ts
- test/app-tests/loading-test.js
https://github.com/vector-im/riot-web/pull/13889 to RC
> Fix login loop where the sso flow returns to `#/login` to release

- docs/e2ee.md
Document https://github.com/vector-im/riot-web/issues/13705
> Add e2ee-default:false docs

- docs/labs.md
**Paired with https://github.com/matrix-org/matrix-react-sdk/pull/4794**
> Mark the new room list as ready for general testing

- src/vector/platform/ElectronPlatform.tsx
Requirement for https://github.com/matrix-org/matrix-react-sdk/pull/4611.
Note, this requires a new Seshat version so we'll want to merge this only after the Seshat release.
> ElectronPlatform: Implement the isRoomIndexed method.

- config.sample.json
- docs/labs.md
- riot.im/develop/config.json
Adds the labs flag introduced in https://github.com/matrix-org/matrix-react-sdk/pull/4842.
> Add the new spinner feature labs flag

- src/components/views/auth/VectorAuthPage.js
Fixes https://github.com/vector-im/riot-web/issues/14364
> Fix welcomeBackgroundUrl array causing background to change during use

- config.sample.json
- docs/labs.md
- riot.im/develop/config.json
https://github.com/matrix-org/matrix-react-sdk/pull/4898
> Release the irc layout from labs

- element.io/app/config.json
- element.io/develop/config.json
Fixes https://github.com/vector-im/riot-web/issues/14500
> Fix hosting signup link

- docs/labs.md
For https://github.com/matrix-org/matrix-react-sdk/pull/5013
> Remove labs info for the new room list

- scripts/copy-res.js
The Lojban translation is now at 21.7% on Weblate, which is on par with a number of other translations, it is actively being worked on by me, and there are people interested in using it, so I am requesting that it be made available in Element.
> Make Lojban translation available

- config.sample.json
- element.io/app/config.json
- element.io/develop/config.json
Part of https://github.com/vector-im/element-web/issues/14892
> Update bug report submission URL

- element.io/app/config.json
- element.io/develop/config.json
Fixes https://github.com/vector-im/element-web/issues/14904
> Update policy links to element.io

- docs/labs.md
Documents https://github.com/matrix-org/matrix-react-sdk/pull/5110
> Document new labs tweaks

- scripts/copy-res.js
Fixes https://github.com/vector-im/element-web/issues/15026
> Make kabyle translation available

- docs/review.md
This adds a initial statement on testing to the review guidelines. No
requirements are made at this time, but reviewers are encouraged to request
tests where they believe it is reasonable to provide them.
Fixes https://github.com/vector-im/element-web/issues/14945
> Add testing to review guidelines

- .eslintrc.js
- src/async-components/structures/CompatibilityView.tsx
- src/vector/init.tsx
- src/vector/platform/ElectronPlatform.tsx
For https://github.com/vector-im/element-web/issues/15036
> Fix eslint ts override tsx matching and delint

- scripts/copy-res.js
Fixes https://github.com/vector-im/element-web/issues/15135
> Enable Estonian in language menu

- src/vector/app.tsx
to prevent locking the user in place
Fixes https://github.com/vector-im/element-web/issues/3543
Requires https://github.com/matrix-org/matrix-react-sdk/pull/5185
> Fix onNewScreen to use replace when going from roomId->roomAlias

- docs/config.md
This is the documentation for all of https://github.com/vector-im/element-web/issues/15185 and its subissues.
> Add end-user documentation for UI features

- package.json
- yarn.lock
Part of https://github.com/vector-im/element-web/issues/15122
> Upgrade sanitize-html

- src/vector/app.tsx
See https://github.com/matrix-org/matrix-react-sdk/pull/5248
> Remove conference handler

- src/vector/index.ts
- src/vector/platform/WebPlatform.ts
- webpack.config.js
Moves ServiceWorker load into Platform so its not done by Electron
Fixes https://github.com/vector-im/element-web/issues/15265
> Tidy up Service Worker, only run Workbox in production

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/user-interface-or-usability-bug-report.md
> Update Riot -> Element Web in issue templates

- docs/review.md
Blame GitHub's crap editor for the MR's
> Update Riot -> Element in docs/review.md

- src/components/views/auth/VectorAuthFooter.js
> Update Riot -> Element in VectorAuthFooter

- docs/feature-flags.md
Gotta fix that up :-) 
Man this is how I spend my free time
> Update Riot -> Element in docs/feature-flags.md

- package.json
- yarn.lock
> Update Jest and JSDOM

- src/vector/platform/ElectronPlatform.tsx
This requires https://github.com/matrix-org/matrix-react-sdk/pull/5312.
> electron-platform: Pass the user/devce id pair when initializing the event index.

- src/vector/jitsi/index.ts
**For https://github.com/matrix-org/matrix-react-sdk/pull/5323**
> Don't fatally end the Jitsi widget when it's not being used as a widget

- package.json
- src/vector/jitsi/index.ts
- yarn.lock
Port https://github.com/vector-im/element-web/pull/15495 to release
> [Release] Adjust for new widget messaging APIs

- src/vector/jitsi/index.scss
- src/vector/jitsi/index.ts
Requires https://github.com/matrix-org/matrix-react-sdk/pull/5266
> Jitsi accept theme variable and restyle

- src/vector/jitsi/index.scss
- src/vector/jitsi/index.ts
https://github.com/vector-im/element-web/pull/15575 to Release
> [Release] Fix Jitsi regressions with custom themes

- docs/config.md
**Review with https://github.com/matrix-org/matrix-react-sdk/pull/5362**
> Add documentation for new UIFeature flag regarding room history settings

- element.io/develop/config.json
Config for https://github.com/matrix-org/matrix-react-sdk/pull/5365
> Add countly experiment to develop/nightly configs

- package.json
- yarn.lock
To prevent accidental package conflicts
> Update the widget-api for element-web

- webpack.config.js
This adjusts our asset path handling to group KaTeX fonts in a more sensible way
alongside the other fonts we have. It also resolves production build issues on
Windows.
Fixes https://github.com/vector-im/element-web/issues/15911
> Improve asset path for KaTeX fonts

- package.json
- yarn.lock
Consistency with https://github.com/matrix-org/matrix-react-sdk/pull/5527
> Update widget-api to beta 11

- scripts/copy-res.js
It has reached ~99% translated, so it's past time to add it.
> Add Hebrew language

- src/vector/jitsi/index.ts
See https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification/pull/3
> Supply server_name for optional federation-capable Jitsi auth

- docs/config.md
Impl in https://github.com/matrix-org/matrix-react-sdk/pull/5560
> Docs for the VoIP translate pattern option

- docs/config.md
Part of https://github.com/vector-im/element-web/issues/16283
Relates to https://github.com/matrix-org/matrix-react-sdk/pull/5586
> Document the mobile guide toast option

- package.json
- yarn.lock
Part of https://github.com/vector-im/element-web/issues/16337
Related to https://github.com/matrix-org/matrix-react-sdk/pull/5607
> Upgrade matrix-widget-api
